### ISSUE TITLE
Cannot always duplicate events in the drum editor

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#1003]
I have seen this before but haven't really been sure how to reproduce it. Not entirely sure now either, but more sure :)

Basically, while in the drum editor and there is a drum note selected. Ctrl+click on it and drag to make a copy. I usually do this to quickly make repetitions (having lots of notes selected).
The copy is created where the mouse is when you release the button. Unless you release it on the same tick as the original note, then it just vanishes. There seems to be more cases where it just vanishes but this one seems to be easily repeatable.

Using AppImage 4.0

Figured this out while I was making instruction videos so if it is unclear I can upload video evidence :D

**Comment by kybos** [comment]
It always vanishes when there is already at least one other event on the same target tick. I would even say that the result is also broken in all other cases when the copy is seemingly working.

Anyway, it should be fixed now. Pretty tough debugging all this undo and operations code...

**Comment by spamatica** [comment]
oh, wow, awesome, was not expecting that \o/
