### ISSUE TITLE
Window dedicated to the mixer.

### ISSUE THREAD

**Issue by Gabrielxd195** [muse-sequencer/muse#1006]
Hello, first of all I would like to say that I just discovered muse and for me it is a hidden gem, I think they make a great contribution with this application. I would like to give two suggestions:

1- Add the maximize button in the mixer.
2- Expand the vertical space where the plugins are placed.

Currently you have the mixer channel on the left side, the mixer can be resized but not in its entirety and the space where the plugins are added is very small and cannot be resized, I think that when mixing many channels it would be more practical to have a maximized window and the option to resize the plugins space of the mixer channels as I constantly remove and add plugins. Greetings

**Comment by kybos** [comment]
The number of plugin slots displayed in the mixer strip can be customized: Right-click on the strip header->Visible Audio Effects.
The max button in the mixer had to be removed because the maximized display of the mixer is broken on many Linux desktops (due to its special nature).

**Comment by kybos** [comment]
The mixer window now can be maximized with the new dock option.
See https://github.com/muse-sequencer/muse/issues/1016 for details.
