### ISSUE TITLE
MusE not working

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [muse-sequencer/muse#1007]
A couple days ago MusE was working just fine on my rpi4, but yesterday and today it is not working, im getting this error:
![2021-05-21-133530_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/119195779-0635f100-ba3a-11eb-8d28-b142c0320297.png)

Any idea how to fix this?

**Comment by spamatica** [comment]
MusE seems to be unable to connect to Jack. A guess is that jack is somehow not starting correctly, though there can be other reasons.
Are you usually starting Jack before starting MusE?
You can try running jack_simple_client from a terminal to validate that jack is working (it should yield a tone on the audio output)

This could be one of those cases where a reboot clears up the problem..

**Comment by The-Sapphire-Starship** [comment]
when i run jack_simple_client it says "Unable to connect to JACK server"
i havent been doing anything with jack before running, i havent had to, this is the script i run to run muse:
![2021-05-21-153605_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/119204450-4d2be280-ba4a-11eb-9d13-f8403be54b22.png)

a reboot isnt clearing it up, ive closed and tried running muse again several times, as well as turned off my computer and turned it back on again several times

**Comment by spamatica** [comment]
Hey, sorry for leaving you hanging.
First, if you want to use MusE as a pure midi sequencer, in which case you can start the midi only mode with command line switch -a.
But I assume you want to use audio. MusE can use two audio backends, Jack and RtAudio/Pulse, of which Jack is the better one.
If you want to quickly get it up and running, you can start with with: muse4 -t
which will force muse to start with the Pulse backend, Not 100% sure about raspberry pi but on other linux systems Pulse is nearly always the default soundserver.

You can read more about this in the documentation
https://github.com/muse-sequencer/muse/wiki/Documentation#getting-up-and-running

Hope this helps you.

Also, these types of issues might be good to bring up in the forum as they are often not bugs and there might be users who have been in similar situations https://linuxmusicians.com/viewforum.php?f=61 
(though admittedly it is good to address them here too for future reference...)

**Comment by The-Sapphire-Starship** [comment]
No worries, people have other things they need to do other than always instantly answering questions
thanks forthe help, it works fine with the pulseaudio, i might bring it up on the forum as well but im not too worried about it as long as i can get it to work
