### ISSUE TITLE
[Feature request] Mixer tab in the main window

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#1016]
Hello,

will there ever be an option for showing the mixer as a tab in the main window rather than individual Mixer A and B windows?

I personally have a hard time keeping track of separate windows and having everything in a single window with individual tabs feels much more comfortable to me. Also because i could switch from the Arranger to the Mixer with a single click or Ctrl+Tab for rapid mixing. Thanks!

**Comment by kybos** [comment]
I was thinking about that when redesigning the UI. I think the mixer would do even better as a docked window (like e.g. the event list is now), not a tab (which would probably look a little weird in a full-size window on a big screen).  
Unfortunately the mixer is very special and very different from the editor windows, so it's not so easy to implement. But if there is enough interest, I will look into it.

**Comment by fpesari** [comment]
Even a docked window it would be a great improvement! But when there are many tracks (and this happens a lot for example in electronic music production), perhaps a docked window would not be large enough.

Keep in mind that the mixer strip is already docked and that's already one way to mix in the same view as the arranger. What is needed right now is a way to easily move from one track to the other.

This is what Ardour does with its mixer:

![Ardour mixer](https://ardour.org/images/mixer4.png)

It is a full-screen tab which reminds of a real mixing console:

![Mackie mixer](https://upload.wikimedia.org/wikipedia/commons/2/2d/MackieMixer.jpg)

I think a separate tab would be consistent with the separate tabs for the various sequencer and the wave editor, because everything is logically separated.

**Comment by kybos** [comment]
> perhaps a docked window would not be large enough.

The dock can be easily made as large as the tabbed window. But, unlike the tabbed window, it can also be made smaller and thus displayed together with the Arranger (just like the List editor I mentioned above...). So it's much more flexible.
BTW: The mixer strip in the Arranger is not a dock (technically).

**Comment by StaffanMelin** [comment]
I think this is a great idea -- I have never been comfortable with the mixer in a separate window (only when I run on multiple screens, which I do very seldom).

**Comment by kybos** [comment]
In current master/AppImage there is now an option to display the mixers in docks (Global settings->Editors).
When the dock is dragged out/floated, a top level window title bar is added, so it can be maximized etc. as a normal top window.
When you drag the floating window back to dock, be sure to drag (or double-click) the floating bar, not the title bar - this is always a source of confusion, but that's how it works in most UI frameworks (because the title bar doesn't belong to the dock, it's a "manual" addition).

**Comment by fpesari** [comment]
This is great @kybos! Thank you. 

I am definitely going to use this feature, might even make it default on the version shipped from our repo.

With the premise that it already solves my personal problem and that you did more than enough, is there any chance of the Mixer being able to turn into a tab too, like it does with the floating window?

**Comment by spamatica** [comment]
Which repo is that if I may ask? :) Apologies if you already mentioned it.

**Comment by fpesari** [comment]
> Which repo is that if I may ask? :) Apologies if you already mentioned it.

It's [GeekosDAW](https://build.opensuse.org/project/show/home:geekositalia:daw), I didn't want to do a shameless plug :smiley_cat:

**Comment by StaffanMelin** [comment]
Great work, @kybos! Looks fine and useful even on my 14 inch laptop! Thanks a lot!

**Comment by kybos** [comment]
> With the premise that it already solves my personal problem and that you did more than enough, is there any chance of the Mixer being able to turn into a tab too, like it does with the floating window?

Even if the docks and the tabs may look similar (both can be made into floating windows), the code behind it is completely different, so no, it can't be done without major effort.

**Comment by fpesari** [comment]
> > With the premise that it already solves my personal problem and that you did more than enough, is there any chance of the Mixer being able to turn into a tab too, like it does with the floating window?
> 
> Even if the docks and the tabs may look similar (both can be made into floating windows), the code behind it is completely different, so no, it can't be done without major effort.

No problem, you can close this ticket then. Thank you again :+1:
