### ISSUE TITLE
[FEATURE REQUEST] Option to show only loaded drums

### ISSUE THREAD

**Issue by dlzi** [muse-sequencer/muse#1020]
It would be nice to have an option to only show the loaded drums in the drum editor. That would increase the usability of the editor, specially when you work with few samples, since it would avoid the user to scroll up and down.

**Comment by terminator356** [comment]
In the drum editor menu there is:
Display > Show/Hide > Show only used instruments
Display > Show/Hide > Show only named and used instruments

Experiment with those settings. Is it helpful?

**Comment by terminator356** [comment]
What is meant by "loaded with samples"? Is a sampler plugin being used? Which sampler plugin?
In some cases it might not be possible for us to know which notes have loaded samples in a sampler plugin.

**Comment by dlzi** [comment]
Humm... let me try to explain:

- New (Ctrl + N)
- Right click -> Synth -> MESS -> simpleDrums
- Open simpleDrums GUI and load some samples. As showed below, I loaded three samples.
![Screenshot_20210603_093948](https://user-images.githubusercontent.com/1160818/120606660-b69af080-c44f-11eb-9014-1ee2b6efbff8.png)
- Add a Drum Track
- Create a midi region, double click to enter the drum editor.
- That's where I say that it would be good to have a toggle to show only the "loaded instruments/samples". So, instead showing like this.
![Screenshot_20210603_094325](https://user-images.githubusercontent.com/1160818/120607724-bf3ff680-c450-11eb-8479-6489257cb142.png)

Once you toggle, it would only show the: Bass drum, hand clap and open hi-hat.

**Comment by terminator356** [comment]
OK Got it.
For SimpleDrums we might be able to do something about that. But I think it would require some work.
I will defer to @spamatica on this one, he has experience with that plugin, what does he think about it?

**Comment by dlzi** [comment]
It's already there!

![Screenshot_20210701_171625](https://user-images.githubusercontent.com/1160818/124148684-2bce0580-da90-11eb-8987-637049d535ba.png)
