### ISSUE TITLE
Copying synth track does not copy pan and volume of track

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#1021]
I select a synth track, right click and select duplicate track. I check the bottom three checkboxes (see attachment).

But the pan and volume of the duplicated track are not copies, only the default values.

![muse_duplicate_track](https://user-images.githubusercontent.com/33361311/120331636-46c12480-c2ee-11eb-9bca-dff2b80f6fba.png)

MusE 4.0 (compiled from master a week ago)

**Comment by terminator356** [comment]
Should be fixed in git master now. Thanks for spotting that, been there a long time. Re-open if any trouble.

**Comment by StaffanMelin** [comment]
Works great, thanks Tim! :)

I noticed that plugins are copied, but not their settings. Is this possible to add, @terminator356 ?

**Comment by terminator356** [comment]
It is supposed to. I stepped through the code and found the problem.
It is attempting to copy the existing synth track's controller values to the new synth track copy
 before the new copy's synth section is instantiated, so there's nothing to copy the values to,
 and the new copy ends up with default values, after it has been created.
Thanks for spotting, again. I think I have a fix, must try...

**Comment by StaffanMelin** [comment]
Thank you for looking into this Tim, I am sure the solution will benefit many!

**Comment by terminator356** [comment]
Should be fixed in git master now.
Tested the various copy dialog options OK with synth tracks and other audio tracks having effect rack plugins
 and having static controller values and controller graphs.

**Comment by terminator356** [comment]
Final note:
Special: Copying MESS synth tracks is a slightly different experience.
Their controllers are midi controllers, not audio controllers like the other synths.
That midi controller data is contained in midi parts, and therefore in this case the
  track copy dialog's parts options.

**Comment by StaffanMelin** [comment]
Hmmm I get a "segmentation fault" when I did the following with the new version:

1. Created empty new project
2. Created a synth track with Surge softsynth
3. Opened Surge and changed to anyother preset
4. Right clicked on the synth track and selected "Duplicate track".
5. Crash

**Comment by terminator356** [comment]
Can you tell me which version of surge? I am having difficulty figuring out what to download.
Did you build it yourself? VST2 or LV2 version?

Does it happen with other synth plugins?

**Comment by StaffanMelin** [comment]
It is Surge LV2 version 1.7, downloaded från kx.studio as a deb.

I also tried with Helm LV2, it doesn't crash.
