### ISSUE TITLE
Allow even more zoom out in piano roll

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#1022]
I would like to be able to zoom out even more, like 1 "grid box" per bar.

I work on some space music right now and using really long bass drone notes.

See attachment of current maxed zoom out.

![muse_zoomout](https://user-images.githubusercontent.com/33361311/120434150-61da7580-c37c-11eb-8ce0-f596c9ca4483.png)

**Comment by cezaryece** [comment]
Vote for this!
