### ISSUE TITLE
Automation editing

### ISSUE THREAD

**Issue by theGreatWhiteShark** [muse-sequencer/muse#1024]
Hey,

First of all, I really like that you expose not just volume/velocity but all sorts of controls for automation! But interacting with the automation track is a not too much fun yet so I want to bring some points up that might improve its handling

- Lines and squares drawn are quite thin/hard too see. I think this is perfectly fine with the default view but when enlarging the track height maybe the linewidth could increase as well.
- Catching the automation line or its points is quite hard. Maybe a margin around these elements could be made sensitive too to ease their handling with the mouse?
- If I haven't missed it in the docs and wasn't able to find it by trying, there is currently no way to delete a point on the automation line.
- When using the mouse in Pointer mode: how about allowing to drag-select automation points and to allow changing their values using mouse move events collectively and to delete them using <kbd>Del</kdb>?
- And most importantly: How about when creating a range in the Time Scale (the horizontal line with number to change the transport location with) to expose a function/button/shortcut to convert this into an adjustable region in the (currently selected/last used) automation. Motivation goes like this: during recording I often got parts of tracks that need to be slightly louder or quieter. Instead of creating two points in very close vicinity both at the beginning and the end of the region with the inner ones and outer ones being matched in their values respectively, it would be awesome to insert like a template of this constellation based on the selected region.

Does any of this would fit into the UX concept you have of MusE and are there any plans for enhancing the automation?

**Comment by spamatica** [comment]
Hi,

I agree it needs some improvements.
Regarding delete, it is actually possible, while hovering over a point, right click with the mouse and there is a remove function in the menu. 
Allowing to manipulate multiple points (drag select, move, delete with delete key) has been on the todo list but hasn't materialized yet.

The last point I didn't grasp my head around exactly what you are after.
I have seen other DAWs have a volume line on the part, to edit the overall volume of an individual part. That I would like to add at least.

**Comment by theGreatWhiteShark** [comment]
> Regarding delete, it is actually possible, while hovering over a point, right click with the mouse and there is a remove function in the menu.

Ah, nice.

> The last point I didn't grasp my head around exactly what you are after.
I have seen other DAWs have a volume line on the part, to edit the overall volume of an individual part. That I would like to add at least.

In [this](https://www.youtube.com/watch?v=dO1OOzfGmLQ&t=1413s) video there is a good example. I have to admit I haven't used such a feature in real life yet. But entering four points and constructing such a plateau takes me about a minute compared to the video where it takes 1-2 seconds. 

I also think it's useful for all automation tracks and not just for the volume. This might be again just me, but I use it too for e.g. increasing the pan of the guitars during chorus or increasing the reverb time of the snare during slower parts of a song.

**Comment by terminator356** [comment]
Regarding the future of audio automation editing:
We talked about this in depth some years ago, and understood the challenges facing us.
If I may summarize an unofficial roadmap, at least the way I see it:
1) The most important thing is that audio automation must be inside moveable parts.
2) This means all audio track types, including Audio Output Tracks, Group Tracks etc, must support drawing parts.
3) This also means the (wave) part editor needs an automation lane editor, just like midi tracks.
4) A question came up as to whether we should still allow automation to be drawn directly on the track
 without parts. While this has some ease-of-use benefits, I believe we should eliminate that in favour of parts.
Because users will regret drawing directly on the track and then not being able to move the points as a group.

A word about dragging and moving the points on a graph: This is quite challenging. When you move a point,
 it is currently not possible to allow it to pass other points on the graph. Thus points will end up bunching together
 since they cannot pass other points that are in the way.
I overcame these challenges in the midi track automation graphs, but it was tricky.
One cannot allow a point to be dragged and dropped onto another point since only one point at a time
 can exist at a given time value. Thus you will see in my midi automation graphs some (slightly awkward)
 options regarding how to erase the existing points when other points are dropped onto them.
In Werner's original MusE-2 (now called evolution in our code attic), he got around this by having a button
 that said "move points with parts". However when I examined this, I found it inadequate, the points should
 have their own parts.

**Comment by theGreatWhiteShark** [comment]
Hey @terminator356,

> 1. The most important thing is that audio automation must be inside moveable parts.

Okay. Could you elaborate why? I haven't looked into the code yet but from user perspective I don't see an advantage. For first-day users it would probably be harder to figure out how the automation works and it would prohibit the drawn automation tracks to be copied between different track types (at least currently parts seem to forbid being dragged into other types).

> 3. This also means the (wave) part editor needs an automation lane editor, just like midi tracks.

Both the ones in the Arranger and the lane editor could share a common basis (in data as well as UX). Or do you mean the overall design of the automation for audio tracks should be aligned with the one of the MIDI tracks?

> 4. A question came up as to whether we should still allow automation to be drawn directly on the track
without parts. While this has some ease-of-use benefits, I believe we should eliminate that in favour of parts.
Because users will regret drawing directly on the track and then not being able to move the points as a group.

With the tweaks I want to introduce they will be able to do so :wink: . I'm still working on a proper proposal that will give an exhaustive list of user interactions available for the automation tracks. Then we can see if the overall concept will fit into Muse, something is missing or unnecessary feature creep etc.

> A word about dragging and moving the points on a graph: This is quite challenging. When you move a point,
it is currently not possible to allow it to pass other points on the graph. Thus points will end up bunching together
since they cannot pass other points that are in the way.
I overcame these challenges in the midi track automation graphs, but it was tricky.
One cannot allow a point to be dragged and dropped onto another point since only one point at a time
can exist at a given time value. Thus you will see in my midi automation graphs some (slightly awkward)
options regarding how to erase the existing points when other points are dropped onto them.
In Werner's original MusE-2 (now called evolution in our code attic), he got around this by having a button
that said "move points with parts". However when I examined this, I found it inadequate, the points should
have their own parts.

I planned to use another approach that was introduced into Hydrogen lately and I found quite intuitive and easy to use. Whenever one or more points are dragged or pasted via keyboard they enter a floating state and are painted slightly different. Floating points will only be used for visualization, not used by the audio engine when getting the next parameter value, and are allowed to live on top of existing points. As soon as the mouse release event is encountered after dragging or the positioning via keyboard is accept by pressing <kbd>Enter</kbd> the floating points will be merged into the existing list of points and all duplicates will be removed. This scales a lot better then ensuring uniqueness point by point during drag when e.g. duplicating large clusters of points as in the [blue one](https://raw.githubusercontent.com/wiki/muse-sequencer/muse/man/main_window_with_automation.png) in your docs via e.g. <kbd>Shift</kbd> + left mouse click. Plus, it groups move actions via drag or arrow keys into logical units for undo/redo for free.

**Comment by terminator356** [comment]
>  The most important thing is that audio automation must be inside moveable parts.
Okay. Could you elaborate why? I haven't looked into the code yet but from user perspective I don't see an advantage. For first-day users it would probably be harder to figure out how the automation works and it would prohibit the drawn automation tracks to be copied between different track types (at least currently parts seem to forbid being dragged into other types).

Parts would allow the points to be moved as a group. Parts are the 'containers' that would hold the points.
If a part also contains a wave event, this allows the wave and the automation points to be moved as a whole unit.
Using parts is really the only obvious logical practical solution here. Creating some new system of containment just for
 the audio automation would just complicate matters.
For this to happen, our enum EventType in type-defs.h would need a new event type: AudioController.
Thus audio controller points become actual events, just like midi controller events for which we have
 the 'Controller' EventType. The point events become part of the event list just like all other event types.

It is true that parts generally cannot be dragged onto other track types.
However, once audio automation points would become actual events in the events lists, they gain the ability
 to use all the cut/copy/paste goodness that all events have.
Then you could cut/copy/paste entire controller graphs to another part on another track - as long
 as the controller ID matches an available controller in the destination. For example, all audio track types
 have Volume and Pan controllers, so you would always be allowed to copy/paste those graphs among
 all audio parts. Beyond common Volume and Pan, if the source and destination controller ID, name,
 and plugin match, copy/paste would be allowed as well. For example if the source graph is a
 'Filter resonance' controller for a plugin 'FancySynth', and the destination track also has the same plugin,
 the copy/paste is allowed.
Thus you can see why making the points become real events held inside parts' event lists, is important.

> Whenever one or more points are dragged or pasted via keyboard they enter a floating state
 and are painted slightly different....

Yes, everything you described there is very much like what I did with our midi controller lanes in the PianoRoll
 and Drum Editor. Try it out, and you'll see the various drag/cut/copy/paste merging options that I present
 to the user via the context menu.

**Comment by theGreatWhiteShark** [comment]
> Parts would allow the points to be moved as a group. Parts are the 'containers' that would hold the points.
If a part also contains a wave event, this allows the wave and the automation points to be moved as a whole unit.
Using parts is really the only obvious logical practical solution here. Creating some new system of containment just for
the audio automation would just complicate matters.
For this to happen, our enum EventType in type-defs.h would need a new event type: AudioController.
Thus audio controller points become actual events, just like midi controller events for which we have
the 'Controller' EventType. The point events become part of the event list just like all other event types.

Okay. Do I get you right that improvements in the automation have to depend on other code changes that not have been written yet, like introducing parts for the audio output track type, and that the interaction will not be handled directly using Qt's event system but by basing it on existing internal event handling (and maybe extending it)? (Sorry, haven't looked into your code base yet.)

**Comment by theGreatWhiteShark** [comment]
This is the overall UX and all changes I have in mind.

AT - automation track
AP - point on an automation track

## Conceptual changes

### Floating state while copying

Goal: Make copy&pasting as well as duplicating both scalable and easy to use.

- Two APs are not allowed to hold the same 'temporal position'/'value' pair (maybe plus/minus a small delta)
- During pasting or dragging the APs will be in a floating state in which the user can change both 'temporal position' and 'value' (x and y) using the arrow keys or moving the mouse cursor
- APs in floating state will be painted slightly different
- After accepting the input via <kbd>Enter</kbd> or clicking at the background/releasing the mouse button the floating selection will be merged into the APs of the selected AT

### Selected vs. unselected ATs

Goal: Ease editing with large number of parameter ATs being activated at once and allow for drag selection and pasting.

- If at least one AT is activated one of them must be selected
- Only the selected AT will be painted in solid color
- Unselected AT and their AP and label will be painted transparently
- If two or more ATs are located on top of eachother, only display a single label. If one is selected, display the label of the selected one. If none is selected, it's undefined which one will be on top (its label will be shown and that particular one will be the target of hovering/click selection etc.)

## Visual changes

### Track pane -> context menu for 'Automation'

Goal: Make track colors more distinct in order to keep them apart by eye more easily.

- Use different base colors for automation tracks for _each plugin_. Using the HSV color model I would define a color range from green to blue (to keep the plugin colors apart from volume and pan), use the current green for the first plugin, and assign the color most distant in terms of hue to all previously selected colors in this range to the next plugin added. Removing a plugin clears the color selection and makes it available for the next addition.
- Use different color shades for each automation track for a parameter of _a single plugin_. Using the base color picked in the previous point and the HSV color model I would assign different value/saturation combinations to each track. There will be a minimal value of both value and saturation in order to avoid a mix up of different light-colored ATs and their distance in color space will be equally paced and depend on the total number of parameters.
- Add a 'Custom' option in the "Change color" menu which opens a `QColorDialog`.

## UX changes

### Halo around ATs and APs

Goal: Ease the editing of ATs and APs via mouse.

- While still painted the concise way currently used both ATs and APs will be affected by click-based mouse actions in a larger area
- This area is three pixels above and below an AT or a circle with a diameter of three pixel around an AT if the track height is larger than a certain value. Below, the area will be one or two pixel.
- As soon as the mouse cursor enters this area, it will be painted using the corresponding color of the AT or AP with a (larger) transparency
- Entering the vicinity of an AP beats entering the vicinity of an AT

## Exhaustive list of user interactions

### Mouse actions (in "Edit Automation" mode)
- hovering over unselected & selected AT -> static tooltip with 'parameter name' and 'value at point'
- hovering over an AP (on both a selected or unselected AT) -> static tooltip showing 'parameter name', 'temporal position', and 'value'
- clicking an unselected AT -> selects the clicked one
- clicking at the background -> clears the selection of APs
- click & drag on background -> start a rectangle selection of APs (this will only affect those on the currently selected AT)
- click & dragging (one of multiple selected) APs -> changing their 'temporal position' and 'value' based on the change in the 'x' and 'y' coordinate of the cursor position. During dragging APs will be in floating state. Releasing the mouse key merges them into the current AT.
- click & dragging + SHIFT modifier (one of multiple selected) APs -> duplicate the selection and place them at the cursor position on mouse release. During dragging APs will be in floating state. Releasing the mouse key merges them into the current AT.
- click & dragging a selected AT -> increase/decrease the value of the nearest AP to the left and to the right (including the beginning and end) by the change of 'y' coordinate of the cursor. The change in the 'x' coordinate will be ignored. Nearest APs will enter floating state.
- click & dragging an unselected AT -> selecting the AT & same as [click & dragging a selected AT]
- double clicking an AP -> input dialog, like a QLineEdit, to set the 'temporal position' and 'value'
- double clicking a selected AT -> input dialog, like a QLineEdit, to set the 'value' of the two adjacent APs (maybe two sequential dialogs of the kind of [double clicking an AP])
- right clicking -> opens the context menu
- middle clicking an AP -> deletes it

- more advanced features, like creating a plateau, a fade-in or fade-out, will be applied to a selected region when in "Edit Automation" mode via a right-click context menu or a shortcut. (In addition to the creation of regions using the general ruler, <kbd>CTRL</kbd> + click&drag could be used as well.)

### Keyboard actions (in "Edit Automation" mode)
- Pressing <kbd>TAB</kbd> selects the next AT based on the order they are listed in the Track Pane -> Automation context menu. This will be required to select a different AT if two or more are located on top of each other over their entire range (not possible via mouse).
- <kbd>CTRL</kbd>+<kbd>X</kbd>/<kbd>C</kbd>/<kbd>V</kbd> for cutting/copying/pasting the current selection of APs (selected via mouse click & drag). The temporal position of the pasted APs won't depend on the playhead but are fixed. This will be required to copy APs on different ATs of various track types (not possible via mouse). After pasting and until accepting the input via <kbd>Enter</kbd> or clicking at the background the selection will be floating. <kbd>ESC</kbd> rejects the action and discards the pasted and moved APs.
- <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>X</kbd>/<kbd>C</kbd>/<kbd>V</kbd> discards the current selection of APs, selects all APs within the Range of the selected AT, and do cutting/copying/pasting.
- <kbd>ESC</kbd> clears the selection of APs
- <kbd>Delete</kbd> deletes the selected APs
- Arrow keys -> move selected APs
- <kbd>CTRL</kbd>+<kbd>A</kbd> discards the current selection of APs, selects all APs within the Range of the selected AT, and do cutting/copying/pasting.

	
# Open questions
- What's with the MIDI tracks? Will there be a common basis?

**Comment by terminator356** [comment]
> > Parts would allow the points to be moved as a group. Parts are the 'containers' that would hold the points.
> > If a part also contains a wave event, this allows the wave and the automation points to be moved as a whole unit.
> > Using parts is really the only obvious logical practical solution here. Creating some new system of containment just for
> > the audio automation would just complicate matters.
> > For this to happen, our enum EventType in type-defs.h would need a new event type: AudioController.
> > Thus audio controller points become actual events, just like midi controller events for which we have
> > the 'Controller' EventType. The point events become part of the event list just like all other event types.
> 
> Okay. Do I get you right that improvements in the automation have to depend on other code changes that not have been written yet, like introducing parts for the audio output track type, and that the interaction will not be handled directly using Qt's event system but by basing it on existing internal event handling (and maybe extending it)? (Sorry, haven't looked into your code base yet.)

Yes, a lot would have to change or be added to support these things. But it would be a natural step.
I should have explained a bit more: We have a fundamental class Event (not related to Qt events),
 and a corresponding class EventList which holds these events.
Class Event holds all the different types of events that can appear in a song, such as midi notes, 
 midi automation controller points, midi SysExes, midi Metas, and Waves.
Each Part has an EventList which all the Events in the Part.

However, currently audio automation points are NOT represented by this class Event.
They are held in a separate list. This makes it awkward to support them.
They really ought to be represented by our class Event, so that they gain the benefits that all other Events have,
 such as cut/copy/paste and so on. They can then be placed into our EventLists like all other events.

That is what I meant when I said that Parts and Events are the most logical obvious place to
 to put these audio automation points, instead of in their own unique point list.

**Comment by theGreatWhiteShark** [comment]
> Yes, a lot would have to change or be added to support these things. But it would be a natural step.
I should have explained a bit more: We have a fundamental class Event (not related to Qt events),
and a corresponding class EventList which holds these events.
Class Event holds all the different types of events that can appear in a song, such as midi notes,
midi automation controller points, midi SysExes, midi Metas, and Waves.
Each Part has an EventList which all the Events in the Part.
>
> However, currently audio automation points are NOT represented by this class Event.
They are held in a separate list. This makes it awkward to support them.
They really ought to be represented by our class Event, so that they gain the benefits that all other Events have,
such as cut/copy/paste and so on. They can then be placed into our EventLists like all other events.
>
> That is what I meant when I said that Parts and Events are the most logical obvious place to
to put these audio automation points, instead of in their own unique point list.

I see that this is an obvious direction for Muse to develop. However, this is also quite a show stopper for me because it make it a lot more work to reuse the code in Hydrogen. I'm glad we talked about it :)

**Comment by cezaryece** [comment]
Last days I tried lot of other free DAWs exactly because of problem with editing automation in movable way.
My problem is I have midi controller with set of some sliders, knobs and pads and I am using them a lot. And once I record my live performed track I can`t move it in time because of recorded automation.

In fact connecting controls features from my controller to instrument`s controls in MusE is best I have found in other DAWs, including even Ardour (maybe in LMMS is good too, at last simpler). In many DAWs it is limited to standard MIDI controls or does not have autorecognition.

Rosegarden has very good features of editing automation than all other (take a look at it), but in other areas it is far behind after MusE. Same with QTractor and LMMS. In some areas they are better, in other areas worse. Live... Nothing is perfect.

I am dreaming that some day someone will bring all best ideas of all free DAWs into one project and made best free DAW all the time.

**Comment by theGreatWhiteShark** [comment]
Hey @terminator356 ,

How should we proceed with this issue for now? Shall I close it?

I'm still interested in polishing the UX of the automation editing. So, if you could ping me once the internal changes are done I will check whether I have time to do some work.

For reference: I did some (dirty) custom changes https://github.com/theGreatWhiteShark/muse/tree/phil-automation-ux by 1)  doubling the detection radius of the automation events and 2) introducing a dialog for setting the frame and value of an automation event via keyboard when double clicking it. At least for me this allows me to use the Automation more convenient now.

**Comment by terminator356** [comment]
Those changes might take quite a long time. I am waaaay behind on all the branches and code I am working on.
Poor @spamatica is waiting for me to finish one code I've been working on for several months, before next release ;-)

Hey great that you have some changes. A dialog where precise values can be entered is cool.
How about when you are confident and satisfied with the work, submit a pull request and we might merge it?

**Comment by theGreatWhiteShark** [comment]
> Those changes might take quite a long time

I'm counting on them to take a while. The more time passes, the more grown up the child will be, and the more time I'll have to invest here. :wink: Don't worry. I'm quite happy with MusE and won't switch applications or quit doing musics any time soon.

 > Hey great that you have some changes. A dialog where precise values can be entered is cool.
How about when you are confident and satisfied with the work, submit a pull request and we might merge it?

Sure

**Comment by terminator356** [comment]
Hi just an update, I am working on the audio automation.
I posted a progress pic and some info in the forum about a month ago.
Hang in there, hope to have something soon-ish. It's tough!

In the meantime I would like to point out that all synthesizer track
 audio automation controllers can be controlled by midi automation graphs.
In the PianoRoll Editor and Drum Editor look closely at the list of available
 midi controllers to show in the controller graphs.
We 'emulate' all the synth's available audio controllers and give them
 arbitrary midi controller numbers waaay up in the NRPN range.
It's not perfect (no interpolation like the audio controllers) but it can help.

**Comment by theGreatWhiteShark** [comment]
Nice! Thanks.

And sorry for opening a PR with the custom changes yet. I'm quite busy lately.

Is there still need for a dialog to change an individual automation node or is this already superseded by/conflicting with your changes? (For me personally it helped a lot to ensure points are of the same height.)
