### ISSUE TITLE
Keyboard-shortcuts sometimes not working

### ISSUE THREAD

**Issue by Tutorius** [muse-sequencer/muse#1026]
**Describe the bug**
When editing music, it is vital to be able to start and stop playing with keyboard shortcuts. When locating the mouse over the play-button, it tells that "Space" ist the shortcut to use, but the space works in some moments, and othe rmoments the play can not be started by the Space-key.

**To Reproduce**
1. Start a project and work on it, adding tracks, editing and so on.
2. Press the space-key from time to time to start playback
3. It works in some cases, but not every time, and i am not able to see whats the reason that it might not work

**Expected behavior**
The Shorcuts should work in every situation

**Screenshots**

**Desktop (please complete the following information):**
Arch-Linux, using Mate as Desktop with GDM as Login-Manager, using different kernels, from Linux, LTS and Realtime

**Additional context**

**Comment by spamatica** [comment]
I made a recent Issue about space and one component in the mixer-strip stealing keypresses. I'm not up to date on the final outcome..  Could this be the same issue?

**Comment by Tutorius** [comment]
Yes, i think this may be the same issue... I have not found out what part was stealing keypresses, i will keep an eye on it...
