### ISSUE TITLE
[Feature Request] A way to blacklist plugins

### ISSUE THREAD

**Issue by dlzi** [muse-sequencer/muse#1027]
It would be a nice touch if we could hide or blacklist plugins from appearing in the plugin/synth dialog or even being loaded. This way I can prevent some bad boys to crash MusE.

**Comment by cezaryece** [comment]
I am voting for this too. Specialy in L:inux when you can install many many different set of plugins and list is very very long. Then even favorite list is not enough. Sometimes I like only one plugin from all set and dont want to uninstall whole set. In this case I`d like to select multiple plugins and hide them making list more usable.

**Comment by oldcastlehq** [comment]
This is a good feature. Any updates?

**Comment by spamatica** [comment]
Indeed it would be, I've been working on this, hope to have something in a bit
