### ISSUE TITLE
Web pages linked in Help menu

### ISSUE THREAD

**Issue by cezaryece** [muse-sequencer/muse#1031]
- Ubuntu Studio 21.04 (Plasma Desktop/KDE)
- default web browser - Chrome

Problem - any link in Help menu does nothing else Chrome is trying to start and disappears after few seconds.
Any other application has not such problems.

In effect Help menu is almost unusable.

**Comment by cezaryece** [comment]
Now I notice that this problem is with AppImage only. Installed version load web browser properly.

**Comment by kybos** [comment]
I could reproduce with with Firefox as well (on Manjaro/KDE).
It's an inherent AppImage problem for which there is no proper solution, despite the issue obviously having been known for years.
I tried to solve it by a workaround in our code, please check if it works for you too.

**Comment by cezaryece** [comment]
it`s working
