### ISSUE TITLE
Custom themes with AppImage

### ISSUE THREAD

**Issue by thoth-amon** [muse-sequencer/muse#1032]
Currently with the AppImage, you can't select a custom qss file because the selection is stuck to a read only folder. It would be helpful if there was a similar way for the themes as there is with the custom colours when you press the Load All button, which allows you to browse the file system.

**Comment by kybos** [comment]
It' now possible to have custom themes in the HOME folder (~/.../themes/...). Just copy your user theme (the .qss file) in there, it should be available in the standard theme selection in Appearance->Themes then.

**Comment by midiaudio** [comment]
What is the exactly path? Now I'm using the MusE  4.0 (AppImage version) and I can't add new themes.

In my home folder I have the next folder: `~/.config/MusE/MusE/themes `

In that folder I add the [Xcolors](https://gitlab.com/lam604/audiothemes) theme but it don't appear in the menu selection.

**Comment by thoth-amon** [comment]
The path was added after 4.0. There is a pre release version here https://github.com/muse-sequencer/muse/releases where it should work.
