### ISSUE TITLE
How to do automation?

### ISSUE THREAD

**Issue by oldcastlehq** [muse-sequencer/muse#1035]
Hi,

LinuxMusicians is down, so I'm asking this stupid question here. How do I do automation? I really cannot see it? Does it "add" a track below (like Ardour) or does it happen on the top of the file (like Qtractor)?

**Comment by thoth-amon** [comment]
https://github.com/muse-sequencer/muse/wiki/Documentation#automation

That link should help. Audio and MIDI are edited differently.

**Comment by oldcastlehq** [comment]
I checked the doc, but still it doesn't show how to do it.

**Comment by spamatica** [comment]
The documentation could be improved...

You can check this video, 
https://www.youtube.com/watch?v=4re2iWdKNzM&list=PLZ9h4Km-GCNYcylMk20a6ZbOSjDMYLEQa&index=10
after 11 minutes or so it describes both how to edit midi controllers and audio automation.

It's for a old version of MusE but it should be possible to undestand
I did make some new videos a few weeks ago but I didn't get to describing automation in MusE 4 yet.

**Comment by oldcastlehq** [comment]
I got it. It's easy once its explained! :-)

Thanks!
