### ISSUE TITLE
[Feature Request] Time stretching/shrinking for midi/drum parts

### ISSUE THREAD

**Issue by cezaryece** [muse-sequencer/muse#1037]
Sorry if it is possible right now and I dont know how to do it, but if it not possible I vote for that possibility.

If it is possible just tell me how I can adjust duration of some midi part.
Let say I have 2 bars with 4 quarter-notes each (2 x 4 = 8) and I would like to get 3 bars with same 8 quarter-notes shifted in time to fill 3 bars.

**Comment by spamatica** [comment]
There is currently no way to stretch midi dynamically.
Our scripting interface could be used to make such a stretch tool. Currently there are the related scripts doublespeed and halfspeed.
