### ISSUE TITLE
Auto correct wave files according to sample rate [sf#1157685]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#105]
Submitted by jonnymind on 2005-03-06 13:06:29

I tried to import a series of waves in various  
formats and rates (44100, 48000, mono, stereo,  
16, 24 and 32-bit float) in a wave track. Although  
the thing works, the pitch of the waves (and their  
duration) is changed of about a semitone and  
half. A E minor tonality becomes something  
imprecise inbetween F minor and G minor. This  
is quite annoying, as the waves sampled from  
instruments cannot be mixed with the midi  
synthesis, that is more or less what muse is for.  
  
I upload one of the files that sounds at correct  
pitch with aplay, play and audacity, but whose  
pitch is altered in  MUSE.

**Comment by danboid** [comment]
+1 for muse offering to re-sample imported audio that does not match the JACK session samplerate.

**Comment by danvd** [comment]
It's not hard to do. The code for this is already here - SimpleDrums open wave file dialog can autoplay selected samples and resamples them on the fly. So it surely can be done for general wave import!

**Comment by danboid** [comment]
Good to hear Andrew! Maybe this will make it into 3.0 then?

**Comment by danvd** [comment]
Hi dan!

Now I'm doing ths task - It will be ready soon. 
Again thanks for all your issues - most of them are very very useful. We will implement (and answer) successively to all of them.

**Comment by danboid** [comment]
Great news Andrew! I look forward to testing that soon!

I'm glad you decided to work on this first as IMO its this and muse's current lack of ability to re-order tracks that stand out to me as being the most widely useful addition/change of the 20 or so issues I've raised in the last few days, provided I'm not missing something there?

Thanks for continuing to support and improve Muse!

**Comment by danvd** [comment]
Hi Dan,

Ok, I made it and pushed changes to master branch.

How it works:

1. Wave file now can be prelistened before import (directly from import dialog). It will be autoresampled on the fly while playing.
2. When importing if wav's sample rate != project's sample rate then MusE will ask to resample it. 
3. Resampling is made by meens libsamplerate with sync best quality resampler.
4. If output clips somewhere, resampling is restarted automatically and normilizes output to be in range [-1.0, 1.0]. 
5. Now there is no need to create ampty wave track - it will be created automatically if none selected.
6. Resampling process can be cancelled at any time.

Test it. If it's ok, than I'll move to next issue ;).

**Comment by danboid** [comment]
Hi Andrew

I've just tried the new wave import/resample code and it seems to be working great thanks! I love the preview and that I don't need to create a wave track first - all good stuff!

If I could request what you look at next then it'd be bug #406 please as I can't carry on with my current muse project until that gets fixed.

I think we can close this issue now at least!

Thanks v,much!

**Comment by danvd** [comment]
Ok, I'm closing this issue then :)
