### ISSUE TITLE
Parameters reset by scripts

### ISSUE THREAD

**Issue by FalCT60** [muse-sequencer/muse#1050]
**Describe the bug**
Some scripts - at least Humanize and RandomizeVelocityRelative which I am focussed on - reset the parameters of the tracks they are applied on

**To Reproduce**
1- Create a track with PAN=16, MainVolume = 100, chorus = 32, PC = 2-4-58 and add notes to be played
2- Play the track so as to be sure it sounds like it should
3- Apply RandomizeVelocityRelative with its standard value to the track
4- Play the track : nothing can be eared but very low ticks where notes should be eared playing
5- Open Event List : PAN = -64, MainVolume = 0, Chorus = 0, PC = 1-1-1

**Expected behavior**
PAN, MainVolume, Chorus and PC (as well as others that could be set) ought have been unmodified by the script

**Desktop (please complete the following information):**
 MusE 4 from GIT main, Ubuntu 20.04, Gnome

**Additional context**
It is still possible to part the parameters from the rest of the track before applying the script, but it will not help preserving the parameters that may exist in other places in the track.

**Comment by spamatica** [comment]
Thank you for this report, there was a typo in the read-back of controller values, causing them to be reset. It should be fixed now in git master.
