### ISSUE TITLE
AppImage doesn't work on Manjaro

### ISSUE THREAD

**Issue by oldcastlehq** [muse-sequencer/muse#1058]
The latest AppImage doesn't work with Manjaro. The error when I run the file is:

    /tmp/.mount_MusE-m4Zar79/AppRun.wrapped: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by spamatica** [comment]
There seems to be plenty of AppImages bitten by this. Manjaro, being a bleeding edge distro looks to be among the first to update to glib2 2.70, which seems to be the source of the problem. 

Trying to find the way to fix it.

**Comment by spamatica** [comment]
Please check if the current master works for you. It should include more gtk dependencies to fix this issue.

**Comment by oldcastlehq** [comment]
All good now. Thank you!
