### ISSUE TITLE
Is necessary create a wca file on the original sample path?

### ISSUE THREAD

**Issue by midiaudio** [muse-sequencer/muse#1060]
When I import a .wav sound MusE resampling the file and create a copy of it. After that MusE create a special file `wca` (peak info) associated with the .wav file but create two copies of `wca` file: one copy in the MusE project folder and another copy in the folder where the original .wav sound is.  

**Expected behavior**
MusE should create only one `wca` file (in the MusE project folder)

**Desktop info:**
 - OS: Debian 11
 - MusE: appimage 4.0

**Comment by spamatica** [comment]
Added a cleanup phase when resampling so the unused wca file is removed.

**Comment by midiaudio** [comment]
> Added a cleanup phase when resampling so the unused wca file is removed.

Was this feature added a most recent AppImage build? And Where is it?

**Comment by spamatica** [comment]
Yes, sorry for being unclear. It is checked into the current master so it should appear in the most recent AppImage.
