### ISSUE TITLE
Bump the release for having some the useful changes such as "theme directory" and etc.

### ISSUE THREAD

**Issue by thunderbirdtr** [muse-sequencer/muse#1064]
Hello, It would be really nice to have version bump If possible so we can have some of the quality of life changes in Muse so we can also bring it to downstream in Fedora as well as others distributions too.

Fedora backport MR : https://src.fedoraproject.org/rpms/muse/pull-request/4 

Thank you.

**Comment by ash57005** [comment]
I would love this as well. As a music producer in fedora i'd love the theme directory and other features.

**Comment by spamatica** [comment]
Indeed, others have noted this also, and I agree. As usual it's been far too long.  
I'm aiming to finalize a release in the coming weeks.

**Comment by thunderbirdtr** [comment]
> Indeed, others have noted this also, and I agree. As usual it's been far too long.  
> I'm aiming to finalize a release in the coming weeks.

Awesome waiting for release so we can push into Fedora as well.

**Comment by thunderbirdtr** [comment]
Awesome, now I can make a PR for upgrade then :) thanks for work
