### ISSUE TITLE
Some cloned parts are wrong with latest Muse-Master (appimage)

### ISSUE THREAD

**Issue by farvardin** [muse-sequencer/muse#1073]
**Describe the bug**

Latest Muse-Master.appimage (8737c4d from 24 may 2022) is not correctly displaying some cloned parts: the notes are simply missing.
The latest 4.1 version (appimage) can load the tune correctly.

**To Reproduce**
Some cloned parts are ok, some others are not, I can't really understand why. I've just loaded an old tune (made with Muse 4.0)

**Expected behavior**
Muse should load all my cloned parts.

**Screenshots**

from muse-master:

![image](https://user-images.githubusercontent.com/477243/172073336-2e18a808-9a22-4055-9be3-530e031bb216.png)

from muse 4.1 :

![image](https://user-images.githubusercontent.com/477243/172073503-bb2aa157-5c43-42ec-a288-862f739dead4.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Desktop: Mate

**Additional context**
I'll send you the file by email

**Comment by terminator356** [comment]
Observed. Thanks for the file.
This is most likely my fault, since in my last commit I re-worked some old clone code.
Hang in there... I'll try to debug it soon...
Tim.

**Comment by terminator356** [comment]
Should be fixed now. It was a typo in my last commit.
Your song seems to load fine now. Let me know if any more trouble.
Thanks very much for the report!
Tim.

**Comment by farvardin** [comment]
well done, thank you Tim!

**Comment by StaffanMelin** [comment]
Issue fixed by Tim.
