### ISSUE TITLE
Muse not restarting at start of song or start point when using a "Schleife"

### ISSUE THREAD

**Issue by Tutorius** [muse-sequencer/muse#1074]
![Bildschirmfoto zu 2022-06-05 20-38-42](https://user-images.githubusercontent.com/85613003/172198456-e6135b61-203c-43f6-84f2-38314ee3e8bf.png)
**Describe the bug**
When activating the blue icon for repeated play (Schleife in germany) and pplay a song so long that it is repeated:
Stopping the play brings the play bar to a point very slightly behind the starting point, so wehen you start the play, it misses the first note(s).

**To Reproduce**
1. create a midi-pattern
2. insert some notes (one direct at the beginning)
3. set "repetition" by using the blue icon with the circle-arrows
4. set start and endpint of the repetition
5. start play, and wait for the first repetiotion to take place
6. stop
7. Look at the read play-bar. Zoom in to see the small sace between start and red bar

**Expected behavior**
When stopping, a new play should start at the start-point or the song-start
![Bildschirmfoto zu 2022-04-18 13-01-38](https://user-images.githubusercontent.com/85613003/172197937-3235889f-1d28-481e-86b4-8355a8647fd3.png)

**Screenshots**
Screenshot added
**Desktop (please complete the following information):**
- OS : Arch Linux
- Desktop: Mate 

**Additional context**

**Comment by Tutorius** [comment]
Please forgive the wrióng screenshot with the modular synth. Was not able to delete it.

**Comment by StaffanMelin** [comment]
Yeah, I've noticed too that the cursor/play marker doesn't always exactly line up to a bar.
