### ISSUE TITLE
File > New > Abort does not abort

### ISSUE THREAD

**Issue by theGreatWhiteShark** [muse-sequencer/muse#1087]
**Describe the bug**
Triggering `MusE::fileNewAction` with changes present in the current project opens a popup dialog asking the user whether to save the changes. The dialog has three buttons labelled "Save", "Skip", and "Abort".

What exactly is "Abort" supposed to do? Just by the looks of the dialog I thought it would cancel the loading of the default template and keeps the current project intact (I hit its shortcut by accident). But when looking at the code it does not seem to be intended to cancel anything. (Seems like it is used to make the current project instead of the default template the basis for the new project. But I just skimmed through that part).

How about either making "Abort" cancel the action or introducing a fourth button for this purpose?

**To Reproduce**
1. Modify an existing song
2. Hit <kbd>Ctrl</kbd>+<kbd>N</kdb>

- Using code at b887a8769cf06ab47c5d0f0985264e685c19fed4

**Comment by spamatica** [comment]
The Abort option should absolutely do Cancel. In my testing it did do that.
There was however a bug that caused the flag keeping track of the project being edited to be cleared when Abort was clicked.
I have fixed that bug and renamed the alternatives to "Save" "Discard' "Cancel", which seems more standard.

If you still find it doesn't work, reopen the bug.

**Comment by theGreatWhiteShark** [comment]
Thanks a lot! Works like a charm
