### ISSUE TITLE
4.1 appimage from arranger cannot copy/paste track or part of it

### ISSUE THREAD

**Issue by revolverve** [muse-sequencer/muse#1088]
Neither audio or midi track copy/paste work from arranger.
Copy/paste works in 4.
Only tested appimages,
From latest 4.1 , create a midi track,a part, select it,ctrl c bring the cursor  to end of selected part ,ctrl v make the cursor return to  beginning but nothing is copy.
  Shortcuts within part editor does work.

**Comment by terminator356** [comment]
Ehm, observed, how did that happen... It must be my fault (of course).
Most likely when I reworked the audio controller graphs a few months ago,
 which included new copy/paste features.

Checking... Thanks very much for the report...

**Comment by terminator356** [comment]
Yup. For 5 months, missing an equals sign in functions.cpp: parseArrangerPasteXml().
Seems OK now. I'll close for now, please reopen if any more trouble.
Thanks!
T.

**Comment by revolverve** [comment]
A1+
Thanks for your work.

**Comment by drautzburg** [comment]
I ran into the same problem. Therefor I cloned MusE from Github and compiled it, but still cannot copy/paste. Paste moves the cursor to the beginning of the song, that's all it does. Am I doing something wrong?

This is the version I have:
`Branch:		master`
`Tag:		4.1.0-81-g76c08672-dirty`
`Commit timestamp:	2022-10-27 21:48:03 -0400`

**Comment by spamatica** [comment]
Indeed, trying it now copy/paste does not work with midi parts. For wave parts I can get it sometimes. Not sure what the triggering factor is.
Don't think I can figure it out at the moment, I'll reopen anyway.

**Comment by spamatica** [comment]
I can add that drag copy (using CTRL+mouse) seems to work.

**Comment by drautzburg** [comment]
Can I create "clones" this way too?

**Comment by revolverve** [comment]
Hmmm , how do you plain know exact version release of muse in an appimage?

Let's check latest appimage; from 14 days ago.. copy paste works here on midi tracks or wave tracks.
drautzburg
Cannot help as i never succeeded at compiling muse.
What's your os?

**Comment by drautzburg** [comment]
@revolverve I'm using Linux. I did `git clone http...` with the url given on the github page and then ran compile-muse.sh. That's it.

Furthermore I checked that the _missing equals sign_ that terminator356 mentioned was actually in the sources (it was in a file called `functions.cpp`). Apparently, more is required to fix this.

@terminator: I didn't know about `Ctrl+mouse` to copy parts. Thanks for pointing this out to me. It turned a showstopper into a mere nuisance.

**Comment by spamatica** [comment]
> Can I create "clones" this way too?

Yes, alt+ctrl+mouse creates a clone.
If it is already a clone ctrl+mouse will also make a clone

**Comment by terminator356** [comment]
Apparently I only tested pasting objects that were copied at position 0 to a new position.
Had I copied objects that were not at position 0 I would have seen it was not fixed.
What a pesky small section of code. For some crazy reason I had trouble with it the first time around too.

Should be OK now (no really!). 
Tested OK copy and paste with multiple objects at different positions.

Hey you Musers ! Thanks very much for spotting that, again.

Sometimes I am so deep into some other fixes and don't have time to actually use the application
 even in its simplest ways.

**Comment by drautzburg** [comment]
I recompiled MusE and copy/paste works.

**Comment by terminator356** [comment]
Good. I'll close for now. Please re-open if any trouble.
Thanks.

**Comment by revolverve** [comment]
Debious here.. i miss somehow something ,great anyhow if solved .
It  was an half of the context question;
 how do you plain know exact version release of muse in an appimage?

 ./MusE-master-x86_64.AppImage -v
-> 10:40:24.422 Read configuration...
Config File </root/.config/MusE/MusE/MusE-seq.cfg>
MusE 4.1
  just a curiosity, no pre-release version details ? not a problem.
I enjoy Muse , solving the timing problems is he hardest one , too much computer not enough music ; )
  Thanks

**Comment by spamatica** [comment]
> just a curiosity, no pre-release version details ?
Good point we should make the build from master show that it is a development build
