### ISSUE TITLE
Wave Edit Segmentation Fault on AppImage

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#1110]
**Describe the bug**
Using the Ver 4.1.0 AppImage, Muse will crash with a Segmentation Fault message when trying to reverse a wav file in Wave Edit.

**To Reproduce**
1. Go to 'File->Import Audio File' and select any WAV file. My file is 3 secs long
2. Go to 'Edit->Wave...'
3. In Wave Editor select 'Edit->Select All'
![image](https://user-images.githubusercontent.com/14888092/211511988-306f6168-ae7c-40a6-9f9f-2fb16181c0fc.png)
4. Select Functions->Reverse Selection and crash. Happens consistently.

> qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 8459, resource id: 3617960, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault (core dumped)

**Expected behavior**
Reverse the wave shape

**Desktop (please complete the following information):**
 - OS: tumbleweed release 20230103
 - Desktop xfce

**Comment by terminator356** [comment]
Hi. Terribly sorry for the very late reply.
I am unable to reproduce this, at least with latest master code.
Are you still having trouble?

**Comment by therealkitman** [comment]
Hi. Just tried again on a few different WAV files and I had no issues this time.

Could it have been a driver issue from the OS itself?

I'll close this.

**Comment by terminator356** [comment]
Hard to say. Many fixes over the last several months.
But there is always the possibility of intermittent bugs lurking in there, waiting to show up...
Let's keep watch for trouble.

**Comment by therealkitman** [comment]
Just to clarify, I am still using the AppImage Ver 4.1.0 from April 2022 (that's still the latest one). So between now and last January my tumbleweed OS has had MANY updates.

**Comment by terminator356** [comment]
I am on Tumbleweed as well. 
I've always been a fan of Suse for a long time. 
I like other distros too, but I was buying boxed sets of Suse long ago. Remember boxed sets?

It is highly recommended to grab the latest MusE AppImage or build from source.
There have been very many critical updates and fixes since then.
We are long overdue for a new official release.
