### ISSUE TITLE
View/edit multiple midi segments

### ISSUE THREAD

**Issue by io7m** [muse-sequencer/muse#1114]
**Is your feature request related to a problem? Please describe.**

When editing complex overlapping instrument parts (such as anything involving counterpoint), it's often extremely helpful to be able to at least see the notes from multiple instruments when editing.

**Describe the solution you'd like**

Something like this:

![layered](https://user-images.githubusercontent.com/612494/218307647-3476c010-52d9-4c3b-b756-df51210ad1f9.png)

Note that `Track 1` is the currently selected track and so is editable and the notes are displayed at full opacity. `Track 2` is not selected, and so the notes aren't editable but are at least visible so that I can see them in relation to the notes of `Track 1`. [Rosegarden](https://rosegardenmusic.com/) already implements this, as do most of the commercial DAWs.

**Describe alternatives you've considered**
I've tried to do without this feature in many DAWs, but editing complex parts is just too painful without it.

**Additional context**
None.

**Comment by spamatica** [comment]
Hi there and thanks for trying it out!

If I understand you correctly I think we do support what you want though.

This is with three parts selected (Pressing Ctrl+E to open them in the piano roll)
![image](https://user-images.githubusercontent.com/4476983/218309589-af5927d8-a3b1-4939-bef9-f6a46c5edbc4.png)

**Comment by io7m** [comment]
Oh, wow! I didn't realize that. I tried shift-selecting to open, and only got one of them.

I'll try this in a bit.
