### ISSUE TITLE
Cannot clone midi part

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#1120]
This concerns MusE compiled from source yesterday, after a git pull

```
Branch:		master
Tag:		4.1.0-127-g0d2cf691-dirty
Commit timestamp:	2023-05-29 17:25:10 -0400
```
When I copy (Ctrl-C) a midi part and paste it as clone (Ctrl-B), the inserted part is really a copy and not a clone. 

The dashed outline is absent, the menu options "select clones" and "De-clone" are inactive and it does not follow changes made to the original part. The same thing happens when I use the Edit menu (Copy, paste special) to clone the part.

**Comment by terminator356** [comment]
Thank you very much for catching that. My fault again from early 2022. (The automation graphs overhaul.)
I cannot believe I missed that. Things got messed up in the last few years. It's better now (than ever?).
But this one I am disappointed in. Because that coding was intense and I was sure it was OK.
Another reason is 'cause now I am trying to not only decode what the heck I was trying to do
 in that tricky code, but also fix it. ;-)
To be continued...

**Comment by drautzburg** [comment]
I am quite pleased with the current system of me finding the bugs and you fixing them.

**Comment by terminator356** [comment]
Hello Martin @drautzburg Sorry for the delay. Quite tricky fixes.

Fixes have now been pushed to git master.
Several pieces of code needed fixing, including one very old (10 years) section, 
 unknown who or what put it there...

The system handles a couple of rare but possible situations gracefully now:
1) Copy some clone and non-clone parts. Then delete them. Then paste.
Previously it stumbled, but now it faithfully recreates the necessary parts and clones
 even when the original parts have been deleted before pasting.

2) Copy say, two parts that are clones of each other. Then de-clone one of them. Then paste.
Previously it stumbled, accidentally making a clone again of one of the originals.
But now it faithfully recreates the necessary clones without altering the originals.

Give it a try and as always let me know if any trouble.
Thanks.

**Comment by drautzburg** [comment]
I didn't try the procedures 1. and 2. but I can confirm, that regular cloning of parts works now.

**Comment by drautzburg** [comment]
Closing issue
