### ISSUE TITLE
Song part definitions [sf#1226923]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#115]
Submitted by plixplox on 2005-06-24 13:12:50

My suggestion is to enable the user to define song
parts that are visible and changeable. With song parts
I mean the parts of a song, like intro, chorus, solo,
outro and so on. These individual song parts are
displayed in the Part Canvas (in different colors,
maybe in connection with self-explaining icons), and in
all other windows that represent (parts) of a MusE song
file or tracks. In the Part Canvas, in terms of layers
these song parts are positioned below the track parts,
and - this is now seen from a perspective of somebody
who is looking at a screen: 

a) the individual song part names are shown below the
lowest track. 

b) the names of the song parts are shown above the bar
indicator.

The size (and the position) of a song part can be
changed by dragging the song part edges. Such a change
does not affect the current arrangement of tracks and
parts within the tracks. This enables you make a song
part longer or shorter, while the song itself (the
track material) does not get changed.

Song parts can always be renamed. The colour of song
parts can always be changed.

**Comment by kybos** [comment]
Introducing another entity of this kind seems like a huge effort without much use to me...
