### ISSUE TITLE
Ubuntu 22.04 LTS: MusE is stuck on the "Populating Track context menu" screen

### ISSUE THREAD

**Issue by novaTopFlex** [muse-sequencer/muse#1234]
I am sorry, but I do not understand why the MusE application fails to proceed beyond the "Populating Track context menu" screen. I have attempted to try again with the recommended dependencies in addition to the required, but MusE still fails to launch (I am currently using MusE 4). Why am I stuck on this screen, unable to actively use MusE 4 on Ubuntu?

**Comment by terminator356** [comment]
Hello. 
Please run MusE in a terminal with the -D option (debug mode) and post the output that you get.

If you are using the official version 4 release, you could try compiling the latest github master branch. 
Many fixes have been applied since the latest official releases.

**Comment by DevMonkeyTennis** [comment]
I installed ubuntu studio controls and used it to configure realtime and startup settings and that resolved this exact problem, the error that causes the startup crash is to do with pulseaudio and jack not being configured correctly

**Comment by spamatica** [comment]
Alright! Thanks for letting us know. Configuring audio is not always a walk in the park :)

I will close this ticket then.
