### ISSUE TITLE
Qt6 port

### ISSUE THREAD

**Issue by edpil02** [muse-sequencer/muse#1239]
Port to qt6

Is there a plan to port muse to qt6.
I think it shouldn't be difficult, because without knowing QT  programming I managed to do a basic port in one day. Now I'm looking for bugs.
Thanks.
![muse](https://github.com/muse-sequencer/muse/assets/43163048/63e1fb78-ccd4-4410-8c41-86885ac41408)

**Comment by spamatica** [comment]
Looks good. 
As far as I know there is no current work with moving to qt6 so feel free to submit your work as a pull-request when you feel ready!
