### ISSUE TITLE
[fix_linux_vst_param branch specific] saved plugin parameters reset to default values on loading

### ISSUE THREAD

**Issue by devloop0123** [muse-sequencer/muse#1272]
**Describe the bug**

Just a heads-up in fact, since I realize this branch is a work in progress....
Specific to the WIP branch fix_linux-vst_parameters: 
Loading a project resets custom plugin parameter values to their defaults.

**To Reproduce**
1. Create new project.
2. Add Calf LV2 EQ plugin
3. Save project
4. Open Calf UI. Generic or Native is irrelevant.
5. Change any one parameter.
6. Save new revision, project_001
7. Compare project and its revision with diff
8. Notice change to parameter has been saved correctly
9. Close MusE
10. Open MusE, open project_001
11. Immediately save new revision, project_002
12. Compare project_001 with project_002 with diff
13. Notice that the adjusted parameter has been reverted to its default value in project_002 

**Additional context**
Calf EQ LV2 is just an example. Using Monitoring2 VST results in the same behaviour.

**Comment by terminator356** [comment]
Thanks. Yes, a big massive work in progress ;-)

I just wanted to warn if testing **this branch**:
Major song file changes have been made.
See the notice: 
https://linuxmusicians.com/viewtopic.php?t=27021

Thanks.
Tim.
