### ISSUE TITLE
Focus doesn't return to the arranger window when the pianoroll is closed.

### ISSUE THREAD

**Issue by toadzrock** [muse-sequencer/muse#1287]
I have a project open in the arranger. I can use keystrokes normally as the window has the focus.

I then open the pianoroll, using a shortcut, to edit a segment.

I then close the pianoroll, expecting the arranger window to again take the focus, and be able to use keystrokes automatically. But I can't. I have to "touch" the arranger window again, usually with the mouse, to give it back the focus.

Debian 12
XFCE 4.18
Muse-4.2.1

**Comment by terminator356** [comment]
I pushed a fix to master branch.
When any TopWin closes, the focus is directed to the canvas (the drawing area) of whichever 
 TopWin now obtains the focus.

Try it out, lemme know if any trouble.

**Comment by toadzrock** [comment]
That works. Thanks.
