### ISSUE TITLE
[Solved, I think] Muse freezes when I attempt to change track colors.

### ISSUE THREAD

**Issue by toadzrock** [muse-sequencer/muse#1291]
When i try to change the color for tracks, no popup window appears, and muse freezes. (Latest git code at the time of posting this bug report)
This is also the case when I select "Appearance" , and attempt to change the color defaults.

Here's the terminal failures that appear.

(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: cannot register existing type 'GtkWidget'
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: cannot add class private field to invalid type '<invalid>'
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: cannot register existing type 'GtkBuildable'
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(muse4:26254): GLib-CRITICAL **: 13:09:07.297: g_once_init_leave_pointer: assertion 'result != 0' failed
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.297: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.298: g_type_register_static: assertion 'parent_type > 0' failed
(muse4:26254): GLib-GObject-CRITICAL **: 13:09:07.298: cannot add private field to invalid (non-instantiatable) type '<invalid>'

 - OS: Debian Trixie. (testing)
 - Desktop XFCE.

The Debian package version of Libglib2.0 and Libglib2.0-dev is 2.82.2-2.

The GTK2 version is 2.24.33-6 (including -dev)

The GTK3 version is 3.24.43 (including -dev)

The GTK4 version is 4.16.3 (including -dev)

In case it's relevant;

The libgtkmm-2.4 version is 2.24.5

The libgtkmm-3.0 version is 3.24.9

The libgtkmm-4.0 version is 4.16.0

*********************************************************************************

EDIT: I've just tried the master appimage (latest version), and that crashed with a GTK2 error.

jack@jack:~/Downloads$ ./MusE-master-x86_64.AppImage
-> 14:13:25.428 Read configuration...
Config File </home/jack/.config/MusE/MusE/MusE-seq.cfg>
New Qt locale: en_US
-> 14:13:25.552 Load theme...
Config File </tmp/.mount_MusE-mi6wTl4/usr/share/muse-4.2/themes/Dark Flat.cfc>
-> 14:13:25.558 Scan plugins...
Initializing Native VST support. Using VESTIGE compatibility implementation.

pluginScan FAILED: waitForFinished: file: /home/jack/.vst/OT P1ANO S.so

-> 14:13:47.660 Init audio...
Denormal protection enabled.
Select audio device from configuration : 0
User JackAudio backend - backend selected through configuration
MusE:initJackAudio: jack_get_version() returned zeros. Setting version major to 1.
Using Jack
-> 14:13:49.047 Init MIDI...
-> 14:13:50.133 Init plugins...
-> 14:13:50.134 Init VST plugins...
-> 14:13:50.134 Init native VST plugins...
Initializing Native VST support. Using VESTIGE compatibility implementation.
-> 14:13:50.135 Init DSSI plugins...
-> 14:13:50.135 Init LV2 plugins...
Gtk-Message: 14:13:50.301: Failed to load module "atk-bridge"
/tmp/.mount_MusE-mi6wTl4/AppRun.wrapped: symbol lookup error: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libgail.so: undefined symbol: g_once_init_enter_pointer

So I added the -2 switch to stop LV2 plugins from being loaded, and the appimage worked. (I assume this might be a GTK2 error for older LV2 plugins.)

However, when I tried the same thing with the git build, it didn't make a difference. Muse4 froze and I got the same original error message.

**Comment by toadzrock** [comment]
i've started again with building a new pull of git, and undoing the changes I made to CMakeLists.txt.

With a default install, Muse built ok, and the color palletes have reappeared without a problem.


The biggest change i made was installing the Kvantum theme. (for both qt5 and qt6) And, given a couple of conversations here, and in the linuxmusicians forum, about potential problems with Fusion versus Windows, i'm wondering if that made the difference.

Anyway, it seems to be ok, so I guess i'll mark this as solved for now.

**Comment by terminator356** [comment]
Thanks very much for the tests and good to hear it's working now.
Yes, as you see reports have come in about GTK and so on. 
It doesn't seem to be MusE's fault, but I'm not sure what we could change to help the situation.

Close when you are satisfied that it is stable now.

**Comment by toadzrock** [comment]
> Thanks very much for the tests and good to hear it's working now. Yes, as you see reports have come in about GTK and so on. It doesn't seem to be MusE's fault, but I'm not sure what we could change to help the situation.
> 
> Close when you are satisfied that it is stable now.

So far so good, so i'll close this now.

**Comment by toadzrock** [comment]
Closed as solved.

**Comment by terminator356** [comment]
Hi all.
There is some news on this: The problem was observed. See #1303 for reference.

MusE has a setting in the Appearance dialog under the Themes tab.
It is called 'Use Native Standard Dialogs'. It is on by default.

Please try turning it off and restarting the app.

This fixed the problem for at least two of us so far.

Definitely not a MusE problem. It's an OS theme/style issue.
You can try another OS theme/style.
