### ISSUE TITLE
Disabling multi opening of editor windows  ? [sf#1390196]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#130]
Submitted by linium on 2005-12-25 21:34:43

It happens to me frequently to open by error twice the
note editor window for the same part. 

I think that it is easy to forget an editor window
specially when you click on another window, because it
makes the window disappear behind the new one.

Since there are probably very little cases of
usefullness to have 2 different views of the same part,
i would suggest the default behaviour to be changed to
disallow several views. 

Furthermore, clicking on a part for edition whereas an
opened editor already exist (but hidden behind), would
put it back on top.

I think it may improve the "control" feeling of the UI. 

BTW, if it is wise to keep the current possibility to
have 2 views of the same part, an alternate key
combination could be dedicated to force this when needed.

**Comment by kybos** [comment]
Implemented in current master (see changelog).
