### ISSUE TITLE
Simple-Drums - changing the pan values [sf#1305676]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#138]
Submitted by plixplox on 2005-09-27 12:14:12

It is a little bit tricky to adjust the pan for each
individual drum instrument in the simpledrums editor -
when you try to  move the pan indicator to the right or
the left, you have to move the indicator very carefully
because there is little space for the pan indicator to
be moved. And when you want to put the pan back to the
middle (with a value of zero), you ask yourself if you
really have put the pan indicator back to the middle,
or somewhere else, i.e somewhere to the left or the
right, but not in the middle.

My solution proposal for this the following:

A pan indicator can be moved to the left or to the
right step by step (by pan values of 5), by clicking
respectively the left or the right edge of the pan
indicator. Every click on the left or right edge
increases / decreases the pan value by 5. The current
pan value is displayed in the middle of the pan
indicator. There are tiny arrows visible on the right
and the left edge, on the right edge pointing to the
right, on the left edge pointing to the left. This
should indicate to the user that he can click (or drag)
one of the edges. When he moves the mouse over one of
these edges, the color of the arrows changes (mouse
over effect).

**Comment by danboid** [comment]
I agree - it is still tricky to adjust the simpledrums controls.

**Comment by kybos** [comment]
No longer relevant:
- There is now a text output field showing the exact value.
- The sliders in the current default style are easy to adjust with the mouse.
- A mouse wheel (or similar) is now standard.
- When clicking on the slider grove, values are changed in steps of 10.

The only (cosmetic) issue I see is the default (middle) value, which is 63 (on the scale 0-127) and not 0 as I would expect.
