### ISSUE TITLE
Length not extended after changing tempo [sf#1470451]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#156]
Submitted by thorwil on 2006-04-14 18:39:37
- Start new project
- Import very long audio: Lenght gets updated
- Disable Master in transport window, increase tempo
  (from 120 to 170)
  -> Length stays the same. Zoomed out far, it's still
  all visible and the playhead can be placed everywhere,
  but after the measure given by Len, MusE refuses to play.

Expected: All parts/clips always being contained in the
area limited by Lenght.

**Comment by spamatica** [comment]
This bug is very old, this should be working since long.
