### ISSUE TITLE
latency compensation [sf#1099141]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#157]
Submitted by efocht on 2005-01-09 23:43:42

... adding this after a small thread on lmuse-user... 

There is a certain latency induced by the insert chain and by 
the hardware itself. Also when recording the player listens to 
the sound generated by some softsynth, maybe also going 
through some effect plugins, and stays in sync with what 
reaches the ear. In the end one collects a certain amount of 
latency and it would be nice to have a way to specify this 
for an input track. This should lead to the recording position 
slightly shifted in time. Input or wave tracks should have 
latency compensation times associated with them. They should 
be individually tunable, and should determine by how much 
the recorded track will be shifted in time. 

Erich

**Comment by spamatica** [comment]
Latency compensation is added by Tim since a little while! Closing
