### ISSUE TITLE
Remembering port 0 MIDI device [sf#1074617]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#159]
Submitted by christeck on 2004-11-28 14:00:53

I use an UM-1S, an USB2MIDI adapter. 

As soon as I start Muse and the device isn't plugged in 
yet, muse forgets the setting and sets all channels in 
the arrangement window to 'none'. 

After pluggin it in, I have to select the midi preferences 
and select the USB device anew. 

OK, I have to admit that then at least each track 
remembers that it now should use the UM-1S, ut it's 
somehow inconvenient to be urged to select the prefs 
because I had forgotten to plug the device in before I 
started Muse.

**Comment by spamatica** [comment]
midi port handling has been much reworked and improved. This should be working now. Closing.
