### ISSUE TITLE
Delete doubles [sf#1546858]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#161]
Submitted by romport on 2006-08-25 21:50:03

After quantisize a miditrack you often got
same notes on the same "place" on the grid.

By Drumtracks for example, you can hear this 
because these doubles notes generate a flanging
(midi never will be exact).
In the editors you only see one note.

MuSE should offer a feature to delete this doubles
automatically (in menue, or editors)

with kind regards and with many thanks for your work!

romport

**Comment by danboid** [comment]
+1

**Comment by spamatica** [comment]
The function 'Delete overlapping' can be used for this purpose. Closing
