### ISSUE TITLE
list editor: changin controller value B affects value A [sf#1552774]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#162]
Submitted by kutor on 2006-09-05 17:34:25

If one records events of value A = 21 and value B = 64
and then try to change value B in list editor, value A
changes to 1. I have tested it with controll change
numbers: 21-28, and effect1dep, effect3dep. All of
these controllers change value A to 1 after
modifications of value B.

**Comment by kybos** [comment]
Tested, not longer reproducible.
