### ISSUE TITLE
notes color coded by channel [sf#1594521]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#184]
Submitted by dabrowsa on 2006-11-11 02:27:42

I love Muse, I greatly admire the dedication of
everyone who has worked on it, it's the best linux
native sequencer available now, but...

It's useless to me without one feature which is
standard in almost every other sequencer I've seen: the
piano roll editor must be able to display notes from
multiple channels, with the notes color coded according
to channel, so I can tell the voices apart.  

Even freeware sequencers like Music Studio Producer
(from Frieve.com) for Windows and Midigraphy for Mac
classic OS have this, so I was crestfallen to find it
still has not been implemented on Muse.

I want to love Muse!  Please add this feature!

Andrew

**Comment by kybos** [comment]
Multiple tracks meant? This is already possible.
