### ISSUE TITLE
List editor - sort method by field nature [sf#1603840]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#185]
Submitted by linium on 2006-11-27 17:31:29

In the List editor, clicking on "tick" "bar" "valA" or "comment" (on so on), produces the same behaviour wich is presenting the events by time order (clicking switchs either forward or backward order). 

When u have a huge number of midi controllers it's for instance not possible to isolate them by alphabetic order clicking on "comment" or "Type".

This would be very handy to have an proper sorting method for each field.

-alphabetic for "Type" and "comment" (and may be "valA" when the event is a note).

-numeric for the others

**Comment by kybos** [comment]
This is already implemented.
