### ISSUE TITLE
abilitty to set default Displayed Resolution [sf#1610827]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#188]
Submitted by allan_k on 2006-12-07 15:46:24

Hi 

To prevent having to change 
"Globacl Settings/Midi/Displayed Resolution (Ticks/Quarternotes)"
on every startup, it would be great to have the ability to modify the default startup resolution. 

This is particulary of use to people using external drum machines and sequencers synced to MusE. 

cheers 

Allan

**Comment by kybos** [comment]
Just create own template?
