### ISSUE TITLE
program change works after restart of muse [sf#1687165]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#201]
Submitted by kutor on 2007-03-23 22:59:50

When using muse 0.9.2pre program change on a does not work properly.
When you adjust program change during a session on a track info and after that you want to play this track, it will set the program change to previous value. If you want to get rid of this unwanted change, you have to save the file with the new program change setting and restart muse.
You can off course record the program change setting from track info on a track, but if you want to find a right sound for your track while listening to the track in a loop it is tedious to edit track part and change the program change in the list editor, because every time after the loop is repeated the old program change setting goes back.

**Comment by kybos** [comment]
Obsolete
