### ISSUE TITLE
feature request: autoreconnect to midi ports [sf#1718969]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#204]
Submitted by ninjakoala on 2007-05-15 00:34:37

I use QSynth. I often want to change my instruments. This requires restarting QSynth, and this in turn necessitates going into the Settings > Midi Ports menu item, turning all my QSynth ports to "none", then turning them all back to the appropriate virtual MIDI ports.

This is a giant pain.

**Comment by spamatica** [comment]
As is noted above, this is really a corner case.
Using jack-midi the original scenario with restarting the synth is working. Not sure if it works with alsa-midi. Closing anyway, if it's not working with alsa-midi I don't see us spending much time on it.
