### ISSUE TITLE
graphic edition for sustain and other non-note events [sf#1885141]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#210]
Submitted by cargobidibulle on 2008-02-02 11:55:57

Today, sustain is displayed in midi edit window, but cannot be edited (except event by event, in event list editor).

I wish there were functions like a graphical cut/paste of sustain events in the midi edit window.

My version:
muse 0.9pre2

**Comment by kybos** [comment]
Obsolete

**Comment by terminator356** [comment]
Yes all of that can be done now. Should be working.
