### ISSUE TITLE
No input latency compensation [sf#1475813]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#221]
Submitted by emmef on 2006-04-24 23:54:14

This is about version 0.8.1 (gentoo) but might as well
exists in other versions. 

When recording audio from the audio inputs, the
recorded data is not compensated for latency (the
number of frames in the -p option of the jack server). 
This means that when you make a recording, based on
what you hear via the playback, the recorded sound will
be delayed.

If you connect the audio line-out and line-in (mind the
mixer settings!) and playback a track, recorded sound
should be equals to the played track: 
- Ardour over-compensates (recorded sound is EARLIER
  than original). Also posted a bug there; 
- MusE does not compensate (recorded sound is LATER). 

For various reasons it is not always necessary or even
desireable to have a tweaked audio setup with latencies
<5ms. (note 1)

It _is_ possible to ask jackd what input latency it
provided and this could be added as an extra to the
InputDevice class, which you undoubtedly have in some
form, so that the recorded wave part is compensated.
As MusE supports plugin-latency compensation, you could
also create a hidden insert in the input track, that
claims the jack latency, but has no actual latency (so
that the plugin latency mechanism fixes things).

NOTE 1: 
Kernel patches don't always work and some distributions
even break on them if they did succeed after all. If
you don't use many plugins and do many accoustic and/or
live instruments, hardware (real zero latency)
monitoring together with the sound played back is
enough. Recording tools should correct the latency

**Comment by spamatica** [comment]
I believe there are still some lose ends but this is basically implemented now by Tim!
