### ISSUE TITLE
Precount for metronome does not work [sf#1092311]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#223]
Submitted by spamatica on 2004-12-28 19:22:39

 metronome precount does not work. With current JACK 
transport interface this cannot be implemented. MusE has 
no control over when the transport is actually started 
because of "slow sync" clients. (Added here for 
completeness)

**Comment by spamatica** [comment]
This has actually been fixed now. Tim added support for precount a while ago!
