### ISSUE TITLE
Tempo/Sig sync with Ardour [sf#1713360]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#254]
Submitted by steph5150 on 2007-05-05 13:23:13

Hello,

As discussed in the request nÂ° 1229265 (old bug report reopened) it is possible to make Ardour the tempomap master.

Could you tell me if the code I've submitted in the request nÂ°1229265 is usable in the current and next releases, and if so, could you include this modification ?

Thanks, waiting for feedbacks...

steph.
.

**Comment by kybos** [comment]
Obsolete

**Comment by terminator356** [comment]
Ah yes, syncing our tempo and signature maps with Ardour and other apps.

I do remember this exchange clearly, a patch was submitted which would allow this in a kind of hackish way,
 a way I also thought of (ask if you would like details). But the sands of time kind of blew over this,
 as I felt this was not the ideal solution.

Instead, I engaged in conversation on LAD about implementing a **shared tempo map** facility,
 and even submitted skeletal code, and my suggestion was even listed on the Jack website but I can't seem to find it now.
But nothing ever came of it.
I've been trying for years to get folks to jump on the idea, it really is essential if apps are going to share time lines.
