### ISSUE TITLE
No foot controller(cc4) recorded when type of track is drum [sf#2976809]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#259]
Submitted by cinqmarsb on 2010-03-26 03:36:37

When type of track is Midi, i can record the foot controller from Roland TD9
When type of track is Drum, the foot controller from Roland TD9 is NOT recorded.
Muse version: 1.0.1
This problem was on older version to.
Ubuntu Studio 10.04 beta1

Benoit Cinq-Mars
Montreal, Quebec Can

**Comment by kybos** [comment]
Obsolete
