### ISSUE TITLE
Crash in Drum Editor when changing Drum-Map Order [sf#2948580]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#262]
Submitted by elmex on 2010-02-09 17:04:33

I've got a crash with muse 1.0.1 and recent svn revision when changing the order of the Drum-Instruments.
I'm trying to drag the a line in the drum map upwards to change the order. Then the order kind of changes a bit sloppy and the a green box stays
over the drum map. Then I try to move another drum voice up and the whole editor kind of freezes, but it's not a 100% CPU loop kind of. Shortly (a few secs later) muse crashes with this backtrace (from the recent svn checkout, Revision: 396):

```
http://ue.o---o.eu/txt/65e7aca45e9fd8541cbc6fc712082267.txt
```

I'm using muse on a debian amd64 unstable with a graphics tablet as mouse. It was connected to jack to control an external drum machine.
The crash happens with muse 1.0.1 and with the svn revision 396. This is the output of the 'configure' script:

   http://ue.o---o.eu/txt/b0d988de05906c8866881cc9fc8eac15.txt

If you need further information or me trying to reproduce the problems when you got a fix just send a mail.

Thanks & Greetings,
   Robin

**Comment by kybos** [comment]
Obsolete (there is a new drum editor now).
