### ISSUE TITLE
Crashes on start [sf#3029328]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#264]
Submitted by gmiernicki on 2010-07-14 08:38:18

$ muse
Denormal protection enabled.
Muse: **i386** or **x86_64** defined. Using optimized float buffer copying (asm movsl).
Muse: using unoptimized non-SSE dsp routines
Enhanced3DNow! detected
SSE2 detected
no locale <muse_en_US.UTF-8>/</usr/share/muse/locale>
Trying RTC timer...
fatal error: open /dev/rtc failed: Permission denied
hint: check if 'rtc' kernel module is loaded, or used by something else
Trying ALSA timer...
AlsaTimer::initTimer(): timer open -2 (No such file or directory)
muse: timer.c:548: snd_timer_info: Assertion `timer' failed.
Aborted

**Comment by kybos** [comment]
Obsolete

**Comment by tylercodes1** [comment]
New to Linux, but this error seems to persist on Windows Subsystem for Linux (WSL).

I've updated the permissions on rtc0 with `chmod 777 rtc0` and checked permissions with `ls -la | grep rtc0`:
 `crwxrwxrwx  1 root root 251,   0 Feb 27 12:30 rtc0` 
 
After, I ran `muse` and the same errors that were originally listed appeared. I can also verify that ALSA and `/dev/snd/timer` file. Just putting this out there in case someone can help/let it be known this is still an issue for some.

**Comment by tylercodes1** [comment]
Quick follow up to this issue: I was able to resolve the first error through two steps:

1. Renamed `/dev/rtc0` to `/dev/rtc`: `mv rtc0 rtc`
2. Updated `/sys/class/rtc/rtc0/max_user_freq` from 64 to 2048 as recommended [here](https://linux-audio-user.linuxaudio.narkive.com/37IcuyRp/lau-muse-rtctimer-cannot-set-freq): `echo 2048 > /sys/class/rtc/rtc0/max_user_freq`

**Comment by terminator356** [comment]
> Renamed /dev/rtc0 to /dev/rtc: mv rtc0 rtc

On my system it is a link rtc -> rtc0
That would be a safer way to do it. Keep the rtc0 but add a link rtc.

Any luck running?

**Comment by tylercodes1** [comment]
> On my system it is a link rtc -> rtc0
> That would be a safer way to do it. Keep the rtc0 but add a link rtc.

I'll change mine back, If you have a linux machine, I trust your system more than I trust mine.

Unfortunately, no. I can't get past an Alsa/soundcard related error where it references something at `/dev/snd/timer`. In my WSL2, there doesn't exist a `/snd` directory, and I can't seem to get it.

**Comment by terminator356** [comment]
Hm, if you can get the RTC to respond properly without error,
 then MusE should skip trying the ALSA timer and just continue running.
If you would like, post some terminal output and I'll take a look.
Be sure to use the -D command line option which provides more debugging output.
