### ISSUE TITLE
Soft Synth GUI Button Loses Sync [sf#3040360]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#265]
Submitted by roncemer on 2010-08-06 04:14:51

If you open the Soft Synth Configuration dialog and add a soft synth, then click in the GUI column, the green button lights up in the GUI column, and the soft synth's GUI dialog comes up.  If you click the green GUI button again, it goes away.  So far so good.  But if instead you close the soft synth's GUI dialog, the green button stays green but clicking it to make it go away actually brings up the soft synth's GUI dialog again.

Manually closing the soft synth's GUI dialog should cause the corresponding green button to go away also.

**Comment by kybos** [comment]
Still relevant.
