### ISSUE TITLE
Adding second fluidsynth-dssi instance crashes Muse [sf#3040357]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#266]
Submitted by roncemer on 2010-08-06 04:08:16

Muse 1.0.1, as it comes in fedora 13 i386.

If you add one fluidsynth-dssi, everything's fine.  As soon as you add the second, Muse hangs for several seconds then terminates.

**Comment by danlyke** [comment]
I'm starting to use MusE, and was playing with Fluidsynth, and fluidsynth-dssi appears to be working correctly. Perhaps this one can be closed?
