### ISSUE TITLE
deicsonze synth doesn't memoriize its parameters [sf#3474229]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#278]
Submitted by ycollette on 2012-01-15 20:29:38

I use muse2  trunk on mageia 1 32 bits.
I added a synth track with deicsonze. I set the parameters of deicsonze (I select a synth).
I  added a midi track.
I start recording some chords.
Then I replay (I hit the button "go to start" + the plaay button).
Muse2 play the chords but with the default deicsonze parameters.

**Comment by kybos** [comment]
It's working in muse3.
