### ISSUE TITLE
Pencil Tool - make a note longer to the left [sf#1298642]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#292]
Submitted by plixplox on 2005-09-22 13:29:24

(Noticed in MusE 0.7.1 - 0.7.2pre2:) 

With the pencil tool one can make notes longer that
already exist in the piano roll editor. One can make
notes longer by pulling the right edge of the note to
the right. But it is not possible to a make a note
longer by pulling the left edge of the note to the left.

As a workaround one needs to drag the note itself to a
new position left from the actual note position, and
then use the pencil to make the note longer at its
right edge. 

It would be easier to just make the note longer by just
being able to drag the left edge of the note to the left.

**Comment by danboid** [comment]
This still seems to be the case in git.

Would this be tough to fix?

**Comment by danvd** [comment]
Although this can't be called a 'fix', because it's surely closer to a new feature, it's done in ae77158. 
Realization was a bit tricky - resizing to the left is actially a combo of 2 operations - move+reisize. But now it works and as a bonus parts in the arranger window can also be resized to the left with pencil tool ;)

/Andrew

**Comment by danvd** [comment]
Just a little note - there are changes in vtanle for several common classes, so your build should be cleared and rebuilt from scratch.

**Comment by danboid** [comment]
Great news Andrew!

I'll be back home tomorrow and trying your recent MusE work out.

Thanks!

**Comment by danvd** [comment]
Ok :). Also don't forget to check realtime wave drawing ;)

**Comment by danboid** [comment]
Great to see this get fixed! Works fine for me so I'd say this can be closed now.

Thanks Andrew!
