### ISSUE TITLE
internal audio editor problems [sf#3565113]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#299]
Submitted by danboid on 2012-09-06 00:52:16

None of the functions (ie gain, mute, normalize, fade in/out) seem to work on either a selection or if I have the full wave selected.

Also, if I select a section of the wave then I'd expect the playhead to be moved to the start of the selection, for it to stop at the end of the selection and to loop the selection when loop mode is enabled but the integrated sound editor is doing none of these things currently.

**Comment by danboid** [comment]
This can be closed - I no longer have this issue under muse3.
