### ISSUE TITLE
Muse 2.0 track forgets patch/volume settings [sf#3569047]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#312]
Submitted by None on 2012-09-18 21:09:35

Reproduction recipe: 
- create new midi channel
- assign it to a port (with an instrument mapped to it)
- select a patch from the instrument, choose volume, etcetera
- whenever you go to the start of the song, the track forgets all these settings and sets them to "off"
- same applies when setting these parameters in a part
- the only way to fix this is to hard code the parameters as control events in the part.

This is a functional design bug
- you would expect that the settings are stored or 
- you would not expect them to but there is no indication of how to remember them.

Thanx in advance.

**Comment by spamatica** [comment]
closing as I don't think there is anything to change
