### ISSUE TITLE
arranger starts 'windowed' when loading a song [sf#3596240]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#315]
Submitted by danboid on 2012-12-15 12:28:26

Whenever I load a song under AVL6 the arranger starts in 'windowed' mode vs being maximized.

This also has the side effect of causing an odd drawing issue with the track info display column on the left of the arranger which causes its background to become transparent, making the text difficult to read due the grid etc in the background ie the arranger looks messy when you load a song.

**Comment by danboid** [comment]
This is still an issue in git and it applies to new sessions too, that is ones created from the default set of song templates. The arranger should default to using the max space available within the Muse window IMO.

I'm running Cinnamon (2.6?) under Arch

**Comment by danboid** [comment]
Ooops!

I've just created a dupe for this:

https://github.com/muse-sequencer/muse/issues/401

It's an old bug then!

**Comment by danboid** [comment]
I've closed my dupe issue now but this is still an issue in git, at least the bit about projects being displayed in a non-maximized window withinthe arranger after being loaded when they were saved maximized is still an issue.

**Comment by danboid** [comment]
I think a side-effect of this bug is that the user is required to click within their projects window after loading it to bring it into focus so that keyboard shortcuts work. Hitting SPACE after loading a project doesn't start playing it for this reason.

**Comment by danvd** [comment]
Fixed by commit 45c0e94.
I hope this also fixes #426 (may be).
And after project load space and othe transport shortcuts should work without any clicking.

**Comment by danboid** [comment]
Projects start maximized now but unfortunately it hasn't fixed #426 as I still have to click within the project window before the transport shortcuts work.

I think we can close this issue now though.

**Comment by danvd** [comment]
Forced setFocus on arranger window after loading a song. Now transport keys should work without clicking.

**Comment by danboid** [comment]
Yes, transport keys work without clicking for me now.

Thanks Andrew!
