### ISSUE TITLE
MESS synth GUIs hidden on addition [sf#3596544]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#316]
Submitted by danboid on 2012-12-16 11:46:26

Whenever you add a MESS synth to a MusE song, it automatically opens its GUI although it doesn't bring the window to the front as its hidden behind the arranger.

MESS synths should either bring their GUI to the foreground when added or not automtically open the GUI when you add, them like the VSTs.

**Comment by danboid** [comment]
We can close this one now.
