### ISSUE TITLE
muse doesn't always start under AVL6 [sf#3596239]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#323]
Submitted by danboid on 2012-12-15 12:12:26

I'm runnimg the latest svn trunk under AV Linux 6 compiled with debug but muse fails to start half (or more) of the time.

AVL6 comes complete with DSSI-VST (which I'd like to keep installed for qtractor) as well as a few Windows VSTs (which I'd prefer to keep as qtractor isn't complaining about them) alongside many LADSPA, DSSI and I've installed a few native LInux VSTs alongside the ones it comes with so I can't help but think this could be caused by DSSI-VST or a naughty DLL VST?

Here's what happens when muse fails to start, normally:

muse2
LOCALE en_GB
Denormal protection enabled.
Trying RTC timer...
RtcTimer::setTimerFreq(): cannot set freq 1024 on /dev/rtc: Permission denied
  precise timer not available, check file permissions and allowed RTC freq (/sys/class/rtc/rtc0/max_user_freq)
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 66
RemoteVSTClient: all cache files are up-to-date, not running scanner
RemoteVSTClient: all cache files are up-to-date, not running scanner
Master :    new PRESET NUM value : 15
enabledTimbre = 0
enabledModulation = 0
enabledGainDelay = 0
enabledEnvelope = 0
Best predicted CPU load (256/2048/8192): 	6.39 %
Segmentation fault

Thats the error I usually get, but I got a different error during a recent try:

muse2 
LOCALE en_GB
Denormal protection enabled.
Trying RTC timer...
RtcTimer::setTimerFreq(): cannot set freq 1024 on /dev/rtc: Permission denied
  precise timer not available, check file permissions and allowed RTC freq (/sys/class/rtc/rtc0/max_user_freq)
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 66
RemoteVSTClient: all cache files are up-to-date, not running scanner
RemoteVSTClient: all cache files are up-to-date, not running scanner
Master :    new PRESET NUM value : 15
enabledTimbre = 0
enabledModulation = 0
enabledGainDelay = 0
enabledEnvelope = 0
Best predicted CPU load (256/2048/8192): 	6.39 %
*** glibc detected *** muse2: malloc(): memory corruption: 0x09f6f0e1 ***
======= Backtrace: =========
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6aac1)[0xb5351ac1]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6d8a4)[0xb53548a4]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(+0x6ff7c)[0xb5356f7c]
/lib/i386-linux-gnu/i686/cmov/libc.so.6(realloc+0xdd)[0xb53574ad]
/usr/lib/vst/drumsynth.so(+0x10158a)[0xb184558a]
======= Memory map: ========
08048000-08054000 r-xp 00000000 08:02 10757686   /usr/local/bin/muse2
08054000-08055000 rw-p 0000c000 08:02 10757686   /usr/local/bin/muse2
097ba000-0ab28000 rw-p 00000000 00:00 0          [heap]
b1300000-b1422000 rw-p 00000000 00:00 0 
b1422000-b1500000 ---p 00000000 00:00 0 
b1500000-b1600000 rw-p 00000000 00:00 0 
b1744000-b1ae9000 r-xp 00000000 08:02 11147156   /usr/lib/vst/drumsynth.so
b1ae9000-b1afb000 r--p 003a4000 08:02 11147156   /usr/lib/vst/drumsynth.so
b1afb000-b1afd000 rw-p 003b6000 08:02 11147156   /usr/lib/vst/drumsynth.so
b1afd000-b1aff000 rw-p 00000000 00:00 0 
b1aff000-b1b00000 ---p 00000000 00:00 0 
b1b00000-b2300000 rw-p 00000000 00:00 0 
b2300000-b2400000 rw-p 00000000 00:00 0 
b24fc000-b251f000 r--p 00000000 08:02 11675121   /usr/share/fonts/truetype/msttcorefonts/Verdana.ttf
b251f000-b2520000 ---p 00000000 00:00 0 
b2520000-b2d20000 rw-p 00000000 00:00 0 
b3082000-b309b000 r-xp 00000000 08:02 9961684    /lib/libselinux.so.1
b309b000-b309c000 r--p 00018000 08:02 9961684    /lib/libselinux.so.1
b309c000-b309d000 rw-p 00019000 08:02 9961684    /lib/libselinux.so.1
b309d000-b30a1000 r-xp 00000000 08:02 11020352   /usr/lib/i386-linux-gnu/libzita-resampler.so.1.1.0
b30a1000-b30a2000 r--p 00003000 08:02 11020352   /usr/lib/i386-linux-gnu/libzita-resampler.so.1.1.0
b30a2000-b30a3000 rw-p 00004000 08:02 11020352   /usr/lib/i386-linux-gnu/libzita-resampler.so.1.1.0
b30a3000-b30a9000 r-xp 00000000 08:02 11020351   /usr/lib/i386-linux-gnu/libzita-convolver.so.3.1.0
b30a9000-b30aa000 r--p 00005000 08:02 11020351   /usr/lib/i386-linux-gnu/libzita-convolver.so.3.1.0
b30aa000-b30ab000 rw-p 00006000 08:02 11020351   /usr/lib/i386-linux-gnu/libzita-convolver.so.3.1.0
b30ab000-b30ae000 r-xp 00000000 08:02 10624939   /usr/lib/libboost_system.so.1.42.0
b30ae000-b30af000 rw-p 00002000 08:02 10624939   /usr/lib/libboost_system.so.1.42.0
b30af000-b31e3000 r-xp 00000000 08:02 10625527   /usr/lib/libfftw3f.so.3.2.4
b31e3000-b31ec000 rw-p 00133000 08:02 10625527   /usr/lib/libfftw3f.so.3.2.4
b31ec000-b32ee000 r-xp 00000000 08:02 10625698   /usr/lib/libgio-2.0.so.0.2800.6
b32ee000-b32f1000 rw-p 00101000 08:02 10625698   /usr/lib/libgio-2.0.so.0.2800.6
b32f1000-b32f2000 rw-p 00000000 00:00 0 
b32f2000-b33db000 r-xp 00000000 08:02 10625701   /usr/lib/libgiomm-2.4.so.1.3.0
b33db000-b33e6000 rw-p 000e8000 08:02 10625701   /usr/lib/libgiomm-2.4.so.1.3.0
b33e6000-b33ea000 r-xp 00000000 08:02 10626375   /usr/lib/libsigc-2.0.so.0.0.0
b33ea000-b33eb000 rw-p 00004000 08:02 10626375   /usr/lib/libsigc-2.0.so.0.0.0
b33eb000-b344e000 r-xp 00000000 08:02 10625716   /usr/lib/libglibmm-2.4.so.1.3.0
b344e000-b3450000 rw-p 00062000 08:02 10625716   /usr/lib/libglibmm-2.4.so.1.3.0
b3450000-b3526000 r-xp 00000000 08:02 11020854   /usr/lib/ladspa/ladspa_guitarix.so
b3526000-b3549000 rw-p 000d6000 08:02 11020854   /usr/lib/ladspa/ladspa_guitarix.so
b3549000-b360a000 rw-p 00000000 00:00 0 
b360a000-b360f000 r-xp 00000000 08:02 10624864   /usr/lib/libartsc.so.0.0.0
b360f000-b3610000 rw-p 00004000 08:02 10624864   /usr/lib/libartsc.so.0.0.0
b3610000-b3649000 r-xp 00000000 08:02 10625685   /usr/lib/libgig.so.6.4.0
b3649000-b364b000 rw-p 00038000 08:02 10625685   /usr/lib/libgig.so.6.4.0
b364b000-b36e6000 r-xp 00000000 08:02 10626418   /usr/lib/libsqlite3.so.0.8.6
b36e6000-b36e8000 r--p 0009a000 08:02 10626418   /usr/lib/libsqlite3.so.0.8.6
b36e8000-b36e9000 rw-p 0009c000 08:02 10626418   /usr/lib/libsqlite3.so.0.8.6
b36e9000-b36ea000 rw-p 00000000 00:00 0 
b36ea000-b3960000 r-xp 00000000 08:02 11021025   /usr/lib/linuxsampler/liblinuxsampler.so.3.0.0
b3960000-b396b000 rw-p 00275000 08:02 11021025   /usr/lib/linuxsampler/liblinuxsampler.so.3.0.0
b396b000-b3975000 rw-p 00000000 00:00 0 
b3975000-b3978000 r-xp 00000000 08:02 10625727   /usr/lib/libgmodule-2.0.so.0.2800.6
b3978000-b3979000 rw-p 00002000 08:02 10625727   /usr/lib/libgmodule-2.0.so.0.2800.6
b399a000-b39a7000 rw-p 00000000 00:00 0 
b39a7000-b39e1000 rw-s 00000000 00:04 819208     /SYSV00000000 (deleted)
b39e1000-b39e2000 ---p 00000000 00:00 0 
b39e2000-b41e2000 rw-p 00000000 00:00 0 
b41e2000-b421a000 r-xp 00000000 08:02 10625938   /usr/lib/libjpeg.so.8.3.0
b421a000-b421b000 rw-p 00037000 08:02 10625938   /usr/lib/libjpeg.so.8.3.0
b421b000-b427d000 r-xp 00000000 08:02 11020339   /usr/lib/i386-linux-gnu/libtiff.so.4.3.6
b427d000-b427e000 ---p 00062000 08:02 11020339   /usr/lib/i386-linux-gnu/libtiff.so.4.3.6
b427e000-b4280000 r--p 00062000 08:02 11020339   /usr/lib/i386-linux-gnu/libtiff.so.4.3.6
b4280000-b4281000 rw-p 00064000 08:02 11020339   /usr/lib/i386-linux-gnu/libtiff.so.4.3.6
b4281000-b42b1000 r-xp 00000000 08:02 10625998   /usr/lib/liblcms.so.1.0.18
b42b1000-b42b3000 rw-p 0002f000 08:02 10625998   /usr/lib/liblcms.so.1.0.18
b42b3000-b42b5000 rw-p 00000000 00:00 0 
b42b5000-b432b000 r-xp 00000000 08:02 10626091   /usr/lib/libmng.so.1.1.0.10
b432b000-b432e000 rw-p 00075000 08:02 10626091   /usr/lib/libmng.so.1.1.0.10
b432e000-b434d000 r-xp 00000000 08:02 10625937   /usr/lib/libjpeg.so.62.0.0
b434d000-b434e000 rw-p 0001e000 08:02 10625937   /usr/lib/libjpeg.so.62.0.0
b434e000-b436d000 rw-p 00000000 00:00 0 
b436d000-b436f000 rw-s 00000000 00:04 524295     /SYSV00282929 (deleted)
b436f000-b4375000 r-xp 00000000 08:02 11541178   /usr/lib/qt4/plugins/imageformats/libqgif.so
b4375000-b4376000 rw-p 00005000 08:02 11541178   /usr/lib/qt4/plugins/imageformats/libqgif.so
b4376000-b4385000 r--p 00000000 08:02 11675137   /usr/share/fonts/truetype/ttf-bitstream-vera/VeraBd.ttf
b4385000-b43bc000 r--p 00000000 08:02 11675100   /usr/share/fonts/truetype/msttcorefonts/Arial_Bold_Italic.ttf
b43bc000-b4400000 r--p 00000000 08:02 11675097   /usr/share/fonts/truetype/msttcorefonts/Arial.ttf
b4400000-b449b000 r--p 00000000 08:02 11675149   /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
b449b000-b44ab000 r-xp 00000000 08:02 9962133    /lib/i386-linux-gnu/i686/cmov/libresolv-2.13.so
b44ab000-b44ac000 r--p 00010000 08:02 9962133    /lib/i386-linux-gnu/i686/cmov/libresolv-2.13.so
b44ac000-b44ad000 rw-p 00011000 08:02 9962133    /lib/i386-linux-gnu/i686/cmov/libresolv-2.13.soAborted

Hope you can glean something out of that?

**Comment by danboid** [comment]
This is an oooold bug report from me.

I don't seem to have this issue under muse3 so lets close it.
