### ISSUE TITLE
Add pitching to simpledrums [sf#3602273]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#333]
Submitted by danboid on 2013-01-27 12:17:17

It would be useful if simpledrums gained the ability to be able to set the root note and also maybe the range over which a sample could be pitched which would go some way to doing most of what people might otherwise need to use (the unsupported) Euphoria or the as yet not usable as a muse plugin samplv1 for.

**Comment by danboid** [comment]
I think Robert implemented this but I've not got round to trying it so I'm not sure if I'm making things up?

I'll be trying simpledrums again shortly.

**Comment by danboid** [comment]
To reply to myself, as far as I can see this didn't get implemented.

samplv1 can do this so I should try using that under MusE in the mean time.

**Comment by spamatica** [comment]
There is an embryo to pitching. One of the knobs can adjust which pitch the
sound is replayed at. I don't recall now but there was a bunch of related
improvements that were requested.
There are many improvements that could be done to simpledrums, I'll revisit
it and see if I can tick of some easy ones.


2016-01-26 23:02 GMT+01:00 danboid <notifications@github.com>:
