### ISSUE TITLE
piano roll or scoreeditor integrated with the arranger

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#344]
like in ardour. that's really cool!

It's basically flo's "slotted editors" suggestion plus some usability.

**Comment by kybos** [comment]
I hear from many people that they hate the inline midi editor in Ardour and use QTractor or MusE just because of this.
And for people that like it, why not use the original?
So I don't think this request makes any sense.

**Comment by terminator356** [comment]
If I may offer a personal opinion: Ardour was, is, and always will be, a superb **recorder**.
But unless it changes, actual midi composition from scratch? No. It really needs editors.

Flo's idea has a lot of merit but the challenges are immense and may not be worth it.
For useful editing the user would have to keep vertically expanding the tracks
 to see all the notes (like Ardour).
To have all the Arranger editing features **plus** all the midi ediitng features in one place
 would be daunting I think.
Another problem is editing overlapping parts. You'll note that our Arranger parts 
 do not have a 'Z order', so there's no mechanism to keep the last selected part
 on top of others.
It's certainly doable, but complex. When we can simply double-click to open an editor
 on the part, it doesn't seem worth the effort at this (that) time.
Yes, we actually do allow audio controller graph editing in the Arranger,
 but really that was a mistake. The plan is to move that into actual parts. And the difficulty
 with that is that it means **all** audio track types would have to be able to have parts.
Again, doable, and the plan is always on my mind, but complex. Some day we'll have it...
