### ISSUE TITLE
Crashes on key/mouse combination

### ISSUE THREAD

**Issue by LakeIshikawa** [muse-sequencer/muse#353]
Muse crashes with the following steps:
- Create a new midi track
- Open piano roll view for the newly created track
- Add a note with pencil tool
- Drag mouse over the new note in order to adjust its length (no mouse release)
- Press "delete" key

I suppose this is a GUI issue that crashes the whole application.
Muse version: 2.1.2
Jack version: 0.3.10
Kernel: low-latency 
Ubuntu: 14.04

**Comment by spamatica** [comment]
Should be fixed. Closing
