### ISSUE TITLE
Crash on start (still present in 2.2.1)

### ISSUE THREAD

**Issue by falkTX** [muse-sequencer/muse#358]
I get a crash when starting muse and closing the "did you know dialog".
Using this works around the issue:
```
muse -style plastique
```

The following is printed in the terminal:
> The program 'muse' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 2215 error_code 3 request_code 20 minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

I'm using Ubuntu 14.04, KDE4 with QtCurve theme.

**Comment by danvd** [comment]
Hi!
I'm now installing ubuntu 14.04 to catch this bug. Does it matter, which version to install - kubuntu or ubuntu and then apt-get kde4 on it?

/Andrew

**Comment by falkTX** [comment]
I don't think so, it's the style that matters.
Using "plastique" skips the bug. I know it crashes with QtCurve.

**Comment by danvd** [comment]
Ok, I see. Thanks!

**Comment by danvd** [comment]
Just installed ubuntu 14.04, then kde4, qtcurve style. Set qtcurve by default, but didn't catch crash. Tried debug and release versions of muse. Can you send a backtrace here?

**Comment by spamatica** [comment]
I run kubuntu and apparantly it doesn't preinstall qtcurve, added it now but can't get it to crash.

falkTX, maybe a backtrace would help?

**Comment by danvd** [comment]
Hmm. I will also try to install fresh kubuntu 14.04 and all kxstudio repos. Will see how it will behave :)

**Comment by danvd** [comment]
Hi falkTX,
I made another test. 
1. Installed clean kubuntu 14.04. 
2. Connected, installed and updated kxstudio repos followed the instructions on your page: http://kxstudio.sourceforge.net/Repositories
3. Installed qtcurve. Made it the default style.
4. Installed muse (I checked - version 2.2.1 was installed from kxstudio repos).
5. Started jackd, than muse. Closed "Did you know?" dialog. No crash.
6. Closed muse - also no crash.
7. Started muse with explicit style: muse -style qtcurve. Again no crash.

What can I do else? Backtrace needed now  :)

**Comment by falkTX** [comment]
You could try the kxstudio theme, like this:
- install kxstudio-artwork package
- set KDE style to qtcurve
- open qtcurve settings, set style to "KXStudio"
- set KDE colors to "KXStudio"

with this you'll also be able to experience the black-on-black bug.

Anyway, I can't get a trace.
The error is caused by some X11 thing, which will cause the qt app to quit.
MusE can't accept custom CLI arguments which is needed to debug this ("muse --sync").

**Comment by danvd** [comment]
Ok, thanks! I'll try it now.

**Comment by danvd** [comment]
Finally got a crash! 
Now will try to find a reason :)

**Comment by danvd** [comment]
Hi falkTX!

Finally got a working solution.
The error was because gtk support libraries were loaded before qt main loop. Don't know why, but kdeui lbrary don't like it and tries to set poroperty on non-existent X window.
Here is a patch for 2.2.1 version:
https://gist.github.com/danvd/ddde49f36feaa8604321#file-0001-later-loading-of-gtk2-helper-to-make-qt-main-loop-happy-patch

It will make muse load gtk libraries on first call for opening lv2 native gui (with error handling).
This is also fixed in master now.

Can you test it on your configuration?

Regards,
Andrew

**Comment by falkTX** [comment]
I can confirm that patch fixes this specific issue.
