### ISSUE TITLE
Compiling 2.2.1 gives PluginI has not been  declared error

### ISSUE THREAD

**Issue by parisnight** [muse-sequencer/muse#360]
I compiled 2.2.1 on a slackware machine and got the following error. Version 2.1.2 seemed to compile fine on this computer.  Andrew suggested deleting CMakeCache.txt and retrying.  Doing this gave the same error message.  cbuild reported that only the Native VST component will be built.  Andrew compiled it successfully on a slackware machine so it may just be operator error.

bash-4.2$ uname -a
Linux ku 3.2.29-smp #2 SMP Mon Sep 17 13:16:43 CDT 2012 i686 Intel(R) 
Core(TM) i5-2520M CPU @ 2.50GHz GenuineIntel GNU/Linux 

... 

[ 48%] Building CXX object 
muse/widgets/CMakeFiles/widgets.dir/pixmap_button.o
[ 48%] Building CXX object 
muse/widgets/CMakeFiles/widgets.dir/plugindialog.o
In file included from 
/home/fuzz/muse-2.2.1/muse/widgets/plugindialog.cpp:10:0:
/home/fuzz/muse-2.2.1/muse/plugin.h:143:41: error: 'PluginI' has not been 
declared
make[2]: *** [muse/widgets/CMakeFiles/widgets.dir/plugindialog.o] Error 1
make[1]: *** [muse/widgets/CMakeFiles/widgets.dir/all] Error 2
make: *** [all] Error 2

**Comment by danvd** [comment]
Hi parisnight,
Thanks for registering and posting issue.
Please make the following steps:
delete CMakeCache.txt again
then run:
cmake .
and send all output here

But as you wrote about only vst detected it seems that you need to install liblo and dssi now because thay are critical for compilation.

Regards,
Andrew

**Comment by spamatica** [comment]
Hi guys,

2015-02-03 20:08 GMT+01:00 Andrew Deryabin <andrew@audioplugins.org>:
> UPDATE: May be dssi is also not installed. So install dssi+liblo or disable
> them (run ccmake .. instead of cmake to open console UI).
>

Indeed you are right! Though disabling seems not to work either, I
couldn't get it to work anyway..

Seems liblo is indeed needed to build at the moment, without it I get
an error about a header file missing
muse/ctrl.h:34:29: fatal error: lo/lo_osc_types.h: No such file or directory
 #include <lo/lo_osc_types.h>

And dssi is needed, without it I get the sought error:
muse/plugin.h:143:41: error: ‘PluginI’ has not been declared
       virtual LADSPA_Handle instantiate(PluginI *);


Adding the dependencies seems like the short term solution.
I'll add this information to the ticket also.

Regards,
Robert
