### ISSUE TITLE
Fluidsynth plugin doesn't load soundfonts in folders whose name contain special characters

### ISSUE THREAD

**Issue by equis5000** [muse-sequencer/muse#361]
The  fluidsynth plugin seems not to like soundfonts that are stored in directories with certain special characters in its name.

For example, I had a folder named "Música" with soundfonts. It didn't load these soundfonts (terminal gave me: "fluidsynth: error: Unable to open file") , when I changed the name of the directory to "Music" all worked fine.

Could be a character encoding issue, but I am no expert.

Muse version: 2.1.2
OS: Debian 8

**Comment by spamatica** [comment]
Hi,

Yes, I think it's an encoding issue. I actually had a note on a todo list which mentions problems with loading certain soundfonts, but I had neglected to write down what I was trying to load ;)
Now I have a test case, I will have a look at this as soon as possible!

Thanks

**Comment by spamatica** [comment]
Hello,

I just pushed a potential fix for this to MASTER branch in git. If you have the possiblity please test and see if it works for you. Getting encoding right is surprisingly hard and I without more testing I can't see if it's right. ;)
