### ISSUE TITLE
When adding a more shorter midi file to an audio arrangement, the playback stops at the end of the midi file

### ISSUE THREAD

**Issue by Tomtiger66** [muse-sequencer/muse#363]
This is because tag <long> in the <song> section will be overwritten with the imported midi file. I got this issue by importing a midi drum pattern of 92 bars to a project that already contents an audio recording of 184 bars. After importing of the midi pattern, the playback stops at the end of the midi section. 
I could fix this behavior manually by increasing the value of the tag <long>.

**Comment by spamatica** [comment]
Hi and thanks for the bug report.
This should be fixed now in the master git repository.

**Comment by Tomtiger66** [comment]
Hi Spamatica, thank you for the fast fix!
