### ISSUE TITLE
Dexed VST settings not remembered in saved song

### ISSUE THREAD

**Issue by lunadog** [muse-sequencer/muse#364]
I saved a song using various different preset sounds in Dexed VST, but when I reloaded it, the voices had been replaced with the default sound.

**Comment by spamatica** [comment]
As a work around you could try the LV2 version of Dexed.

As for the actual problem, it's quite possible the Dexed VST uses chunks to save it's settings. 
I didn't implement this but as I understand it MusE only supports chunks for native VSTi when compiled against the real VST SDK. 
The VST support bundled with MusE does not have complete functionality (for legal reasons I believe we cannot include the real VST SDK). This should probably be made a bit more evident.

--
I'll give this a try in a bit and see if this analysis holds up.

Thanks for reporting

**Comment by lunadog** [comment]
Thanks! Is there a way to build muse with the real VST SDK to try this out?

**Comment by spamatica** [comment]
Hi and sorry, haven't gotten around to verifying this..

Hmm, I thought this was documented more clearly but seems not.
I believe you need to point the VST_HEADER_PATH environment variable
to the vstsdk dir where the aeffectx.h file is located.

When saving projects with a VST added you will get a warning: "support
for vst chunks not compiled in!" if this does not appear you will have
succeeded with the build. Still it's not sure it works with this
particular synth.

Thanks for testing!


2015-05-02 12:22 GMT+02:00 lunadog <notifications@github.com>:

**Comment by spamatica** [comment]
I've reproduced the problem and successfully verified that it works when compiling with the Steinberg VST SDK.
To set it up to compile with the Steinberg SDK had some problems though so I checked in some fixes to the master branch.
I also added a README.vstsdk with instructions on compiling with the Steinberg VST SDK
