### ISSUE TITLE
sord build error

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#366]
2.2.1 builds fine w/LV2 on my Arch install but git currently fails to compile with this error:

[ 74%] Building C object muse/lv2Support/CMakeFiles/lv2_support.dir/sord/sord.o
/home/dan/src/muse/muse2/muse/lv2Support/sord/sord.c: In function ‘sord_iter_next’:
/home/dan/src/muse/muse2/muse/lv2Support/sord/sord.c:378:34: error: array subscript is above array bounds [-Werror=array-bounds]
    const int idx = iter->ordering[i];
                                  ^
/home/dan/src/muse/muse2/muse/lv2Support/sord/sord.c: In function ‘sord_find’:
/home/dan/src/muse/muse2/muse/lv2Support/sord/sord.c:378:34: error: array subscript is above array bounds [-Werror=array-bounds]
    const int idx = iter->ordering[i];
                                  ^
cc1: all warnings being treated as errors
muse/lv2Support/CMakeFiles/lv2_support.dir/build.make:97: recipe for target 'muse/lv2Support/CMakeFiles/lv2_support.dir/sord/sord.o' failed
make[2]: *** [muse/lv2Support/CMakeFiles/lv2_support.dir/sord/sord.o] Error 1
CMakeFiles/Makefile2:1524: recipe for target 'muse/lv2Support/CMakeFiles/lv2_support.dir/all' failed
make[1]: *** [muse/lv2Support/CMakeFiles/lv2_support.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by danboid** [comment]
Apparently I need to build muse from git to get the U-he plugs to work.

Does Muse support VST sub-plugins like zebralette within zebra2?

**Comment by spamatica** [comment]
Hi Dan, nice to see you around.
Indeed, to get U-he plugins to work correctly the Steinberg SDK is currently necessary.
I can't recall if I tried the zebra plugins but I believe they all started to work with the U-he targeted fixes.

As for the build error I did notice this error with Arch some weeks ago but were not able to fix it. I'll take a look when I have access to an Arch machine. 
Possibly switching compiler to clang will allow MusE to build as I believe it is the new gcc version that introduced some new error check.

**Comment by spamatica** [comment]
-Werror (treat warnings as errors) was enabled on release build for lv2Support, I removed it in git so do try to build again, I think it should work.

**Comment by danvd** [comment]
Hi all! 
-Werror=array-bounds trigger can tell that there are can be errors in sord code and may lead to segfaults.
@danboid, can you post some more info about your compiler and cmake build type? 
Better I'll try to fix sord code so this error will not trigger again :)

Regards,
Andrew

**Comment by danvd** [comment]
Just examined sord.c code and found, that reported error defenetely can lead to segfault.
this piece of code:
for (int i = 0; i < iter->n_prefix; ++i) {
		const int idx = iter->ordering[i];
does not check iter->ordering[] array for size, but it's size is fixed and is equal to TUP_LEN macro which is defined as 4 in code. So, if iter->n_prefix is larger than 4, this code will recive segmentation fault (or can lead to different unpredictable bugs).

Now this loop is more predictable:

for (int i = 0; (i < iter->n_prefix) && (i < TUP_LEN); ++i) {
			const int idx = iter->ordering[i];
I just pushed fixes to master, though this code also can lead to array of bounds compiler warning, so I'm still waiting for compiler info from @danboid :)

Regards,
Andrew

**Comment by danboid** [comment]
Hi Robert and Andrew!

Thanks for the quick response! I've not tried Muse since 2.0 so I'm looking forward to seeing whats new. I was v.happy to see we can now draw lines in the GUI mastertrack editor since 2.2 so that's a great start! :)

gcc 5.1.0
cmake version 3.2.3

**Comment by danboid** [comment]
git builds now so I suppose this can be closed now.

Thanks!

**Comment by danvd** [comment]
I'm on arch with gcc 5.1.0 and also have no problems now. 
Thanks all :)
Closing this.
