### ISSUE TITLE
zebralette / VST sub-plugin support

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#367]
I've just built the latest git with Steinberg headers (I think, more on that in a sec) but Muse doesn't seem to show zebra2 or zebralette as a loadable plugin under the MIDI config window.

I think there might be a small typo in README.vstsdk - shouldn't it say:

cmake -DENABLE_VST_VESTIGE=OFF -DVST_HEADER_PATH=<pathtosdk>/pluginterfaces/vst2.x/

instead of

cmake -DENABLE_VST_VESTIGE=OFF -DVST_HEADER_PATH<pathtosdk>/pluginterfaces/vst2.x/

Notice the missing equals sign in the second which is how it is in the README.

Is there any way to check if Muse has been built with VeSTige or Steinberg headers? I'd like to see this added to the About window if there is no way to tell currently.

Now, onto the actual bug report! :)

I have exported my VST_PATH including the path to zebra and I notice the following when muse loads:

[dan@arch76 ~]$ export VST_PATH=/home/dan/.u-he/Zebra2/:/usr/lib/vst
[dan@arch76 ~]$ muse2
Config File </home/dan/.config/MusE/MusE.cfg>
LOCALE en_GB
Denormal protection enabled.
Trying RTC timer...
RtcTimer::setTimerFreq(): cannot set freq 1024 on /dev/rtc: Permission denied
  precise timer not available, check file permissions and allowed RTC freq (/sys/class/rtc/rtc0/max_user_freq)
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 73
Aquired timer frequency: 300
sh: xdg-user-dir: command not found
/home/dan/Desktop/Zebra2.log 
no deskTopFile found 
creating shell plugin
Plugin does not support processReplacing
AM_MemoryRecord closing down with 0 allocations vs 0 freed
scanVstNativeLib: dlopen(/home/dan/.u-he/Zebra2//Zebra2.32.so) failed: /home/dan/.u-he/Zebra2//Zebra2.32.so: wrong ELF class: ELFCLASS32
Found LV2 plugin: Noize Mak3r
...

So I guess the key bit here is 'Plugin does not support processReplacing'?

One of the first things I'll want to try when you get it working is if I can change the UI display size by right-clicking in the zebralette UI.

Thanks!

**Comment by spamatica** [comment]
Hi Dan,

2015-06-24 16:00 GMT+02:00 danboid <notifications@github.com>:

> I've just built the latest git with Steinberg headers (I think, more on
> that in a sec) but Muse doesn't seem to show zebra2 or zebralette as a
> loadable plugin under the MIDI config window.
>
> I think there might be a small typo in README.vstsdk - shouldn't it say:
>
> cmake -DENABLE_VST_VESTIGE=OFF -DVST_HEADER_PATH=/pluginterfaces/vst2.x/
>
> instead of
>
> cmake -DENABLE_VST_VESTIGE=OFF -DVST_HEADER_PATH/pluginterfaces/vst2.x/
>
> Notice the missing equals sign in the second which is how it is in the
> README.
>
Indeed, fixed now.


> Is there any way to check if Muse has been built with VeSTige or Steinberg
> headers? I'd like to see this added to the About window if there is no way
> to tell currently.
>
During building it should be printed but it is harder to see when already
built, would be good if it was more evident, I'll check!


> Now, onto the actual bug report! :)
>
> I have exported my VST_PATH including the path to zebra and I notice the
> following when muse loads:
>
> [dan@arch76 ~]$ export VST_PATH=/home/dan/.u-he/Zebra2/:/usr/lib/vst
> [dan@arch76 ~]$ muse2
> Config File
> LOCALE en_GB
> Denormal protection enabled.
> Trying RTC timer...
> RtcTimer::setTimerFreq(): cannot set freq 1024 on /dev/rtc: Permission
> denied
> precise timer not available, check file permissions and allowed RTC freq
> (/sys/class/rtc/rtc0/max_user_freq)
> Trying ALSA timer...
> AlsaTimer::initTimer(): best available ALSA timer: system timer
> got timer = 73
> Aquired timer frequency: 300
> sh: xdg-user-dir: command not found
> /home/dan/Desktop/Zebra2.log
> no deskTopFile found
> creating shell plugin
> Plugin does not support processReplacing
> AM_MemoryRecord closing down with 0 allocations vs 0 freed
> scanVstNativeLib: dlopen(/home/dan/.u-he/Zebra2//Zebra2.32.so) failed:
> /home/dan/.u-he/Zebra2//Zebra2.32.so: wrong ELF class: ELFCLASS32
> Found LV2 plugin: Noize Mak3r
> ...
>
> So I guess the key bit here is 'Plugin does not support processReplacing'?
>
That shouldn't be a problem.
I think the real issue is next to last line. wrong ELF class etc. It seems
you have the 32-bit version of the plugin and a 64-bit system?


> One of the first things I'll want to try when you get it working is if I
> can change the UI display size by right-clicking in the zebralette UI.
>

Okay, is there any known issues with that overall?

Thanks,
Robert

**Comment by danboid** [comment]
Hi Robert

Yes I spotted the ELF class error but thats because the Zebra install script installs both the 32 and 64 bit builds. I have got the 64 bit Zebra plugin installed and it loads under both qtractor and Tracktion. Have you tried it under Muse yet?

Both qtractor and Tracktion had to tweak their VST support so that it handled dynamic resizing of plugin UIs before it worked. I can't say I've seen this feature in any Linux VSTs before so that might explain it.

**Comment by spamatica** [comment]
2015-06-24 16:47 GMT+02:00 danboid <notifications@github.com>:

> Hi Robert
>
> Yes I spotted the ELF class error but thats because the Zebra install
> script installs both the 32 and 64 bit builds. I have got the 64 bit Zebra
> plugin installed and it loads under both qtractor and Tracktion. Have you
> tried it under Muse yet?
>
I just did with pretty bleak outcome. It just doesn't show up, hmmm.


> Both qtractor and Tracktion had to tweak their VST support so that it
> handled dynamic resizing of plugin UIs before it worked. I can't say I've
> seen this feature in any Linux VSTs before so that might explain it.
>
Okay, I'll research that. I gather the VST did show up in qtractor and
Tracktion without adding the resize support though?

Regards,
Robert

**Comment by danboid** [comment]
Yep, Zebra and Zebralette would load under both before the display issues were fixed although thats because Rui had already added VST sub-plugin support by the time I came to test it. qtractor didn't resize the window at all initially whilst under Tracktion it did resize but the bottom of the UI was cropped until you manually resized it, up until the last-but-one release of Tracktion.

The guys on KVR say Zebra works great under Bitwig but its very unstable for me under Arch qtractor and Tracktion so I'm hoping it will be more stable under Muse. Apparently abique builds the Linux U-he plugins under Arch so that shouldn't be the issue.

I'm focusing on zebralette initially because I think that's their only free Linux plugin right now.

**Comment by spamatica** [comment]
2015-06-24 17:13 GMT+02:00 danboid <notifications@github.com>:

> Yep, Zebra and Zebralette would load under both before the display issues
> were fixed although thats because Rui had already added VST sub-plugin
> support by the time I came to test it. qtractor didn't resize the window at
> all initially whilst under Tracktion it did resize but the bottom of the UI
> was cropped until you manually resized it, up until the last-but-one
> release of Tracktion.
>
> The guys on KVR say Zebra works great under Bitwig but its very unstable
> for me under Arch qtractor and Tracktion so I'm hoping it will be more
> stable under Muse. Apparently abique builds the Linux U-he plugins under
> Arch so that shouldn't be the issue.
>
> I'm focusing on zebralette initially because I think that's their only
> free Linux plugin right now.
>

Okay, what and where is the most recent version of them?

The problem is that MusE is not happy with the capabilities that Zebra
display atleast. I think it would be best for me to make sure I have the
most recent build before digging deeper.

Thanks,
Robert

**Comment by danboid** [comment]
The most recent (beta) build of the U-he Linux plugs - 3531 - are available here:

http://www.kvraudio.com/forum/viewtopic.php?f=31&t=424953

The first post in that thread is the only place they're available AFAIK.

I've got tarballs of a couple of older releases I could send you if its any help.

Thanks Robert!

**Comment by danboid** [comment]
I should also mention that to get vst-shell plugins aka sub-plugins discovered under qtractor you have to turn View/Options.../Plugins/Experimental/Dummy VST plugin scan OFF.

I asked Rui why this was necessary and what dummy plug-in are and he replied:

"A dummy-plugin is kind of a a stub for each one of the library shared objects files (.so) that are found across the search path scan; for each library file that is found, it makes it a generic so called "dummy-plugin" instance filename, each one faking 1 MIDI input and stereo (2 channels) audio inputs/outputs .

this dummy scan is/was the safest way to scan for VST plugins that doesn't cope with actual open/load and close/unload in quick succession (aka. real non-dummy scan process); historically, many JUCE based VSTs were prone to crash and lock-up the host that eg. doesn't open their GUI editor immediately on load, something that qtractor doesn't do ever, especially while scanning on discovery--this might not be an issue any more for most recent JUCE-plugin builds, but it takes just one old leftover still around to doom and compromise it all.

now, VST-shell (sub-)plugins can only be discovered if its library object (.so) is actually loaded up and gone through its run-time programmatic interface, something that is simply skipped while on a dummy-scan, as explained before.

besides, the dummy-scan is just an user safety option rather than an official stance against VST sub-plugins or whatever."

I hope that helps?

**Comment by spamatica** [comment]
2015-06-24 18:11 GMT+02:00 danboid <notifications@github.com>:

> I should also mention that to get vst-shell plugins aka sub-plugins
> discovered under qtractor you have to turn
> View/Options.../Plugins/Experimental/Dummy VST plugin scan OFF.
>
> I asked Rui why this was necessary and what dummy plug-in are and he
> replied:
>
> "A dummy-plugin is kind of a a stub for each one of the library shared
> objects files (.so) that are found across the search path scan; for each
> library file that is found, it makes it a generic so called "dummy-plugin"
> instance filename, each one faking 1 MIDI input and stereo (2 channels)
> audio inputs/outputs .
>
> this dummy scan is/was the safest way to scan for VST plugins that doesn't
> cope with actual open/load and close/unload in quick succession (aka. real
> non-dummy scan process); historically, many JUCE based VSTs were prone to
> crash and lock-up the host that eg. doesn't open their GUI editor
> immediately on load, something that qtractor doesn't do ever, especially
> while scanning on discovery--this might not be an issue any more for most
> recent JUCE-plugin builds, but it takes just one old leftover still around
> to doom and compromise it all.
>
> now, VST-shell (sub-)plugins can only be discovered if its library object
> (.so) is actually loaded up and gone through its run-time programmatic
> interface, something that is simply skipped while on a dummy-scan, as
> explained before.
>
> besides, the dummy-scan is just an user safety option rather than an
> official stance against VST sub-plugins or whatever."
>
> I hope that helps?
>

Indeed I think that explains what I'm seeing. I wasn't at all aware of
sub-plugins and neither is our implementation so I think we have a hurdle
to overcome there first.
The plugin we see from the .so has no capabilities at all.

No more time now but hopefully I can get back to this soon.

Regards,
Robert

**Comment by danboid** [comment]
zebralette works and is much more stable under Ardour 4 than under qtr or Tracktion. The UI resize doesn't work under A4 yet but it seems I'd have to recommend you look at how Ardour handles VST sub-plugins instead of qtractor if you wanted to see how others have got this to work. A4 also has the advantage of not hiding this feature behind an almost hidden option which basically says Rui isn't confident in sub/dummy/shell plugins working properly under qtr.

**Comment by spamatica** [comment]
2015-06-24 22:14 GMT+02:00 danboid <notifications@github.com>:

> zebralette works and is much more stable under Ardour 4 than under qtr or
> Tracktion. The UI resize doesn't work under A4 yet but it seems I'd have to
> recommend you look at how Ardour handles VST sub-plugins instead of
> qtractor if you wanted to see how others have got this to work. A4 also has
> the advantage of not hiding this feature behind an almost hidden option
> which basically says Rui isn't confident in sub/dummy/shell plugins working
> properly under qtr.
>

Alright, thanks for the tip.

Regards,
Robert

**Comment by danboid** [comment]
Is there any update on this?

I've just tried git (muse3) but Zebralette still isn't showing up under the VST synth menu.

**Comment by spamatica** [comment]
Hi Dan,

2015-11-17 2:42 GMT+01:00 danboid <notifications@github.com>:

> Is there any update on this?
>
> I've just tried git (muse3) but Zebralette still isn't showing up under
> the VST synth menu.
>
Sorry to say, definitely my fault. I took it under my wings but time and
energy has unfortunately not been there. So, after some initial analysis
not much has happened.

**Comment by danboid** [comment]
Thanks for the update Robert!

It's getting colder now... I'm sure we'll get this working!

**Comment by danvd** [comment]
Hi all,
I very much like to investigate such things ;)

**Comment by danboid** [comment]
I hoped you might and I'm sure Robert isn't going to be greatly upset (or surprised) if you beat him to it!

:D

**Comment by spamatica** [comment]
2015-12-02 23:32 GMT+01:00 danboid <notifications@github.com>:

> I hoped you might and I'm sure Robert isn't going to be greatly upset (or
> surprised) if you beat him to it!
>
> :D
>
Indeed I do not :)

**Comment by danvd** [comment]
Viola! 
Commit c2568f0 - native vst shell plugins support!

By the way, zebra2 plugin dll consists of 4 plugins:
zebra2
zebralette
zebrify
zrev

The last 2 are effects only with no midi inputs but are initialized right. 

Guis are working.

Please test, test, test ;)

Regards,
Andrew

**Comment by danboid** [comment]
EXCELLENT! :D

It's so good to have Zebralette working under MusE!

You're right about the 4 Zebra2 sub-plugins - I neglected to mention those although I was aware of them. An extra bonus surprise is that Zebralette doesn't have the 100% zoom problem that Podolski (still) does. Zebralette opens at 100% (as I expected Podoski would) and has no probs re-opening at 100% or any other zoom setting.

Great work Andrew! Thanks v.much! :)

**Comment by terminator356** [comment]
On December 3, 2015 11:53:14 AM Andrew wrote:
> Viola!
> Commit c2568f0 - native vst shell plugins support!
> 
> By the way, zebra2 plugin dll consists of 4 plugins:
> zebra2
> zebralette
> zebrify
> zrev
> 
> The last 2 are effects only with no midi inputs but are initialized right.
> 
> Guis are working.
> 
> Please test, test, test ;)
> 
> Regards,
> Andrew
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/367#issuecomment-161764111

32-bit OS here:

[ 93%] Building CXX object muse/CMakeFiles/core.dir/wave.o
/home/col/Source/muse3-20151101/muse3/muse/vst_native.cpp: In function ‘void 
MusECore::scanVstNativeLib(QFileInfo&)’:
/home/col/Source/muse3-20151101/muse3/muse/vst_native.cpp:479:157: error: 
format ‘%ld’ expects argument of type ‘long int’, but argument 4 has type 
‘VstIntPtr {aka int}’ [-Werror=format=]
           fprintf(stderr, "ERROR: Failed to instantiate plugin in VST library 
\"%s\", shell id=%ld\n", fi.filePath().toLatin1().constData(), currentPluginId);


TIm.

**Comment by danvd** [comment]
Don't have 32 bit os right now, but hope that just pushed a8b2ba0 fixes this error.

**Comment by terminator356** [comment]
On December 3, 2015 02:24:02 PM Andrew wrote:
> Don't have 32 bit os right now, but hope that just pushed a8b2ba0 fixes this
> error.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/367#issuecomment-161805357

Yup.

Thanks!

Testing...

T.

**Comment by danvd** [comment]
I remembered, that I had not modified save/load project to support vst shell plugins. Now working on it.

**Comment by danvd** [comment]
Oops. vst plugin id is already here when song is loading, so there is no need to save/restore it! I have to sleep more surely :D
