### ISSUE TITLE
opening a file via terminal fails if current directory isn't ~/Documents/Muse2-Sequencer/

### ISSUE THREAD

**Issue by ericfont** [muse-sequencer/muse#371]
If I want to open up a file using the command muse2 $filename, the file will only be sucessfully opened only if I changed my current directory to ~/Documents/Muse2-Sequencer/ before running the command.  

I don't know if this is just my machine.  I'm running self compiled install on arch linux x86-64.  Could someone verify this behavior?  

Could I submit a feature request for muse2 to open a file starting from any directory in command line?  The reason I'd like to is because I want to run inotify on a directory and open muse if a midi file has appeared there.  (my use case is editing something in musescore, exporting it as midi, and then having it automatically open up in muse2).

**Comment by ericfont** [comment]
hmm...I can't seem to reproduce this now.  I no longer think the current directory was the cause of why files wouldn't open.

**Comment by danvd** [comment]
Hi Eric,

Ok, Me too. Tried to launch muse from song's directory and with full path - opened normally, tithout errors.
