### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#373]
Hi,

if I try to compile version 2.2.1, I get an error that ladspa.h cannot be found. However, it does exist in /usr/include folder.

I am relatively new to compiled (have done a few music programs without problems) so I am not sure where to go next.

My system is running openSUSE 13.2.

Thanks,
Chris.

**Comment by luxigo** [comment]
Same here with Debian 8

cmake complains for missing ladspa.h despite it can be found in /usr/include

Comment the 4 lines beginning with CHECK_INCLUDE_FILE(ladspa.h HAVE_LADSPA_H)  in CMakeLists.txt as workaround.

After cmake is successful (after having installed all the missing dependencies cmake pinpointed) the lines checking for ladspa.h can be restored.

Maybe the error message is innapropriate, @therealkitman ?

**Comment by spamatica** [comment]
I'm not doubting that this problem exists but it is very puzzling.
I tried to reproduce it but failed this far. Installed debian 8 in a VM and both muse-2.2 and muse-3.0 compiled without any issues. 
muse-3.1 requires too new Qt version, I don't know if there is a debian way to upgrade it.

I double checked that ladspa.h only seems to be at /usr/include/ladspa.h
cmake version is 3.0.2

Thanks for listing the workaround anyway.
