### ISSUE TITLE
WIN VST

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#374]
HI,

is is possible to compile v2.2.1 with WIN VST support? There is a nice vocoloid'ish VST at http://www.a-quest.com/products/aquestone1.html but it is a .dll file.

I can use this dll if I use it via the Carla LV2 plugin but I wonder if version 2.2.1 can use it natively. I saw an old screen shot of version 1 with WIN VST.

Thanks,
Chris.

**Comment by spamatica** [comment]
Hi,

Looks like a wierdly funny plugin :)
But no, MusE does not support Win VST directly. I haven't tried the Carla LV2 plugin, but there is a dssi proxy that I use, which allows for seamless integration, dssi-vst. To get the most out of it there is a patch that never seem to have gotten merged to upstream dssi-vst.
You can read about it here:
http://muse-sequencer.org/index.php/Faq#Windows_VST_support_through_DSSI_.2B_patch
If you are using a distribution with a specific audio repository (like *buntu + kxstudio) there is a good chance this dssi plugin is already packaged and ready.
If you get it all installed the win vsts will appear in the plugin list just as any other plugin, but listed as a dssi plugin.

Hope that helps, let me know if there's something further

**Comment by therealkitman** [comment]
Thanks. I'll try the dssi-vst approach tomorrow.

Regards...

**Comment by therealkitman** [comment]
Hi,

I have decided to keep with the Carla plugin for now and maybe play with the dssi-vst patch a little later.

I'll close this issue and say thanks,
Chris.
