### ISSUE TITLE
A score editor for drums

### ISSUE THREAD

**Issue by kbanelas** [muse-sequencer/muse#375]
It is a pleasure to have known MusE.
In a range 0 to 10 points, my feedback would be to say at least 8 point for this awesome application.
My hobby is composing MIDI files, I make often music with Cakewalk 9. Yes, it's an older application, but it still works fine. Although it works fine only in other operating system very known for all us.
Well, now, I have installed debian and have known this program among others, and I see that this is, in my opinion, the best option.
So I would want to add modestly my opinions with the spirit of offer ideas if you let me do it.

For example, a score editor for drums. I have watched the matrix editor for drums and it is fantastic for tweaking, but for composing drums is simpler and faster the sheet music.

Thanks

Cheers!

**Comment by Windfisch** [comment]
Hey! The author of the score editor here!

Once back in the old days™, I had this on my to do list, however then I could not afford investing more time into MusE :/.

Also, I never really knew how a drum score editor should actually work. Which features would it need? How does one denote the length of some notes, like drum rolls? Can you sketch me how this drum score would look like, how it would behave on user input, etc?

Maybe I can find some time to implement this :)

**Comment by kbanelas** [comment]
Hey! Fantastic news! A "maybe" is a beginning! I am sketching how could be. Let me several hours because I'll try to document you about this the best I can.

Regards

**Comment by kbanelas** [comment]
Hi again!

I have sketched something, I hope this sketch can help you for something.

Well, first three free links from youtube

1 https://www.youtube.com/watch?v=dhVsbb61CpY

2 https://www.youtube.com/watch?v=zVeym8LU0b0

3 https://www.youtube.com/watch?v=I-jV7zmtCDM 

And of course the sketch:

![drums](https://cloud.githubusercontent.com/assets/14902547/10216808/03f5398e-682c-11e5-81ab-84f47e503931.jpg)

Advices:
1º I suggest that when somebody is putting a note, this note is emitting its sound.
2º Triplets and dotteds exist and make easier the write.

Little by little ;)
