### ISSUE TITLE
Cross fade?

### ISSUE THREAD

**Issue by scemama** [muse-sequencer/muse#377]
Hi,
Is there a simple way to make a cross fade between audio files in the main window? I couldn't find the keyword "cross fade" in th documentation so this is why I ask it here.
Thanks!

**Comment by spamatica** [comment]
Hi,
It's possible but not as easy as it should be, the crossfade button is still on the to-do list.
To achieve it the wave files must be on separate tracks and then create volume automation on each of them to lower volume on the first and increase on the second.

**Comment by scemama** [comment]
OK, thanks for your quick reply!

**Comment by terminator356** [comment]
Also try using a crossfade plugin such as LV2 4-In 4-Out Crossfade.
You will need to create the crossfade as a synth track, not a rack plugin,
 to be able to use all the channels.
You can automate any MusE plugin controls.

And with the latest git master changes, coming soon in release, 
 it is now easier to work with multi-channel synths and tracks
 such as a crossfade.

Tim.

**Comment by scemama** [comment]
Thanks for the info!
