### ISSUE TITLE
cannot register forum

### ISSUE THREAD

**Issue by tjingboem** [muse-sequencer/muse#378]
the image verification process seems to be broken

**Comment by R-a-l-f** [comment]
The same here.

http://lists.linuxaudio.org/pipermail/linux-audio-user/2015-October/102849.html
http://lists.linuxaudio.org/pipermail/linux-audio-user/2015-October/102850.html

**Comment by danvd** [comment]
Hi All!

It seems, that recaptcha api has been changed. Will look now.
Thanks for the info :).

Regards,
Andrew.

**Comment by danvd** [comment]
Ok, the problem fixed. Can you retest now?

**Comment by R-a-l-f** [comment]
Thanks,

I confirm that registration now works.

Regards,
Ralf

**Comment by tjingboem** [comment]
yes it works now.
thanks Ralf and Andrew
