### ISSUE TITLE
Ingen window size

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#379]
Hi all,

I have loaded an ingen patch as a LV2 synth. However I can't resize the ingen window in any way (dragging corners or clicking FULLSCREEN in its toolbar) to see the patch contents. I can load the same patch in Carla and resize ok so I'm guessing a MusE issue? Apart from that the patch works fine in MusE.

PS. On a slightly off topic, the patch is just a test of drone/whooshy sounds. Is it possible to load a short sound file into a track and loop it  while the other tracks plays or do I need to use an external loop machine?

Thanks,
Chris.

![ingensize](https://cloud.githubusercontent.com/assets/14888092/10714484/66d9ea6e-7b2c-11e5-949b-6a7d17e8b7d4.png)

**Comment by danvd** [comment]
Hi Chris,

What version (release or git/vcs) of ingen do you use? I can check it today, I think.

Regards,
Andrew.

**Comment by therealkitman** [comment]
Hi Andrew,

It's 0.5.1.

Thanks... 

----- Original Message -----

**Comment by danvd** [comment]
Hi Chris,
Fixed in b966736.

Not closing - waiting for you to check if it works right.

**Comment by therealkitman** [comment]
Hi Andrew and thanks.
However, do I assume I need to download the master zip first to get muse3? I am still using Muse2.

Regards,
Chris.

**Comment by danvd** [comment]
Yes, this fix only in current master.

**Comment by therealkitman** [comment]
Hi Andrew,

I have downloaded the new master.zip and installed. Muse3 runs ok with all lv2 plugins except my ingen based ones. Log attached.

PS. Am confused; is muse3 a new released version? All labels still say v2.2 as well no news on the web page or forum? 

Thanks,
Chris.

[muse3.log.zip](https://github.com/muse-sequencer/muse/files/62029/muse3.log.zip)

**Comment by therealkitman** [comment]
Uh oh. The issue with the pianoroll that was fixed in #376 has returned in muse3. That is a drawn A4 note plays back as A5 (in the first bar in the attached image) but recorded A4 notes in bars 2 and 3 play back ok as A4 but are labelled as A3.

![pianoroll](https://cloud.githubusercontent.com/assets/14888092/11801696/69fba84e-a323-11e5-83a9-c372e8ea8218.png)

**Comment by danvd** [comment]
Hi Chris!

I'll look at your log file soon, but now about pianoroll labelling. Yes, I had to revert my changes back, because original labelling was right. See #397.
According to midi specification middile C is C3.

**Comment by therealkitman** [comment]
Hi ,

I find the issue of middle C most peculiar. I learned that middle C is 
C4 at ~256Hz and corresponds to midi number 60 and A4 at 440Hz midi 69.

https://en.wikipedia.org/wiki/C_%28musical_note%29

It shouldn't matter what synth is used because as long as key 60 is sent 
that should correspond to C4.

Most odd.

Regards...

**Comment by danvd** [comment]
Wow :)
I did not chacked wikipedia. Now digging other resources, and the information seems to be very different. So let's consider middle C is C4. I'll redo changes soon ;)

**Comment by therealkitman** [comment]
I've got Ardour4 and LMMS. I repeat my pianoroll tests (tonight) just to 
see if they conform as well.

**Comment by danvd** [comment]
Ok. thanks! Waiting for the info.

**Comment by danvd** [comment]
Just checked yout muse.log. More info needed.
Can you made this steps?:
1. Recompile with CMAKE_BUILD_TYPE=Debug
2. Run under gdb
3. When it will crash, type `bt` and send output here.

**Comment by danvd** [comment]
Just checked note numbers in Logic Pro X. They are the same as in MusE. 
Cheked: 60 is C3, 72 is C4 in both apps.

It seems that it'll be better to leave labels as is.

**Comment by therealkitman** [comment]
That is puzzling. I just used both LMMS and Ardour3 (Ardour4 died on me) and their respective pianorolls. Both recorded midi (note 69), as well as hand edited notes, play the correct note and are labelled  correctly in the pianoroll - that is a real A4 @ 440Hz is labelled A4.

I don't know about Logic Pro X (LPX) but I am willing to bet that it is wrong. I nearly got caught out with LMMS as you can calibrate the keyboard scale and I made sure A4 was 440Hz. I wonder if LPX has a similar calibration trick? Ardour3 works out of the box.

**Comment by danvd** [comment]
Hmm, I also made tests with ardour (version 4 in my case):
drawed notes C3 and C4, exported midi part
imported it into muse - they appeared as C2 and C3.

Perhaps it can be done by adding "Middle C" config option which can be changed at runtime...

I also want to know Tim's and Robert's opinion before making changes.

**Comment by danvd** [comment]
Some UPDATE: also imported this midi file into logic pro - they appeared as C2 and C2 as in MusE.

**Comment by therealkitman** [comment]
I have recompiled muse3 with DEBUG and ran things as requested under gdb. New log attached.
[muse3.log.zip](https://github.com/muse-sequencer/muse/files/62382/muse3.log.zip)

**Comment by therealkitman** [comment]
If you drew notes C3 and C4(middle C)  and exported the midi file (midi 48 and 60) but the Muse and LPX plays C2 and C3 then something has to be amiss?

![midi](https://cloud.githubusercontent.com/assets/14888092/11809735/e8fc3efc-a363-11e5-92df-29ef394c7d22.png)

**Comment by danvd** [comment]
Recorded video with logic midi+list editor. Here it is:
https://youtu.be/sfyYbMKZePE

**Comment by therealkitman** [comment]
OK, so you typed midi number 72 and it gave you C4 and midi 60 gave you 
C3. That has to be wrong?

See chart at https://newt.phys.unsw.edu.au/jw/notes.html

**Comment by danvd** [comment]
Yes. MusE also displays 60 as C3 and 72 as C4.
But ardour displays 60 as C4 and 72 as C5

**Comment by danvd** [comment]
Hi Chris,

I examined your log file. The error is triggered when plugin instantiated, not when gui opens. Does this error apper in other hosts or not?

**Comment by spamatica** [comment]
Hi Chris,

2015-12-15 4:47 GMT+01:00 therealkitman <notifications@github.com>:

> Hi Andrew,
>
> I have downloaded the new master.zip and installed. Muse3 runs ok with all
> lv2 plugins except my ingen based ones. Log attached.
>
> PS. Am confused; is muse3 a new released version? All labels still say
> v2.2 as well no news on the web page or forum?
>
No, MusE 3 is the coming version. the master.zip file you downloaded is a
snapshot of the master branch, essentially what we are working on currently
and now are trying to stabilize as MusE 3. Be aware that there has been a
number of changes and improvements so there may be new bugs, but we try to
fix the bugs as soon as possible, especially Andrew ;)

To explain further, incase it is unclear. MusE is developed in the open so
what you see on the github page is the sourcecode as we are working on now.
Some development may occur in separate branches but when it approaches
being stable it is merged to the master branch, when we make a release we
take what is in the master branch and package it up and put it on the
download page. The idea ofcourse being that this is more stable than using
MusE built from github.
 Usually access of sourcecode is not through the master.zip file but with
the git tools which allows to download and manipulate the files in a more
developer friendly way. This goes for users who want bleeding edge too, you
have the same source folder and just update with the latest changes.
E.g
1. download the full source code
git clone https://github.com/muse-sequencer/muse.git
2. perform an update to get the latest changes
git pull (standing in the muse sourcecode folder)

Hope that clears it up, if not ask away :)

/Robert

**Comment by spamatica** [comment]
2015-12-15 12:27 GMT+01:00 Andrew <notifications@github.com>:

> I also want to know Tim's and Robert's opinion before making changes.
>
Not really my area, sounds very odd that there are two different variants
of this.
I found this (which seems closest to the spec which I believe you still
have to pay for):
http://www.midi.org/techspecs/midituning.php
where it mentions middle C as 60, no number for middle C though.

/Robert

**Comment by terminator356** [comment]
On December 15, 2015 05:29:41 AM Andrew wrote:
> Yes. MusE also displays 60 as C3 and 72 as C4.
> But ardour displays 60 as C4 and 72 as C5

This is mildly amusing how much confusion it's causing.

According to The SoundBlaster Book, note # 00 is supposed 
 to be C0, and it goes up from there to #127 = G10.

Which makes sense, you don't need a book to 
 realize that.

However, at one time I had written in pencil on the page, 
 that the octaves go from -2 to +8.
IIRC that was because that is how the MusE piano displays it, 
 so I wrote it down to remember it.

Therefore, now I am recalling more about this problem:
There are at least two possible reasons for the disparity:

1) 
Someone was trying to shift the octave numbers so that 
 two digits are not required. Octave 10 would require 
 a wee bit more horizontal space to display, and it is 
 possible we were trying to minimize that, given the
 limited space in the piano. 
This may be the more likely scenario.

2)
Someone was trying to align the octaves so that C0 is
 "middle C". 
I can't recall what the official Midi middle C is...
Ah yes, The SoundBlaster Book says note #60 is "middle C"
 which is our C3, which is way off, so I guess theory 2) is wrong.

Make any sense?

Tim.

**Comment by therealkitman** [comment]
I have only used Carla as a host and that worked fine with the same 
ingen patch.

**Comment by therealkitman** [comment]
Thanks Robert, it sort of clears things.

I am a newbie when it comes to git (haven't found a decent youtube video 
yet :) ) but then I don't do a lot of compiling as I usually use 
opensuse's packages. I might clean my PC up a bit and put the git 
development stuff in a virtual environment.

Regards...

**Comment by terminator356** [comment]
On December 15, 2015 06:03:26 PM you wrote:
> On December 15, 2015 05:29:41 AM Andrew wrote:
> > Yes. MusE also displays 60 as C3 and 72 as C4.
> > But ardour displays 60 as C4 and 72 as C5
> 
> This is mildly amusing how much confusion it's causing.
> 
> According to The SoundBlaster Book, note # 00 is supposed
>  to be C0, and it goes up from there to #127 = G10.
> 
> Which makes sense, you don't need a book to
>  realize that.
> 
> However, at one time I had written in pencil on the page,
>  that the octaves go from -2 to +8.
> IIRC that was because that is how the MusE piano displays it,
>  so I wrote it down to remember it.
> 
> Therefore, now I am recalling more about this problem:
> There are at least two possible reasons for the disparity:
> 
> 1)
> Someone was trying to shift the octave numbers so that
>  two digits are not required. Octave 10 would require
>  a wee bit more horizontal space to display, and it is
>  possible we were trying to minimize that, given the
>  limited space in the piano.
> This may be the more likely scenario.
> 
> 2)
> Someone was trying to align the octaves so that C0 is
>  "middle C".
> I can't recall what the official Midi middle C is...
> Ah yes, The SoundBlaster Book says note #60 is "middle C"
>  which is our C3, which is way off, so I guess theory 2) is wrong.
> 
> Make any sense?
> 
> Tim.

An old description is found in piano.cpp, by an original coder.
(Note the German h for b.)
The range matches what I wrote in my book:

/*
      0   1   2  3  4  5  6  7  8  9  10
      c-2 c-1 C0 C1 C2 C3 C4 C5 C6 C7 C8 - G8

      Grid ьber Oktave:

           +------------+ ------------------------------
       11  |            |
           |         h  |         7
           +------+     |
       10  |  a#  +-----+ ..............................
           +------+  a  |
        9  |            |         6
           +------+     |
        8  |  g#  +-----+ ..............................
           +------+  g  |
        7  |            |         5
           +------+     |
        6  |  f#  +-----+ ..............................
           +------+  f  |
        5  |            |         4
           |            |
           +------------+ ------------------------------
        4  |            |
           |         e  |         3
           +------+     |
        3  |  d#  +-----+ ..............................
           +------+  d  |
        2  |            |         2
           +------+     |
        1  |  c#  +-----+ ..............................
           +------+  c  |
           |            |         1
        0  |            |
           +------------+ ------------------------------
 */

The actual characters are bitmaps found in piano.cpp

I've cleaned up the bitmaps a few times in the past and the code. 
But I never changed the octave numbers.

I'm not sure if there was some other reason why it is like this.
Trying to recall. There's always something...

But I'm wondering if there's no reason why we can't change 
 the number range to a proper 0 through 10. Personally I've 
 never paid much attention to the octave numbers so I probably 
 never considered changing them.

There /is/ enough space to draw the "C10" in the bitmaps
 on the piano. It's only the top octave so it won't be too ugly.

Also I think we should mark middle 'C' specially.
For example with brackets or a star or something.

I just /know/ I'm forgetting something. 
Am I?

T.

**Comment by therealkitman** [comment]
Out of curiosity, if there is a final consensus that C4 is midi 60 and 
should be labelled as such, as it is in LMMS and Ardour3/4, should 
someone have a word with the Logic Pro X people too?

**Comment by danvd** [comment]
Some more tests: just installed Cacewalk pro audio 9 (remember it?).
Tests are more and more interesting :):
Originally drew notes in ardour and exported midi file.

In Ardour: C4 and C5
In MusE: C3 and C4
in Cakewalk: C5 and C6

Brrr.

**Comment by terminator356** [comment]
Just to clarify, middle C note 60 is C5, not C4, given that C0 is note 00.

**Comment by therealkitman** [comment]
This is so confusing.

https://en.wikipedia.org/wiki/C_%28musical_note%29#Middle_C
Piano Keyboard

**Comment by terminator356** [comment]
Yes, just been reading up on it. Guess what? Sonar defines middle C as 60 C5,
 just as I proposed. They said they are simply going logically by the midi notes,
 the same as I proposed.
However - they said there is a drop-down option where you can alter the 
 base octave number to whatever you want, like -2.
It affects nothing else whatsoever but the drawn octave numbers.

It seems that we may just have to do this, since there's no consensus 
 and people may have different uses, eh guys?
Consider that some may use a treble or bass clef and some may use
 a grand staff. Each user might want the middle C and/or the octave 
 numbers at different places. We may need to provide a shift for both.

As for anything else - played notes, recorded notes, step record etc,
 do not touch them. Just the octave drawing.
Our 'transpose' track info box will do any required real note shifting.

Whacha think?

Tim.

**Comment by terminator356** [comment]
Further: Since different physical instruments might define middle C
 and indeed the entire octave range differently, I think we should
 add a couple of new parameters to our Midi Instrument class.
That way the user can define them in each instrument, either
 directly in the xml .idf files or using the Instrument Editor.
Then these parameters are applied while drawing the piano keyboard.

Sound reasonable?
Tim.
