### ISSUE TITLE
Drop down lists.

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#380]
Hi,

after Andrew released a patch for issue #376 I find that the dropdown lists to select synths, effects etc changed from a single column to a multitab/sheet affair that I find terrible to navigate. If I want to select a LV2 (effects) to have to move my mouse VERY quickly because as soon as the mouse hovers over the LV2 (synths) most of the screen is covered by the multitab/sheets.

It was far friendlier to navigate when I had a single column of (many) effects or synths.

May I suggest reverting back to the old format.

Thanks,
Chris.
![ingensize1](https://cloud.githubusercontent.com/assets/14888092/10714568/9b63b780-7b2f-11e5-9a73-c918411759e8.png)

**Comment by danvd** [comment]
Hi Chris,

The submenu style is controlled by "Scrollable submenus" option in MusE's settings (it's a checkbox). No restart is needed after changing it. By default leveled submenus are used. As for me I also prefer scrollable submenus, but I don't know the statistics.

Regards,
Andrew.

**Comment by therealkitman** [comment]
Hi Andrew,

Thanks very much. The submenus are so much easier now to use.

Regards,
Chris.
 

----- Original Message -----
