### ISSUE TITLE
Cannot read template

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#383]
I've just installed muse3 from git under Arch and I get the error

Cannot read template

Every time I start muse3.

**Comment by danvd** [comment]
Hi @danboid 

This is because of old settings from 2.2 version. Just clear ~/.config/MusE directory and error will gone.

**Comment by danboid** [comment]
Hi  Andrew!

Yep, deleting ~/.config/MusE fixed that minor annoyance!

Thanks
