### ISSUE TITLE
Abort and restart recording shortcut

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#384]
It'd be very useful for crappy musicians like me to have a new Muse shortcut that would stop recording, delete/undo the just-recorded take(s), rewind to where the current take started and arm the transport for recording all in one keypress so the user only need push this 'Abort and restart take' key then hit space to do another take (and another...)

I think it'd be cool if right (or middle) clicking on the stop button when recording did this too so you could start over easily enough using just a mouse too.

**Comment by danboid** [comment]
I hope none of the main muse devs would be opposed to adding this feature?

After becoming accustomed to a DAW with such a feature I now feel uncomfortable whenever I try recording audio (or playing a MIDI device in realtime) with a DAW without such a feature.

I wanted to check as the author of another open source DAW is reluctant to add such a feature and I can't understand why.

**Comment by danvd** [comment]
I think htis is a good feature (I also need this :) ). One question: from what place restart record? from left mark or from last cursot position?

**Comment by danboid** [comment]
That's good news!

Last cursor position would work best I think - that way it's one less thing I have to do and I'm all about max lazyness! :)

**Comment by danboid** [comment]
I said last cursor position but really I mean last playhead position.

**Comment by spamatica** [comment]
Definitely a + vote on that one. Really good feature idea.

2015-11-18 12:10 GMT+01:00 danboid <notifications@github.com>:

**Comment by danboid** [comment]
I'm glad to hear two of the main muse devs thnk this is a good idea as that means we can safely expect to see this added before long.

I'm looking forward to doing some efficient recording with muse soon!

:)

**Comment by danvd** [comment]
I'll imlement this feature till the end of this year (I hope :) ). I'm not so good singer and guitar/piano player, so this shortcut will be very useful for me too! Thanks for the idea ;)

**Comment by danboid** [comment]
That'd be great! Thanks Andrew!

**Comment by terminator356** [comment]
On November 18, 2015 06:12:08 AM spamatica wrote:
> Definitely a + vote on that one. Really good feature idea.
> 
> 2015-11-18 12:10 GMT+01:00 danboid <notifications@github.com>:
> > I said last cursor position but really I mean last playhead position.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/muse-sequencer/muse/issues/384#issuecomment-157680821>
> > .
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/384#issuecomment-157724525

+1 for me as well.

Been planning/dreaming of such a feature. But some concepts got in the way.

Let's do this nicely and completely if possible ! Some thoughts:

I would suggest we call this feature 're-take', and make it a 'mode'
 with a few different modes.

Mode 1: Re-take:
Upon aborting the recording with space bar or stop, MusE will
 re-position the play head at the place where recording began,
 and erase what was recorded on the previously armed tracks, 
 and re-arm those tracks and the transport record-arm such that 
 the user only needs to press space bar or play to begin re-recording.

Mode 2: Multi-take:
Upon aborting the recording with space bar or stop, MusE will
 re-position the play head at the place where recording began,
 but it will NOT erase what was recorded but instead will create 
 new BLANK COPIES of the tracks in question and arm THESE tracks
 and rec-arm the transport such that the user only needs to press 
 space bar or play to begin re-recording.
Thus each time stopped and re-started, the user is recording 
 multiple takes.
This mode is most important for me. 

Never discard a recording unless it is surely garbage - you may
 find parts of the recording useful and despite having flaws you 
 may not get to repeat some of your 'brilliance' as the quality
 deteriorates with each take and you get more tired as time goes on.

Usually I pre-create several tracks just for this purpose of 
 multiple takes. I review later and decide what to keep or
 take 'snippets' from or delete.
Perhaps a third mode could somehow respect these pre-created
 tracks and just move to the next pre-created track for a re-take.

These proposed modes would sure make recording a lot easier.
It is a PITA to keep re-positioning, rec-arming, and so on. 
Creativity and performance focus take a hit when encumbered by this.

Of course, we also have our transport loop mode. Some artists prefer 
 a looping recording mode. But this is not quite the same as re-taking,
 and our loop mode is, I'm not quite sure 100% reliable. 

Thanks.
Tim.

**Comment by danboid** [comment]
The way I envisioned this feature would work is that the user starts recording as usual. When they want to stop, they'd push SPACE (or click stop), as they usually would. Pushing stop or SPACE should never delete what you just recorded and is what you'd use if you're unsure if you got a good take.

Now, if you know for sure what you just recorded was BS (and we all know this happens a lot) you'd have to hit a slightly more difficult key combo like Alt+a (a for abort) and that would nuke your take with no questions asked. It prob wouldn't have an icon that could be easily clicked by mistake to reduce unwanted loss of takes.

I'm not sure I really understand the use case for Tim's multi-take mode but obviously he has his reasons. I don't care what this feature is called just as I can record with minimum effort.

I'm glad everyone agrees this is a must-have feature anyway! :)

**Comment by danvd** [comment]
Ok, I'm almost ready for this. 
What I'm planning to do first:
(Tim named this Re-take)
1. While in the recording process one can press shortcut (say ALT+SPACE).
2. If shortcut is pressed, then all recordings on armed tracks are deleted, play head jumps to previous recording start position and the process continues.
Note, that my point of view assumes that recording *is not stopped* after shortcut is pressed, but continues from last point (after deleting what was recorded). To actually stop recording you will need to press SPACE only. 
But if recording was stopped with space key, there will remain an ability to restart it using alt+space.

How does it sounds?

**Comment by danboid** [comment]
That's pretty much what I had in mind except my original idea was that recording wouldn't restart until the user hits SPACE or clicks play although I can see why some might prefer it (as it seems you do) if recording restarts instantly. I think your version of it might be better just because its one less key press though so yeah, do it the way you suggested Andrew.

Thanks!

**Comment by danboid** [comment]
Any update on this Andrew? I thought it'd be a pretty easy feature to add. Is that not the case?

**Comment by danvd** [comment]
Hi Dan,

Working on it right now. Hope it will be ready till tomorrow's evening :).

**Comment by danboid** [comment]
Good news! Thanks for the update!

**Comment by danvd** [comment]
Hi Dan,

I think, that initial testing can be done. I've added an ability to restart recording in discard mode:
While recording is running, press CTRL+SPACE (or CTRL+<start/stop> shortcut):
- all recorded events (midi + wave) are discarded
- current position is reverted to last record start point 
- recording continues from this new point

I tested - in my case all works :). Very useful function for me!

Waiting for test results.

Regards,
Andrew

**Comment by danboid** [comment]
Hi Andrew

Thanks for addng this into MusE! I've had a quick test recording audio and hitting CTRL+SPACE and it seems to work fine and works as I expected so it's looking good so far!

The only minor issue is that I couldn't see CTRL+Space / restart recording or whatever its being called (retake?) under the keyboard shortcuts. Am I missing it or has it not been added as a freely bindable shortcut yet? CTRL+Space works well for me but if I was new to the program or you'd not told me here I'd be looking there to find out what the shortcut is of course.

**Comment by danvd** [comment]
Yes, it was only the first step. But now it works, so I'll add shortcut and implement multitake too. 
So don't close this issue yet.

**Comment by danboid** [comment]
OK. This will be a big boon to my MusE prductivity - esp. when I'm recording real instruments! :D

**Comment by danvd** [comment]
Now shortcut for 'restart recording' available in shortcuts menu. Next step will be multitake/single mode recording restart.

**Comment by danboid** [comment]
Thanks for the update!

**Comment by danvd** [comment]
At last! non-discard restart recording (a-la multi-take) is here :)

Some highlights on how it works:

1. Default shortcut is SHIFT+Space while recording.
2. Armed tracks are un-armed and muted, recording parts are commited.
3. New clones of previously armed tracks are created:
- for all types of tracks in and out routes are copied and added to corresponding tracks on the other side.
- for midi tracks midi device and channels are copied.
- for audio tracks volume,pan,gain, num channels and aux sends are copied.
4. Newly created tracks are armed
5. Song position is changed to record start position (as in discard mode)
6. Record continues.

Very useful mode ;). Again, Dan, thanks for the idea.

Regards,
Andrew.

**Comment by danboid** [comment]
That sounds great Andrew but seeing as it was Tim who suggested the multi-take part I would recommend we not close this until he has tested it and is happy with it.

The bug / feature I'd most like to see fixed next is #367 so we can use Zebra 2 and Zebralette under MusE please!

**Comment by danvd** [comment]
Aha, that's right :) 
Tim, can you test this? 
Is it working how you planned?

**Comment by terminator356** [comment]
On December 2, 2015 01:41:07 PM Andrew wrote:
> Aha, that's right :)
> Tim, can you test this?
> Is it working how you planned?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/384#issuecomment-161442447

Will test... give me a day or so, got sidetracked with a bug fix.
T.

**Comment by danboid** [comment]
Thanks Tim!

**Comment by spamatica** [comment]
Ah, this was a while ago ya. Tested and closing.

**Comment by terminator356** [comment]
Sorry for the late reply.
I did some heavy work in this area which made it more stable.
I believe I tested all 'modes' as best I could and all seemed fairly well.

>17.12.2017
      - Some fixes to the 'retake' (restart recording) feature. Complete re-write.
           Much more stable and realtime-safe now. But still slow with wave tracks.
