### ISSUE TITLE
muse doesn't scan ~/.vst for VST plugins

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#385]
The u-he plugins default to installing into ~/.u-he and then create links under ~/.vst.

muse3 currently doesn't scan ~/.vst for VST plugins. I might've been able to fix this by modifying VST_PATH or whatever but ~/.vst should be scanned by default as well as its sub-dirs as u-he creates its symbolic links under ~/.vst/u-he.

Whilst I'm on the subject of plugin paths, there currently seems to be no way to add new plugin search paths under the muse options at present, right?

**Comment by danvd** [comment]
Done this (added ~/.vst to the list). Closing issue.
