### ISSUE TITLE
Podolski (U-he) plugin UI window size issues

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#386]
When you open the Podolski native UI the lower pixels of its UI aren't shown ie its a slightly horizontally-cropped window, at least it is for me running muse3 git under Arch / MATE 1.12.0. I have tried using the Alt+F8 MATE/marco keyboard shortcut to resize the window but that doesn't work.

Also, if you right-click in the plugin UI and choose a different UI zoom factor, the window doesn't resize to fit the UI.

I've not checked yet but I'd expect these issues will be present for all the U-he plugins under Muse git.

**Comment by danboid** [comment]
I'll create another issue ticket if you want but another prob I noticed when loading Podolski is it gets listed twice in the muse Native VST menu.

**Comment by danboid** [comment]
To see the full plugin UI you currently have to set the zoom level to 90% or less.

**Comment by danboid** [comment]
u-he have started bundling avx-optimized builds with their (beta) Linux plugin tarballs. On my machine the avx version of Podolski uses about 1/2 to 1/3 of the CPU on average vs the non-avx build.

Also, note that the best Podolski default patches are all in the 'Legacy' plugin sub-dir. I totally missed that at first.

What a great freeware synth!

**Comment by danboid** [comment]
Another problem with Podolski (and probably other U-he synths) is that muse doesn't save and restore the zoom setting of the pugin's UI zoom setting so every time I open a project I have to open every instance of Podolski and reset the zoom level back to 90%.

I'd be unlikely to want to change the zoom level much when I can see the full UI at 100% zoom but it would still be good if muse could restore the chosen zoom level anyway.

**Comment by danvd** [comment]
Hi Dan, 
Check the last changes to master branch. Now resizing should work fine (I hope :) ).

**Comment by danboid** [comment]
The good news is that ~/.vst is getting scanned now and Podolski only gets listed once in the synths VST menu but I'm still having problems with resizing the Podolski UI - in fact its worse now than t was before! :(

Pod opens at 200% zoom by default which is too big so when I try setting it to 100% or whatever, the UI resizes but the window for the plugin does not. I'm using the MATE desktop.

**Comment by danboid** [comment]
Here's a video showing how the latest git behaves with Pod under Arch / MATE:

https://youtu.be/rLGlD8q5wOM

**Comment by danvd** [comment]
Ok, Got it. Give me some time, I'll try to fix this.
By the way - I see you don't have slider button image on mixer strip. Can you rebuild muse after cleanup to test if it will be shown?

**Comment by danboid** [comment]
Great - thanks Andrew!

As you can see in that video, the plugin window size code does work sometimes currently but most of the time it does not.

I'm not sure what the slider you refer to is but I presume you just want me to do a clean checkout for my next build instead of just doing a `git pull; ./compile_muse.sh` in the existing tree right?

**Comment by danboid** [comment]
Oh of course - that slider button!

Yes - bit of a problem that! :)

**Comment by danvd** [comment]
Hi Dan,

Please update and recheck vst gui resizing. After some modifications it seems, that it works right. Here is my video about the process:
https://youtu.be/54wevJAzulM

**Comment by danboid** [comment]
Hi Andrew

It is working better now as the window resizes correctly but its still not as good as it was before because it used to remember the zoom setting after I closed and re-opened the window. Ideally it would save the zoom setting with the project too so all plugin windows would be the right size upon first opening a project.

**Comment by danvd** [comment]
Hmm. So you mean that:
only when reopening the project  windows size+zoom is not restored, right? In all other cases it works ok? Or I missed something?

**Comment by danboid** [comment]
The Pod UI window always opens at 200% zoom, which is too big even to fit on even a Full HD display.

I can resize the Pod UI window OK but as soon as I close it it always re-opens at 200% zoom regardless of the previous zoom setting selection.

Up until you started to try and fix the window size issues, it used to remember the zoom setting when I opened and closed the UI window, just not between sessions but I'd like that too.

**Comment by danvd** [comment]
I made some more tests with pod synth. Here are my results:
1. Newly created instance starts with 200% ui size.
2. I can change size and window resizes right.
3. When I close and reopen gui in the same session, size remains the same as was in no. 2.
4. I close muse, strart it, load project. Pod ui opens with saves size from no. 2.

So in my case 200% size is shown only in case of new instance.

**Comment by danboid** [comment]
That's strange. Does pod remember its size when you close and re-open it under MATE?

I'm running MATE 1.12.0 and Qt 5.5.1

**Comment by danboid** [comment]
I've just tried muse under LXQT and KDE but pod acts the same as under MATE - the UI always opens at 200%.

**Comment by danvd** [comment]
Yes, I tried with MATE too. This is also strange because I also have arch linux, so our setup should be the same.
BTW, do you have x64 or x32 build?

**Comment by danboid** [comment]
Stranger still then! x64, gcc 5.2.0, glibc 2.22

**Comment by danboid** [comment]
Do you know what distros Tim and Robert run? It'll be interesting to see what happens for them with the pod UI and the mixers.

**Comment by danboid** [comment]
I've found another Arch user from the Linux Musician user forums who will be testing this and the mixer fader issues later. Let's see if its just me!

**Comment by danvd** [comment]
Ok, that's good! Today I installed fresh ubuntu 15.10  - everything is ok here.

**Comment by danboid** [comment]
Thanks for the update!

It's sounding like there is something a bit weird or wrog with my install if it works under Ubuntu too but of course I'd rather not have to re-install everything to fix it! :)

I'll update this issue as soon as I hear how this other Arch user gets on.

**Comment by danvd** [comment]
By the way - what qt theme do you use?

**Comment by danboid** [comment]
How do I check? They keep on changing the theme selection stuff.

**Comment by danvd** [comment]
Try open Appearence settings and choose from the list. It doesn't show what theme is current, but will let you shoose between installed on your system.

**Comment by danboid** [comment]
Appearance settings where?

**Comment by danvd** [comment]
Ahh, in muse app, menu 'MusE Settings'

**Comment by danboid** [comment]
OK, we're making progress with this now!

There are 6 different Qt theme options on my system. I've tried all the different themes and all of them don't alwayd draw the fader icons when I create new tracks

EXCEPT

For the Fusion theme. With that theme, the fader always gets drawn when creating new tracks.

I can also be more precise on the VST UI zoom bug now too. Muse does save and restore the Pod UI zoom setting EXCEPT for when using 100% zoom. When using every other zoom level (ie 90% and 110% etc)  the zoom setting gets saved and restored when I close and re-open the window except for when I choose 100% zoom as it re-opens at 200% if I choose that.

**Comment by danboid** [comment]
I've just tested the restoring of the window zoom between sessions ie closng and re-opening a project.

If I create a project with 1 pod instance, change its zoom to 90%, save, exit and then reload the project the project opens with the Pod window open and at 200% zoom. If I then close and re-open the pod window, it will be back to 90%.

I want projects to open with no plugn windows open but when I do open one it should be at the previous zoom setting.

Almost there now! :)

**Comment by danboid** [comment]
Although muse is auto-opening the pod UI in my save/restore test, it isn't doing that for my pre-existing project. Maybe that only happens if you only have 1 plugin instance and no other pugins or tracks in a project?

**Comment by danvd** [comment]
muse tries to remember if the plugin windows was opened and saves this flag with the project. May be in previous version uis were closed before saving?

**Comment by danboid** [comment]
Oh right. That sounds good to me. I prob saved my test with the plugin open but in that case it should've re-opened it at 90% instead of me having to close and re-open it first.

**Comment by danboid** [comment]
Does restoring the window at 100% zoom work for you Andrew?

**Comment by danvd** [comment]
No, I have the same issue as you - when reopening project or close/restore UI in my case it's resized to 150%. But if I choose any other value for zoom - everything is fine.

**Comment by danvd** [comment]
May be it's a plugin issue - I'll check this. 
I also checked plugin in qtractor and ardour. 
qtractor crashes 90% of time when opening gui,
ardour 4 handles resizing in a strange way - the holder window is not resized (only the content) and the background is not cleared. So if I chose 150% and the 100% here - the part of 150% that is outside of 100% size will be still shown on the screen.

**Comment by danboid** [comment]
Yes, qtractor is funny with the U-he plugins. I've not really tried Pod much in qtr but to use Zebralette under qtr without it crashing I have to insert the plugin with 'Dummy VST plugin scan' (under its plugin options tab) enabled, then save the session, turn dummy scan off then reload the qtr session with dummy scan turned on or vice versa.

Its the dummy scan thing that causes the Uhe plugins to be unstable under qtr basically. Ardour didn't handle the window resizing last time I tried it although it does handle VST shell/sub plugins so its possible to load Zebralette, which is the best freeware synth.

**Comment by danboid** [comment]
100% zoom restore is still broken.

**Comment by danboid** [comment]
Thankfully the 100% zoom issue doesn't apply to Zebra(lette).

**Comment by danvd** [comment]
The more I test, the more it seems as podolsky problem because vst gui code dinamycally resizes plugin window to size asked from plugin. Though I have not tested it since last changes to vst gui code.
