### ISSUE TITLE
Seemingly pointless LV2 UI option

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#388]
If I insert the LV2 version of the Helm synth into Muse and then open its native UI I am presented with two seemingly pointless LV2 UI URI options. It seems to be pointless because no matter which one I pick, I get the same UI.

On subsequent viewings of the native UI for the same plugin instance the user doesn't get asked about the choice of LV2 URI again for the duration of that session. If they add another Helm plugin the use will be presented that option again the first time they open the native UI.

**Comment by danvd** [comment]
Hi dan,
I'm open for a discussion about this behavior. The practive says that all of the available plugin UIs are performing without any difference.
As a workaround I can add new checkbox in options page, say 'LV2 UI behavior': 1. Use the first available (will be default), 2. Always ask which to use, 3. Ask only once for new instance (that is how it works now).

**Comment by danboid** [comment]
Hi Andrew

So is there a reason I am given an option of UIs? As I say, they both look idetntical to me and no other LV2 host that I've tried Helm with gives me a choice of UI. I'd understand it if there was some real difference between the two but I can't see any difference.

Does another LV2 plugin need this sub-option in place?

**Comment by spamatica** [comment]
2015-11-18 21:27 GMT+01:00 Andrew <notifications@github.com>:

> Hi dan,
> I'm open for a discussion about this behavior. The practive says that all
> of the available plugin UIs are performing without any difference.
> As a workaround I can add new checkbox in options page, say 'LV2 UI
> behavior': 1. Use the first available (will be default), 2. Always ask
> which to use, 3. Ask only once for new instance (that is how it works now).
>
Sounds like a good plan.
I imagine the separate GUI abilities of LV2 were added to cater for use
cases where wildly different guis would improve certain abilities. Say a
GUI that is specific for live use with touch controls, or the LV2 guis for
MOD DUO, specialized guis for a certain use case.

I don't think I have seen a plugin yet that actually has two DIFFERENT guis
so allowing to set behavior sounds like a good plan.

Btw, Dan, many thanks for taking time to voicing your opinion :)

**Comment by danboid** [comment]
You're very welcome Robert! I've been doing this testing thing so long now I'm getting quite good at it as I feel as I know where most of the Linux audio pitfalls are by now. One day I'd like to think I'll learn to program C/C++ and be of more help but you guys don't seem to mind me just testing and giving feedback and suggestions so that's cool. :)

Whilst we're talking about this, I'd like it so that I could simply double-click on synth or plugin's name in the arranger and get straight to its native UI which is what I want 99% of the time. I'll file that as a separate feature request if you guys want me to and you don't disagree with it?

**Comment by spamatica** [comment]
2015-11-18 22:48 GMT+01:00 danboid <notifications@github.com>:

> Oops!
>
> I meant I'd like a plugins native UI to be opened when I double-click on a
> plugins port name. Double-clicking the (track/plugin) name re-names it.
>
Good idea, went ahead and did it :)

**Comment by danboid** [comment]
I've just re-built and double-clicking to open the Native UI seems to work fine!

Thanks for  the quick turnaround with that tweak Robert! It seems like a big muse usability win for little effort to me! :)

**Comment by danvd** [comment]
What a cool idea, Dan, and quick realization, Robert! :+1: 
Again, Dan, thanks for your ideas :)

**Comment by danvd** [comment]
Hi guys!

This is done by 3b411bc.
Closing this.
