### ISSUE TITLE
Don't ask to create ~/MusE

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#389]
My apologies - I closed this issue recenty thinking it was fixed when it is not because I had not tried importing an audio or MIDI file into muse3 until now.

Muse still wants to create ~/MusE if it doesn't already exist when you import a wav or MIDI file but that doesn't fit how my home dir is organised. You can cancel it but it should never ask to do this as the user should get to decide where they store muse files.

**Comment by terminator356** [comment]
On November 18, 2015 01:56:46 PM danboid wrote:
> My apologies - I closed this issue recenty thinking it was fixed when it is
> not because I had not tried importing a wav file into muse3 until now.
> 
> Muse still wants to create ~/MusE but that doesn't fit how my home dir is
> organised. You can cancel it but it should never ask to do this as the user
> should get to decide where they store project files for muse.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/389

Not sure if this was mentioned but have you tried this?

 Global Settings -> Application tab : Project Directory

You can also change this setting via the Create Project Dialog.

If it still wants to create ~/MusE afterwards, let me know.

Tim.

**Comment by danboid** [comment]
Ah OK! Setting the Project Directory has got rid of that annoyance then.

Still - I'm not sure about it. Do we really need this? If so, then the window that offers to create ~/MusE should instead prompt the user to set their Project Directory and either take them to Global Settings -> Applications tab or tell them where it can be set.

Thanks Tim!

**Comment by terminator356** [comment]
On November 18, 2015 05:44:37 PM danboid wrote:
> Ah OK! Setting the Project Directory has got rid of that annoyance then.
> 
> Still - I'm not sure about it. Do we really need this? If so, then the
> window that offers to create ~/MusE should instead prompt the user to set
> their Project Directory and either take them to Global Settings ->
> Applications tab or tell them where it can be set.
> 
> Thanks Tim!
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/389#issuecomment-157920475

Good point.
Probably was overlooked way back when that stuff was added.

Tim.
