### ISSUE TITLE
Fluidsynth plugin soundfont file history

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#395]
I frequently use the same soundfont file(s), often just as a kind of placeholder sound until I've got the synth sound I want sorted for a track and so it's tiresome having to always browse to find my soundfont file(s) every time I use the Fluidsynth plugin. Ideally it would have some kind of dropdown or menu with previously loaded file history that would persist over sessions and reboots etc so I could quickly load a previously used soundfont.

**Comment by asbaklm** [comment]
You could set up a template with Fluidsynth preconfigured, see #425 for instructions on how to do this.

**Comment by danboid** [comment]
Templates would be a last resort but thanks for your suggestion asbakim!

**Comment by danboid** [comment]
I want to see MusE have as efficent a workflow as possible without the user having to create templates for every style of track they may wish to create. It just jars with me! :)
