### ISSUE TITLE
import / replace MIDI file oddities

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#396]
If I start a brand new session in muse and then the very first thing I do is import a MIDI file even before creating  a single track, why does muse give me the option of 'Replace' when it asks me "Add midi file to current project" when there is nothing to replace? I think it means do I want to replace the song/session?

If I do choose replace at this point, it messes up the arranger by opening it in a new arranger muse sub-window. This new arranger sub-window overlaps the previous session window yet there only seems to be one set of window controls so the user has to resize muse to utilise the full window and get rid of the clutter caused by the previous session.

**Comment by danboid** [comment]
If the 'replace' option is going to stay, I think it should probably be called 'Import into new muse project', or just 'New Project' if that's what it's doing.

**Comment by asbaklm** [comment]
Use the 'add to project' option, it will append MIDI tracks to the project (assuming you started with the template described in #425) with data from the midifile you are importing below the pre-configured Fluidsynth GM Synth.

**Comment by danboid** [comment]
Your suggestion doesn't address the arranger drawing issue I mention which is the main problem here.

**Comment by asbaklm** [comment]
Here's what I get, I think it is similar to what you're experiencing:

The Muse window seems to resize on my system if I select 'replace' when importing a MIDI file and the original Muse window was NOT maximised.

If the original Muse window was maximised, when importing a MIDI file and choosing 'replace', it redraws the window into a resized smaller sized window in the top lefthand corner of the monitor which is superimposed on the previous maximised Muse window. To fix this, the Muse window needs to be redrawn for example by manually maximising it again.

So there's definitely some kind of a redrawing bug.

How it should work:
When selecting MIDI Import, Replace and screen is Maximised, it should redraw the Maximised Window with the updated data. It should not overlay a smaller newly created Muse Window over the original Maximised window, thus producing garbled output which must be corrected manually.

When selecing MIDI Import, Replace and the screen is NOT Maximised but drawn to a specific size, it should redraw the screen with updated data without resizing the window to whatever default it currently appears to be set to. In other words, it shouldn't replace the non-minimised Window with a new Window, sized according to some presumably default value it currently uses.

Does that match what you're experiencing?

**Comment by danboid** [comment]
Yes, that's the issue.
