### ISSUE TITLE
MIDI editor window cursor / keyboard position disparity

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#397]
Within the MIDI editing window, just to the left of 'Snap' there is a box which shows the note value of the cursor. The value it currently shows is one octave less than the value displayed on the virtual keyboard displayed to the left of the editor window.

**Comment by danboid** [comment]
I've also noticed that the widget (text box?) that displays the note under the cursor (the same one that is an octave out) is taller than it needs to be which has the side-effect of making that whole row of icons consume more vertical screen space than it should.

**Comment by danboid** [comment]
It would seem the note display text box is correct and it is the labels on the virtual keyboard running up the side of the MIDI editor window that are an octave higher than they should be.

**Comment by danvd** [comment]
Accorfing to this table:
http://www.phy.mtu.edu/~suits/notefreqs.html
frequency of A4 is 440 Hz. So it seems, that piano roll labeling is right (tested with tuner now).
So the note display should be fixed.

**Comment by danvd** [comment]
Made some tests:
Pressing on A4 pianoroll buton in different synths (with instrument tuner attached):
mda piano: A4 440Hz
Zebra2: A3 220Hz
DeicsOnze: A4 440Hz

Looks like everything depends on soft synth selected, but more synths are in sync with current pianoroll labelling.

**Comment by terminator356** [comment]
On December 6, 2015 06:28:11 AM Andrew wrote:
> Made some tests:
> Pressing on A4 pianoroll buton in different synths (with instrument tuner
> attached): mda piano: A4 440Hz
> Zebra2: A3 220Hz
> DeicsOnze: A4 440Hz
> 
> Looks like everything depends on soft synth selected, but more synths are in
> sync with current pianoroll labelling.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/397#issuecomment-162320994


Meant to reply to this.

It's just a reference marking. Think of it as 'relative'.

Actually I think it is supposed to be the same as the
 'official' midi note number values. If not, it should be.

It becomes meaningless depending on the hardware, soft synths,
 AND the 'transpose' track info box, which I use a lot, and a few
 other things like the midi transformer settings and so on.

Tim.

**Comment by danvd** [comment]
Just read midi documentation. Yes, labels should be 1 octave down.
It's interesting, that it's me who is the reason of current pianoroll labelling.
See issue #376.
I have to revert my changes back then.

**Comment by danvd** [comment]
Fixed by commit a6b9421
Closing this.

**Comment by danboid** [comment]
The note disparity is fixed now but it seems you forgot about:

"I've also noticed that the widget (text box?) that displays the note under the cursor (the same one that is an octave out) is taller than it needs to be which results in that whole row of icons consuming more vertical screen space than it should."

Would you like me to create a new, separate issue for that?

**Comment by terminator356** [comment]
On December 6, 2015 01:34:55 PM danboid wrote:
> The note disparity is fixed now but it seems you forgot about:
> 
> "I've also noticed that the widget (text box?) that displays the note under
> the cursor (the same one that is an octave out) is taller than it needs to
> be which results in that whole row of icons consuming more vertical screen
> space than it should."
> 
> Would you like me to create a new, separate issue for that?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/397#issuecomment-162349468

(Yeah sorry I just noticed that box's octave number was not the same 
 as the piano.)

So, that 'big' box has been a thorn in my side for a long time.
I've tried several times to shrink it over the years. 

But I've learned a lot the last couple of years about widget sizing policies. 
I uh, /should/ be able to fix it, if no one else does.
I mean, it's glaringly obvious that it /must/ be possible to fix, eh?

I may not get around to it for a while though...

Tim.

**Comment by danvd** [comment]
>The note disparity is fixed now but it seems you forgot about:

>"I've also noticed that the widget (text box?) that displays the note under the cursor (the same one that is an octave out) is taller than it needs to be which results in that whole row of icons consuming more vertical screen space than it should."

>Would you like me to create a new, separate issue for that?

No I didn't forget about it :). Just decided to make it silently :D
 
Will continue with this today, and if I'll be out of luck, then it'll be time to make a new issue :)

**Comment by danvd** [comment]
Surprisingly the reason of too big height of note label was not in this lebel's height, but in... LabelCombo widget, that holds label named 'Snap' and a combobox with snap values. HBox layout in which this widget resides had too big content margins. 
The problem was solved with one line in lcombo.cpp:
layout->setContentsMargins(0, 0, 0, 0);
See commit 9c4c4b4.

**Comment by terminator356** [comment]
On December 7, 2015 02:14:42 AM Andrew wrote:
> Surprisingly the reason of too big height of note label was not in this
> lebel's height, but in... LabelCombo widget, that holds label named 'Snap'
> and a combobox with snap values. HBox layout in which this widget resides
> had too big content margins. The problem was solved with one line in
> lcombo.cpp:
> layout->setContentsMargins(0, 0, 0, 0);
> See commit 9c4c4b4.

I could swear I did all that, and that there was more to the story! 
But maybe not, eh?

Yeah that setContentsMargins gets me every time.

Thanks man! Will test...
Tim.
