### ISSUE TITLE
hidden zoom and draw icons in MIDI editing window

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#398]
For some reason you are required to click on a drop-down menu (with 2 arrows on it) to reveal the zoom and draw icons / tools within the MIDI editing window.

This shouldn't be necessary because even if those two icons were displayed alongside the others contained within that row (which they should be), that row would still be the shortest horizontally of the three rows of icons within the MIDI editing window.

**Comment by danboid** [comment]
I consider this a bug and think it should be fixed for the next release.

**Comment by danvd** [comment]
Hi Dan,
Fixed by dc66310.

**Comment by danboid** [comment]
Not here Andrew. I still have to click the arrow to see/use the zoom and draw tools.

**Comment by danvd** [comment]
Hmm, interesting. Can you post a screenshot?

**Comment by danvd** [comment]
I have the same issue on ubuntu, but not on arch. Screenshot is not needed anymore :)

**Comment by danvd** [comment]
Ok, when I removed my ~/.config/MusE folder in arch, I got the same issue. Investigating...

**Comment by danvd** [comment]
....
It's been a long long day. I tried all of the qt methods to make pianoroll tools toolbar show all of it's contents. And only now(!!!) I found that initial toolbar sizes and positions were stored in default MusE.cfg file which is copied to ~/.config/MusE if this folder is empty. 

#$%@#$%$@%#$!!!!

Now pushed a fix 3bb9b16. To test it, ~/.config/MusE folder must be cleared before launch.  When MusE app is closed, all toolbars positions for all window types are saved to user's MusE.cfg.

Hope this fix will help to solve the issue :)

**Comment by spamatica** [comment]
Ouch I feel your pain :S
All better from here I hope :)


2015-12-29 22:16 GMT+01:00 Andrew <notifications@github.com>:

**Comment by danboid** [comment]
It's fixed! :D

Sorry to hear this took so much effort to fix! We know you're a very talented programmer so it must be very frustrating when something that should logcally be an easy fix takes you all day! :(

Look at it this way though - the MIDI editor window finally looks and functions properly now and for me and many other MusE users this is the main window where most of the work gets done. I'd say MusE is primarily regarded as a MIDI sequencer over an audio DAW as that its speciality as far as open source DAWs are concerned, at least for the moment.

Thanks Andrew!

**Comment by danvd** [comment]
Thanks, guys :)

**Comment by danvd** [comment]
Dan, which issue should be fixed next?

**Comment by terminator356** [comment]
On December 29, 2015 01:16:54 PM Andrew wrote:
> ....
> It's been a long long day. I tried all of the qt methods to make pianoroll
> tools toolbar show all of it's contents. And only now(!!!) I found that
> initial toolbar sizes and positions were stored in default MusE.cfg file
> which is copied to ~/.config/MusE if this folder is empty.
> 
> #$%@#$%$@%#$!!!!

Ha! Not the first time somebody was pained by that.

Yes, we have not only default structure values in the code but
 a complete default .cfg file. 
Even on startup there's some checking and forcing of a couple of 
 values to ensure sane initial values.
It keeps you on your toes being aware of all that stuff.
I think Flo added the .cfg file to make sure there was a sane 
 initial configuration.


Speaking of #$%@#$%$@%#$!!!! pain, moments before I read this
 I just spent several hours trying to fix drawing problems such as
 no lasso left and right edges, and pianoroll control canvas velocity lines
 are random widths depending on height of the line. I stripped
 everything down and the problem is still there. Argh...

The good news is I've finished the note off / zero velocity note on stuff.
Andrew, as I suspected it was /waaay/ more complicated.
There were many places that allowed drawing notes or velocities such 
 that it ended up with /zero/ note on velocity - that's in an Event instance,
 where zero on velocity is a no-no, or at least it is now, so I fixed up a 
 bunch of places.
Testing OK so far. I'll commit and explain more later...

T.

**Comment by danvd** [comment]
Thanks Tim!

**Comment by terminator356** [comment]
On December 29, 2015 04:02:58 PM danboid wrote:
> It's fixed! :D
> 
> Sorry to hear this took so much effort to fix! We know you're a very
> talented programmer so it must be very frustrating when something that
> should logcally be an easy fix takes you all day! :(
> 
> Look at it this way though - the MIDI editor window finally looks and
> functions properly now and for me and many other MusE users this is the
> main window where most of the work gets done. I'd say MusE is primarily
> regarded as a MIDI sequencer over an audio DAW as that its speciality as
> far as open source DAWs are concerned, at least for the moment.

It does excel at midi, with a lot of small devlish details in place 
 and some hard-fought clever features.

The Linux way of bits and pieces /would/ be fine for coupling MusE 
 together with an expert audio DAW.
I found it can be done but not as easy as it could be at the moment,
 with a lack of information sharing such as tempo/signature maps.

T.

**Comment by danvd** [comment]
Though I'm not a profeccional musician, those DAW features that muse has are sufficient to me (Long time ago I used the same with cubase). Now I'm lacking only one major thing - vocal autotuner (with offline draw ability). On windows the best was autotune, but on linux there are no such software. Autotalent and clones can't do the work even near of how autotune did it. May be someday I'll find time to dive into this probem, coz it requires very strong dsp and math background.

Dan, Tim,
if you can write list of features that can make muse a competitive daw, it would be very nice :).

**Comment by danboid** [comment]
Hi Andrew

As I said recently, I've only created one proper track in MusE so far and it was all MIDI. Whilst I have given MusE's audio features a quick test, I've yet to create a proper audio project with it but that's what I'll be doing as soon as I get back home, starting on new years day most likely. Doing that may highlight some more missing audio features I'd like to see in MusE but as it stands the feature I want the most in muse now is #420 - the clipping warning LED in the mixer strips.

You're right about the autotune stuff - the existing Linux solutions do not compare to the commercial Win/Mac stuff like autotune and Melodyne. As you say, that's a very tough one to tackle and good on you for having the guts to take that on eventually Andrew! If you can come up with a good working solution to that for MusE I'm sure it'll prove to be a big draw over the alternative Linux DAWs, both free and otherwise!

**Comment by terminator356** [comment]
On December 29, 2015 10:12:25 PM Andrew wrote:
> Though I'm not a profeccional musician, those DAW features that muse has are
> sufficient to me (Long time ago I used the same with cubase). Now I'm
> lacking only one major thing - vocal autotuner (with offline draw ability).
> On windows the best was autotune, but on linux there are no such software.
> Autotalent and clones can't do the work even near of how autotune did it.
> May be someday I'll find time to dive into this probem, coz it requires
> very strong dsp and math background.

Why not put all that effort into learning how to sing better ;-)
It's worth it!

> 
> Dan, Tim,
> if you can write list of features that can make muse a competitive daw, it
> would be very nice :).

I don't think the internet supports sending such a long list !

:-)

**Comment by danvd** [comment]
>Why not put all that effort into learning how to sing better ;-)
>It's worth it!

May be, may be.. Don't know now which task will consume more time though :D

>I don't think the internet supports sending such a long list !

Heh :)
