### ISSUE TITLE
Cursor feedback when resizing notes and MIDI controllers

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#399]
Resizing notes is performed using the draw tool but the cursor currently doesn't change to the two 'resizing arrows' cursor until you have clicked on a note or MIDI controller bar.

I'd find the MIDI editor easier to use if, when in draw mode, the cursor changed to the resize arrows as soon as it is over a note or controller so you can be certain that when you click in the piano roll area you will be resizing and not inserting a note. Either that or a introduce a new resize-only mode entirely separate from the draw tool.

**Comment by danboid** [comment]
This is the minor 'bug' that bugs me the most now, especially after the resizing has been fixed to work to the left too.

**Comment by danvd** [comment]
Hi Dan, 

Made a fix. Can you check?

**Comment by danboid** [comment]
Hi Andrew

The cursor changes as I'd expect for resizing notes and parts now but it doesn't seem that you've done anything the adjust resizing individual MIDI controller.

If the user mouseovers the end of a MIDI controller bar, the cursor should change and the user should be able to drag it up and down by holding LMB.

Thanks!

**Comment by danboid** [comment]
Maybe you'd prefer to implement this when you get round to adding MMB adjustment of multiple selected MIDI controller bars within the MIDI editor?

**Comment by danboid** [comment]
Actually yes, I requested the controller adjustment stuff as part of #402 so I'm closing this.

Thanks Andrew!

**Comment by danvd** [comment]
Ok!
Yes, controller pane should be a separate task.
