### ISSUE TITLE
Preference which makes muse starting jackd automatically [sf#1069065]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#40]
Submitted by christeck on 2004-11-19 00:02:17

Rosegarden has a optional preference where the user 
can enter the parameters to start jackd automatically 
at startup if it's not running. Cool stuff.

**Comment by spamatica** [comment]
This can be done by muse but it is a bit complex and not recommended. I don't think we will make much change to this functionality so closing.
