### ISSUE TITLE
velocity colour-coded MIDI notes and controllers

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#400]
Currently muse's MIDI controllers are yellow bars on a white background which are quite hard to see, not only because they are yellow on white but they're thin too.

It would be useful if the colour of both MIDI notes and their velocity bars were governed by their velocity value ie a note with a velocity of 0 would be black, 127 darkish blue and 255 is shown as blue.

It may be more instructive to use a 3-colour based gradient instead like black for 0, green for 127 and red for 255.

**Comment by danboid** [comment]
In addition to this, some people might prefer it if there was an option to have the velocity of notes and controllers displayed numerically directly on top of each note or controller.

**Comment by kybos** [comment]
All that is already there in some way or other...
