### ISSUE TITLE
Ability to change the track display order

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#403]
I can't see any way to change the order that tracks are displayed within the arranger or the mixer.

I have frequently found myself needing to re-arrange the order of tracks within other DAWs and sequencers, especially when it comes to mixing. Ideally the user should be able to re-arrange the track display order from the arranger and/or the mixer.

As it stands, it looks like you can almost drag tracks up and down in the arranger but they don't move when you drop them in a new position.

**Comment by danboid** [comment]
Good to see that we can re-arrange tracks within the arranger now but changing the order in the arranger doesn't change their order in the mixer, yet. Could we have them linked please?

**Comment by danboid** [comment]
This is the feature I'd most like to see finished next other than latency compensation but I think Tim said that will be a post 3.0 feature.

Currently we can re-arrange the display order of tracks in the arranger but the order they're shown in the mixer doesn't change to match. Ideally the user would be able to change the order from the mixer too without having to use the arranger although I could live with only being able to re-arrange tracks in the arranger.

Thanks!

**Comment by danvd** [comment]
Though latency compensation is a hard-to-implement task, Tim will surely cope with it without too much trouble :).

Some questions about this issue:
1. Is the tracks order must be in sync between arranger and mixer, or not?
2. Hmm, by now I have no more questions :)

**Comment by danboid** [comment]
Hi Andrew

I didn't reply to this as I presumed you were joking about both questions. Were you not?

I know you will be back at work by now but did you manage to make a start on this? Maybe you were waiting for Tim to finish whatever he wanted to do to the mixer first?

**Comment by danvd** [comment]
Hi Dan,

Robert said, that he will do the task and I stopped it may be a week ago.

**Comment by danboid** [comment]
Ah OK!

Thanks guys!

**Comment by spamatica** [comment]
Hiya,

Yeah, I try to keep low profile with promises, I'm not really to be trusted
;)
BUT, I have been working on this and been doing pretty good progress, I
expect to wrap something up before the end of the week. The mixer code got
mangled quite a bit so it might be delayed a bit to allow for Tim to check
in his mixer improvements, if he is still working in that domain, not
entirely sure.

**Comment by danboid** [comment]
Thanks for the update Robert! I look forward to testing the improved mixer soon!

Last new feature for 3.0?

**Comment by spamatica** [comment]
2016-01-14 22:58 GMT+01:00 danboid <notifications@github.com>:

> Thanks for the update Robert! I look forward to testing the improved mixer
> soon!
>
> Last new feature for 3.0?
>
In our little bubble of anarchy you never know ;) but it's getting time to
wrap it up..

Another thing. I reread the ticket and it seems you were requesting both
changing the order in mixer and arranger?
The arranger should already be quite possible to change the order, could
you try again?
Moving a track to the bottom is finicky so maybe that is what you
experienced.

Regards,
Robert

**Comment by danboid** [comment]
If we carry on adding new stuff the 3.0 changelog might break the Internet, or at least cause great distress to authors of alternative FOSS DAWs! ;)

As you say Robert, yes you can already change the track order in the arranger. The prob is that the tracks don't get re-arranged in the mixer to match the order in the arranger.

The other, less important, request here is it would be nice to be able to re-arrange tracks within the mixer too but I can survive without that if its much work or a bit too disruptive to implement so long as their order is synced with the arranger.

**Comment by danboid** [comment]
I know you haven't given me the go-ahead yet Robert but I've already had a go with the latest mixer code. As it stands it appears we can now move channels in both the mixer and the arranger but they are arranged independently. I think I'd pretty much always want the two to be interlinked but maybe there are use cases where the user would want to have them arranged in a different order so maybe having the order in one affect the other should be optional?

Also, I've had the new mixer die a drawing death where all the elements within the mixer window start getting deleted just by moving the cursor about after trying to move channels although it doesn't happen all the time. You're probably not finished yet though, are you?

**Comment by spamatica** [comment]
Good morning,

2016-01-16 23:35 GMT+01:00 danboid <notifications@github.com>:

> I know you haven't given me the go-ahead yet Robert but I've already had a
> go with the latest mixer code. As it stands it appears we can now move
> channels in both the mixer and the arranger but they are arranged
> independently. I think I'd pretty much always want the two to be
> interlinked but maybe there are use cases where the user would want to have
> them arranged in a different order so maybe having the order in one affect
> the other should be optional?
>
Also, I've had the new mixer die a drawing death where all the elements
> within the mixer window start getting deleted just by moving the cursor
> about after trying to move channels although it doesn't happen all the
> time. You're probably not finished yet though, are you?
>
The feature set I had in mind is pretty much finished but there are still
bugs. If you prefer that Arranger and Mixer show the same thing, select
View->Strips->Arranger order in the menu. Also note that it's possible to
hide strips independently also, if you prefer a leaner mixer. The hidden
strips can be brought back from the menu.

I've seen this problem that it starts removing the strips when you move the
cursor but haven't found the cause yet.

**Comment by danboid** [comment]
Hi Robert

View->Strips->Arranger order makes the mixer order match that of the arranger but there doesn't seem to be a way to make the arranger order match the mixer order or have the two linked without having to perform a manual sync so that changes in order are applied to both on the fly?

**Comment by spamatica** [comment]
2016-01-17 21:23 GMT+01:00 danboid <notifications@github.com>:

> Hi Robert
>
> View->Strips->Arranger order makes the mixer order match that of the
> arranger but there doesn't seem to be a way to make the arranger order
> match the mixer order or have the two linked without having to perform a
> manual sync so that changes in order are applied to both on the fly?
>
Right, sorry, for now the syncing with arranger is one-way, the mixer
displays the same order as the arranger.
When you make changes in the mixer after having set it to follow the
arranger it will change it's setting to User order. I see now that it might
be just as useful to have the arranger follow the mixer. I'll keep it on
the todo.

**Comment by danboid** [comment]
The mixer strips 'Arranger' view mode now lets me move tracks in both the arranger and the mixer in sync, on the fly so this can be closed now.

Thanks v.much Robert!
