### ISSUE TITLE
Tidy up arranger menus

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#404]
I think there are too many menus in the arranger and that their contents could be better organised. I'm not going to detail a complete new menu structure now, I just thought I'd detail a few of my ideas to get everyones (well, at least the devs) opinions. I'd put this pretty low on my list of requests.

The first thing that strikes me is why do we have separate menus for "Window config", "View", "Windows" as well as the Qt menu which contains even more window/view related options? I think that the Qt menu can go entirely and the contents of "Window config" and "Windows" could be amalgated into "View".

Audio menu - most of what is under here I would expect to find under File -> Export. What does 'Restart Audio' do? Is that different to 'Panic'?

Everything under 'Functions' could prob be relocated to live under an sub-menu of the 'Edit' or 'MIDI' menus.

Does the stuff under the Automation menu work? I'm not sure what those options do and to me they sound like they should be accessible via the automation controls elsewhere in the arranger but then again I'm not sure of their purpose so maybe a dedicated Automation menu is needed?

**Comment by kybos** [comment]
I think this is not longer relevant. There have been lot of changes to the menus so the current state is different anyway.
