### ISSUE TITLE
Muse isn't saving and restoring all of Podolski's settings

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#406]
Not only is Muse not saving and restoring Podolski's UI zoom settings but its not saving and restoring all of its synth settings correctly either.

Three settings I know that aren't being saved and restored properly with Podolski are Arp Sync, Arp Order and the Loop setting. I have tried changing these settings with Podolski under qtractor and it saves and restores them fine.

This is unfortunately a showstopping bug for completing my current musical project with MusE :(

**Comment by danvd** [comment]
Dan, is this the right place where I can get a copy of podolski synth for linux?
http://www.kvraudio.com/forum/viewtopic.php?t=424953

This version seems somewhat outdated, that's why I'm asking.

**Comment by danboid** [comment]
Yep. It shouldn't be outdated - the top posting in that thread gets updated whenever there is a new release - the last being 3965 from earlier this month.

Of course, as I mentioned in another ticket the U-he plugins install to ~/.vst (and ~/.u-he) which muse doesn't scan by default so I had to copy the .so file (I'd use the AVX version if your CPU is pretty new - after 2009 or so) to /usr/lib/vst first.

**Comment by danvd** [comment]
Hi Dan,

After enabling chunks save/restore support for vst host it seems that podolsky saving and restoring it's settings in a right way now. 
Check this please :)

P.S. interesting plugin, sounds very good!

Regards,
Andrew.

**Comment by danboid** [comment]
Oh right! I didn't think to try that so I'll give it a go now.

**Comment by danboid** [comment]
When I first read this I thought you meant I needed to build muse with the Steinberg VST SDK but I've just spotted your latest commit that enables chunks so I'm rebuilding now..

**Comment by danvd** [comment]
Yes, Tim already made support for chunks before, but it was disabled by default without steinberg sdk. Though support for chunks have issues. OXE synth crashes when tries to restore saved settings. Now searching for the reason.

**Comment by danboid** [comment]
Chunks (and Andrew!) to the rescue!

Yes, it seems the latest build w/ chunks support (but not using Steinberg) has fixed my prob with the Podolski. I can't really comment on the stability yet as I've only tred it for 5 minutes but it seems fine so far.

I think I'm safe to resume work on my track now but it'd be nice to have the previous plugin window size code back if you don't think you'll be able to get the window sizing fixed soon. The Pod plugin window is stuck at 200% size right now, regardless of what the  plugin UI size is.

Thanks Andrew!

**Comment by danboid** [comment]
I think we can close this now.

**Comment by danvd** [comment]
Ok. And about gui resizing - may be you can make a video of what happening in your case?

**Comment by danboid** [comment]
Yes - I'll upload one shortly...
