### ISSUE TITLE
Mixer fader icons are invisble until the fader strips are clicked

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#407]
The new mixer fader icons are invisble until the fader strips are clicked, then they appear.

Arch MATE

**Comment by danboid** [comment]
I did a clean checkout / build and just ran compile_muse.sh with the defaults to builld and install.

**Comment by danboid** [comment]
When I create new tracks, sometimes the fader icon is visible without me having to click it first but it seems most of the time I have to click the fader strip to make it appear

**Comment by danvd** [comment]
Interesting :). Can you make a video?

**Comment by danboid** [comment]
https://youtu.be/LFRszQOuPGw

**Comment by danvd** [comment]
Ok. Thanks. Searching for the reason.

**Comment by danvd** [comment]
Dan, can you update and recheck again?

**Comment by danboid** [comment]
No difference. Same problems.

I expect this will be a KDE / GNOME theme issue. From your video you posted it earlier it looks like your are running KDE? It might be worth you installing MATE too to help debug this is if you haven't done so already? MATE is only small, at least compared to KDE!

**Comment by danvd** [comment]
I'm using lxqt, it's close to kde. Mate is not a problem. Will install it now and recheck

**Comment by danvd** [comment]
Installed MATE - no problems there. Very strange. I'll try to investigate it further.

**Comment by danboid** [comment]
This problem doesn't apply to the Fusion Qt theme.

**Comment by danboid** [comment]
Actually, Fusion still doesn't work 100% perfect. The initial 'Out' mini-mixer (the one integrated into the arranger) doesn't display a fader icon until you click on it but every new track created after that is OK, unlike the other themes where the icons sometimes don't get drawn straight away.

**Comment by danboid** [comment]
Another correction to the Fusion theme. Sometimes when I start muse with the fusion theme I can see the 'Out 1' arranger fader icon, othertimes not. It seems to be pretty much 50/50 if it will get shown straight away in the arranger without having to click on it first.

**Comment by danvd** [comment]
I think it could be much easier to catch this error if I can connect to your computer and debug it here (via teamviewer or so). If you don't mind of course. Else I'll try some more variants :)

**Comment by danboid** [comment]
I can imagine this mus be really annoying you now if its come to Teamviewer! :)

Yes, I can get TV installed. When is good for you, UK time?

**Comment by danvd** [comment]
The best time for me is from 4:00 PM till 6:00 PM UK time.  Is it ok for you?

**Comment by danboid** [comment]
Yeah I can do that today if you want. I'll send the connection details to your email shortly before 4PM.

**Comment by danvd** [comment]
Ok.

**Comment by danboid** [comment]
I've emailed the login details to the email address for you thats in the git logs.

**Comment by danvd** [comment]
Hi Dan,
Can you recheck this again? The problem was in uninitialized variable. In non-debug build compiler can take any valuie from memory and add it to y position of slider. Now it's fixed (I hope :) ).

P.S. Can you make another issue about panorama knob offset?

Regards,
Andrew

**Comment by danboid** [comment]
I've tried a few different themes and the faders are always displayed now so I'm closing this.

Thanks Andrew!
