### ISSUE TITLE
LADSPA plugins don't work

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#408]
If I add a LADSPA plugin to a wave track bad things happen when I try to change its settings.

There is usually a delay before anything appears in the LADSPA plugin settings window then, if the settings do actually show and MusE doesn't crash, the slider bars for the settings don't display properly and nor can you edit the parameter values manually.

**Comment by terminator356** [comment]
On November 23, 2015 05:10:47 PM danboid wrote:
> If I add a LADSPA plugin to a wave track bad things happen when I try to
> change its settings.
> 
> There is usually a delay before anything appears in the LADSPA plugin
> settings window then, if the settings do actually show and MusE doesn't
> crash, the slider bars for the settings don't display properly and nor can
> you edit the parameter values manually.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/408

Observed.
Opening a plugin generic GUI may crash MusE.

The generic plugin window may appear but the 
 horizontal sliders are actually vertical, if you can see them.

I think this is obviously related to Andrew's slider work,
 I'm not sure if he's aware of these horizontal slider usages. 

Tim.

**Comment by danvd** [comment]
Yes, I know about 2 modes of slider code. But now I'm dealing with knobs, and only after that will turn to sliders again :)

**Comment by danvd** [comment]
I'm closing this, because of reverting mixer to previous look. The problem should gone now.
