### ISSUE TITLE
pan knobs askew

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#409]
The mixer pan knobs aren't drawn correctly.

**Comment by spamatica** [comment]
Can confirm this.
On my system the pan on audio strips don't draw correctly. The pan on midi
strips seem to be perfectly center.

2015-11-25 13:32 GMT+01:00 danboid <notifications@github.com>:

**Comment by danvd** [comment]
I reverted mixer to previous look, so I think this issue can be closed.
