### ISSUE TITLE
Installing config files for KDE [sf#1069075]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#41]
Submitted by christeck on 2004-11-19 00:14:28

On KDE it would be useful to install some .desktop files: 
- One file to let KDE know what filetype *.med is 
- One file to associate muse with *.med files; currently, 
  klicking a med file opens the file in a text editor 
- One file for an entry in the KDE menu system 

I know not all users are KDE users, but if so, the above 
files would increase the usability a lot.

**Comment by kybos** [comment]
KDE is just one of many DE these days.
And it should be no problem to assign the filetype manually, if desired...
