### ISSUE TITLE
Use onscreen MIDI editor keyboard as MIDI input device during recording

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#412]
Although the onscreen keyboard with the MIDI editor can be used to preview instruments, it doesn't seem to be possible to record its input to a MusE MIDI track yet.

Having this feature is useful for marking out rhythms in MIDI tracks when you don't have a physical MIDI keyboard or whatever to hand and it would save the user having to use an external MIDI keyboard app in many cases.

**Comment by terminator356** [comment]
On November 25, 2015 06:43:07 PM danboid wrote:
> Although the onscreen keyboard with the MIDI editor can be used to preview
> instruments, it doesn't seem to be possible to record its input to a MusE
> MIDI track yet.

> 
> Having this feature is useful for marking out rhythms in MIDI tracks when
> you don't have a physical MIDI keyboard or whatever to hand and it would
> save the user having to use an external MIDI keyboard app in many cases.

MusE features FULL step recording, either with the onscreen keyboard,
 or with a midi keyboard where we feature chord detection (by Florian).

The Step Record icon is there. Try it.
Be sure to set the Snap Size as desired. The notes are set to that size.
You can tap notes in as the transport is recording, although they are
 constrained to the Snap Size, which I believe we should probably
 /not/ do if the transport is rolling, at least if the Snap Size is 'Off' - 
 that is, the recorded note length should be as long as you held the 
 graphical key down, and /then/ snapped to the Snap Size. 

Tim.

**Comment by terminator356** [comment]
On November 26, 2015 02:32:08 AM you wrote:
> On November 25, 2015 06:43:07 PM danboid wrote:
> > Although the onscreen keyboard with the MIDI editor can be used to preview
> > instruments, it doesn't seem to be possible to record its input to a MusE
> > MIDI track yet.
> > 
> > 
> > Having this feature is useful for marking out rhythms in MIDI tracks when
> > you don't have a physical MIDI keyboard or whatever to hand and it would
> > save the user having to use an external MIDI keyboard app in many cases.
> 
> MusE features FULL step recording, either with the onscreen keyboard,
>  or with a midi keyboard where we feature chord detection (by Florian).
> 
> The Step Record icon is there. Try it.
> Be sure to set the Snap Size as desired. The notes are set to that size.
> You can tap notes in as the transport is recording, although they are
>  constrained to the Snap Size, which I believe we should probably
>  /not/ do if the transport is rolling, at least if the Snap Size is 'Off' -
>  that is, the recorded note length should be as long as you held the
>  graphical key down, and /then/ snapped to the Snap Size.
> 
> Tim.

By the way, there are stand alone apps that use the PC keyboard as a 
 midi keyboard. The output can be fed into MusE.

This is probably a better solution than our onscreen keyboard because
 if you turn on the Midi Input icon (besides Step Record), MusE will
 record the input AND probably give you the above mentioned 
 step-chord detection.

**Comment by danboid** [comment]
It's not step recording I'm after here Tim. I'm aware of apps such as vmpk, as I hinted at in my OP but I was kinda hoping I could avoid having to install and use a separate app just to tap our rhythms in MIDI tracks under muse. My request would require the input not be restrained by the snap size when transport is rolling, as you say.
