### ISSUE TITLE
muse3 doesn't load while carlastyle.so is present

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#416]
Removing carlastyle.so allows it to load, problem does not occur in muse 2.2

JUCE Assertion failure in juce_AsyncUpdater.cpp:56
scanVstNativeDir: found /usr/lib/vst/carla.vst/styles/carlastyle.so
Segmentation fault

**Comment by danvd** [comment]
Hi @asbaklm,
can you attach output of 
ldd /usr/lib/vst/carla.vst/styles/carlastyle.so

It seems that the reason of error is qt versions conflict. current muse uses qt5.

**Comment by falkTX** [comment]
Seems like a qt5 app opening a qt4 library causes a crash.
Does muse have a plugin blacklist? Since 'carlastyle.so' is not a plugin it can be blacklisted safely.

**Comment by danvd** [comment]
Fixed by commit 453299b. Limited scanning folder depth to 2 (testing needed).

**Comment by asbaklm** [comment]
much obliged danvd

**Comment by danvd** [comment]
Ok, closing this.
