### ISSUE TITLE
Muse3 Score window missing close, minimize, maximise buttons

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#417]
Buttons to close, minimise or maximise score window appear to be missing
Currently have to tap Escape to get out of score window

**Comment by danvd** [comment]
Hi @asbaklm,

Can you attach screenshot? What window manager do you use? In my case (openbox) everything is fine.

**Comment by asbaklm** [comment]
Hi danvd, the OS is Mint 64 using Cinnamon. 

Don't have a screenshot but the basic idea is that the typical  -+x are missing from top-rh corner. The score window is always maximised when opening. Can only seem to get out of it using Escape key. 

Pianoroll and List Editors are unaffected and don't open maximised or missing the -+x buttons, in other words, they work as expected.

**Comment by danvd** [comment]
Ok. Got it. in cinnamon these buttons are absent in my case too. Will check this :)

**Comment by asbaklm** [comment]
muchos gracias mr danvd
