### ISSUE TITLE
Delay in displaying track selection objects when right-clicking in 'track'

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#418]
On Muse 2.2.1, when rightclicking in track to add midi, wave tracks, instruments etc the options instantly appear.

Muse 3, there's a delay of a couple of seconds

Clicking on Menus at the top also suffering from initial delay, subsequently it seems to work ok?

**Comment by danvd** [comment]
It's because of submenus generation. When there are lots of installed virtual instruments in system, generation takes some time. Actually it *must* be optimized. As a workaround open muse's options and check option "Scrollable submenus". In this mode generation takes several milliseconds.

P.S. Don't close this issue, this behavior should be corrected of course.

Regards,
Andrew

**Comment by spamatica** [comment]
You may be right Andrew, but if it is slower with MusE3 that is kind of
strange. Did we change anything? Qt5 issue?

asbakim, could you verify that the same amount of menu items are visible
both when opening with 2 and 3 ?

---
As for optimizing it, maybe we can create this menu only once and then
reuse it?


2015-11-29 18:47 GMT+01:00 Andrew <notifications@github.com>:

**Comment by danvd** [comment]
I found the reason.
This line 
int w = _cur_menu->actionGeometry(act).width();

in PopupMenu class addAction* methods is exetuted for every plugin in submenu. 
It seems, that method actionGeometry() of QMenu is very slow in qt5.

This needs to be investigated to get to the right code replacement.

**Comment by asbaklm** [comment]
Same amount of menuitems in both 2 and 3, 2 is instant, 3 lags badly. Thanks for checking!

**Comment by danvd** [comment]
Hi @asbaklm,

Fixed but e36283b commit. 
Now non-scrollable popup menus are divided in 1-column submenus with several <More...> items.

Please recheck when you'll have time.

**Comment by asbaklm** [comment]
Just checked, fix worked. Fantastic work danvd. The division of 1-column submenus is another major improvement because before the menus took up the entire screen which led to workflow frustration.

Thank you very much
