### ISSUE TITLE
Cursor keys also selecting tracks when no segment is selecte [sf#1069089]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#42]
Submitted by christeck on 2004-11-19 00:25:05

When a segment is selected, the cursor up and down 
keys select the next track with a segment. 

When no segment is selected, simply the next track 
could get selected. 

OK, this is really an unimportant one ;-) .

**Comment by spamatica** [comment]
We have keyboard shortcuts for these navigations, maybe not the exact mechanism outlined but keyboard can be used. Closing
