### ISSUE TITLE
xrun count

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#421]
I know qjackctl shows xruns but its window is often obscured by MusE's, especially if you only have the one display to work with. The same applies if you run JACK from a terminal so it'd be useful if an xrun count was displayed in MusE's arranger window.

I'd add it to the row of icons that shows the tempo and the snap settings simply because it currently has the least amount of stuff within that row.

**Comment by danboid** [comment]
xrun count - issue #421! OK, its not #123 or #321 but #421 still makes sense as a kind of binary countdown ;)

**Comment by danvd** [comment]
Hi Dan,

Xruns counter is now on cpu load toolbar. when this toolbar is clicked, xrun counter will reset.

**Comment by danboid** [comment]
I don't see it in the arranger nor in the git log. Have you pushed it?

**Comment by danvd** [comment]
Opps. Fixed :).

**Comment by danboid** [comment]
Works great for me!

Thanks Andrew!
