### ISSUE TITLE
realtime drawing of arranger audio tracks

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#422]
Currently MusE doesn't draw the waveforms for audio tracks in the arranger until you stop recording.

One reason it is useful to have realtime drawing of audio tracks is when you are recording multiple tracks at once (recording drums, for example) and you don't have the mixer window open, you would still be able to see if audio is being recorded on multiple tracks before you stop recordng without having the mixer window open too.

**Comment by danvd** [comment]
Hi Dan,

Done this task! 
Commit 9fe3945 - Added live update of wave parts while recording

Though this task seems to be rather simple, it was not so trivial to implement it. But now it works and the process looks very nice :). It makes an impression of a 'pro feature' IMHO.

BTW, this is now configurable via global settings and is 'on' by default.

Regards,
Andrew

**Comment by danvd** [comment]
All this need to be tested, of course :)

**Comment by spamatica** [comment]
Wow, need to try this.
I was gonna respond earlier that it would require some redesign so it
likely won't happen now, but here we are. Awesome Andrew :)
I think I will request you take a break now ;)


2015-12-05 23:53 GMT+01:00 Andrew <notifications@github.com>:

**Comment by danvd** [comment]
Hi Robert!
You think I should stop making chnges until a release?

**Comment by danvd** [comment]
Be sure to pull the latest changes - they fix serious regression in SndFile class that lead to segfault if jack buffer size is greater then 256. Now tested in Arch x64 and Kubuntu x32 - works fine for me.

**Comment by danboid** [comment]
Hi Andrew!

I didn't think ths would be trivial to add - I know I never said that as I expected this would be the hardest of all my MusE requests so far to add.

It is mostly working but there are two probs I've noticed so far. The first is that muse adds a few seconds worth of blank wave to the end of every recording after the stop point now.

The second  prob is that realtime preview doesnt always work although it does always show you the wave when you stop recording. My current guess is this issue could be related to the user resizing the track during recording but that seems to work OK so maybe thats not what is causing it?

Great work again Andrew! It seems Robert, Tim and I will have to fight over who is your biggest fan! :D

**Comment by danboid** [comment]
I agree this makes MusE's UI look a lot more professional - or it will as soon as Andrew fixes it! ;)

Have you guys decided what will and won't be in 3.0?

**Comment by danvd** [comment]
Hi Dan, 
Very good!
I think it will be not so hard now to correct these issues. 
Can you make a video of the second prob (I know about the first)?

>Great work again Andrew! It seems Robert, Tim and I will have to fight over who is your biggest fan! :D

Honestly, I joined to the MusE project only last year just because I was the fan of Tim's and Robert's work :D

**Comment by danboid** [comment]
https://youtu.be/mtRZV0vktss

RT wave drawing fails on the third take.

I suppose we'll have to agree to be mutual fans then! :)

**Comment by danvd** [comment]
Hi Dan,
>The first is that muse adds a few seconds worth of blank wave to the end of every recording after the stop point.
I think this is because you have snap to 1 bar selected. Arranger adds missing space to fill part to the current bar end.

Now working with second case :)

**Comment by terminator356** [comment]
On December 6, 2015 09:12:19 PM Andrew wrote:
> Hi Dan,
> Very good!
> I think it will be not so hard now to correct these issues.
> Can you make a video of the second prob (I know about the first)?
> 
> >Great work again Andrew! It seems Robert, Tim and I will have to fight over
> >who is your biggest fan! :D
> Honestly, I joined to the MusE project only last year just because I was the
> fan of Tim's and Robert's work :D

He he. Careful now, take a deep breath and concentrate, watch out for
 unexpected collateral functional damage, both of us did some work 
 trying to draw these -  it is not easy!


I joined around 2007 after looking around Linux for music apps.

MusE definitely caught my attention because, first of all, it had a
 track info 'transpose' box immediately in plain view. This immediately
 let me shift my five-octave keyboard, no other app had this.

Beyond that, I saw someone (Werner and the past gang) had put
 a lot of thoughtful work into it, even though it was only at version 0.7
 and had a lot of bugs. So I went to work, helping out.

After amassing a huge patch of fixes and introducing myself, I was
 informed, unaware, that Werner had moved MusE on to version 2.0
 (now called muse_evolution in our attic) !
But he had already sort of abandoned that version. Yet it was
 more advanced - with Qt4 and better ideas and so on.
But eventually we decided to stay with this version. Strange, eh?

Tim.

**Comment by danboid** [comment]
Interesting stuff Tim!

I can see eventually there will be a book, film or some kind of document on the history of MusE called something like 'Muso MusE Musings'

**Comment by danboid** [comment]
I'm going on holiday today and I won't be back until the 13th December so I probably won't be able to help out with testing MusE for the next week or so.

I expext Andrew will have rewritten most of MusE by the time I return! :D

**Comment by danvd** [comment]
Second case is fixed now. 
Another small problem in wave drawing code - it rather slow (but not so slow to make work not comfortable). I already made a quick fix that allows not to draw samples not visible on screen, but I'll search further ways of optimization.

**Comment by danboid** [comment]
Seems to work fine now.

Thanks Andrew!
