### ISSUE TITLE
Feature enhancement request: Print score

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#424]
Would it be feasible (simple enough to implement) to request a print feature for the score, preferably to a typical A4 sized page layout with 4 bars to a line? The current score window doesn't have an option to wrap to new lines. (Excuse the terminology, I'm not sure what the correct words are to explain).

**Comment by kybos** [comment]
This is definitely not simple to implement and quite out of scope in MusE, I'm afraid (the score editor is not widely used anyway). Better to transfer the midi tracks to MuseScore.
Sorry.
