### ISSUE TITLE
Transport keyboard shortcuts not working

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#426]
Muse3, appears to have issues on my comp with transport buttons. For example, Spacebar doesn't stop or start transport. When trying to assign keys via 'configure shortcuts' it is sometimes not possible to assign new keys at all, and when it is (for example assigning Spacebar to Play, Stop, Rewind it doesn't appear to have any affect. 

Clearing out ~/.config/Muse/MusE.cfg doesn't resolve problem.

Muse 2.2.1 doesn't seem to be affected and transport works as expected.

**Comment by danvd** [comment]
Hi @asbaklm,

Can you attach a screenshot of your shortcuts dialog (with transport bindings visible)?

**Comment by danboid** [comment]
Hi asbakim

Do they still not work after you click within your projects arranger window?

See my latest comment on #315

**Comment by danboid** [comment]
Andrew - I was going to suggest you try to fix #315 next as its a high visibility bug.

**Comment by terminator356** [comment]
On December 3, 2015 09:42:58 AM asbaklm wrote:
> Muse3, appears to have issues on my comp with transport buttons. For
> example, Spacebar doesn't stop or start transport. When trying to assign
> keys via 'configure shortcuts' it is sometimes not possible to assign new
> keys at all, and when it is (for example assigning Spacebar to Play, Stop,
> Rewind it doesn't appear to have any affect.
> 
> Clearing out ~/.config/Muse/MusE.cfg doesn't resolve problem.
> 
> Muse 2.2.1 doesn't seem to be affected and transport works as expected.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/426

Verified.

Cause:
Space has been assigned to both 
 "play/stop/rewind" and
 "reset recording"

Either the "reset recording" is taking priority (normally does nothing),
 or our key processor is completely ignoring it, I can't remember how 
 we deal with double entries (if we arbitrarily pick the last one)...

Solution:
Open the keyboard shortcuts editor and use another shortcut 
 for "reset recording" (or "play/stop/rewind"  if desired).

T.

**Comment by terminator356** [comment]
On December 3, 2015 05:37:22 PM you wrote:
> On December 3, 2015 09:42:58 AM asbaklm wrote:
> > Muse3, appears to have issues on my comp with transport buttons. For
> > example, Spacebar doesn't stop or start transport. When trying to assign
> > keys via 'configure shortcuts' it is sometimes not possible to assign new
> > keys at all, and when it is (for example assigning Spacebar to Play, Stop,
> > Rewind it doesn't appear to have any affect.
> > 
> > Clearing out ~/.config/Muse/MusE.cfg doesn't resolve problem.
> > 
> > Muse 2.2.1 doesn't seem to be affected and transport works as expected.
> > 
> > 
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/muse-sequencer/muse/issues/426
> 
> Verified.
> 
> Cause:
> Space has been assigned to both
>  "play/stop/rewind" and
>  "reset recording"

BTW that's an error condition, should not be allowed.
Andrew try to find another default shortcut for that new one
 (or try to eliminate the new shortcut and work with 'space'
 in the code?) 

> Either the "reset recording" is taking priority (normally does nothing),
>  or our key processor is completely ignoring it, I can't remember how
>  we deal with double entries (if we arbitrarily pick the last one)...
> 
> Solution:
> Open the keyboard shortcuts editor and use another shortcut
>  for "reset recording" (or "play/stop/rewind"  if desired).
> 
> T.


Definitely a problem here:

I'm likely misunderstanding the shortcut usage (must re-read your post), 
 but here's a first test:

I assigned 'Shift+space' to "reset recording" and upon testing the 
 new retake feature, I thought 'Shift+space' would work after
 hitting 'space' to stop the recording, but it didn't.
Instead I found that only while transport is recording actually just 
 'Shift' initiated the retake - space had no effect.

Puzzled, I looked at the keyboard editor again and saw garbage 
 characters for "Restart recording (multi take)" - Sorry I didn't notice 
 this other new shortcut so I don't remember what it said before all this.

Possibly our keyboard manager freaks out with double entries
 since they are, well, not supposed to exist and might be /assumed/
 to be enforced before addition.
 
The retakes themselves seemed to initiate well, but unfortunately
 each of the retake tracks were not armed, so silence was recorded.


See the snapshot for all of the above:

https://dl.dropboxusercontent.com/u/53315356/retake_test_1.jpeg


Thanks.
Tim.

**Comment by danvd** [comment]
Tim, Thanks for the info.

Corrected shift+space shortcut. I didn't notice that the default key conbination for multi-take was not only without space key, but I also used Qt::Key_Shift which is defenetely not the same as Qt::SHIFT. Likely this is the reason of garbage in shortcuts config. My fault - I hurried to make a commit.

Now, after clearing ~/.config/MusE everything is fine.

Now, how it works:

1. re-take and multi take are initiates only while transport is armed and is rolling.
2. If Ctrl+Space is pressed then re-take is initiated
3. If Shift+Space is pressed - multi-take.
4. When the transport is stopped these shortcuts shouldn't have no effect. 

About not armed tracks - strange. Now seatching for the reason.
Tim, can you post your OS version? I'll then install it for testing too.

**Comment by danvd** [comment]
Tim, it seems, that you are using Ubuntu 14.04.3 LTS i686?
I looked at your mail massage signature (Linux/3.13.0-68-generic; KDE/4.13.3; i686)
While waiting for your answer, will install it.

**Comment by danvd** [comment]
In clean kubuntu 14.04.3 i686 lts clonet current git master, built it.
retake and multi-take works here in my case.
I recorded video of the process: 
https://youtu.be/2qd_CLryBds

What is done:
1. Added midi and wave track, connected wave tack to input
2. armed both tracks
3. pressed space 
4. after some time pressed ctrl+space - retake is initiated and record restarted from beginning discarding all recorded information.
5. After pressed space to commit recordings and started new recording from new position.
6. some time later pressed shift+space (while recording is being done) - this initiated multi-take: new copies of armed tracks were created, armed, connected to same routes and recording process restarted from previous position.
7. after some more takes pressed space to commit.

Sorry for this long explanation :)

**Comment by terminator356** [comment]
On December 4, 2015 03:44:25 AM Andrew wrote:
> In clean kubuntu 14.04.3 i686 lts clonet current git master, built it.

Yes, that's what I'm running.

> retake and multi-take works here in my case.
> I recorded video of the process:
> https://youtu.be/2qd_CLryBds
> 
> What is done:
> 1. Added midi and wave track, connected wave tack to input
> 2. armed both tracks
> 3. pressed space
> 4. after some time pressed ctrl+space - retake is initiated and record
> restarted from beginning discarding all recorded information. 5. After
> pressed space to commit recordings and started new recording from new
> position. 6. some time later pressed shift+space (while recording is being
> done) - this initiated multi-take: new copies of armed tracks were created,
> armed, connected to same routes and recording process restarted from
> previous position. 7. after some more takes pressed space to commit.
> 
> Sorry for this long explanation :)

OK, will retest.
I think it may be time to trash my ./config file and let it start from fresh.
But first I'll retest to see why it happened this way.
Might have just been the shortcut thing messing it up.

Thanks.
T.

**Comment by spamatica** [comment]
2015-12-04 18:31 GMT+01:00 Tim <notifications@github.com>:

> On December 4, 2015 03:44:25 AM Andrew wrote:
> > In clean kubuntu 14.04.3 i686 lts clonet current git master, built it.
>
> Yes, that's what I'm running.
>
> > retake and multi-take works here in my case.
> > I recorded video of the process:
> > https://youtu.be/2qd_CLryBds
> >
>
>
Looks cool! I can see this being very usable.

Two feature requests:
- if loop is enabled so the rec restarts, trigger this new-track thingy
(unless this is already done)
- Folder tracks! :) and add all these 'takes' to the same folder.

Something to think about for 3.1  :D

/Robert

**Comment by danvd** [comment]
Hi Robert!
>- if loop is enabled so the rec restarts, trigger this new-track thingy
Not a problem!

>- Folder tracks! :) and add all these 'takes' to the same folder.

Yes! I also thought about this feature, though it requires some more coding, than just tracks copying :). But it will be very cool!

**Comment by asbaklm** [comment]
Apologies for the late reply and thanks as always for the amazing work and development speed. I really love this sequencer, it is so flexible and user friendly :)

Thanks a lot for fixing this issue gentlemen.

PS, before closing this issue, perhaps it's worth copying the shortcuts configuration instructions from danvd and the information about configuration storage in the MusE.cfg file to a dedicated wiki or forum section in order to document Muse features?

One major hurdle with this project, as with many OS projects is the lack of documentation. Perhaps a section could be started at http://muse-sequencer.org/forum/forumdisplay.php?fid=5 to start collecting instructions on how to use Muse which can later, one day, be combined into a more comprehensive manual?

There is a lot of knowledge in the Git issues section which would be useful to have transferred to such a knowledge base.
