### ISSUE TITLE
MusE freeze when trying to copy effects from one track to another 

### ISSUE THREAD

**Issue by luxigo** [muse-sequencer/muse#427]
Using MusE 2.1.2 on Debian 8.1

It's nice, thanks !

But when I select "Edit -> Duplicate Tracks" for an audio track, the checkbox "Copy effects rack plugins" is disabled.

When I try to drag'n'drop effects from a track to another track in the mixer view, erratic things happend with some ladspa modules. Sometimes MusE freeze and I have to restart it, sometimes I can copy the effect after many tries... 

Looking at the console output, "CabinetIV" drag'n'dropped okay
```
[<?xml version="1.0"?>
<muse version="1.0">
  <plugin file="caps" label="CabinetIV" channel="1">
    <control name="model" val="12" />
    <control name="gain (dB)" val="0" />
    </plugin>
</muse>
]

But zita-reverb did not
[<?xml version="1.0"?>
<muse version="1.0">
  <plugin file="zita-reverbs" label="zita-reverb" channel="1">
    <control name="Delay" val="0.0464" />
    <control name="Xover" val="50.5836" />
    <control name="RT-low" val="2.75" />
    <control name="RT-mid" val="2.75" />
    <control name="Damping" val="1500" />
    <control name="F1-freq" val="159.054" />
    <control name="F1-gain" val="0" />
    <control name="F2-freq" val="2514.87" />
    <control name="F2-gain" val="0" />
    <control name="Output mix" val="0.23" />
    <gui>1</gui>
    <geometry x="371" y="103" w="358" h="278"></geometry>
    </plugin>
</muse>
]
unexpected EOF reading xml file at level 2, line 13, <control><@	xC><>
unexpected EOF reading xml file at level 2, line 13, <control><@	xC><>

The invada low pass filter neither:

[<?xml version="1.0"?>
<muse version="1.0">
  <plugin file="inv_filter" label="invada_lp_stereo_filter_module_0_1" channel="1">
    <control name="Frequency (Hz)" val="3306.89" />
    <control name="Gain (dB)" val="0" />
    <control name="Soft Clip" val="0" />
    <gui>1</gui>
    <geometry x="232" y="1754" w="383" h="123"></geometry>
    </plugin>
</muse>
]
unexpected EOF reading xml file at level 2, line 6, <control><gui><>
unexpected EOF reading xml file at level 2, line 6, <control><gui><>

When I try again with CabinetIV (on a failed target) it doesn't works anymore:

[<?xml version="1.0"?>
<muse version="1.0">
  <plugin file="caps" label="CabinetIV" channel="1">
    <control name="model" val="12" />
    <control name="gain (dB)" val="0" />
    </plugin>
</muse>
]
PluginI-Control: unknown tag <49�b(2���> at line 4
```

**Comment by danvd** [comment]
Hi @luxigo,

We now not supporting this version. But if you have time, you can checkout current development version (which is upcoming 3.0.0), work with it and create issues.

Regards,
Andrew

**Comment by spamatica** [comment]
2015-12-04 17:56 GMT+01:00 Andrew <notifications@github.com>:

> Hi @luxigo <https://github.com/luxigo>,
>
> We now not supporting this version. But if you have time, you can checkout
> current development version (which is upcoming 3.0.0), work with it and
> create issues.
>
> Regards,
> Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muse-sequencer/muse/issues/427#issuecomment-162020778>
> .
>

Yes, please try the latest release or current development version. I
remember a bug with plugin copying and it should be fixed.

/Robert

**Comment by luxigo** [comment]
Yes it's fixed, thanks
