### ISSUE TITLE
Delete selected tracks capability missing from menu choices when right-clicking selected tracks

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#428]
Currently, the only way to delete multiple tracks at once appears to be by Ctrl-Clicking each track individually and to then select 'Delete Selected Tracks' from the Edit Menu. 

When right-clicking on these selected tracks, it is only possible to delete one track at a time. This cripples workflow and requires the user to perform numerous, wasteful actions in order to achieve a task.

It is also not currently possible to duplicate selected tracks from the right-click menu.

I think that to make behaviour more consistent, behaviour should be like this:

Ctrl-click to select invidividual tracks (already implemented)
Shift-click to select a range of tracks (currently this does not seem to be implemented)
Right-Click on tracks options to include 'Delete Selected Tracks' and 'Duplicate Selected Tracks'  (currently not implemented)

**Comment by danvd** [comment]
Hi @asbaklm,
Fixed by commit 96b2613
Closing issue.
