### ISSUE TITLE
Feature enhancement request: Score Window right-click 'Tools' menu

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#429]
The Muse Master Window and Piano Roll Window has a 'Tools' right-click menu which appears to not exist in the Score Window.

It would also be useful to have cut, copy, copy events in range, paste, and paste with dialog and delete (selected) menu options, and the ability to right-click and paste copied events at the location of the mouse cursor in the Score Window.

Currently this has to be done by moving the follow head to the desired location and then use paste from the menu or via keyboard shortcut.

**Comment by kybos** [comment]
Tools context menu has been added to the Score editor.
