### ISSUE TITLE
Bug affecting synth setups and templates when closing Muse project and opening new one

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#430]
This seems to be a new bug, wasn't present before.

Example

A Fluidsynth GM player template is created with FluidSynth saved as the 'Useable devices' and it's the first Device under 'Device Port Assignment'
Drum channel set to 10, Fluid R3 GM soundfont loaded.
Save template.
Close project, the click on File, New, Fluidsynth template

Problem

It won't load the soundfont or MIDI channel setup.

When you close and restart Muse application and load the same template, it now will load the soundfont and MIDI channel setup.

Problem seems to occur when a project in Muse is closed and a new one is opened.

The same thing happens with a med project. It loads the correct synth configuration when a project is loaded after starting Muse.

When loading the same project after the previous project window was closed, the synth configuration data is gone.

**Comment by asbaklm** [comment]
To view the problem:

It assumes that a GM instrument template using Fluidsynth as the GM synth was created beforehand, and that a GM Soundfont was loaded into Fluidsynth and saved.

Muse was then restarted, a "New" project was opened using the GM template. A MIDI file was imported and it was saved as a Muse Project.

Then close the Project and create a New Project again using the GM template. However, now the Fluidsynth Plugin has lost its Soundfont.

Go to Configure Midi Devices, Midi Ports and Synthesizers.
Navigate to Fluidsynth in Usable Devices

Go to Usable Devices, Open the Fluidsynth GUI.
The "Loaded Soundfonts" are missing.
For some reason Fluidsynth (and possibly other devices) are losing their configuration data.

The only way to restore this is to restart Muse, and to load the template again.
This is something that I think used to work but stopped working a month or two ago.

**Comment by asbaklm** [comment]
**Update**

This problem seems to be cause by filename handling. To avoid problems, ensure that soundfonts have .sf2 extensions and not .SF2. Removing spaces from soundfont names may also be beneficial.

So for example, if the soundfonts have .SF2 extensions instead of .sf2, it causes a problem for the MESS Fluidsynth plugin to find the .soundfont when a new project template is loaded and midi file is imported.

Why this doesn't happen the first time after muse is started I don't know. For some reason, Fluidsynth MESS can then still find the .SF2 named soundfonts.

Also, perhaps having spaces in the soundfont names could cause issues but I'm not sure about this.

**Comment by asbaklm** [comment]
Unfortunately this still doesn't resolve the original problem, that Fluidsynth loses its soundfont when closing a project and opening a new project using a template with Fluidsynth configured in it.

It only works if one either then manually loads in the Soundfont, or one restarts Muse.

**Comment by spamatica** [comment]
Hi,
I've been trying to provoke this but actually this works for me :/ .. so there must be some other parameter.

The soundfont I load is FluidR3 GM.SF2 and located in my $HOME under audio/audio_sf2/sf_download.
This configuration I save as a template in the user template folder.
Now, without restarting MusE I click new and select the template.
The loaded template is OK and can play a few notes I left in the template.

Raking my brain what else to test..
Do you have a non english language set in the operating system?
What is printed in the terminal when it loads the template? It should print the name of the soundfont it wants to load I believe.

**Comment by asbaklm** [comment]
Hi there!

My system is set to English. I tried it as you suggested (just running it from the terminal) and now it works fine.

I investigated my system and I think that this issue bears some resemblance to the other recent issues I reported, to do with how Muse behaves when certain environment variables were set. See #467, #468

This particular problem was caused by me loading LD_LIBRARY_PATH as part of a startup script to start Muse. Perhaps because the path to the Soundfont was not set in LD_LIBRARY_PATH? (That's what I suspect although I'm not 100% sure.) Having LD_LIBRARY_PATH in the startup script caused Muse to fail to detect the soundfont when opening successive New, GM Templates. The first time it works fine, subsequently it would fail to find the soundfont.

This is kind of similar to how the "Configure Midi Devices" section would work "as normal" initially, but when making extra subsequent mods it would either crash Muse or cause weird menus to load. (This was described in other recent issues I created #467, #468).

So in this case, provided that there's no LD_LIBRARY_PATH in a startup script Muse has no problem picking up the Soundfont again and again. (Although it always worked with the first song for some reason.)

Thanks for looking into this.

**Comment by asbaklm** [comment]
I did some more testing and am now confused about what is happening. The problem has re-appeared again so my previous post may not be entirely relevant to this issue. Unfortunately I don't yet know how to reliably reproduce the problem. It seems to be fine at times, and then magically stops working. Here are the errors.

What's strange is that as is shown in the logs it works the first time, it (sometimes) works the second time (finds the sf2) but on this occasion, the third time I closed the template and loaded a "New" template, it shows an error to find the soundfont even though that same soundfont loaded the previous two times.


fluidsynth sampleRate 48000
projPathPtr .
SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
JACK: buffersize changed 64
Config File </home/music/.config/MusE/MusE.cfg>
buildMidiEventList: unknown Meta 0x2 2 unabsorbed, adding instead to track:
buildMidiEventList: unknown Meta 0x54 84 unabsorbed, adding instead to track:untitled



** (muse3:7853): CRITICAL **: fluid_synth_cc: assertion 'num >= 0 && num <= 127' failed
FluidSynth::setController() - error processing controller event: 
fluidsynth sampleRate 48000
projPathPtr .

SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
JACK: buffersize changed 64
Config File </home/music/.config/MusE/MusE.cfg>
fluidsynth sampleRate 48000
projPathPtr .

SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
JACK: buffersize changed 64
Config File </home/music/.config/MusE/MusE.cfg>
Muse: fluidsynth error: Failed to load SoundFont ""

**Comment by asbaklm** [comment]
Some guesses...

Maybe some process is sometimes "preventing access" to the soundfont during the time it is supposed to be loaded by the Muse template into Fluidsynth?

Or maybe there is some other issue with how Fluidsynth loads soundfonts?

When the soundfont doesn't want to load via the template I can manually load it into Fluidsynth without seeing errors, but something still prevents it from being loaded from the template.

**Comment by spamatica** [comment]
Hello again.. wierd. It does give some indications of memory corruption..
Could you try running muse and disabling plugins? E.g muse3 -pNI2 to
disable all but internal plugins.
Myself I believe I have a problem with some native VST plugins on my system
causing corruption when MusE loads them to inspect them. More testing is
needed there.

2016-02-04 19:28 GMT+01:00 asbaklm <notifications@github.com>:

**Comment by asbaklm** [comment]
Hi there

I get this, it looks like it still "loses" the soundfont. First time the GM template is loaded it works. Second time, it can't find the soundfont.


$muse3 -pNI2
Config File </home/music/.config/MusE/MusE.cfg>
LOCALE en_GB
Denormal protection enabled.
string2sysex: Cannot convert string to sysex r ct bn bt f7
Trying RTC timer...
got timer = 74
Aquired timer frequency: 2048
Connected to session bus, unique name is ":1.50"
JACK: buffersize changed 64
starting with template /usr/local/share/muse-3.0/templates/default.med
JACK: buffersize changed 64
fluidsynth sampleRate 48000
projPathPtr .
SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
JACK: buffersize changed 64
Config File </home/music/.config/MusE/MusE.cfg>

** (muse3:4639): CRITICAL **: fluid_synth_cc: assertion 'num >= 0 && num <= 127' failed
FluidSynth::setController() - error processing controller event: 

** (muse3:4639): CRITICAL **: fluid_synth_cc: assertion 'num >= 0 && num <= 127' failed
FluidSynth::setController() - error processing controller event: 
fluidsynth sampleRate 48000
projPathPtr .
SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
JACK: buffersize changed 64
Config File </home/music/.config/MusE/MusE.cfg>
Muse: fluidsynth error: Failed to load SoundFont ""

**Comment by spamatica** [comment]
Hi,

2016-02-05 22:23 GMT+01:00 asbaklm <notifications@github.com>:

> Hi there
>
> I get this, it looks like it still "loses" the soundfont. First time the
> GM template is loaded it works. Second time, it can't find the soundfont.
>

Okay, hmm.
I need to try more but I don't think I can reproduce this..
Would you mind rebuilding with debug? If it is due to memory corruption,
which seems likely.. it would probably not behave the same when built with
debug since memory might be allocated differently.

> $muse3 -pNI2
> Config File
> LOCALE en_GB
> Denormal protection enabled.
> string2sysex: Cannot convert string to sysex r ct bn bt f7
> Trying RTC timer...
> got timer = 74
> Aquired timer frequency: 2048
> Connected to session bus, unique name is ":1.50"
> JACK: buffersize changed 64
> starting with template /usr/local/share/muse-3.0/templates/default.med
> JACK: buffersize changed 64
> fluidsynth sampleRate 48000
> projPathPtr .
> SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
> JACK: buffersize changed 64
> Config File
>
> SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
>
> fluidsynth: error: Unable to open file ""
>
Odd

> fluidsynth: error: Couldn't load soundfont file
> fluidsynth: error: Failed to load SoundFont ""
> JACK: buffersize changed 64
> Config File
> Muse: fluidsynth error: Failed to load SoundFont ""
>

I see you are running with extremely small jack buffers. Not that it should
interfere but do try running with something bigger to rule out problems
with it.
On this machine it's impossible to go that low, jack goes nuts :P

/Robert

**Comment by asbaklm** [comment]
For running with small buffers, please experience the POWER of the Behringer UMC 404! :zap: 

I tried to compile the debug version but it keeps failing to compile on this machine. I'm not sure what the problem is, it may be that there are "mixed" libraries from Ubuntu dev packages and from packages I compiled myself.  arggggghhh :(

The release version compiles OK though.

**Comment by asbaklm** [comment]
Debug fails with this error, not sure how to resolve it.

In file included from /home/music/src/muse/muse3/muse/vst_native.cpp:45:0:
/home/music/src/muse/muse3/muse/driver/jackaudio.h: In member function ‘virtual void MusECore::JackAudioDevice::setPortName(void*, const char*)’:
/home/music/src/muse/muse3/muse/driver/jackaudio.h:129:58: warning: ‘int jack_port_set_name(jack_port_t*, const char*)’ is deprecated (declared at /usr/local/include/jack/jack.h:899) [-Wdeprecated-declarations]
       virtual void setPortName(void* p, const char* n) { jack_port_set_name((jack_port_t*)p, n); }
                                                          ^
/home/music/src/muse/muse3/muse/driver/jackaudio.h:129:95: warning: ‘int jack_port_set_name(jack_port_t*, const char*)’ is deprecated (declared at /usr/local/include/jack/jack.h:899) [-Wdeprecated-declarations]
       virtual void setPortName(void* p, const char* n) { jack_port_set_name((jack_port_t*)p, n); }

**Comment by spamatica** [comment]
Ah yes, that can happen.
When you compile debug we set -Werror which causes all warnings to be
treated as errors.
If you remove this in CMakeLists.txt the compile should work better.

/Robert

2016-02-06 21:09 GMT+01:00 asbaklm <notifications@github.com>:

**Comment by asbaklm** [comment]
Thanks! Now we're in business. :)

I tried 4 or 5 times to reproduce the problem with the debug build and couldn't. Strange, hehe
Here is the gdb log.

[muse3_gdb_log.zip](https://github.com/muse-sequencer/muse/files/120655/muse3_gdb_log.zip)

**Comment by asbaklm** [comment]
*Update: I eventually managed to reproduce it with dbg*

SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
[New Thread 0x7fff9b7fe700 (LWP 12911)]
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
[Thread 0x7fff9b7fe700 (LWP 12911) exited]
[New Thread 0x7fffc9d48700 (LWP 12912)]
JACK: buffersize changed 128
[New Thread 0x7fff9b7fe700 (LWP 12913)]
[New Thread 0x7fffb2280700 (LWP 12914)]
Config File </home/music/.config/MusE/MusE.cfg>
Muse: fluidsynth error: Failed to load SoundFont ""
[New Thread 0x7fffb1a7f700 (LWP 12915)]
[New Thread 0x7fff9a0c0700 (LWP 12916)]
[Thread 0x7fffb127e700 (LWP 12908) exited]
[Thread 0x7fffb1a7f700 (LWP 12915) exited]
[Thread 0x7fff9a0c0700 (LWP 12916) exited]
+extra note-off! 87496 pitch 62 velo 0
+extra note-off! 87496 pitch 62 velo 0
+extra note-off! 87496 pitch 74 velo 0
+extra note-off! 87496 pitch 74 velo 0
+extra note-off! 87525 pitch 74 velo 0
+extra note-off! 87525 pitch 74 velo 0
+extra note-off! 87525 pitch 74 velo 0
+extra note-off! 87525 pitch 62 velo 0
+extra note-off! 87525 pitch 62 velo 0
[New Thread 0x7fff9a0c0700 (LWP 12918)]
[New Thread 0x7fffb1a7f700 (LWP 12919)]
[New Thread 0x7fffb127e700 (LWP 12920)]
[Thread 0x7fff9a0c0700 (LWP 12918) exited]
[Thread 0x7fffb127e700 (LWP 12920) exited]
[Thread 0x7fffb2280700 (LWP 12914) exited]
[Thread 0x7fffc9d48700 (LWP 12912) exited]
[Thread 0x7fff9b7fe700 (LWP 12913) exited]
fluidsynth sampleRate 48000
projPathPtr .
SOUNDFONT FILENAME + PATH /home/music/Samples/sf2/FluidR3_GM.sf2
[New Thread 0x7fff9b7fe700 (LWP 12921)]
fluidsynth: error: Unable to open file ""
fluidsynth: error: Couldn't load soundfont file
fluidsynth: error: Failed to load SoundFont ""
[Thread 0x7fff9b7fe700 (LWP 12921) exited]
[New Thread 0x7fffc9d48700 (LWP 12922)]
JACK: buffersize changed 128
[New Thread 0x7fff9b7fe700 (LWP 12923)]
[New Thread 0x7fffb2280700 (LWP 12924)]
Config File </home/music/.config/MusE/MusE.cfg>
Muse: fluidsynth error: Failed to load SoundFont ""
[Thread 0x7fffb1a7f700 (LWP 12919) exited]
