### ISSUE TITLE
Make Wine VST plugins support via MESS synth

### ISSUE THREAD

**Issue by danvd** [muse-sequencer/muse#431]
Take base code from dssi-vst project, add shell plugins support, make 32/64 vst server process to support both archs (wine64 works rather well now), make built-in chunks and multi-out support. Also add an ability to auto-restart crashed plugins with internal state restored (try to save chunks periodically to achieve this).

**Comment by spamatica** [comment]
good idea. I know you know the internals of dssi-vst so it might be the best choice, I just wanted to note that there are other implementations like CarlaVST and Airwave.

**Comment by danvd** [comment]
Hi Robert,
Ok, thanks for the info, will check them too. The main reason of implementing this is to make guitar rig, kontakt and addictive drums work in production. Now dssi-vst doesn't cope with this task - random crashes, not working guis some times and so on...
14 дек. 2015 г. 12:44 AM пользователь spamatica <notifications@github.com> написал:good idea. I know you know the internals of dssi-vst so it might be the best choice, I just wanted to note that there are other implementations like CarlaVST and Airwave.

**Comment by spamatica** [comment]
Implementing the support closer to MusE seems like a good idea indeed.
I would like to note though that I run Addictive without problems* with dssi-vst and have done so for many years, so I'm not sure the problem is dssi-vst if you have stability issues.

* Actually right it only works for 32-bit OSs but the reason is not dssi-vst but something lowlevel.

**Comment by danvd** [comment]
Hmm, may be something wrong with mywine prefix. I tryed to use version 2. How about you? Also thinking about the idea of drag and drop of midi parts from wine vst plugin to muse's arranger :)

**Comment by spamatica** [comment]
Ah, yes, didn't think about the new version of Addictive Drums, I'm using
1.5 or something like that so you may be right about the new being unstable.
Didn't want to break what I got working, plus it's not exactly cheap.



2015-12-13 22:26 GMT+01:00 Andrew <notifications@github.com>:

**Comment by danvd** [comment]
I'm using a demo version, bu it seems, that this demo differs from full only in number of patches. Though Addictive Keys works just fine.

By the way, I tryed both airwave and carla wine vst hosts. They work similar to dssi-vst, but airwave's design seems to be more clear. Anyway I'll try to write support from scratch :)

**Comment by asbaklm** [comment]
I've never been able to get good Windows VST performance with Carla, unless it works well for other people (good low-latency performance, stability etc) is it really worth pursuing?

dssi-vst is a lot more stable and capable of low-latency operation. 
Airwave performs quite well too although it has some quirks.

**Comment by danvd** [comment]
>is it really worth pursuing?
I think, the answer is 'yes' IMO.
If no one of the recent wine vst hosts can give a 100% guarantee of segfault-free work I can't afford using it while composing something...
Can't say now that new host will work better, but I'll try my best to do so.

**Comment by asbaklm** [comment]
Last time I tried hosting Windows VSTs with Carla (perhaps a month or two ago) it was unusable because of xrunning so I gave up on it. But when I tried it just now, it worked OK.

So I guess dssi-vst, carla and airwave are all good options.

**Comment by terminator356** [comment]
We have the old deprecated fst based vst.cpp module just as a small reference.
Hey, remember when fst 'just worked' ? 
For a while I looked at moving VST back closer to MusE, like Ardour or LMMS.
Seemed it could be done but did not pursue it further.

Tim.

**Comment by spamatica** [comment]
Popular subject it seems :)
Just wanted to note that with a recent fix in airwave (the related fix in muse will probably be removed), Addictive Drums works (i tried 1, which I own, and a demo of 2), it seems there is a problem with storing presets though, I'm going to research this more.
