### ISSUE TITLE
Panic doesn't work in muse3

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#433]
Hi again,

I just did some playing with muse3 and had a piano synth with a long delay. The Panic button did not kill the sound.

Regards,
Chris.

**Comment by derselbst** [comment]
cant confirm this, panic works fine in f4803bef6bedb31b97d7683e4bee5fd47e10c0ad

**Comment by therealkitman** [comment]
Hi, 
I downloaded v3.0.0pre2 c8d6dc2 and this problem still exists.
I test it by playing a wave file with a ridiculously huge reverb then stopping playback. While the reverb is dying down I click the Panic button but it keeps ringing until the reverb naturally stops.
It is not a fatal issue for me but thought you'd like to know :)
Regards,
Chris.

**Comment by spamatica** [comment]
2017-02-07 7:59 GMT+01:00 therealkitman <notifications@github.com>:

> Hi,
> I downloaded v3.0.0pre2 c8d6dc2 and this problem still exists.
> I test it by playing a wave file with a ridiculously huge reverb then
> stopping playback. While the reverb is dying down I click the Panic button
> but it keeps ringing until the reverb naturally stops.
> It is not a fatal issue for me but thought you'd like to know :)
> Regards,
> Chris.
>

Uh oh, I see your problem. And now that you mention it, it's not apparent.
The panic button only works for midi. The reason being if a NoteOff event
for some reason was lost, keeping a synth playing forever (and potentially
louder and louder). The mechanism was never meant for audio, I understand
your logic, it makes sense to add a safety there too, but unless I'm
mistaken it is not apparent how to solve it. The main reason for amok audio
is plugins, for instance the example you had with a reverb. We can't know
how to manipulate the reverb to make it stop. What we can do is stopping
playback, but that is more or less the same thing as hitting mute on the
main output. The benefit of muting the output is that you can see on the
meters where the noise is coming from and hopefully tracking it down.

**Comment by therealkitman** [comment]
Hi,
Thanks for that explanation. I can live with that understanding and am happy to close this issue.
Regards....
