### ISSUE TITLE
Multi-core processing

### ISSUE THREAD

**Issue by danvd** [muse-sequencer/muse#437]
Determine parallel paths of audio signals and compute them in pre-created pool of realtime threads (one per core) when 'process_callback' is called. Modern processors can for sure reduce overall dsp cpu usage by 10-20% in large projects with lots of synths and plugins.

**Comment by terminator356** [comment]
On December 22, 2015 09:21:48 AM Andrew wrote:
> Determine parallel paths of audio signals and compute them in pre-created
> pool of realtime threads (one per core) when 'process_callback' is called
> Modern processors can for sure reduce overall dsp cpu usage by 10-20% in
> large projects with lots of synths and plugins
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/437

I'm still running on an old AMD single core !

But soon I am upgrading 'cause I really want to see how MusE
 behaves with modern CPUs.

And I'm sooo tired of waiting for compiles to finish ;-)

I told my dealer to set me up with a modern i5 system.
Some folks on LAD say i5 is better for us than i7.

T.

**Comment by danboid** [comment]
Jeez T! What exactly have you got?

I really don't know how you've held out so long. Is money really that tight?

**Comment by terminator356** [comment]
On December 22, 2015 03:16:56 PM danboid wrote:
> Jeez T! What exactly have you got?
> 
> I really don't know how you've held out so long. Is money really that tight?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/437#issuecomment-166760007

Ha! Donations welcome he he ;-)


When I have cash, new guitars take priority over PCs !

Really I'm just lazy I guess, but yeah I made it clear
 to my guy that yes, it's really time to upgrade, and let's 
 really do it for real, real soon, now that I have the cash.

Looking forward to it.

T.

**Comment by danvd** [comment]
>I told my dealer to set me up with a modern i5 system.
>Some folks on LAD say i5 is better for us than i7.

I had i5 system and it performed very well. Then I changed cpu to i7 and it outperformed i5. On one project with lots of plugins cpu load dropped by 10% or so.
But these 10% don't cost the difference in price between i5 and i7 though :).

**Comment by spamatica** [comment]
Hiya guys, remember me? ;)

2015-12-23 0:24 GMT+01:00 Tim <notifications@github.com>:

> On December 22, 2015 03:16:56 PM danboid wrote:
> > Jeez T! What exactly have you got?
> >
> > I really don't know how you've held out so long. Is money really that
> tight?
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/muse-sequencer/muse/issues/437#issuecomment-166760007
>
> Ha! Donations welcome he he ;-)
>
>
> When I have cash, new guitars take priority over PCs !
>
> Really I'm just lazy I guess, but yeah I made it clear
> to my guy that yes, it's really time to upgrade, and let's
> really do it for real, real soon, now that I have the cash.
>

 Even if you refer to it as laziness I do admire the dedication to really
using stuff to their full potential and lifetime. I have close friends, not
the least my son, that belong in this category as well and in this day and
age it's all for the better.

Myself I'm more at the opposite end of the spectrum and I can never fully
utilize all the hardware I have access to, though much of it is second
hand..
Though a single core might just start to be slightly antiquated, I'm not
sure when I last used one. ;)

Some word of advice regarding buying new gear.
Doing such a long jump in tech likely means you have to upgrade mostly
everything. Both to be able to really use the more power (HDDs of
yester-year just don't cut it anymore) and lots of tech isn't compatible.
PCI is mostly gone and Firewire too. There may yet be a motherboard with
PCI and/or FW so maybe it's a question of shopping around.
- Another solution (what I mostly do) is to buy second hand, you'll get
plenty more bang for the buck and you can still get a i5 or i7 rig. Not as
fun as buying brand new though.

As for the discussion about i5 and i7 and hyperthreading. There seems to be
some technical merit behind this though I wonder if it makes any difference
unless you are going for extremely small buffers and use PCI.
I usually use a firewire interface with a Thinkpad dual core laptop(T400)
when making music and I can get the latency low enough that it isn't a big
problem for me: 2x128 at 44.1khz is reasonably stable. Going lower than
that is possible but xruns increase too much.
I have a feeling that at these buffersizes it doesn't matter much your
hyperthreading abilities or settings and with Firewire or even worse, USB,
it is not possible to go lower than this in a stable manner without too
many sacrifices in usability.

That got long winding.. oh well

Regards,
Robert

**Comment by danboid** [comment]
It's easy enough to find a FW PCI card and add that into a desktop machine but its nigh-on impossible to find a modern laptop with FW or and ExpressCard slot to add FW ports. It has been dead for almost a decade now.

I can highly recommend the Focusrrite Scarlett USB 2.0 audio devices such as the 2i4 and 18i20 as I've got them both and both work great OOTB with ALSA/JACK.

I couldn't prob get by with a decent single core if I didn't do so much compiling (I'm not saying you guys don't of course) and I didn't use so many softsynths!

**Comment by terminator356** [comment]
I guess I keep everyone on their toes and preventing them being speed-lazy in the code:
"If it runs on mine, you pass!"

Hey Dan what kind of Jack buffer size, added USB latency, and xruns can you get out of that FR?
Like Robert says, I'll work happily with 128 buffer and even 256 is OK.

Can you get 'live' realtime performance, for live guitar effects (Jack Rack, Guitarix et. al.)
 from a modern laptop, say 64 or 128 buffer?
I would really love to go that way, especially if multi-channel USB products are out there
 and I could replace my Delta-1010 desktop PCI card.

Thanks.
Tim.

**Comment by danvd** [comment]
I also can say something interesting about usb cards. My computer is 10 meters away from monitor and periferals (in a storeroom). So the only one way for me was usb audio card. I choosed e-mu 0404 usb. It's connected to pc via 5m usb active repeter+ 8port usb hub (I also tried to connect it directly to PC - performance was the same). With all these I've got the following:

24/96kHz with 256 samples buffer - is my everyday setup. Works just fine.
In muse: 
one input from microfone with calf compressor + eq10q 
another input is for guitar: calf compressor + eq10q.
Aux effects - calf reverb + calf vintage delay.

With this template there is no xruns and 2,7*2 ms overall latency.

P.S. the must have kernel is patched with bfs scheduler.

**Comment by danboid** [comment]
I have been able to run at 24/96 w/ 128 buffer without xruns for audio-only projects with my Focusrite cards but to operate xrun-free using softsynths too 256 seems to be as low as I can go usually.

**Comment by danboid** [comment]
I should note that these figures relate to using qtractor / Tracktion. I have yet to do any real audio recording under MusE but thats what I'll be working on next when I get back from visiting my parents for xmas.

**Comment by asbaklm** [comment]
"Can you get 'live' realtime performance, for live guitar effects (Jack Rack, Guitarix et. al.)
from a modern laptop, say 64 or 128 buffer?"

I can do softsynths & wine VST's at 128, even with cheapo Behringer UMC series. But it does require a lot of setup work to eliminate most of the xrun causes and to improve the baseline performance.

**Comment by danvd** [comment]
@asbaklm,

128 at which samplerate? and what interface of your sound card is?

**Comment by asbaklm** [comment]
Cards: Behringer UMC404, Edirol UA-25. On another computer a RME 9652.

48K Sample rate on all systems.
Periods set to "3" for the USB, "2" for the RME PCI card.

I also have one of these super cheap Chinese (C-Media chipset) guitarlink-cables. That one has to be run at 256, it xruns too much on the laptop at 128.

**Comment by danvd** [comment]
Ok, thanks.
I'm running at 96000 with 256 buffer size and 2 periods. at 48000 I can also get 128.
With ice1712 the lowest buffer size was 64x2 at 96000.

**Comment by asbaklm** [comment]
Yeah I'm sure I could go lower but I don't want to run at 96K, hehe. (Not even dogs and bats will appreciate the difference in sound quality.)

So the best compromise setting at 48K for me is 128
Something like this for the USB cards:
jackd -S -P89 -m -dalsa -r48000 -p128 -n3 -Xraw -D -Chw:U96k,0 -Phw:U96k,0 -i4 -o4

**Comment by danvd** [comment]
I'm using nearly the same settings :)

**Comment by asbaklm** [comment]
PS, that old M-Audio Delta / ice1712 is a pretty cool PCI card . I got my RME running OK on a more recent Asus P9D-X motherboard which has bridged PCI slots but I took a risk, not being sure whether or not it would work.
