### ISSUE TITLE
Muse plugin detection problems

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#438]
I'm experiencing issues with plugin detection and the plugin menus.

1st Issue - menu mis-categorisation of plugins

- Many LV2 effects are currently being mis-classified as LV2 synths when selecting "Add Synth" 
- Native VST menu mis-identifies some effects as synths (pizmidi plugins for example)

2nd issue - missing plugins (plugins not being shown)

- WINE VST menu - doesn't display any FX plugins, only synths
- Native VST menu doesn't show any VST FX
- No LADSPA effects are being shown

I tried exporting these paths and started muse3 from terminal but it doesn't resolve the above issues.

export VST_PATH=/usr/local/lib/vst:/usr/lib/vst:~/.vst
export DSSI_PATH=/usr/local/lib/dssi:/usr/lib/dssi
export LV2_PATH=/usr/local/lib/lv2:/usr/lib/lv2
export LADSPA_PATH=/usr/local/lib/ladspa:/usr/lib/ladspa

Additional Feature request:

It would be useful to be able to define plugin paths inside Muse, because currently it doesn't find plugins not in the "standard" locations when started from the menu.

When exporting paths for plugin locations and starting Muse from the terminal it does find additional plugin paths, but ideally it shouldn't be necessary to have to do this.

**Comment by danvd** [comment]
Hi @asbaklm,
Abous 1st: In LV2 synths menu all effects having at least 1 midi input are displayed. Many lv2 synths have one. 
About Native VSTs: Can you give concrete examples?

2nd: Also examples needed, the more - the better :)

About plugin paths: It can be done, of course. Good idea, thanks :)

**Comment by asbaklm** [comment]
Hi Dan, thanks! :)

- Issue 1 - Misplaced LV2 effects:

For example: I have Calf FX suite installed from git.
In Muse3, I right-click to Add Synths, browse to LV2 (Synths) submenu.
In there, Calf FX plugins show up. This is wrong. Calf FX plugins should be in the LV2 (Effects) menu.

I also see a small a number of Guitarix effects in there, Zamaudio LV2 plugins, drow plugins, OpenAV plugins, meters.lv2 from Robin Gareus etc.


- Issue 2 - Missing VST effects (Both Linux Native and Windows VST)
There seems to be no VST effects (Linux or Windows) displayed even though I have loads installed in /usr/local/lib/vst and I put export VST_PATH=/usr/local/lib/vst:/usr/lib/vst:~/.vst in .bashrc

VST effects are completely missing in Muse even though other audio apps like Carla can see them.

Here are some of the missing (in muse) VST plugin suites.

zamaudio
drowaudio
GVST
Klangfreund
ndc
SAFE
TAL-Togu Audio Line

Windows VST effects are completely missing from Wine VST or any other submenus.

**Comment by danboid** [comment]
asbakim:

danvd is actually called Andrew. I'm 'the Dan' round here! :)

**Comment by asbaklm** [comment]
Haha, sorry for being asleep Andrew :D

**Comment by danvd** [comment]
Actually my nickname should be 'ander' (ANdrew DERyabin), but there too many anders on the net :). danvd is not so popular, that's why I choosed it (it's composed from my full name - Deryabin ANdrey VlaDimirovich). But danvd is more closer to Dan, then to Andrew, so if there was no real name, I should have been also called me Dan, he-he :).

**Comment by asbaklm** [comment]
xoxo, eto zabavno :D

**Comment by danvd** [comment]
:D
Lets work with actual issue now :)
About wine vst - do you have dssi-vst installed? It's must have now for wine vst to work.

Now will try to rearrange lv2 synths/effects.

**Comment by asbaklm** [comment]
Yes dssi-vst is installed on my system and it works. I have some Windows VST's installed like PG-8X synth, Limiter6 Windows VST FX from vladg installed. I can play PG-8X in Muse or in Carla, tested, working.

- In Muse3, PG-8X shows up as an available instrument. Works.
- In Muse3, Limiter no6 does not show up as a VST effect. Not available.

In a different host like Carla, Limiter no6 works, so there's something strange happening with Muse.

Also, in Muse3, no native Linux VST effects are showing up on my system. 
They are available in Carla.

I think (not completely sure), that Muse isn't showing LADSPA effects or synths either. For example, I have ambisonics ladspa effects installed but they are not in the Muse menus. These plugins also work in Carla.

So the problem summary would be:
----------------------------------------------

- Linux Native VST Effects not showing up in Muse
- Windows (dssi-vst) VST Effects not showing up in Muse
- LADSPA Effects and synths? not showing up in Muse
- Many LV2 effects are appearing in the muse LV2 (Synths) menu.

I ensured to load plugin paths like this before starting Muse:
----------------------------------------------------------------------------

export LD_LIBRARY_PATH=/usr/local/lib/libgig
export VST_PATH=/usr/local/lib/vst:/usr/lib/vst:~/.vst
export DSSI_PATH=/usr/local/lib/dssi:/usr/lib/dssi
export LV2_PATH=/usr/local/lib/lv2:/usr/lib/lv2:/usr/local/lib/lv2/swh
export LADSPA_PATH=/usr/local/lib/ladspa:/usr/lib/ladspa:/usr/local/lib/ladspa/swh

**Comment by danboid** [comment]
asbakim:

I'm pretty sure Tim said there was a good reason for the LV2 FX appearing in the synths menu as I've highlighted that before but I can't remember his explanation as it was quite involved.

**Comment by asbaklm** [comment]
I think he mentioned something about LV2 plugins which have MIDI are detected as synths? (I can't remember the explanation very well so I could be mistaken?)

If that's the case such a detection method will not produce accurate results because many LV2 FX plugins have MIDI (Calf FX and X42 Meters from Robin Gareus for example). 
The LV2 Synths submenu quickly becomes messy because now it contains a mixture of Synths & Effects.

Carla host can differentiate between synths and effects but I'm not sure how it detects the function (effect or instrument) of the plug.

**Comment by danvd** [comment]
For lv2 plugins this separation can be done, of course. Now working on it. Will do this issue step-by-step.

**Comment by asbaklm** [comment]
awesome :)

**Comment by danvd** [comment]
Step 1 done by commit bad78c3: Properly identify lv2 plugins and synths.

**Comment by asbaklm** [comment]
It works, fantastic! Yay :)

**Comment by danvd** [comment]
Good :).
Moving to step 2: missing vst fx.

**Comment by spamatica** [comment]
2015-12-30 10:09 GMT+01:00 Andrew <notifications@github.com>:

> Good :).
> Moving to step 2: missing vst fx.
>

Sorry if I missed something in this thread, just wanted to chime in that I
think this was never properly implemented.. fixing it would of course be
great.

Regards,
Robert

**Comment by danvd** [comment]
Hi Robert!
Do you mean vst fx?

**Comment by spamatica** [comment]
2015-12-30 16:27 GMT+01:00 Andrew <notifications@github.com>:

> Hi Robert!
> Do you mean vst fx?
>

Yes, if I recall correctly native VSTs are only fully implemented for synth
use. They are not listed in the plugin dialog for use as effects.

**Comment by danvd** [comment]
> They are not listed in the plugin dialog for use as effects.
Tested it - that's true! It will be a kind of interesting task :)

P.S. for lv2 I made a ladspa wrapper which is rather ugly. So may be the proper way is to rewrite plugin interface in common manner (muse only support ladsapa plugins for fx natively). Will think about it :)

**Comment by terminator356** [comment]
On December 30, 2015 10:20:01 AM spamatica wrote:
> 2015-12-30 16:27 GMT+01:00 Andrew <notifications@github.com>:
> > Hi Robert!
> > Do you mean vst fx?
> 
> Yes, if I recall correctly native VSTs are only fully implemented for synth
> use. They are not listed in the plugin dialog for use as effects.
> 
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/muse-sequencer/muse/issues/438#issuecomment-168019313>
> > .
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/438#issuecomment-168048585

What? You mean the rack plugin dialog? Aren't all plugins listed there?
Both DSSI-vst and native VST?
They should be. Something got broken?

**Comment by spamatica** [comment]
2015-12-30 22:14 GMT+01:00 Tim <notifications@github.com>:

> On December 30, 2015 10:20:01 AM spamatica wrote:
> > 2015-12-30 16:27 GMT+01:00 Andrew <notifications@github.com>:
> > > Hi Robert!
> > > Do you mean vst fx?
> >
> > Yes, if I recall correctly native VSTs are only fully implemented for
> synth
> > use. They are not listed in the plugin dialog for use as effects.
> >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/muse-sequencer/muse/issues/438#issuecomment-168019313>
> > > .
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/muse-sequencer/muse/issues/438#issuecomment-168048585
>
> What? You mean the rack plugin dialog? Aren't all plugins listed there?
> Both DSSI-vst and native VST?
> They should be. Something got broken?


Really? I could definitely remember wrong but as I recall the extra support
for allowing them as plugins was never completed.

/Robert

**Comment by asbaklm** [comment]
Just to be clear, what I'm experiencing is missing VST - EFFECTS - plugins. 
VST instruments (both Windows DSSI-VST & Native VST) are present and working.

I also don't seem to get any LADSPA plugs (effects or instruments) on my latest Muse3 build at the moment.

LV2 is fine.

**Comment by danboid** [comment]
AFAIK there is no such thing as a LADSPA instrument, only FX hence they only apply to audio (wave) tracks.

Did you have the LADSPA dev headers installed before bullding MusE?

**Comment by asbaklm** [comment]
I see, no instruments.

I have ladspa-sdk installed on Mint/Ubuntu, is that the correct package or do I need something else?

**Comment by danboid** [comment]
I'm pretty sure you have the right package installed to enable LADSPA plugin support then.

devs:

I'm being very lazy here by not checking myself - MusE doesn't come with the required LADSPA headers etc to enable LADSPA support, does it? If it doesn't, then maybe we should add LADSPA to the list of enabled plugin formats under 'About MusE' so this question is easier to answer?

**Comment by danvd** [comment]
Hi guys!

I created issue #448 - specifically for native vst fx.

Happy New Year!

**Comment by asbaklm** [comment]
Happy New Year Andrey!

**Comment by danboid** [comment]
Happy New Year Andrew, Tim, Robert and asbakim!

**Comment by spamatica** [comment]
Thank you and happy new year all around! :)

Regarding the initial problem here, no ladspa plugins being listed. If I
understood it right?
If that is the case I have never come across this error.
Try starting MusE with
muse3 -DNI2
(debug printouts and don't load vst, dssi or lv2 plugins)
The console should print some debug info, including lines like:
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ZaMaximX2-ladspa.so
name:ZaMaximX2 label:ZaMaximX2

If you don't get these printouts, maybe your LADSPA_PATH environment
variable points to the wrong location?

Regard,
Robert


2016-01-01 10:20 GMT+01:00 danboid <notifications@github.com>:

**Comment by asbaklm** [comment]
Thanks spamatica, I believe that my LADSPA paths are valid.

env | grep LADSPA
LADSPA_PATH=/usr/local/lib/ladspa:/usr/lib/ladspa:/usr/local/lib/ladspa/swh

Also, LADSPA plugs show up in other (non-muse) hosts.

- Partial results from muse3 -DNI2 (I didn't include everything because there's a lot of info)

loadPluginDir: ladspa path:/usr/local/lib/ladspa:/usr/lib/ladspa:/usr/local/lib/ladspa/swh
loadPluginDir: loading ladspa dir:/usr/local/lib/ladspa
scan ladspa plugin dir </usr/local/lib/ladspa>
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/AmplitudeImposer-ladspa.so name:Amplitude Imposer label:AmplitudeImposer
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/CycleShifter-ladspa.so name:Cycle Shifter label:CycleShifter
RemoteVSTClient: all cache files are up-to-date, not running scanner
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix.so name:guitarix label:Simulators
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_amp.so name:guitarix_amp label:guitarix_amp
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_compressor.so name:guitarix_compressor label:guitarix_compressor
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_crybaby.so name:guitarix_crybaby label:guitarix_crybaby
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_distortion.so name:guitarix_distortion label:guitarix-distortion
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_echo.so name:guitarix_echo label:guitarix_echo
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/guitarix_freeverb.so name:guitarix_freeverb label:guitarix_freeverb


loadPluginDir: loading ladspa dir:/usr/lib/ladspa
scan ladspa plugin dir </usr/lib/ladspa>
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic0.so name:Three cardioids to AMB matrix label:Tricardioid-to-AMB
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic0.so name:Virtual stereo microphone label:Virtualmic
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic0.so name:UHJ Encoder label:UHJ-encoder
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic0.so name:UHJ Decoder label:UHJ-decoder
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic1.so name:AMB order 1,1 mono panner label:Ambisonics-11-mono-panner
loadPluginLib: adding ladspa plugin:/usr/lib/ladspa/ambisonic1.so name:AMB order 1,1 stereo panner label:Ambisonics-11-stereo-panner


loadPluginDir: loading ladspa dir:/usr/local/lib/ladspa/swh
scan ladspa plugin dir </usr/local/lib/ladspa/swh>
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/swh/alias_1407.so name:Aliasing label:alias
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/swh/allpass_1895.so name:Allpass delay line, noninterpolating label:allpass_n
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/swh/allpass_1895.so name:Allpass delay line, linear interpolation label:allpass_l
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/swh/allpass_1895.so name:Allpass delay line, cubic spline interpolation label:allpass_c
loadPluginLib: adding ladspa plugin:/usr/local/lib/ladspa/swh/am_pitchshift_1433.so name:AM pitchshifter label:amPitchshift

But when I go to add synth, there are no LADSPA plugins.

**Comment by danvd** [comment]
Hi asbaklm,

ladspa can't go to synth submenu because they don't have midi input. These plugins can only be used for rack fx as audio-processing only. It seems, that you are trying to use them as synth tracks, but this is not implemented.

**Comment by spamatica** [comment]
2016-01-01 18:57 GMT+01:00 Andrew <notifications@github.com>:

> Hi asbaklm,
>
> ladspa can't go to synth submenu because they don't have midi input. These
> plugins can only be used for rack fx as audio-processing only. It seems,
> that you are trying to use them as synth tracks, but this is not
> implemented.
>
Right.
There is the use-case with adding them in the arranger to allow for plugins
with more than two inputs or outputs (as the plugin rack can't handle that)
but since we allow this for LV2 already I don't think this is a very high
priority issue.

**Comment by asbaklm** [comment]
Ahh! (lightbulb moment) 
Thanks for the explanation guys :+1:

**Comment by danvd** [comment]
@asbaklm,

Native vst fx is supported now. See #448 for reference.
Closing this issue.

**Comment by danboid** [comment]
I've noticed we have sub-menus for both VST and LV2 FX under the synths menu now.

Should both of these be listed here seeing as these are FX and not synth plugins?

**Comment by danvd** [comment]
Hi Dan,
Yes, if effect is added as synth track, we can also route audio to it and apply insert effects. The one example is calf sidechain compressor. It produces stereo output from 2 stereo inputs and have no midi in port.
