### ISSUE TITLE
startup segfault

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#439]
https://gist.github.com/danboid/21bec31c59c561a9c867

**Comment by danvd** [comment]
Hi Dan,

Can you also make a backtrace (with Debug build)?

**Comment by danboid** [comment]
I will do but having to do that has made me realise something, the process for creating a BT should be documented in an obvious place of the website. I'd expect to find it under the Fix Bugs section of

http://www.muse-sequencer.org/index.php/Helping

IIRC you have to set CMAKE_BUILD_TYPE=Debug with a capital D or it doesn't work, right?

**Comment by danboid** [comment]
https://gist.github.com/danboid/add44c6705a2310b74e4

**Comment by danvd** [comment]
Strange error. When it segfaults - on the first startup, or when loading a song?
P.S. try to launch without plugins (-I -n -2) also will it segfault or not?

**Comment by danboid** [comment]
It segfaults on startup before any window gets opened.

I think you meant -N instead of -n, right?

[dan@arch76 ~]$ muse3 -I -N -2
Config File </home/dan/.config/MusE/MusE.cfg>
LOCALE en_GB
Denormal protection enabled.
Trying RTC timer...
RtcTimer::setTimerFreq(): cannot set freq 1024 on /dev/rtc: Permission denied
  precise timer not available, check file permissions and allowed RTC freq (/sys/class/rtc/rtc0/max_user_freq)
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 71
Aquired timer frequency: 300
Segmentation fault (core dumped)

**Comment by danvd** [comment]
Yes, -N, right.
Try to rename yout .config/MusE folder (may be it's settings problem?)
If it dows not help, make a clean rebuild in debug mode again. There are not line numbers in your last log. man be some files were not recompiled after update.

**Comment by spamatica** [comment]
2015-12-27 16:22 GMT+01:00 danboid <notifications@github.com>:

> I will do but having to do that has made me realise something, the process
> for creating a BT should be documented in an obvious place of the website.
> I'd expect to find it under the Fix Bugs section of
>
> http://www.muse-sequencer.org/index.php/Helping
>
> IIRC you have to set CMAKE_BUILD_TYPE=Debug with a capital D or it doesn't
> work, right?
>
Hi, I added a step by step here
http://www.muse-sequencer.org/index.php/Helping#Report_Bugs that hopefully
explains this, feel free to comment if I missed anything or if something
was explained differently previously, this was mostly from the top of my
head.

Regarding the capital D, I never type it like that but it is listed like
that in the documentation so not sure what to believe (:

**Comment by danvd** [comment]
Hi Robert!
Thanks for the addition :).

2 Dan: if segfault still persists, may be we can try via teamviewer?

**Comment by danboid** [comment]
Hi Robert

Thanks for adding those instructions, but they way I like to create a debug build is to edit the buld type in compile_muse.sh. Is there a reason you didn't write the instructions to do it that way instead of running cmake manually with the correct switch? If not, I think it'd make the process a little simpler.

**Comment by danboid** [comment]
This seems to have just been caused by not doing a 'make clean' before re-compiling. I've done a clean build and muse starts up fine now.

Sorry about that!

**Comment by danvd** [comment]
ok!

**Comment by spamatica** [comment]
2015-12-27 18:04 GMT+01:00 danboid <notifications@github.com>:

> Hi Robert
>
> Thanks for adding those instructions, but they way I like to create a
> debug build is to edit the buld type in compile_muse.sh. Is there a reason
> you didn't write the instructions to do it that way instead of running
> cmake manually with the correct switch? If not, I think it'd make the
> process a little simpler.
>

True, there is no really no valid reason to not use the script, I'll change
the instructions to use this instead.

Regards,
Robert
