### ISSUE TITLE
New logo for version 3

### ISSUE THREAD

**Issue by danvd** [muse-sequencer/muse#446]
I made a new logo for a splash screen. What do you think about it?

**Comment by danvd** [comment]
Updated text

**Comment by spamatica** [comment]
Looks good to me :)

2015-12-29 5:04 GMT+01:00 Andrew <notifications@github.com>:

**Comment by terminator356** [comment]
On December 28, 2015 12:27:42 PM Andrew wrote:
> I made a new logo for a splash screen What do you think about it?

Nice!

MusE cubed!

If you are looking for more 'racing decals' to show,
 you can show the Fluidsynth logo, two of which are found
 in our xpm dir, we use the blue wavey thingy.

**Comment by danvd** [comment]
Ok, thanks for the feedback, guys!
Will try to use fulidsynth image too :)

BTW, about fluidsynth - what do you think about sfz format? Do you use it? Integrating linuxsampler into muse can be a good idea. It also supports sf2 files too. 
Now there are many sampled instruments made as sfz. One of them if free salamander grand piano. Lv2 version  of linuxsampler is rather inconvenient to use.

**Comment by terminator356** [comment]
On December 30, 2015 10:03:59 PM Andrew wrote:
> Ok, thanks for the feedback, guys!
> Will try to use fulidsynth image too :)
> 
> BTW, about fluidsynth - what do you think about sfz format? Do you use it?
> Integrating linuxsampler into muse can be a good idea. It also supports sf2
> files too. Now there are many sampled instruments made as sfz. One of them
> if free salamander grand piano. Lv2 version  of linuxsampler is rather
> inconvenient to use.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/446#issuecomment-168129698

Ha! I just had an sf and sfz brainstorming session tonight ;-)

I was looking at midi import - someone asked us to auto-load a synth 
 to make some noise. 
There's FluidR3 SF, there's a cut down version of that and there's 
 the 6MB Timidity SF (they're OK,consider that I use Creative's old 
 4 and 8MB SFs for recording - let's use them!)...
 ... and then there's sfz.

In fact I was investigating what sfz or LS libraries we need,
 the sfz specification, and linuxsampler licensing.

To embed support does MusE need the linuxsampler part?
Isn't there some controversy over the licensing where
 some distros (mine) don't include the linuxsampler part, 
 thus if MusE /requires/ linuxsampler they can't include MusE?

You should know that the Open Octave Midi 2 project, 
 which was partly based on MusE, was heavily centred around
 the idea of orchestral instruments and linuxsampler and so on.
LS was built into it. 
Take a look.

I note that the excellent Swami SF editor also loads GIG files.

I'm still a bit cloudy on what all this stuff does, and the libraries
 and so on.

Thanks.
Tim.

**Comment by danvd** [comment]
It seems, that licensing scheme of linuxsampler can make a headache if it will be integrated  into muse... Considering this I prefer to use LS lv2 plugin :).

**Comment by spamatica** [comment]
2015-12-31 9:51 GMT+01:00 Tim <notifications@github.com>:

> On December 30, 2015 10:03:59 PM Andrew wrote:
> > Ok, thanks for the feedback, guys!
> > Will try to use fulidsynth image too :)
> >
> > BTW, about fluidsynth - what do you think about sfz format? Do you use
> it?
> > Integrating linuxsampler into muse can be a good idea. It also supports
> sf2
> > files too. Now there are many sampled instruments made as sfz. One of
> them
> > if free salamander grand piano. Lv2 version of linuxsampler is rather
> > inconvenient to use.
>

Not using sfz much, there was a drumkit released the other day I would like
to try though (or rather two) that are in sfz format.
http://bandshed.net/avldrumkits/index.html



> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/muse-sequencer/muse/issues/446#issuecomment-168129698
>
> Ha! I just had an sf and sfz brainstorming session tonight ;-)
>
> I was looking at midi import - someone asked us to auto-load a synth
> to make some noise.
> There's FluidR3 SF, there's a cut down version of that and there's
> the 6MB Timidity SF (they're OK,consider that I use Creative's old
> 4 and 8MB SFs for recording - let's use them!)...
> ... and then there's sfz.
>

I didn't know about the cut down version of FluidR3, only 12MB (looking at
the MusEScore repository). Seems definitely the way to go if we want to
bundle a soundfont.
For making easy demos that would be a good thing I believe.

/Robert


>
> In fact I was investigating what sfz or LS libraries we need,
> the sfz specification, and linuxsampler licensing.
>
> To embed support does MusE need the linuxsampler part?
> Isn't there some controversy over the licensing where
> some distros (mine) don't include the linuxsampler part,
> thus if MusE /requires/ linuxsampler they can't include MusE?
>
> You should know that the Open Octave Midi 2 project,
> which was partly based on MusE, was heavily centred around
> the idea of orchestral instruments and linuxsampler and so on.
> LS was built into it.
> Take a look.
>
> I note that the excellent Swami SF editor also loads GIG files.
>
> I'm still a bit cloudy on what all this stuff does, and the libraries
> and so on.
>
> Thanks.
> Tim.
