### ISSUE TITLE
DSSI-VST FX bug when adding or removing audio outputs

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#449]
- Effect Rack dssi-vst problem summary: 

After loading dssi-vst fx in effects rack and opening the native gui, then closing native gui and removing dssi-vst fx from rack, adding or removing audio outputs fails and muse3 eventually  crashes.

This behaviour is consistent and can be recreated.

- Recreate bug condition:

Start muse3
Add Audio Output (Out2)
Click on Out2 Effect Rack, "empty"
Load a dssi-vst effect, for example vladg sound Molot or Limiter no6 https://vladgsound.wordpress.com/downloads/
Show Native GUI
Close GUI
Remove effect from effect rack
Now attempt to remove or add Audio Out, it fails, eventually Muse3 crashes.

- Logs:
- Loading dssi-vst plugin in effect rack

RemoteVSTClient: all cache files are up-to-date, not running scanner
DSSIVSTPlugin::instantiate(Limiter6.dll)
DSSIVSTPluginInstance::DSSIVSTPluginInstance(Limiter6.dll)
Returning file identifiers: XPV8r6WivbyCKyXIMtcUJRQG
RemoteVSTClient: executing /usr/local/lib/dssi/dssi-vst/dssi-vst-server.exe Limiter6.dll,XPV8r6WivbyCKyXIMtcUJRQG
DSSI VST plugin server v0.986
Copyright (c) 2012-2013 Filipe Coelho
Copyright (c) 2010-2011 Kristian Amlie
Copyright (c) 2004-2010 Chris Cannam
Loading "Limiter6.dll"... done
Testing VST compatibility... fixme:win:EnumDisplayDevicesW ((null),0,0x33f4c8,0x00000000), stub!
fixme:win:EnumDisplayDevicesW ((null),0,0x33f4c8,0x00000000), stub!
fixme:wincodecs:PngDecoder_Frame_GetMetadataQueryReader (0x1983cc,0x33f0e8): stub
fixme:wincodecs:PngDecoder_Frame_GetMetadataQueryReader (0x13d7bc,0x33f0e8): stub
..........................

Initialising Windows subsystem... done
cannot create dummy timer window
DSSIVSTPluginInstance::DSSIVSTPluginInstance(Limiter6.dll) construction complete
client sized shm to 2048
sized shm to 2048, 2 inputs and 2 outputs

- Opening dssi-vst gui

DSSIVSTPlugin::configure(guiVisible,/tmp/rplugin_gui_7J6Zrn)
DSSIVSTPluginInstance::configure(guiVisible,/tmp/rplugin_gui_7J6Zrn)
DSSIVSTPluginInstance::configure: show gui: value /tmp/rplugin_gui_7J6Zrn

- Closing gui

CompactSlider::getMouseOverThumb setting _mouseOverThumb:0 to v:1

- Remove dssi-vst plugin from effect rack

DSSIVSTPlugin::cleanupdssi-vst-server[1]: reset
DSSIVSTPluginInstance::~DSSIVSTPluginInstance
DSSIVSTPluginInstance::~DSSIVSTPluginInstance: asking plugin to terminate
RemoteVSTServer::terminate: setting exiting flag
Remote VST plugin audio thread: returning
Audio: read pipe failed: Interrupted system call

- Attempt to add another audio out and remove audio out 2

audio: bad serial number, read 0 expected 5
unknown seq message 171877600
audio: bad serial number, read 0 expected 6
unknown seq message 169776384
audio: bad serial number, read 0 expected 7
unknown seq message 170585280
audio: bad serial number, read 0 expected 8
unknown seq message 170189328
audio: bad serial number, read 0 expected 9
PANIC: processInit: no buffer from audio driver
PANIC: processInit: no buffer from audio driver
Segmentation fault

- Crash

**Comment by danvd** [comment]
Hi @asbaklm,
windows vst support in muse highly depends on dssi-vst. which is a separate software, and your error is releted to it only. There are plans to make muse's own implementation of win vst plugins, but now you cat try airwave vst bridge. it can export windows vst plugs ans linux native ones.

I'll close this issue, because it's not releted to muse itself.
