### ISSUE TITLE
arranger drawing issue

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#450]
If I go to Muse settings -> Global settings, change a setting and then push 'Apply' it messes up the drawing of the arranger by seemingly creating a new, smaller arranger on top of the existing one.

**Comment by danvd** [comment]
Hi Dan,
This is a floating error. Sometimes I also get it. Can you make a video? It will be the reference for this issue :)

**Comment by danboid** [comment]
https://youtu.be/znCXklalCsQ

**Comment by danboid** [comment]
The arranger breaks whether you choose 'Apply' or 'OK'

**Comment by danvd** [comment]
Addition: this error becomes persistent only if muse's window is maximized.

**Comment by danvd** [comment]
Just pushed a fix: be341f5
Can you test?

**Comment by danboid** [comment]
It would seem to be fixed here.

Thanks for another quick fix Andrew!
