### ISSUE TITLE
Can't copy and select notes in the pianoroll under certain conditions

### ISSUE THREAD

**Issue by songo** [muse-sequencer/muse#451]
There seem to be no way to copy notes in the pianoroll editor (by dragging it with
ctrl) to place them exactly one above other. Dragged note just disappears.  When
notes are misaligned vertically they can be copied successfully. However, when
they are aligned manually again, only one note can be selected and other one seems
to be stuck.

How to reproduce:
- start MusE,
- add a new MIDI track,
- draw a new part using pencil,
- open it in the pianoroll editor,
- enable snapping to be precise,
- draw a note (e.g., C),
- try to drag it with ctrl and place exactly above old one (as E or other),
- it disappears unless it is misaligned vertically a bit.

See attached screenshot:

![muse-copybug](https://cloud.githubusercontent.com/assets/1877240/12128679/1c865edc-b3ff-11e5-9956-4ada572d4984.jpeg)

Four notes are dragged (with ctrl pressed) exactly above existing ones but they will disappear as soon as they are dropped.

I'm using Debian 8.x with KDE. Tried `muse` packages from kxstudio repository,
build Muse 2.2.x and 3.x myself, all to no avail.

This bug affects MusE 2.2.1 and git master (8e99a5826a26db3175c37df0665cb09afec968bb). Didn't tried 2.2.0 yet.
However, in 2.1.2 all works fine.

**Comment by danvd** [comment]
Hi @songo,
Thanks for the info! Will check this soon.

**Comment by danvd** [comment]
Hi Krzysztof,

Just pushed a fix 8bc1bdb. Can you update and retest?

**Comment by songo** [comment]
Hello @danvd,

Just build 03b9b65386271e0f38163693e8321e8f21d8407a and tried copying notes (and group of notes) in various configurations. Now all works flawlessly, so now I can use 3.x for my regular projects instead of 2.1.2. And the bug has been smashed really fast! Thanks!

BTW, do you plan to backport the fix to current stable (2.2.x)? It's quite serious IMO, because normal MIDI editing in the pianoroll is then a bit problematic.

**Comment by danvd** [comment]
Ok. That's good!
3.0 will be released soon (I hope till the end of February) and will replace 2.2 as a stable version, so we'll not backport and make bug-fix release of previous version. 
But if you need this patch for 2.2, you can look at the fix 8bc1bdb - it's really small, and make changes to 2.2 source file.

If everything is fine now, please close this issue then :)

**Comment by songo** [comment]
Yes, I know the fix can be cherry-picked easily. I just asked  about possible 2.2 bug release out of curiosity. Now I'm using 3.0 and I'm very pleased with it. Thanks again!
