### ISSUE TITLE
arranger cursor display mode

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#453]
Currently the cursor box in the top left of the arranger window only displays the cursors position in bars and beats. It would be useful if you could toggle it between showing bars and beats versus displaying hours, minutes and seconds by clicking on it.

Some might want a SMPTE mode too, eventually?

**Comment by terminator356** [comment]
On January 7, 2016 04:34:00 PM danboid wrote:
> Currently the cursor box in the top left of the arranger window only
> displays the cursors position in bars and beats. It would be useful if you
> could toggle it between showing bars and beats versus displaying hours,
> minutes and seconds by clicking on it.
> 
> Some might want a SMPTE mode too, eventually?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/453

We might be able fulfill your request for this one control. 

But it really needs to be part of a larger overhaul involving how 
 the timeline is displayed, how the canvas is displayed and so on.
There are deep fundamental operational implications to consider.
We must be careful of short-term haphazard patchwork changes.

I mentioned I had started a branch called infrastructure which
 made major changes to prepare for this.

Tim.

**Comment by danboid** [comment]
OK Tim - sounds good.

This is one of my lower priority requests seeing as the Big Clock shows the time in hhmmss - it'd just be nice to see where you are without having to have the Big Clock window open.
