### ISSUE TITLE
Yamaha S30/S80 instrument definition

### ISSUE THREAD

**Issue by DennisSchulmeister** [muse-sequencer/muse#455]
Hello everybody,

Here's another instrument definition file for the Yamaha S30 or Yamaha S80 synthesizers.

Dennis

[Yamaha-S30_S80.idf.zip](https://github.com/muse-sequencer/muse/files/85220/Yamaha-S30_S80.idf.zip)

**Comment by spamatica** [comment]
I think this has been added. And thanks!
