### ISSUE TITLE
fluidsynth plugin drum channel drop-down menu offset

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#456]
When you click on any drum channel drop-down in the MESS fluidsynth plugin window, the menu that appears is offset near to the right edge of the cell containing the option. A minor complaint I know but I thought I'd still log it as it looks a bit weird.

**Comment by danboid** [comment]
This has got a lot worse under the latest git. Now when I click on any of the drum chnl drop down menus the menu appears way outside to the right of the plugin window - there is a gap of over a centimeter between the right edge of the window and the drum channel menus.

**Comment by terminator356** [comment]
On January 24, 2016 10:05:15 AM danboid wrote:
> This has got a lot worse under the latest git. Now when I click on any of
> the drum chnl drop down menus the menu appears way outside to the right of
> the plugin window - there is a gap of over a centimeter between the right
> edge of the window and the drum channel menus.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/456#issuecomment-174325718

Yes, observed but ignored for a while.

I think it happened way back at the switch to Qt4.

Will try to fix.

Thanks.
Tim.
