### ISSUE TITLE
highlighted track selections

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#457]
There are two parts to this request but they're very closely related so I thought I may as well bundle them into one issue.

First, the mixer doesn't currently seem to have a concept of a selected or highlighted track. I like to be able to click within a mixer channel and see its edge or decor become darker to visually highlight thats the one I'm currently working on whilst switching between or using other muse windows, plugins or other apps. This ability also makes a lot of sense when we can move mixer strips - the highlighted one will be he one that gets moved when you click and drag.

Secondly, when you select / highlight a track in the arranger the same track should become highlighted in the mixer and vice versa.

**Comment by danboid** [comment]
As discussed on the dev list, we should also ideally be able to CTRL-click to highlight multiple tracks.

**Comment by spamatica** [comment]
This is mostly implemented now, tracks selected in the arranger or mixer cause the track to get highlighted. Using CTRL+click in the mixer allows for selecting several tracks. 
CTRL+left/right allows for changing active track
Up/down allows for changing volume.

Missing:
- selecting several tracks doesn't work between mixer and arranger, a bit of a corner case so I won't fix it now atleast.
- dragging multiple tracks in the mixer isn't possible yet either.

I'd like to add Left/Right to change Panning of a track also but the implementation has changed and I couldn't figure out how to manipulate the pan value :P
