### ISSUE TITLE
cannot read or edit (full) track names in mixer

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#459]
It would seem that muse cannot currently display more than about 7 characters for the track names in the mixer. It is highly likey the user will want to have several tracks that all begin with the same seven characters eg "backing_vocals" easily exceeds seven characters so its hard to tell backing_vocals from backing_vocals_2, backing_vocals_3 etc when you are just looking at the mixer. This will be less of a problem when my previous feature request of being able to highlight tracks gets implemented as that would allow the user to highlight a track in the arranger and tally it up as it would also become highlighted in the mixer.

We should also be able to edit track names from within the mixer. Implementing this would lessen the need to be able to resize mixer strips horizontally, which is the only other way I can think of being able to view longer track names within the mixer. Clicking on a tracks label in the mixer should make an editable text box appear that shows the tracks name in full and lets the user modify it.

**Comment by danboid** [comment]
Single-clicking on a tracks label in the mixer should highlight that track by making it darker somehow than the other tracks. Double-clicking the tracks label in the mixer should show the full track name and allow it to be edited.

**Comment by terminator356** [comment]
On January 17, 2016 02:03:12 PM danboid wrote:
> It would seem that muse cannot currently display more than about 7
> characters for the track names in the mixer. It is highly likey the user
> will want to have several tracks that all begin with the same seven
> characters eg "backing_vocals" easily exceeds seven characters so its hard
> to tell backing_vocals apart from backing_vocals_2, backing_vocals_3 etc
> apart when you are just looking at the mixer. This will be less of a
> problem when my previous feature request of being able to highlight tracks
> gets implemented as that would allow the user to highlight a track in the
> arranger and tally it up as it would also become highlighted in the mixer.
> 
> We should also be able to edit track names from within the mixer.
> Implementing this would lessen the need to be able to resize mixer strips
> horizontally, which is the only other way I can think of being able to view
> longer track names within the mixer.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/459

Relax, work is in progress on that exact area.
Go back a few versions and see how it auto-fits the text
 and auto-adjusts the font size (there's an Appearance Setting: 
 the last Font # 8 IIRC is specifically for the mixer strip labels,
 read the tooltips above each font).

In fact it should be auto-fitting the text /now/

There should never be /any/ missing text unless Robert is changing something.

Right now the auto-font-size mechanism is /not/ working/
 but the word splitting /is/ working. There should be no missing text at all,
 just all vertically arranged if necessary.

Notice that, it may be hard to tell (++your font size and see), 
 but the midi strip Instrument and patch boxes /are/ currently
 auto-adjusting their font size.
(This is actually confounding me ATM. That both the strip labels and 
 the instrument/patch boxes use the /same/ auto-font-size technique
 but the strip label isn't working. It is a stylesheet issue. WIP.)

---

Editing the names from the labels is a great idea !
Of course. Like actual masking tape and black MM on a real strip.
Mmm...

Definitely kick us if it hasn't been done soon.

I had the same idea for the advanced router dialog.
All those listed objects and no way to change the names.
But I thought, "careful, how far do we go with that, do we want to 
 turn this dialog into an arranger?'

T.

**Comment by terminator356** [comment]
On January 17, 2016 05:32:56 PM you wrote:
> On January 17, 2016 02:03:12 PM danboid wrote:
> > It would seem that muse cannot currently display more than about 7
> > characters for the track names in the mixer. It is highly likey the user
> > will want to have several tracks that all begin with the same seven
> > characters eg "backing_vocals" easily exceeds seven characters so its hard
> > to tell backing_vocals apart from backing_vocals_2, backing_vocals_3 etc
> > apart when you are just looking at the mixer. This will be less of a
> > problem when my previous feature request of being able to highlight tracks
> > gets implemented as that would allow the user to highlight a track in the
> > arranger and tally it up as it would also become highlighted in the mixer.
> > 
> > We should also be able to edit track names from within the mixer.
> > Implementing this would lessen the need to be able to resize mixer strips
> > horizontally, which is the only other way I can think of being able to
> > view
> > longer track names within the mixer.
> > 
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/muse-sequencer/muse/issues/459
> 
> Relax, work is in progress on that exact area.
> Go back a few versions and see how it auto-fits the text
>  and auto-adjusts the font size (there's an Appearance Setting:
>  the last Font # 8 IIRC is specifically for the mixer strip labels,
>  read the tooltips above each font).
> 
> In fact it should be auto-fitting the text /now/


> There should never be /any/ missing text unless Robert is changing
> something.
> 
> Right now the auto-font-size mechanism is /not/ working/
>  but the word splitting /is/ working. There should be no missing text at
> all, just all vertically arranged if necessary.

Uh, sorry clarification:
It supports text word break only - not break anywhere.

Choose 'yer track names wisely !

But I can easily rework that label (we'll be doing that anyway to 
 allow editing) so that the label /does/ break text anywhere. 

Example of text break anywhere: The advanced router.

Tim.

> 
> Notice that, it may be hard to tell (++your font size and see),
>  but the midi strip Instrument and patch boxes /are/ currently
>  auto-adjusting their font size.
> (This is actually confounding me ATM. That both the strip labels and
>  the instrument/patch boxes use the /same/ auto-font-size technique
>  but the strip label isn't working. It is a stylesheet issue. WIP.)
> 
> ---
> 
> Editing the names from the labels is a great idea !
> Of course. Like actual masking tape and black MM on a real strip.
> Mmm...
> 
> Definitely kick us if it hasn't been done soon.
> 
> I had the same idea for the advanced router dialog.
> All those listed objects and no way to change the names.
> But I thought, "careful, how far do we go with that, do we want to
>  turn this dialog into an arranger?'
> 
> T.
