### ISSUE TITLE
fluidsynth plugin not restoring settings properly

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#462]
I have a muse project with a MIDI drum track that was using a standard GM drum kit on channel 10 via the MESS fluidsynth plugin.

I've not tried opening the project for a few revisions but I just did so under the latest git and there now seems to be some issue with loading/restoring the correct settings for the FS plugin voice. Instead of hearing a drum kit I get the (most likely default) piano sound. It was loading and saving fine until this latest build.

The FS plugins loaded soundfonts and channel setup settings are as they should be but thats not what I'm hearing. If I delete the FS plugin and recreate it with the same settings it works fine until I save, exit and reload the project.

**Comment by asbaklm** [comment]
I think this could be somewhat related also to issue #430

**Comment by danboid** [comment]
Sounds like it could be related although this was working for me at the time you reported #430 and for a few weeks worth of revisions after too.

**Comment by asbaklm** [comment]
Interesting
