### ISSUE TITLE
simpledrums channels vs GM drums

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#463]
Today marks the first time I've ever tried using the simpledrums plugin with some pre-existing MIDI drums, hence why I've only just made the following observation.

The file I'm editing uses the 'Acoustic Bass Drum' sound for the kick BUT the first/lowest assignable channel in simpledrums (Channel 1) maps to the next MIDI drum instrument up which is 'Bass Drum 1' despite the fact that the MusE drum editor starts at and displays the 'Acoustic Bass Drum' drum channel (effectively an unmappable channel 0).

I know it wouldn't be hard for me to move all of the bass drum notes from Acoustic onto bass drum 1 but obviously its greatly preferable for simpledrums to be fixed so as to work nicely with GM drum tracks.

Another less concerning issue with simpledrums is that it has a scrollbar to the right side of its window that doesn't do anything!

**Comment by danboid** [comment]
Currently, the simpledrum channels are labelled with both a number and their note value. It would be very useful if they also displayed which GM drum sound they map too, maybe when you mouseover its channel/note label? 

I'd prefer it if we scrapped the channel and note labels and replaced them with the drum sound names and then the note value (w/octave number) would be displayed on mouseover.

**Comment by danboid** [comment]
Some of the extra space for the wider channel labels that showing the drum sounds would require could be reclaimed by making  the L and C icons much narrower than they currently are. I don't think the user really needs to see the filenames of the samples that have been loaded in the main plugin window. It'd be more useful to see what the channels map to.

The L and C icons could be replaced by a single 'Load sample' icon that is one colour/shade when it has a sample loaded and another colour when its not being used or something similar.

**Comment by spamatica** [comment]
Hi Dan,

2016-01-24 20:48 GMT+01:00 danboid <notifications@github.com>:

> Some of the extra space for the wider channel labels that showing the drum
> sounds would require could be reclaimed by making the L and C icons much
> narrower than they currently are. I don't think the user really needs to
> see the filenames of the samples that have been loaded in the main plugin
> window. It'd be more useful to see what the channels map to.
>
> The L and C icons could be replaced by a single 'Load sample' icon that is
> one colour/shade when it has a sample loaded and another colour when its
> not being used or something similar.
>
I rearranged it a bit, it needs more work under the hood but it's a start.
Let me know if it looks alright.

Regards,
Robert

**Comment by danboid** [comment]
Hi Robert

It's looking a bit better now but there are still a couple of issues:

The most important issue here, and the main reason I created this ticket, is that you currently can't map anything to 'Acoustic Bass Drum' which according to both the MusE drum editor and the MIDI file I'm currently editing is assigned to the MIDI note (B) just below 'Bass Drum 1'. Fixing this would prob require creating a channel 0 in simpledrums or adjusting the current channel numbers as appropriate.

Also, can you not get rid of or hide the scrollbar to the right of the simpledrums mixer section? That's no biggie of course but it just looks a bit odd.

Thanks Robert!

**Comment by spamatica** [comment]
2016-01-25 20:34 GMT+01:00 danboid <notifications@github.com>:

> Hi Robert
>
> It's looking a bit better now but there are still a couple of issues:
>
> The most important issue here, and the main reason I created this ticket,
> is that you currently can't map anything to 'Acoustic Bass Drum' which
> according to both the MusE drum editor and the MIDI file I'm currently
> editing is assigned to the MIDI note (B) just below 'Bass Drum 1'. Fixing
> this would prob require creating a channel 0 in simpledrums or adjusting
> the current channel numbers as appropriate.
>
Indeed, haven't really looked at that yet but I fear that fix will be
slight harder, but I could be wrong. :)


> Also, can you not get rid of or hide the scrollbar to the right of the
> simpledrums mixer section? That's no biggie of course but it just looks a
> bit odd.
>

Ah, probably something that doesn't quite add up after I changed the
layout, I don't see any scrollbar, right after the master slider I guess?
Unless it's the master slider you are seeing, it's not marked that well :P

/Robert

Regards

**Comment by danboid** [comment]
![sd-scrollbar](https://cloud.githubusercontent.com/assets/1429783/12564597/feb8fe60-c3a7-11e5-8e99-c066ee59128d.png)

**Comment by danboid** [comment]
That scrollbar appears by default and doesn't disappear even if I make the simpledrums window full screen. It doesn't do anything at any wndow size.

**Comment by asbaklm** [comment]
Isn't that the SimpleDrums Master Volume?? At least, that's what it seems to be on my computer.

**Comment by spamatica** [comment]
2016-01-29 16:56 GMT+01:00 asbaklm <notifications@github.com>:

> Isn't that the SimpleDrums Master Volume?? At least, that's what it seems
> to be on my computer.
>

Yes, it's supposed to be the Master volume but I think Dan might be right,
it doesn't really do anything :P
I'll see if I can get it connected to the right place.

**Comment by spamatica** [comment]
Haha, seems I spoke to soon. I looked at the code and couldn't see the slider actually controlling anything but trying it now I see it is indeed working ;)

**Comment by danboid** [comment]
Looking at it again, it does actually tell you in its tooltip that its the Master Volume slider. I dunno how I missed that one!

Please ignore my ignorant scrollbar rant!
