### ISSUE TITLE
Configure Midi Devices; Device Port Assignments bug

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#466]
Happy New Year and prosperous 2016 for everybody :)

This seems to be a relatively simple bug affecting device selections in Device Port Assignments. 
The problem is that the dropdown menu doesn't behave consistently. Upon first time use after restarting Muse it presents the full selection of "Instrument" templates. Every subsequent click selection then causes it to increment menus with More2,More3 etc.

**Bug Summary**
Muse Settings: Configure Midi Devices, Midi Ports and Synthesizers
Device Port Assignments
Click on Instrument, it will present some options and seems to work OK. (Default is GM)
However, subsequent clicking on Instrument loads menus with increasing values (More2, More3, More4 etc)
From that point, many MIDI devices are missing. It's not possible to select GM any longer. The only way to reset this condition is to restart Muse

**Comment by asbaklm** [comment]
Update:
Issue caused by #468

**Comment by asbaklm** [comment]
Closing

**Comment by terminator356** [comment]
On January 29, 2016 02:57:58 AM asbaklm wrote:
> Happy New Year and prosperous 2016 for everybody :)
> 
> This seems to be a relatively simple bug affecting device selections in
> Device Port Assignments The problem is that the dropdown menu doesn't
> behave consistently Upon first time use after restarting Muse it presents
> the full selection of "Instrument" templates Every subsequent click
> selection then causes it to increment menus with More2,More3 etc
> 
> **Bug Summary**
> Muse Settings: Configure Midi Devices, Midi Ports and Synthesizers
> Device Port Assignments
> Click on Instrument, it will present some options and seems to work OK
> (Default is GM) However, subsequent clicking on Instrument loads menus with
> increasing values (More2, More3, More4 etc) From that point, many MIDI
> devices are missing It's not possible to select GM any longer The only way
> to reset this condition is to restart Muse
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/466

Hi. Thanks for the report. 

You were not imagining things.
That really was a bug.

It was fixed a couple of commits ago.
It may have fixed itself if you pulled the latest master during your tests.

(The problem was the popup menu was not being properly destroyed
 each time it was opened, thus it had 'left over' items in it each 
 subsequent time it opened.)

Tim.
