### ISSUE TITLE
Crash occurs when clicking on output routing

### ISSUE THREAD

**Issue by asbaklm** [muse-sequencer/muse#468]
Open Muse, it starts by default with audio Out1 track loaded.
Navigate to bottom left of screen, click on output routing 'jack' to select output routing.

Muse crashes.....

**Comment by spamatica** [comment]
Hi,

I can't reproduce this,
could you try getting a backtrace for this?
http://muse-sequencer.org/index.php/Helping#Report_Bugs

Regards,
Robert


2016-01-29 12:59 GMT+01:00 asbaklm <notifications@github.com>:

**Comment by asbaklm** [comment]
I think the issue is solved or resolved but perhaps it is possible or worth considering to put a safeguard into place in the code to prevent this kind of thing from happening?

**What I did**

I rebuilt muse with -DCMAKE_BUILD_TYPE=Debug
Started gdb
Ran muse3 in gdb

It didn't crash any longer, and running ./muse3 from the terminal also doesn't cause this issue.

Upon further investigation, I realised that I'm using a startup script to set some environment variables for Muse3 which seems to have caused this crash to occur when clicking on the jack plug:

**Cause of error**

This error is caused if LD_LIBRARY_PATH was exported without containing /usr/local/lib

Here's the error from the terminal:
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
QXcbWindow: Unhandled client message: "_GTK_LOAD_ICONTHEMES" 
/usr/local/bin/muse3: symbol lookup error: /usr/local/lib/muse-3.0/modules/libmuse_widgets.so: undefined symbol: _ZN9QMetaType22registerNormalizedTypeERK10QByteArrayPFvPvEPFS3_S3_PKvEi6QFlagsINS_8TypeFlagEEPK11QMetaObject

**Comment by terminator356** [comment]
On January 29, 2016 03:59:28 AM asbaklm wrote:
> Open Muse, it starts by default with audio Out1 track loaded
> Navigate to bottom left of screen, click on output routing 'jack' to select
> output routing
> 
> Muse crashes
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/468

Hi. See the response to #467.

This may be an actual bug, related to bug #467 which
 is waiting to be fixed.

Thanks.
Tim.

**Comment by asbaklm** [comment]
I see! Thank you very much for the information and investigation.

**Comment by spamatica** [comment]
Haven't seen any mention of this for a while now so I assume it is indeed fixed.
If it's still an issue, reply to this ticket.
