### ISSUE TITLE
[git master] midi input initialization problem

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#469]
Thought I would create some bug reports of issues I've seen with current git, so they are not forgotten.

There is a problem with initialization of the new midi reconnect feature.
If I do the following:
1. create song
2. insert keyboard
3. find keyboard in Midi-config (alsa)
4. press OK.
5. rec enable track and play. works!
6. stop and start muse
7. reload song, everything is still rec enabled and the input keyboard is configured, all as I left it.
8. But when I try to play with keyboard it doesn't doesn't work anymore.
9. Workaround: click the [ALSA] button in the midi config and it gets going again.

**Comment by terminator356** [comment]
On February 13, 2016 05:29:12 AM spamatica wrote:
> Thought I would create some bug reports of issues I've seen with current
> git, so they are not forgotten.
> 
> There is a problem with initialization of the new midi reconnect feature.
> If I do the following:
> 1. create song
> 2. insert keyboard
> 3. find keyboard in Midi-config (alsa)
> 4. press OK.
> 5. rec enable track and play. works!
> 
> 6. stop and start muse
> 7. reload song, everything is still rec enabled and the input keyboard is
> configured, all as I left it. 8. But when I try to play with keyboard it
> doesn't doesn't work anymore. 9. Workaround: click the [ALSA] button in the
> midi config and it gets going again.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/469

This is my fault.
I haven't yet added the ability to 'remember' the
 state of that ALSA button (store it in the song.)
So yes, you have to click it again when you reload.

Tim.

**Comment by terminator356** [comment]
On February 13, 2016 05:29:12 AM spamatica wrote:
> Thought I would create some bug reports of issues I've seen with current
> git, so they are not forgotten.
> 
> There is a problem with initialization of the new midi reconnect feature.
> If I do the following:
> 1. create song
> 2. insert keyboard
> 3. find keyboard in Midi-config (alsa)
> 4. press OK.
> 5. rec enable track and play. works!
> 
> 6. stop and start muse
> 7. reload song, everything is still rec enabled and the input keyboard is
> configured, all as I left it. 8. But when I try to play with keyboard it
> doesn't doesn't work anymore. 9. Workaround: click the [ALSA] button in the
> midi config and it gets going again.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/469

A fix has been pushed.

We now remember the state of the ALSA button.

Aiming for simplicity, it is a global setting, not per-song.

Tim.

**Comment by spamatica** [comment]
I think it's a good thing this is remembered in the configuration and not in the song so all is good.

I think there still are some situations where it seems to get lost and the device doesn't show up until a lot of clicking but I'll close this one and create a new ticket if I find a test case where it breaks.
