### ISSUE TITLE
MusE specific TAP reverb gui, doesn't work (probably since Qt5)

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#470]
Haven't really paid attention but the move to Qt5 probably broke the support.

For those that don't know, MusE has the ability to create custom guis with *.ui files that bind plugin parameters to widgets and labels created for the specific purpose. 
We only have two such *.ui files so it's not really a deal breaker but it would be nice to get it fixed as the TAP reverb is really cool, but with the default GUI it is very hard to use.

**Comment by terminator356** [comment]
On February 13, 2016 05:44:07 AM spamatica wrote:
> Haven't really paid attention but the move to Qt5 probably broke the
> support.

No, actually it was the ThinSlider stuff during the transition to the 
 my new sliders.

Pushed fix for that, and other related fixes, and some nice goodies. 

Generic plugin UIs should be all good now, including output meters
 which were broken. Scale markings EVERYWHERE now ;-)

Check out say, Invada Input Strip or Calf Input Strip.

Hope y'all like it.

See the ChangeLog for savoury details.

Tim.

**Comment by spamatica** [comment]
Works now :)
