### ISSUE TITLE
Mixer windows are always on top

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#474]
I just compiled muse3 from GitHub and I noticed that the two mixer windows are now always on top of the arranger window. Not sure if this is intended, or if I'm missing something. Is there anything I can do about it, such that clicking on the arranger raises it above the mixer windows?

**Comment by spamatica** [comment]
2016-02-16 11:12 GMT+01:00 Martin Drautzburg <notifications@github.com>:

> I just compiled muse3 from GitHub and I noticed that the two mixer windows
> are now always on top of the arranger window. Not sure if this is intended,
> or if I'm missing something. Is there anything I can do about it, such that
> clicking on the arranger raises it above the mixer windows?
>
 Now that you mention it, I have it too.
If I recall correctly this is the same as I reported some time ago, seems
the bug resurfaced... I'll try to fix it tomorrow.

Regards,
Robert

**Comment by spamatica** [comment]
Removed the parent from mixer creation, this should allow it to be placed in the background again.

**Comment by drautzburg** [comment]
Works now
