### ISSUE TITLE
The score editor has one octave more than the piano-roll editor

### ISSUE THREAD

**Issue by mfreire2** [muse-sequencer/muse#478]
For instance, C4 in the score editor corresponds to C3 in the piano-roll editor. Someone knows how to correct it?

**Comment by danboid** [comment]
I presume you're running muse 2.X or earlier right? This has been fixed in git / MusE 3.

**Comment by mfreire2** [comment]
I'm sorry the delay in my answer. Yes, I am beginning to use MusE 2.1.2
(svn revision: 0) in Ubuntu 12.04. I was trying to compile MusE 3, but my
efforts don't were successfully, mainly because I am not programing and the
computer lack many developmental files. I decided to use Muse 2.1.2 waiting
that the compiled version of MusE 3 will be available soon in the Ubuntu
software center.
Miguel Freire.

2016-02-24 16:44 GMT+01:00 danboid <notifications@github.com>:

**Comment by spamatica** [comment]
Hi Miguel,
MusE 3 isn't release ready yet, but soon!

Though, I have to ask, are you sure you are really using 12.04 ? 
If so I think you should try to upgrade this to atleast 14.04 so your installation still has support. 14.04 will be superceeded with 16.04 sometime this month so it is getting high time to upgrade... although upgrading seldom is a fun process :/

Secondly, there is a repository for ubuntu called kxstudio which is much more up to date than the software that is bundled with ubuntu. kxstudio can be installed on-top of a regular ubuntu install.

**Comment by mfreire2** [comment]
Thanks for your indications.
I'm using Ubuntu 14.04 LTS, there were a mistake in the e-mail.
I hope that soon it will be upgraded to 16.04 by the Ubuntu Sotware Center.
I want to try kxstudio_14.04 that it appears to be tailored to Ubuntu 14.04.
What happen with the new version of Ubuntu 16.04?
Can Kxstudio_14.04 still run on ubuntu 16.04?
Can I upgrade to 16.04 if I am running kxstudio_14.04?
I will wait your answers before to use kxstudio.
Many thanks in advance for your commentaries.
Miguel Freire.


2016-04-07 19:42 GMT+02:00 spamatica <notifications@github.com>:

**Comment by mfreire2** [comment]
Hello, in my last e-mail, I have misunderstood your phrase "kxstudio can be
installed on-top of a regular ubuntu install".
After reading the documentation of kxstudy, now know that kxstudy is really
an OS devoted to the musical production.
I think that I will be able to install both OS kxstudy and Ubuntu in the
same computer following your excellent manual.
Many thanks again.
Miguel Freire

**Comment by spamatica** [comment]
Hello again Miguel,

actually kxstudio may be both. I have never tried to install it from the
ISO but I think you are right it can be installed separately.

I have installed "on top" of kubuntu myself so you don't need to have a
separate installation, check the menu alternative Repositories/About on the
kxstudio site.
Though, if you are unsure and wish to test some, it is probably a good idea
to install it separately. :)



2016-04-12 18:58 GMT+02:00 mfreire2 <notifications@github.com>:

> Hello, in my last e-mail, I have misunderstood your phrase "kxstudio can be
> installed on-top of a regular ubuntu install".
> After reading the documentation of kxstudy, now know that kxstudy is really
> an OS devoted to the musical production.
> I think that I will be able to install both OS kxstudy and Ubuntu in the
> same computer following your excellent manual.
> Many thanks again.
> Miguel Freire
>
