### ISSUE TITLE
Mixer "View" settings have no effect

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#479]
I just noticed, that the "view" settings on the two mixers have no effect. If I e.g. select "Show wave tracks" I still don't see them, even though I do have wave track. Same for deselecting certain track types.

**Comment by spamatica** [comment]
Uh oh. A remnant from the recent rework in the mixer.
If I recall correctly this toolbar is no longer applicable to the mixer,
now you can individually hide tracks you don't want in the mixer.
Though maybe it was supposed to work still.. I need to look at it again.

2016-02-23 18:03 GMT+01:00 Martin Drautzburg <notifications@github.com>:

**Comment by drautzburg** [comment]
I hadn't been aware of the hide/unhide strip controls. But even with them, something is odd: I have a project which was created, using muse2. The two mixers show what they are supposed to show. I can hide/unhide the strips which are currently shown, but it is difficult to show the strips which are not shown in the first place. 

Playing with traditional/arranger-order seems to make muse respect the "show inputs"... controls.

I find the "show" controls very useful though I am not sure what they are supposed to do in conjunction with hide/unhide. Something like "a strip is shown when its category is shown and it is not hidden". But what are the strips you could unhide? I suppose there is no point in unhiding a strip whose category is not shown.

**Comment by spamatica** [comment]
Pushed a fix to the filtering in the mixer now. It was supposed to work as before but I forgot to test it.

I didn't add any additional logic for hide/show yet though so if you have hidden a single strip for instance, the show/hide on categoriy level will still not show it. The logic problem you noted above is also not resolved.
