### ISSUE TITLE
Segfault on start up v2.2.1(built from source) and v.2.1.2 (debian package no debug info)

### ISSUE THREAD

**Issue by 00rob00** [muse-sequencer/muse#481]
Starting program: /usr/local/bin/muse2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdf6bd700 (LWP 2522)]
[New Thread 0x7fffdf63c700 (LWP 2523)]
[New Thread 0x7fffdd22c700 (LWP 2524)]
[Thread 0x7fffdd22c700 (LWP 2524) exited]
[New Thread 0x7fffdd22c700 (LWP 2525)]
[Thread 0x7fffdd22c700 (LWP 2525) exited]
[New Thread 0x7fffdd22c700 (LWP 2526)]
[New Thread 0x7fffddab6700 (LWP 2527)]
[Thread 0x7fffdd22c700 (LWP 2526) exited]
[Thread 0x7fffddab6700 (LWP 2527) exited]
[New Thread 0x7fffddab6700 (LWP 2528)]
[New Thread 0x7fffdd22c700 (LWP 2529)]
[Thread 0x7fffddab6700 (LWP 2528) exited]
[Thread 0x7fffdd22c700 (LWP 2529) exited]
[New Thread 0x7fffdd22c700 (LWP 2530)]
[New Thread 0x7fffddab6700 (LWP 2531)]
[Thread 0x7fffdd22c700 (LWP 2530) exited]
[Thread 0x7fffddab6700 (LWP 2531) exited]
[New Thread 0x7fffddab6700 (LWP 2532)]
[New Thread 0x7fffdd22c700 (LWP 2533)]
[Thread 0x7fffddab6700 (LWP 2532) exited]
[Thread 0x7fffdd22c700 (LWP 2533) exited]
[New Thread 0x7fffdd22c700 (LWP 2534)]
[New Thread 0x7fffddab6700 (LWP 2535)]
[Thread 0x7fffdd22c700 (LWP 2534) exited]
[Thread 0x7fffddab6700 (LWP 2535) exited]
[New Thread 0x7fffddab6700 (LWP 2536)]
[Thread 0x7fffddab6700 (LWP 2536) exited]
[New Thread 0x7fffddab6700 (LWP 2537)]
[New Thread 0x7fffdd22c700 (LWP 2538)]
[Thread 0x7fffdd22c700 (LWP 2538) exited]
[Thread 0x7fffddab6700 (LWP 2537) exited]
[New Thread 0x7fffddab6700 (LWP 2539)]
[New Thread 0x7fffdd22c700 (LWP 2540)]
[Thread 0x7fffddab6700 (LWP 2539) exited]
[Thread 0x7fffdd22c700 (LWP 2540) exited]
[New Thread 0x7fffdd22c700 (LWP 2541)]
[New Thread 0x7fffddab6700 (LWP 2542)]
[Thread 0x7fffdd22c700 (LWP 2541) exited]
[Thread 0x7fffddab6700 (LWP 2542) exited]
[New Thread 0x7fffddab6700 (LWP 2543)]
[New Thread 0x7fffdd22c700 (LWP 2544)]
[Thread 0x7fffddab6700 (LWP 2543) exited]
[Thread 0x7fffdd22c700 (LWP 2544) exited]
[New Thread 0x7fffdd22c700 (LWP 2545)]
[Thread 0x7fffdd22c700 (LWP 2545) exited]
[New Thread 0x7fffdd22c700 (LWP 2546)]
[New Thread 0x7fffddab6700 (LWP 2547)]
[Thread 0x7fffdd22c700 (LWP 2546) exited]
[Thread 0x7fffddab6700 (LWP 2547) exited]
[New Thread 0x7fffddab6700 (LWP 2548)]
[New Thread 0x7fffdd22c700 (LWP 2549)]
[Thread 0x7fffddab6700 (LWP 2548) exited]
[Thread 0x7fffdd22c700 (LWP 2549) exited]
[New Thread 0x7fffdd22c700 (LWP 2550)]
[New Thread 0x7fffddab6700 (LWP 2551)]
[Thread 0x7fffdd22c700 (LWP 2550) exited]
[Thread 0x7fffddab6700 (LWP 2551) exited]
[New Thread 0x7fffddab6700 (LWP 2552)]
[New Thread 0x7fffdd22c700 (LWP 2553)]
[Thread 0x7fffddab6700 (LWP 2552) exited]
[Thread 0x7fffdd22c700 (LWP 2553) exited]
[New Thread 0x7fffdd22c700 (LWP 2554)]
[New Thread 0x7fffddab6700 (LWP 2555)]
[Thread 0x7fffdd22c700 (LWP 2554) exited]
[Thread 0x7fffddab6700 (LWP 2555) exited]
[New Thread 0x7fffddab6700 (LWP 2556)]
[New Thread 0x7fffdd22c700 (LWP 2557)]
[Thread 0x7fffddab6700 (LWP 2556) exited]
[Thread 0x7fffdd22c700 (LWP 2557) exited]
[New Thread 0x7fffdd22c700 (LWP 2558)]
[New Thread 0x7fffddab6700 (LWP 2559)]
[Thread 0x7fffdd22c700 (LWP 2558) exited]
[Thread 0x7fffddab6700 (LWP 2559) exited]
[New Thread 0x7fffe2cd1700 (LWP 2560)]
[Thread 0x7fffe2cd1700 (LWP 2560) exited]
[New Thread 0x7fffdd2b5700 (LWP 2561)]
[New Thread 0x7fffdc321700 (LWP 2562)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffdd2b5700 (LWP 2561)]
0x00007fffdc3bcc87 in ?? ()

Thread 42 (Thread 0x7fffdc321700 (LWP 2562)):
#0  0x00007fffdc3bcc87 in ?? ()
#1  0x00007fffdc321b28 in ?? ()
#2  0x00007ffff18b93d9 in __nptl_deallocate_tsd () at pthread_create.c:175
#3  0x00007ffff18ba34d in __nptl_deallocate_tsd () at ../sysdeps/unix/sysv/linux/exit-thread.h:36
#4  start_thread (arg=0x7fffdc321700) at pthread_create.c:346
#5  0x00007ffff051ca4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 41 (Thread 0x7fffdd2b5700 (LWP 2561)):
#0  0x00007fffdc3bcc87 in ?? ()
#1  0x00007fffdd2b5b18 in ?? ()
#2  0x00007ffff18b93d9 in __nptl_deallocate_tsd () at pthread_create.c:175
#3  0x00007ffff18ba34d in __nptl_deallocate_tsd () at ../sysdeps/unix/sysv/linux/exit-thread.h:36
#4  start_thread (arg=0x7fffdd2b5700) at pthread_create.c:346
#5  0x00007ffff051ca4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fffdf63c700 (LWP 2523)):
#0  0x00007ffff18c281d in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff63b4c65 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007ffff63b7a6b in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007ffff63b2c60 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff18ba284 in start_thread (arg=0x7fffdf63c700) at pthread_create.c:333
#5  0x00007ffff051ca4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffdf6bd700 (LWP 2522)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007ffff63b42ac in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#2  0x00007ffff63a69e8 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#3  0x00007ffff63b2c60 in ?? () from /usr/lib/x86_64-linux-gnu/libjack.so.0
#4  0x00007ffff18ba284 in start_thread (arg=0x7fffdf6bd700) at pthread_create.c:333
#5  0x00007ffff051ca4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7ef7900 (LWP 2516)):
#0  __GI__dl_debug_state () at dl-debug.c:74
#1  0x00007ffff7dee626 in dl_open_worker (a=a@entry=0x7fffffffd418) at dl-open.c:306
#2  0x00007ffff7dea0f4 in _dl_catch_error (objname=objname@entry=0x7fffffffd408, errstring=errstring@entry=0x7fffffffd410, mallocedp=mallocedp@entry=0x7fffffffd407, operate=operate@entry=0x7ffff7dee4b0 <dl_open_worker>, args=args@entry=0x7fffffffd418)
    at dl-error.c:187
#3  0x00007ffff7dedf33 in _dl_open (file=0x1519788 "/usr/lib/vst/ZamDelay-vst.so", mode=-2147483646, caller_dlopen=0x7ffff7a7c98b <MusECore::scanVstNativeLib(QFileInfo&)+103>, nsid=-2, argc=<optimized out>, argv=<optimized out>, env=0x7fffffffe468) at dl-open.c:653
#4  0x00007ffff1ef2f09 in dlopen_doit (a=a@entry=0x7fffffffd630) at dlopen.c:66
#5  0x00007ffff7dea0f4 in _dl_catch_error (objname=0x664570, errstring=0x664578, mallocedp=0x664568, operate=0x7ffff1ef2eb0 <dlopen_doit>, args=0x7fffffffd630) at dl-error.c:187
#6  0x00007ffff1ef34d9 in _dlerror_run (operate=operate@entry=0x7ffff1ef2eb0 <dlopen_doit>, args=args@entry=0x7fffffffd630) at dlerror.c:163
#7  0x00007ffff1ef2fa1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#8  0x00007ffff7a7c98b in MusECore::scanVstNativeLib (fi=...) at /stuff/build/muse-2.2.1/muse/vst_native.cpp:302
#9  0x00007ffff7a7d8dc in MusECore::scanVstNativeDir (s=...) at /stuff/build/muse-2.2.1/muse/vst_native.cpp:458
#10 0x00007ffff7a7dc08 in MusECore::initVST_Native () at /stuff/build/muse-2.2.1/muse/vst_native.cpp:512
#11 0x0000000000409d96 in main (argc=1, argv=0x7fffffffe458) at /stuff/build/muse-2.2.1/muse/main.cpp:700

Rob

**Comment by spamatica** [comment]
Hi,

2016-03-03 22:31 GMT+01:00 00rob00 <notifications@github.com>:

> /usr/lib/vst/ZamDelay-vst.so


It seems this vst plugin was involved.
I think we have stability issues with certain plugins, unclear if it's the
plugins or our fault, I'm leaning towards a bit of both.

Anyway, try uninstalling this plugin and start it again.

Regards,
Robert

**Comment by artur-shaik** [comment]
@spamatica btw, any chance for implementation of plugins execution as separate process? Like it was done in Bitwig. To secure application from crash.

**Comment by spamatica** [comment]
Good idea, it won't happen in the short run but it would be a good
improvement so I'm all for it.
Please do make a ticket for it.

Regards,
Robert


2016-03-04 13:56 GMT+01:00 Artur Shaik <notifications@github.com>:

**Comment by spamatica** [comment]
closing as the problem was a vst synth.
The real solution, externalizing plugin loading, got it's own ticket
