### ISSUE TITLE
Popup dialog consumes a lot of CPU

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#484]
Under certain circumstances the popup dialog is very cpu intensive, seems to be worse when there is a lot on the menu.

**Comment by terminator356** [comment]
Confirmed with routing popups only. Extreme CPU usage upon mouse movement, even with
 few items in the popup.

All other popup types were OK with moderate to large amounts of items.
(Ex. Track list audio automation popup with Calf Organ having about 200 controls tested OK).

My bad on the routing popup. A fix has been applied. 
Please try and lemme know if it works, or other popups still bad.

Tim.

**Comment by spamatica** [comment]
I believe this is indeed corrected now.
