### ISSUE TITLE
Fluidsynth doesn't work when loading multiple soundfonts

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#490]
A low priority issue as it isn't a very useful feature (better to have different fluidsynth players for each soundfont), but when loading multiple soundfonts it's supposed to be possible to assign them to different midi channels.
When I tried it while examining midi drum soundfonts I could not get it to work, seem like it mostly connected the last loaded soundfont.

**Comment by danlyke** [comment]
Current status on 0909515e51ced2c78708b89dc5d3158fe1055345 using Ubuntu 17.10 seems to be that second attempt to load a Fluidsynth sound font causes lock-up. Even if that's in a separate separate "Device".

**Comment by danlyke** [comment]
Potential workaround: Use the fluidsynth-dssi plugin.
