### ISSUE TITLE
muse3 -F populates MIDI ports with "Closed" state but I want it empty at startup

### ISSUE THREAD

**Issue by GraysonPeddie** [muse-sequencer/muse#492]
Simply running "muse" populates MIDI ports with all the JACK-MIDI devices connected, which is expected.
Simply running "muse3 -F" populates MIDI ports but leaves them at "Closed" state. I want to be able to start with a blank slate in the Usable Devices section of the MIDI Configuration dialog.

If only I could select all MIDI ports and delete them at once. I can remove one MIDI port at a time. This is with a "-F" flag set.

**Comment by spamatica** [comment]
I admit I'm not familiar with what you are trying to solve, why can't there be anything in the useable devices?
The devices are more or less just listed, they aren't connected to muse (that is the 'Device port assignment' part of the dialog).

**Comment by spamatica** [comment]
Digged around a bit, the ports I see in this scenario are all alsa-ports. By setting the parameter     <enableAlsaMidiDriver> to 0 in the ~/.config/MusE/MusE.cfg leaves this dialog empty.
If you use alsa midi there is a problem however as this parameter will be turned on when the [Alsa] button is clicked.

**Comment by terminator356** [comment]
On March 20, 2016 08:32:07 AM Grayson Peddie wrote:
> Simply running "muse" populates MIDI ports with all the JACK-MIDI devices
> connected, which is expected. Simply running "muse3 -F" populates MIDI
> ports but leaves them at "Closed" state. I want to be able to start with a
> blank slate in the Usable Devices section of the MIDI Configuration dialog.
> 
> If only I could select all MIDI ports and delete them at once. I can remove
> one MIDI port at a time. This is with a "-F" flag set.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/492

No problem Robert, I know what he means.
I'll try to fix that loose end after next commit.

Tim.
