### ISSUE TITLE
more ways of automation editing

### ISSUE THREAD

**Issue by tjingboem** [muse-sequencer/muse#493]
the automation can be edited at the level of one point, but i would like to be able to edit and redraw with a pencil a whole region of points

purpose is to be able to correct many automation points at the same time by hand

**Comment by terminator356** [comment]
On March 25, 2016 07:46:09 AM Menno Knevel wrote:
> the automation can be edited at the level of one point, but i would like to
> be able to edit and redraw with a pencil a whole region of points
> 
> purpose is to be able to correct many automation points at the same time by
> hand
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/muse-sequencer/muse/issues/493

Apologies, I know it needs more editing features but I had to
 move on after my last major fixes there.
While I was in there, I really wanted to add such features but there
 was no time left. I was close, but it required much further changes.

Also, we have to be careful about blindly piling on features and 
 going too far digging too deep a hole with this automation editor: 
We need to face an elephant and redesign it to accomodate
 putting points in parts so they can be moved as a unit, while also 
 possibly allowing points outside of parts.
It's a very difficult thing to resolve but we're slowly working on it,
 there are several conceptual problems to overcome (allowing parts 
 on ALL tracks, midi vs audio parts, etc...)
Also, we would like to be able to copy/cut/paste the points, which
 requires much difficult work to make the points 'copyable objects' in MusE.

BTW I'm aware of a bug on recent distros where moving a single point
 can slow MusE down and take a long time to move it. Investigating...

Thanks.
Tim.

**Comment by tjingboem** [comment]
i understand - didn't realize that there was so much and fundamental work involved.

i believe an elaborate automation system is the only option to be able to record and edit the control signals for for example VST instruments.

**Comment by spamatica** [comment]
Tim is absolutely right we should try see the bigger picture and make room
for more enhancements of the automation system. Automation bound to parts
is probably what I miss most.

Still I would argue that it might be possible to add mult-point editing
without too much work.. in any case I will take a look but can't promise
anything..


2016-03-26 13:57 GMT+01:00 Menno Knevel <notifications@github.com>:
