### ISSUE TITLE
Global cut sometimes crashes

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#496]
Simply, sometimes when using the global cut function it crashes. Probably a null-pointer in some situations, just need to find a way to reproduce this.

**Comment by kybos** [comment]
This has been fixed in the meantime, hasn't it?

**Comment by spamatica** [comment]
I think it is. Missing is still to take automation into account

Den ons 18 mars 2020 kl 16:27 skrev kybos <notifications@github.com>:
