### ISSUE TITLE
Zyn lv2 has ttl load errors

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#498]
Not strictly a MusE problem but since we have our own version of lilv we should check if there is a fix for this.
I believe it is simply an URI expansion that isn't compatible with the file-open path.

This is the error I get:
zyn lv2 gets errors for a lot of ttl files lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/ZynAddSubFX.lv2presets/Reed%20and%20Wind.ttl'

I would expect the %20 is an erroneous space expansion.

**Comment by kybos** [comment]
Is this still relevant? I remember reading somewhere that we don't use a custom lilv version any more.

**Comment by spamatica** [comment]
Indeed, I think you are right. 
There are lots of similar load errors on my system though... I have no clue why they settled on the ttl (Turtle?) format for lv2... I don't know much about it but it seems error prone..

**Comment by spamatica** [comment]
Reading the text again, this doesn't really seem because of ttl, anyways it is not in MusE's scope of problems.
And I still don't like ttl format ;)

**Comment by terminator356** [comment]
Wow, an error form 2016, I'll get right on it ;-)

Turtle is OK, it is just so damn foreign and complex to anyone coming at it from
 a C++ background. All of a sudden you have to learn rdf, tuples, doaps, and so on.
It is usually the plugin's fault when there's an error.
Witness the few recent Guitarix plugins missing ttl files (author fixed or is fixing that).
