### ISSUE TITLE
Invert phase

### ISSUE THREAD

**Issue by mekanix** [muse-sequencer/muse#500]
It would be really useful to have "Invert Phase" feature. Is it planned for version 3, perhaps? In the mean time, is there a plugin to achieve this? Thank you!

**Comment by spamatica** [comment]
Hello Goran,

this hasn't been considered yet but it's a good idea so we'll see if we can
take care of it.

In the meantime I saw I had a plugin Inverter (both LADSPA and LV2) that
supposedly does this.

/Robert


2016-03-27 20:23 GMT+02:00 Goran Mekić <notifications@github.com>:

**Comment by mekanix** [comment]
Thank you very much for this info!
