### ISSUE TITLE
Loop recording

### ISSUE THREAD

**Issue by mekanix** [muse-sequencer/muse#501]
I might not understand the transport window buttons, but shouldn't "Overdub" for "Rec Mode" and "Normal" for "Cycle Rec" give multiple audio clips on the same position? I tried looking up the docs and search, I can not find what's expected behavior for combinations of those buttons. Can you clarify, please?

**Comment by spamatica** [comment]
I think Rec mode allows to record several times to the same part when
recording midi.
The other button I actually have to research what it does :P

Regarding what you want, there was a quick rec mode added recently
(CTRL+space) which, when pressed during recording, automatically rewinds to
the previous REC point and records again, to a new part.
There was talk about extending this to automatically create new parts when
loop recording and using this shortcut, but I think it isn't finished yet.


2016-03-28 18:15 GMT+02:00 Goran Mekić <notifications@github.com>:

**Comment by mekanix** [comment]
Loop recording with multiple parts as a consequence would be something really useful to have. I got used to it in similar software so much I can't record without it any more. Are there any plans for it in the version 3?

**Comment by spamatica** [comment]
Den 29 mar 2016 11:11 skrev "Goran Mekić" <notifications@github.com>:
>
> Loop recording with multiple parts as a consequence would be something
really useful to have. I got used to it in similar software so much I can't
record without it any more. Are there any plans for it in the version 3?

It wasn't really cleared up if it was to be implemented, but I will check,
as I understood it should not be a complicated addition.

/Robert

**Comment by mekanix** [comment]
First, CTR+space doesn't work for 2.2.1, or in my setup. Is it version-3 feature? Second, although I'm no expert on DSP and audio, I'd like to contribute. I couldn't find contribution guidelines.

**Comment by spamatica** [comment]
Yes CTRL+space is coming in 3.0 so you need to checkout the git master
version if you want to test.

There is some information on http://muse-sequencer.org/index.php/Helping
but I see it should be updated, quite a lot of old info, about svn etc.

If you feel like helping with coding I recommend subscribing to the devel
mailinglist and ask if there is something unclear.

In general we do not have any strict guidelines. If you make fixes etc,
making pull requests on github is probably the best way to submit fixes but
we can take patches over mail too.

Regards,
Robert



2016-03-29 13:28 GMT+02:00 Goran Mekić <notifications@github.com>:

**Comment by spamatica** [comment]
I've been taking a look at loop recording to multiple parts and adapted the mentioned shortcut to be triggered upon loop end, there is a problem with timing however that I'm not sure will be so easy to overcome, so I'm not sure this will make it into the release..
