### ISSUE TITLE
muse could Multi Instruments  and/ or split keybaord pluging 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#503]
this just rough idea I the video explains it better.
https://youtu.be/YA-ODMD19as?t=3m50s

**Comment by spamatica** [comment]
Hi Reaper10,

interesting idea.
Implementing something like this, on the level of functionality as
displayed here will probably require to much work to be feasible but some
easier solutions might be possible. Like allowing to select several targets
for the Midi Track Output, atleast in the gui it's pretty much prepared for
it. Might be a bit harder under the hood.

Allowing for separate track-info settings (like transposing, panning) for
the individual synths doesn't map well with how MusE displays stuff now so
that seems hard. Apart from transposing most settings should be available
on the soft synth though.


2016-04-20 20:04 GMT+02:00 Reaper10 <notifications@github.com>:

**Comment by terminator356** [comment]
On April 20, 2016 12:13:47 PM spamatica wrote:
> Hi Reaper10,
> 
> interesting idea.
> Implementing something like this, on the level of functionality as
> displayed here will probably require to much work to be feasible but some
> easier solutions might be possible. Like allowing to select several targets
> for the Midi Track Output, atleast in the gui it's pretty much prepared for
> it. Might be a bit harder under the hood.
> 
> Allowing for separate track-info settings (like transposing, panning) for
> the individual synths doesn't map well with how MusE displays stuff now so
> that seems hard. Apart from transposing most settings should be available
> on the soft synth though.

Gee, I thought every pro DAW has features like that these days. No?

Would it surprise you that I'm on top of some of this stuff?
I have been carefully considering the very same things for MusE.

We have almost everything we need in place.

For example the effects rack:

We already have a system for duplicating plugins across channels.
For example if a track is stereo and a plugin is mono, MusE duplicates 
 the plugin for each channel.

What I have been considering is to allow the exact plugin to be
 chosen for /each/ channel.

One challenge is exposing /each/ plugin's set of controls instead
 of /sharing/ them with just one set of controls like we do now.
This is what I've been working on (plans) lately.

And allowing parallel or series combination of plugins is definitely a 
 good idea I would like to see.

As for the synths:

The architecture is identical to the effect racks (it's part of 
 the same system). 
But we never included the same duplication scheme above
 for synths, thus you can see that one cannot change a synth
 track from mono to stereo or vice versa.
That fact has always been in the back of mind.
That we should someday fix that. Perhaps sooner, now.
It is certainly do-able with some effort. It should have been done.

@Robert: Yes you hit the nail on the head with the multiple 
 midi track output routes. We only allow a single output route
 at the moment.
A lot under the hood is now /prepared/ for multiple midi track output routes.
But you know the only thing that has so far stopped me from finishing it?
The /presentation/ of the information, as you say.
It's tricky. We want it to be inclusive but not cumbersome to use.

Werner's original MusE-2 had multiple midi track output routes
 and I saw how he implemented the display of the information,
 so I know some of the challenges.

A note about keyboard splitting:
If I recall, MusE can do it using the Midi Transformator dialog.
You can direct ranges of notes towards different midi ports and channels.
Just not quite as advanced as per-instrument as shown in the video.

Tim.

**Comment by spamatica** [comment]
2016-04-21 19:26 GMT+02:00 Tim <notifications@github.com>:

> On April 20, 2016 12:13:47 PM spamatica wrote:
> > Hi Reaper10,
> >
> > interesting idea.
> > Implementing something like this, on the level of functionality as
> > displayed here will probably require to much work to be feasible but some
> > easier solutions might be possible. Like allowing to select several
> targets
> > for the Midi Track Output, atleast in the gui it's pretty much prepared
> for
> > it. Might be a bit harder under the hood.
> >
> > Allowing for separate track-info settings (like transposing, panning) for
> > the individual synths doesn't map well with how MusE displays stuff now
> so
> > that seems hard. Apart from transposing most settings should be available
> > on the soft synth though.
>
> Gee, I thought every pro DAW has features like that these days. No?
>
> Would it surprise you that I'm on top of some of this stuff?
>

Haha, you seem to be working on the whole shebang at once? ;)

Sounds cool though, seems I shouldn't be so fast at rejecting =)

/Robert

**Comment by Reaper10** [comment]
@terminator356 mention a effects rack witch i have made icon you can use it for the effects rack
the icon
![effects rack](https://user-images.githubusercontent.com/8137561/33354788-20c6d088-d47a-11e7-86a9-34b1fc84df7c.png)
[fx track icon.zip](https://github.com/muse-sequencer/muse/files/1512340/fx.track.icon.zip)
