### ISSUE TITLE
Native GUI of Calf Organ shows GUI of main window of MusE

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#506]
Hi,

I detected the following behaviour in MusE in version 3.0pre1 on a Ubuntu Studio 14.04.4 LTS machine.

Steps to reproduce the behaviour:
1. Create a new, empty song
2. Create a Midi track 
3. Create a track with the LV2 synth Calf organ.
4. Ensure that the Midi track is connected to the Calf organ.
5. Open the native GUI of the Calf organ.

The window with the native GUI of the Calf organ shows only a part of the GUI of the Calf organ. The rest in this window shows the GUI of the main window of MusE (see attached screenshot). MusE needs to be killed with the "kill" command on a virtual console in order to regain control over the machine. 

Regards,

Jens
![screenshot](https://cloud.githubusercontent.com/assets/16398560/14949998/b6ce0304-104e-11e6-8dad-73367eac8446.png)

**Comment by jensplixplox** [comment]
All other Calf synths either show a similar or the same behaviour. If the native GUI of Calf Wavetable is opened, MusE disappears from the screen.

**Comment by spamatica** [comment]
Hi Jens,

2016-05-03 8:54 GMT+02:00 jensplixplox <notifications@github.com>:

> All other Calf synths either show a similar or the same behaviour. If the
> native GUI of Calf Wavetable is opened, MusE disappears from the screen.
>

Seems the Calf guis do exhibit some wierd things, like the crash problems
Tim reported.
Would you mind trying to open the calf-gui with another host, like qtractor
and see if it works there?

/Robert

**Comment by jensplixplox** [comment]
Hi Robert,

I tested the Calf synths with Qtractor in version 0.5.11. This version is from the Ubuntu Studio repositories.

The following Calf synths properly show their GUI's in Qtractor:

- Calf Fluidsynth
- Calf Monosynth
- Calf Organ

The following Calf synth caused Qtractor to disappear from the screen when I tried to open its GUI (GUI not displayed):

- Calf Wavetable

The following Calf synth caused Qtractor to freeze after I opened its GUI:

- Calf Organ

Regards,

Jens

**Comment by jensplixplox** [comment]
I successfully could open the GUI's of all Calf synths which I mentioned in this issue before in MusE version 2.2.1 - their GUI's are properly displayed.

**Comment by jensplixplox** [comment]
In my MusE installation, Global Settings > GUI Behaviour, the "LV2 UI Open behaviour" is set to "Use first available".

I changed this setting to "Ask always" and restarted MusE 3.0 pre-release.

I then opened the native GUI of the Calf Fluidsynth, but in that moment I was not asked which GUI should be displayed. Instead, the GUI of the Calf Fluidsynth is completely displayed, but additionally to this GUI a part of the main window of MusE is displayed in the upper left corner of the screen. Refer to the attached screenshot.

I then opened the native GUI of the Calf Monosynth, but in that moment I was not asked which GUI should be displayed. The GUI of the Calf Monosynth is wrongly displayed, as before my change in Global Settings. Refer to the attached screenshot.

I did not test the other Calf synths and Calf effects which I tested before in the context of this issue because testing the Calf Fluid- and Monosynth resulted in a erroneous behaviour.
![calf_fluidsynth](https://cloud.githubusercontent.com/assets/16398560/15118888/716139b0-160e-11e6-85ef-2230f42048c6.png)
![calf_monosynth](https://cloud.githubusercontent.com/assets/16398560/15118890/7554baec-160e-11e6-9465-1f9775082807.png)

**Comment by spamatica** [comment]
Hello Jens,

2016-05-09 17:50 GMT+02:00 jensplixplox <notifications@github.com>:

> In my MusE installation, Global Settings > GUI Behaviour, the "LV2 UI Open
> behaviour" is set to "Use first available".
>
> I changed this setting to "Ask always" and restarted MusE 3.0 pre-release.
>
> I then opened the native GUI of the Calf Fluidsynth, but in that moment I
> was not asked which GUI should be displayed. Instead, the GUI of the Calf
> Fluidsynth is completely displayed, but additionally to this GUI a part of
> the main window of MusE is displayed in the upper left corner of the
> screen. Refer to the attached screenshot.
>
I installed UbuntuStudio in a virtual machine and I can reproduce this
problem. The cal guis show up OK but there is graphic corruption the same
size as the window but on another place of the screen, as you show.

I saw that Tim is updating the support lib for LV2, not entirely sure what
that contains but maybe we should retry this when that is done.

I can't reproduce the previous problem with showing only parts of the gui.
It could be that they are related though, or possibly your graphics driver,
there are several to chose from with AMD I think and none is perfect.

> I then opened the native GUI of the Calf Monosynth, but in that moment I
> was not asked which GUI should be displayed. The GUI of the Calf Monosynth
> is wrongly displayed, as before my change in Global Settings. Refer to the
> attached screenshot.
>
Yeah it doesn't seem to ask anymore I will have to verify if this is right.

/Robert

**Comment by spamatica** [comment]
For completeness I tried UbuntuStudio 16.04 also and it has the same crash
bug as all other 16.04 derivatives so it's not an option at the moment
either..


2016-05-12 16:50 GMT+02:00 Robert Jonsson <spamatica@gmail.com>:

> Hello Jens,
>
> 2016-05-09 17:50 GMT+02:00 jensplixplox <notifications@github.com>:
>
>> In my MusE installation, Global Settings > GUI Behaviour, the "LV2 UI
>> Open behaviour" is set to "Use first available".
>>
>> I changed this setting to "Ask always" and restarted MusE 3.0 pre-release.
>>
>> I then opened the native GUI of the Calf Fluidsynth, but in that moment I
>> was not asked which GUI should be displayed. Instead, the GUI of the Calf
>> Fluidsynth is completely displayed, but additionally to this GUI a part of
>> the main window of MusE is displayed in the upper left corner of the
>> screen. Refer to the attached screenshot.
>>
> I installed UbuntuStudio in a virtual machine and I can reproduce this
> problem. The cal guis show up OK but there is graphic corruption the same
> size as the window but on another place of the screen, as you show.
>
> I saw that Tim is updating the support lib for LV2, not entirely sure what
> that contains but maybe we should retry this when that is done.
>
> I can't reproduce the previous problem with showing only parts of the gui.
> It could be that they are related though, or possibly your graphics driver,
> there are several to chose from with AMD I think and none is perfect.
>
>> I then opened the native GUI of the Calf Monosynth, but in that moment I
>> was not asked which GUI should be displayed. The GUI of the Calf Monosynth
>> is wrongly displayed, as before my change in Global Settings. Refer to the
>> attached screenshot.
>>
> Yeah it doesn't seem to ask anymore I will have to verify if this is right.
>
> /Robert
>

**Comment by jensplixplox** [comment]
I just compiled and installed MusE 3.0.0pre1 from git master from 2016-06-16. My MusE installation has now internal (built-in) LV2 libraries.

The behaviour, as described in comment 1 and 2 of this issue description, still exists in Ubuntu Studio 14.04.4

**Comment by jensplixplox** [comment]
Robert wrote:

> I can't reproduce the previous problem with showing only parts of the gui. It could be that they are related though, or possibly your graphics driver, there are several to chose from with AMD I think and none is perfect.

I am not using a proprietary driver for my graphics card. The graphics card driver I am using is the package xserver-xorg-video-radeon. And, as far as I can remember, there is no working proprietary driver for my card existing because the proprietary drivers of the manufactor of my graphics card are too old, i.e. they are incompatible with the version of xorg installed in my Ubuntu Studio installation: xorg is too new for these proprietary drivers.
