### ISSUE TITLE
reMID (LV2) preset file selector doesn't show

### ISSUE THREAD

**Issue by danboid** [muse-sequencer/muse#507]
MusE can load reMID fine but there is currently no way to load new presets because there is no file selector displayed in the plugin window, at least not one for loading reMID instruments, as is the case under Ardour.

https://github.com/ssj71/reMID.lv2

**Comment by danvd** [comment]
Hi Dan,

This feature requires LV2 Patch support (http://lv2plug.in/ns/ext/patch/) which is not implemented in muse right now. reMID is the first plugin that uses this feature (at least it's the first one where this spec makes sence).

In reMID, instrument file property duplicates preset property which is supported by muse, but there are not all presets visible.
To fix this, you can open remid.ttl file and add preset block to the end, just like this:

<http://github.com/ssj71/reMID.lv2/blob/master/instruments/subsynth.conf>
	a pset:Preset ;
	lv2:appliesTo <http://github.com/ssj71/reMID.lv2> ;
	rdfs:label "subsynth" ;
	state:state [
		<http://github.com/ssj71/reMID.lv2/blob/master/instruments/instruments.conf> <subsynth.conf>
	] .

(this example adds missing subsynth.conf patch to the presets list)

This is a hack, but lv2 patch spec is a big deal for now. May be I'll have time to implement it near the end of this year :).

Or may be someone else whishes to do this job? ;)

Regards,
Andrew
