### ISSUE TITLE
build Helm into muse 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#512]
Could someone build Helm into muse?
https://github.com/mtytel/helm

**Comment by spamatica** [comment]
Though it would be nice to have as a default, I don't think this will happen. 
Helm is not finished and if it were to be incorporated we would have to update "our version" to keep up with the master version, a lot of work with marginal benefit.
Better to have the package handling system of the distribution handling this. There are several package repositories for various distributions that does a good job at keeping up to date with the latest audio software releases.
