### ISSUE TITLE
Visible/invisible toolbar & button states should be remembered

### ISSUE THREAD

**Issue by ViktorNova** [muse-sequencer/muse#515]
By default, MusE displays A LOT of toolbars and buttons, cluttering up the interface. 
Disabling the ones I don't need makes the UI a lot more pleasant and less distracting, but some of the toolbars come back as soon a MusE is restarted

  - Song position bar (the most annoying of the 3)
  - Panic button
  - Metronome button

**Comment by spamatica** [comment]
I think this is fixed now, there was an oversight in the configuration storage.
Closing. Please reopen if you think differently.

**Comment by ViktorNova** [comment]
PERFECT
thank you! it's fixed
