### ISSUE TITLE
Arranger view should be a permanent part of the top-level window

### ISSUE THREAD

**Issue by ViktorNova** [muse-sequencer/muse#516]
One of the only things that makes MusE seem weird compared to other DAWs is the fact that the top level window is not the timeline sequencer, or Arranger View. The fact that this can be closed or minimized or moved off-canvas is very strange and could be confusing to new users

Even if MusE keeps the Windows 3.1 desktop style of subwindows, it would be a huge UX improvement if the Arranger permanently was the top level window, and was un-closeable/un-movable/un-minimizable, always shared a menu with the top-level window, and was forced to always be on the bottom so that no other subwindows are ever covered by it (this also can get confusing) 

(This is one of the changes that OpenOctave MIDI made which made their fork of MusE feel inviting and user friendly)

**Comment by GraysonPeddie** [comment]
I concur. I thought I've lost my song when I do Ctrl+S but my ring finger hit W which closed the arranger. Fortunately, going to View > Arranger View saved my grief. Honestly, this does not make any sense and once it's permanent, the Arranger View should be made obsolete.

**Comment by terminator356** [comment]
On Thursday, August 11, 2016 4:00:52 PM EDT Grayson Peddie wrote:
> I concur. I thought I've lost my song when I do Ctrl+S but my ring finger
> hit W which closed the arranger. Fortunately, going to View > Arranger View
> saved my grief. Honestly, this does not make any sense and once it's
> permanent, the Arranger View should be made obsolete.

Just want to pipe in for a quick response, quite busy here.

Have you tried Global Settings -> GUI Style ?

There are three major GUI styles available:
You can have standard 'traditional' style, 'Cakewalk' style,
 and 'Mac/Borland' style.

The usefulness of a /separated/ Arranger View will become apparent
 for example when you try the 'Mac/Borland' style.

You may want to close/reopen all windows, even Arranger View, 
 for the new settings to take full effect - the new settings affect all 
 newly opened windows, I think.

Also, regarding the look and feel discussions popping up here, 
 has anyone tried the 'dark' and 'Ardour' style sheets in 
 Appearance Settings?

Throw it on 'dark' for a completely new look.

Tim.

**Comment by ViktorNova** [comment]
@terminator356 
I understand how this could be useful to some people who are used to a certain workflow or people who want to get more advanced in their window setup.. I totally get it. 

I guess what I'm saying is that to someone coming to MusE from _any_ other DAW, this behaviour is unintuitive and feels clunky. I suggest a new mode in addition to Borland/Cakewalk/etc that emulates the feel of normal DAWs more closely, and keeps the Arranger as the top level window, without the ability to close it, and perhaps setting this mode as the default, and let the advanced MusE users choose the workflow that suits them more.

This would make MusE much friendler to newcomers

**Comment by kybos** [comment]
This is old but still perfectly valid.
The problem affects all the "GUI styles" (standard/Cakewalk/Borland) in the same manner.
I don't see any reason why the Arranger window should be closeable and the empty main window displayed instead.
@terminator356 
I think what you wrote above was a misunderstanding, the problem has nothing to do with the individual GUI styles (or perhaps I am on the wrong track...).
Is it OK to make the arranger fixed? If there is a reason not to, the we should at least have an option to do so.

**Comment by kybos** [comment]
Changed in master.
When the arranger is a subwindow (i.e. default SDI and Cakewalk GUI styles), then it is fixed to the main window now to avoid confusion for new users (I ran into this problem myself so I know ;-) ). 
For the Borland style (arranger is not a subwindow) Tim is probably right that the separation makes sense, so this continues to work as before.

**Comment by kybos** [comment]
In the new tabbed GUI design, Arranger is now definitely fixed and can't be closed.
