### ISSUE TITLE
mixer fx chain redo

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#521]
I just can mixer fx chain redo
![mixer](https://cloud.githubusercontent.com/assets/8137561/17086834/bef8507a-51c1-11e6-8dd2-6d97cb14eab5.png)
<img width="846" alt="untitled" src="https://cloud.githubusercontent.com/assets/8137561/17087047/915506b8-51c6-11e6-82bc-1154d8a75eef.png">
list of new FX controls for fx chains 
1. FX amount knob 
2. FX amount readout
3. FX on/ off button 
all of these  FX controls should be automatable
more  FX slots or unlimited  FX slots and way to save and recall FX chains

**Comment by spamatica** [comment]
Hello, I'm not entirely sure what you mean with the first sentence.

Fx on/off is available in the right click menu on the effect (called
Bypass). If you want to control the amount of effect please try an Aux
track. Then you will get a knob on all strips to control the amount that
goes to the Aux.
Usually this is what you use with e.g Reverb, which also is a prime
candidate for reusing the effect on several tracks.

Regards,
Robert


2016-07-25 0:46 GMT+02:00 Reaper10 <notifications@github.com>:

**Comment by Reaper10** [comment]
Sorry about this I use windows 10 so I can't try it yet but what about more FX slots or unlimited FX slots and way to save and recall FX chains?

**Comment by terminator356** [comment]
> Sorry about this I use windows 10 so I can't try it yet but what about more FX slots or unlimited FX 
> slots and way to save and recall FX chains?

Hi, the saving FX chains idea is cool. Currently we can store and recall individual effects
 but not chains. It should be a relatively smooth thing to add... at some point...

About the number of effects slots: Yes, I feel your pain.
I've been caught many times at final mix time, wishing there was at least one more rack slot.

Here's the situation: 
In muse/globaldefs.h there is currently an **absolute** maximum of slots, defined by this value:
  const int MAX_PLUGINS  = 8;  // (This value must never change!)

We currently don't use all 8 slots. For historical and space reasons it was always 4.
So the current actual number of slots used, a fixed value, is this one:
const int PipelineDepth = 4;  // plugins in mixer rack, max up to MAX_PLUGINS

But the _intention_ was always to one day **increase** that number from 4
 to something up to 8. 
Note: That day may come soon... I had plans to increase the number,
 given the recent mixer strip changes.

So, that's our fixed number of slots.
Much better to have unlimited, I know, but that's the way it is right now.
There are some very tricky things tied to our maximum fixed number. 
Unlimited would be very hard to do for us right now... but maybe someday.

Note: You may _increase_ that fixed number if you wish, for personal use,
 up to 8. Be careful about saving and then opening in an older muse though -
 the extra plugins and any controller graph data would be discarded.
Too many rack slots makes the rack too big so I need to work on the rack 
 sizing and add scrollbars and so on...
Might want to wait 'till we decide when to increase and by how much.

Thanks. 
Tim.

**Comment by Reaper10** [comment]
a new fx channel track #535

**Comment by Reaper10** [comment]
. FX chains window could look and function similar to this https://www.youtube.com/watch?v=YA-ODMD19as except muse needs unlimited number of spits. When
