### ISSUE TITLE
taking over OpenOctave 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#523]
Muse should take over OpenOctave  code
https://github.com/ccherrett/oom
there is a lot of stuff muse could use

you could use OpenOctave mixer gui mixed your 
![mixer-dock-show-fx](https://cloud.githubusercontent.com/assets/8137561/17257475/e8b2356a-5587-11e6-8285-eb3b48439a9d.png)
With OpenOctave mixer gui mixed your mixer gui will part of the way fix #521 and part of the way fix #518 
![mixer-dock-full](https://cloud.githubusercontent.com/assets/8137561/17257486/f0975fc6-5587-11e6-9dbb-f7021311b10d.png)
![mixer-dock-menu](https://cloud.githubusercontent.com/assets/8137561/17257487/f536873c-5587-11e6-8e42-9419db71b3a2.png)
![mixer-dock-show-aux](https://cloud.githubusercontent.com/assets/8137561/17257494/fa6b3b12-5587-11e6-9c2c-f8b70a231495.png)

With the OpenOctave  mixer there could a group of buttons to show/hide the Built-in parametric EQ and Compressor/limiter for all audio-producing tracks #440

The OpenOctave code base will help make the audio and midi mixers one mixer
https://github.com/ccherrett/oom/wiki/Mixer-Window
https://github.com/ccherrett/oom/wiki/Tracks
![mixer-window-rows](https://cloud.githubusercontent.com/assets/8137561/19214939/e2984222-8d55-11e6-8641-9097fdc001c6.gif)
![track-header-midi-new](https://cloud.githubusercontent.com/assets/8137561/19214941/ef412ed0-8d55-11e6-8aa0-beb48c57634d.png)

With OpenOctave track list gui could fix #514 and #518 

![687474703a2f2f7777772e6f70656e6f63746176652e6f72672f73697465732f64656661756c742f66696c65732f747261636b2d686561646572732e706e67](https://cloud.githubusercontent.com/assets/8137561/17258450/88d4f3a8-558c-11e6-9419-82bd09fbf5be.png)

With OpenOctave audio track could fix #513 and #518
![working-audio-fades-1](https://cloud.githubusercontent.com/assets/8137561/17259453/29d04128-5591-11e6-97e7-6c2075b497e3.png)
not to mention midi clips
![patch-seq-1](https://cloud.githubusercontent.com/assets/8137561/17261433/4b382236-559b-11e6-85e4-8807912d7bf9.gif)
and also #525 
![keyswitch-dialog-2](https://cloud.githubusercontent.com/assets/8137561/18060329/496f631e-6de3-11e6-9f0d-ae9f65315cbe.png)

OpenOctav could fix #519
![tracklist-workingview-1](https://cloud.githubusercontent.com/assets/8137561/17258359/16ff1a38-558c-11e6-8e76-c8960e7dcee5.gif)
https://github.com/ccherrett/oom/wiki/Instrument-Sets
![instrument-editor-list](https://cloud.githubusercontent.com/assets/8137561/19214971/a51e3cac-8d56-11e6-9812-79e56ad40674.png)

quick audio editing in main window like this
https://www.youtube.com/watch?v=K0iBhsBxX08
and this
https://www.youtube.com/watch?v=LjnL3pMxS5c
![crossfades-1](https://cloud.githubusercontent.com/assets/8137561/17263735/45dd82d8-55a8-11e6-94d7-96cf94e6d6f9.png)
![crossfades-2](https://cloud.githubusercontent.com/assets/8137561/17264124/a32e1ad6-55aa-11e6-81d8-0476c666c8d2.png)

![working-audio-fades-1](https://cloud.githubusercontent.com/assets/8137561/17263741/4f45f29c-55a8-11e6-8c51-859971f38b03.png)
OpenOctave can help here two
https://github.com/ccherrett/oom/wiki/Working-with-Audio

simplify Automation like this
https://www.youtube.com/watch?v=CL63VJxvM0w
OpenOctave can all so help here two
https://github.com/ccherrett/oom/wiki/Automation
![auto-select-nodes](https://cloud.githubusercontent.com/assets/8137561/19204728/137089d4-8ca4-11e6-8156-b6aa7da3d6c5.gif)

OpenOctave can help with completely dockable UI, multiple view presets #345 

https://github.com/ccherrett/oom/wiki/The-Composer
![composer-main-canvas](https://cloud.githubusercontent.com/assets/8137561/19214512/7ba85232-8d4b-11e6-860b-ef75b6505ff5.png)

Combining muse and OpenOctave together could be the start to a free and open source alterative to Adobe Audition. / Digital Performer / studio one / mixbus / cakewalk sonar.  Doing this all so keep OpenOctave  alive. I think the best thing for muse is to blend all the other for mentioned DAW with muse will make muse the best pro level free DAW.

**Comment by GraysonPeddie** [comment]
First, what I can say is that could require a lot of work, but I could definitely see MusE Sequencer start to become a fully-fledged Digital Audio Workstation. In my opinion, I really think MusE should strongly focus on MIDI work, as I would use Harrison Mixbus for audio work, once converted from MIDI. I don't know about MusE developers, but it would probably be in the 4.0 milestone, though.

It's quite a letdown to see the development of OpenOctave stalled.
