### ISSUE TITLE
default gui for vst

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#524]
Dose muse have a default gui for vst and vsti? Some of my vst vsti don't have there own gui

**Comment by spamatica** [comment]
MusE allows you to open the plugins native gui if it exists. If you right click on the synth in the port column you can select which you want to open. 
Usually it is the native, but may want the muse-gui to bind parameters to midi.

**Comment by therealkitman** [comment]
Hi,
If it is of any interest I use the pre-compiled carla lv2 plugin from http://kxstudio.linuxaudio.org/Applications:Carla in Muse. Then I can open all my old Windows vst-i with their own gui via carla.
Regards...

**Comment by Reaper10** [comment]
Some of my vst don't have there own gui

**Comment by spamatica** [comment]
MusE has a default gui when the plugin does not have a gui

2016-10-02 0:55 GMT+02:00 Reaper10 <notifications@github.com>:
