### ISSUE TITLE
Muse crash on track cut with scissors

### ISSUE THREAD

**Issue by jphaenlin** [muse-sequencer/muse#526]
Muse crashes when trying to cut a track after having changed the tempo in the master track.
How to reproduce:
make a midi track from 5.1.0 to 13.1.0
change the tempo at 1.1.0 from 120 to 140 in the master track
(as side effect we see that the right and left locators are lost, if we want to go to locators, the cursor doesn't go on the blue lines on the arranger)
use the scissor (c key), try to cut at 9.1.0
-> crash

**Comment by GraysonPeddie** [comment]
I tried following your steps but could not reproduce the crash. I built muse3 from AUR and I'm currently running 3.0.pre1-3.

**Comment by jphaenlin** [comment]
I'm using release V3.0pre1 from Github. Fedora 24, XFCE, GCC V6.1.1.
Have you reproduced the problem with the locators? 
I assume the keys 1 and 2 are affected to left and right locators, after a change of tempo in the master track at position 1.1.0, the 1 and 2 keys don't move the cursor to the good locations.
I think some recalculations are missing when the tempo is changed, and it explains the crash.

**Comment by terminator356** [comment]
Verified. Apologies for the delayed response.
Will try to fix at some point. Stay tuned...

**Comment by terminator356** [comment]
Should be fixed in master now. Seemed an old bug.
Thanks for the clear instructions. It was likely to have crashed regardless of changing the tempo.
Merely having the Master List open should have also caused the crash.

Oh, forgot to check locators... will do. Lemme know if no reply and still not OK.
