### ISSUE TITLE
Midi Note Labeling (again)

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#528]
Hi,
after a long absence from anything musical I have started playing with Muse (V3 Pre1) again. In #372 I submitted last year I complained about the labeling of notes in the piano roll being out by an octave.

I downloaded a midi file from https://freemidi.org/download-22129-mull-of-kintyre-paul-mccartney?PageSpeed=noscript to experiment with on my virtual guitar via Muse. Now while both Muse and Tuxguitar play the midi file correctly and hit the right notes on the guitar. I noticed that the musical score in Muse is out by 1 octave. See screen shot.

![spectacle w10230](https://cloud.githubusercontent.com/assets/14888092/17659111/09fff7c4-6303-11e6-8e8a-41b3f28ea76d.png)

Look at the first note in bar 36 taken from track 3 in the midi file - it is D4 and plays like that. Tuxguitar scores it as D4 while Muse scores it as D3. Surely that is wrong, as is the pianoroll labeling, if my score notation is out?

Regards,
Chris.

**Comment by terminator356** [comment]
On Monday, August 15, 2016 1:24:59 AM EDT therealkitman wrote:
> Hi,
> after a long absence from anything musical I have started playing with Muse
> (V3 Pre1) again. In #372 I submitted last year I complained about the
> labeling of notes in the piano roll being out by an octave.
> 
> I downloaded a midi file from
> https://freemidi.org/download-22129-mull-of-kintyre-paul-mccartney?PageSpee
> d=noscript to experiment with on my virtual guitar via Muse. Now while both
> Muse and Tuxguitar play the midi file correctly and hit the right notes on
> the guitar. I noticed that the musical score in Muse is out by 1 octave.
> See screen shot.
> 
> ![spectacle
> w10230](https://cloud.githubusercontent.com/assets/14888092/17659111/09fff7
> c4-6303-11e6-8e8a-41b3f28ea76d.png)
> 
> Look at the first note in bar 36 taken from track 3 in the midi file - it is
> D4 and plays like that. Tuxguitar scores it as D4 while Muse scores it as
> D3. Surely that is wrong, as is the pianoroll labeling, if my score
> notation is out?
> 
> Regards,
> Chris.

Octave labelling has been discussed lately so we are studying it.
There are no, or confusing standards, or differing user needs, 
 therefore many DAWs have selectable ocatve labeling. 
I have a few ideas on the back burner...

If I recall, our current labeling does not follow the midi octave numbers, 
 the original author may have been trying to align the octave numbers 
 with a regular musical staff or something.

Tim.

**Comment by therealkitman** [comment]
Hi Tim,
I installed Musescore last night and it's score notation was in line with Tuxguitar. While I appreciate different DAWs may do different things in the pianorolls (I reread the comments from last year) I would have expected any printed score to be consistent in all programs.
Say I write something that sounds right to me in regard of octaves and print the score and give it to a another person - they'd play an octave out reading it?
Regards,
Chris.
