### ISSUE TITLE
No midi contoller events get sent to external device

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#530]
**muse3.0.0pre1 (self-compiled for 64 bit)**

I just noticed that the volume and pan setting do not seem to have any effect on external midi devices. As far as I can tell with kmidimon no events are emitted when I change volume or pan. 

When I "draw" controllers, then Volume still doesn't work and Pitch Bend also has no effect. It looks like no controller makes it. 

I tried with two different devices and two different ALSA midi interfaces.

Note-on/off events and program changes work okay and controllers do work with softsynths, just not with external devices.

I wonder if I misconfigured something or if this is a genuine bug.

**Comment by drautzburg** [comment]
I ran some more checks:

When I connect Rosegarden to kmidimon, I can see the faders produce controller events in kmidimon.

When I start muse with -M (muse3 -A -J -N -I -L -M) and move the faders, stdout shows things like

```
ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7 b=112
running paint event highlight 0
ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7 b=111
```

However, nothing appears in kmidimon

**Comment by drautzburg** [comment]
Sorry, I accidentally closed this. Reopening.

**Comment by terminator356** [comment]
On Wednesday, August 17, 2016 9:38:49 AM EDT Martin Drautzburg wrote:
> I ran some more checks:
> 
> When I connect Rosegarden to kmidimon, I can see the faders produce
> controller events in kmidimon.
> 
> When I start muse with -M (muse3 -A -J -N -I -L -M) and move the faders,
> stdout shows things like
> 
> ```
> ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7
> b=112 running paint event highlight 0
> ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7
> b=111 ```
> 
> However, nothing appears in kmidimon

Hm, by gosh you are right.

I probably broke something with all the changes recently.
Hang in there, will check what's going on, or not...

Tim.

**Comment by terminator356** [comment]
On Wednesday, August 17, 2016 3:12:53 PM EDT you wrote:
> On Wednesday, August 17, 2016 9:38:49 AM EDT Martin Drautzburg wrote:
> > I ran some more checks:
> > 
> > When I connect Rosegarden to kmidimon, I can see the faders produce
> > controller events in kmidimon.
> > 
> > When I start muse with -M (muse3 -A -J -N -I -L -M) and move the faders,
> > stdout shows things like
> > 
> > ```
> > ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7
> > b=112 running paint event highlight 0
> > ALSA MidiOut pre-driver: <KMidimon>: time:0 port:0 chan:1 type:0xb0 a=7
> > b=111 ```
> > 
> > However, nothing appears in kmidimon
> 
> Hm, by gosh you are right.
> 
> I probably broke something with all the changes recently.
> Hang in there, will check what's going on, or not...
> 
> Tim.

Fixed in git master.

Misplaced return statement.
Sorry about that, folks.

Please keep an eye out for anything unusual,
 it is especially important these days since I did major 
 changes to ALSA and Jack code in the last several months.

Thank you for reporting!

Awaiting response.
Tim.

**Comment by drautzburg** [comment]
Just git pulled, recompiled and it works now.
