### ISSUE TITLE
5.1 send sound 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#538]
5.1 send sound support

**Comment by terminator356** [comment]
Can you do us a wee favour?
Can you go back and label some of these requests as nice-to-have 
 or enhancement or bug. It helps sort them.

Thanks.
Tim.

**Comment by Reaper10** [comment]
how do you do that?

**Comment by terminator356** [comment]
On the right side of the github issues page there are Labels.
I think some can only be added by devs but others are for users.
I'm not sure 'cause I'm a dev so I can't check from user's perspective.
Do you see them? Apologies if there are none at all, maybe it's only for us?

Thanks.

**Comment by Reaper10** [comment]
I see them I can't add them I am not dev

**Comment by terminator356** [comment]
Hm, I checked our settings and could not find a way for a user to add them,
 or at least there's no 'user vs. dev' settings, just names and colours...
Sorry about that. Strange. Would have thought there'd be a way. Am I missing something?

**Comment by Reaper10** [comment]
well this is **audio** **and nice to have**

**Comment by terminator356** [comment]
On Thursday, September 29, 2016 10:34:35 AM EDT Reaper10 wrote:
> well this is **audio** **and nice to have**

Ha ha, yep sure is.

So about the 5.1 stuff, currently all our audio tracks, and variants, 
 only support up to a maximum of 2 channels - __except__ for
 synthesizer tracks which can be multi-channel.

True multi-channels tracks (like Ardour for example) are now
 on the horizon and within reach with recent additions,
 although there is still a long way to go.

Once that happens we should be able to 'send' multi-channel as well.

Also multi-channel encoder plugins (AC3 etc.) would finally be usable
 in our effects racks.

Thanks.
Tim.
