### ISSUE TITLE
new website gui

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#539]
Hi I am not programmer but I would like to help by designing a new website gui

**Comment by spamatica** [comment]
Do give us some examples of what you had in mind?

Also note that our website has index.html (static frontpage) and a
mediawiki behind for all other pages. It would be good if the style for the
front page can also be used for the wiki.


2016-09-30 2:26 GMT+02:00 Reaper10 <notifications@github.com>:

**Comment by Reaper10** [comment]
I will can I have the muse font file you used

**Comment by spamatica** [comment]
Hello again, which font do you mean, the logo? I fear the source font for
the logo is lost in time :(

2016-09-30 17:02 GMT+02:00 Reaper10 <notifications@github.com>:

**Comment by Reaper10** [comment]
website mock up it's a Greek arch based on the god of war games the artwork I did 
![muse wabsite](https://cloud.githubusercontent.com/assets/8137561/19096046/21c5cf5e-8a5f-11e6-9577-f311adf1cca2.png)
what dose everyone think?

**Comment by drautzburg** [comment]
You lost me here

**Comment by Reaper10** [comment]
How can I help you understand? With app icon reminds me a lot of the god of war and grepolis  games so you could make the website stand out from all of the other daw's websites. This could all so help bring some new users. Not to mention you use could use this as a opportunity to reorganize the website.
