### ISSUE TITLE
Cannot select multiple tracks

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#546]
This is muse 3.0.0pre1 compiled from source. 

I cannot select multiple tracks in the arranger by holding the Shift key, as described in the manual. Only the last track clicked remains selected.

**Comment by terminator356** [comment]
On Monday, October 31, 2016 2:10:47 AM EDT Martin Drautzburg wrote:
> This is muse 3.0.0pre1 compiled from source.
> 
> I cannot select multiple tracks in the arranger by holding the Shift key, as
> described in the manual. Only the last track clicked remains selected.

Hi, this should be fixed in the git master, as of a few weeks ago.

Use the control key, not shift.

Tim.

**Comment by drautzburg** [comment]
Control Key works for selecting multiple tracks.
