### ISSUE TITLE
Mixer hotky (F10) doesn't toggle

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#547]
This is muse 3.0.0pre1 compiled from source. 

F10 brings up the mixer, but pressing F10 again doesn't make it disappear. This is in contrast to the menu entry "Mixer A   F10" which does toggle the mixer. You would expect the same thing to happen, regardless of whether you invoked that function via menu or via hotkey.

**Comment by drautzburg** [comment]
I just realized that this behaviour is caused by the focus going to the mixer window after pressing F10. The F10 key actually works as expected as long as the arranger window has the focus. However, you cannot press F10 twice in a row and hope for the mixer to appear and disappear.

**Comment by terminator356** [comment]
On Tuesday, November 8, 2016 7:40:42 AM EST Martin Drautzburg wrote:
> I just realized that this behaviour is caused by the focus going to the
> mixer window after pressing F10. The F10 key actually works as expected as
> long as the arranger window has the focus. However, you cannot press F10
> twice in a row and hope for the mixer to appear and disappear.

Hi sorry didn't reply sooner. I confirmed the behaviour. 
Will try to tackle it...

Thanks.
Tim.

**Comment by terminator356** [comment]
Hi, this seems to have cleared up on its own, possibly from recent mixer strip 
 tabbing and key fixes. Are you still getting this problem as of today's git master? 
Thanks. Tim.
