### ISSUE TITLE
MusE sometimes hangs and has to be killed

### ISSUE THREAD

**Issue by oswald2** [muse-sequencer/muse#552]
Unfortunately not very deterministic, but I had this since MusE 2.2.1 and also in current builds (terminal output from git 8f761a062206660cddd3a61e9408a086ccfd60bc

Terminal output when it hangs:

```
sem_timedwait(): Interrupted system call
muse3: ../src/semaphore.cc:152: bool Semaphore::wait(const milliseconds&): Assertion `false' failed.
```

Issue which is probably related: #548 
Although in my case it doesn't crash on startup, it just hangs (sometimes after hours of normal operation).

**Comment by kybos** [comment]
Obsolete, probably fixed.
