### ISSUE TITLE
MusE development version - Help with installation

### ISSUE THREAD

**Issue by budislav** [muse-sequencer/muse#555]
I would like to try new development version 3 but I have a problem with installing it.
Like an artist not a programmer and without any experience in compiling of software this is way too difficult for me because I don't have a detailed instructions. 

In README file https://github.com/muse-sequencer/muse/blob/master/muse3/README
I see a list of websites from those I should need to download and install some files but I don't know which files and how.

I can only install QT development files because I see the command line (sudo apt-get install qt5-default qttools5-dev qttools5-dev-tools). 

Can anyone write command lines for how to install all other things we need? I would be very grateful! 
(I believe that optional stuff are not necessary to run a MusE).
Keep on mind that I have a fresh installed Ubuntu 16.10 and nothing else.

- CMake >= 2.4
- gcc >= 4.x.x or clang >= 2.9
- libsndfile >= 1.0.1 (development files)
- libsamplerate >= 0.1.0 (development files)
- JACK >= 0.103 (development files)
- LADSPA (development file ladspa.h)

**Comment by terminator356** [comment]
On Thursday, January 19, 2017 2:02:36 PM EST Budislav wrote:
> I would like to try new development version 3 but I have a problem with
> installing it. Like an artist not a programmer and without any experience
> in compiling of software this is way too difficult for me because I don't
> have a detailed instructions.
> 
> In README file
> https://github.com/muse-sequencer/muse/blob/master/muse3/README I see a
> list of websites from those I should need to download and install some
> files but I don't know which files and how.
> 
> I can only install QT development files because I see the command line (sudo
> apt-get install qt5-default qttools5-dev qttools5-dev-tools).
> 
> Can anyone write command lines for how to install all other things we need?
> I would be very grateful! (I believe that optional stuff are not necessary
> to run a MusE).
> Keep on mind that I have a fresh installed Ubuntu 16.10 and nothing else.
> 
> - CMake >= 2.4
> - gcc >= 4.x.x or clang >= 2.9
> - libsndfile >= 1.0.1 (development files)
> - libsamplerate >= 0.1.0 (development files)
> - JACK >= 0.103 (development files)
> - LADSPA (development file ladspa.h)

Hey Budislav the Artist.

On Ubuntu this should work get you started:
	sudo apt-get install 
	 build-essential cmake libsndfile1-dev libsamplerate0-dev
	 libjack-jackd2-dev ladspa-sdk

The 'build-essential' meta-package should give gcc and other tools, 
 it is usually best to use that package.

Highly recommended to install:
	 sudo apt-get install synaptic
 a gui for apt, much easier to use when you are 'collecting' packages 
 to install and you are not sure what their package names might be 
 (as in MusE instructions), vs. when you know the exact names.
Synaptic has search tools etc.
(But each major distro has different package tools.)

Generally in Ubuntu 'development' packages end with "-dev"
 but there are exceptions (ladspa-sdk).

I guess I should paste that text into README, eh?

Hope you get it working, try the latest git master, 
 the more testers the better.
I took some of your suggestions and made sliders.
And then I made knobs again. Smaller.
You can switch from knobs to sliders with a popup menu
 by right-clicking any mixer strip, or in Settings.

Tim.

**Comment by budislav** [comment]
Thank you Tim!
I install it without a problem so please copy this instructions to README file. I hope all is correct, those installation instructions are from Andrew.

1. Open terminal and type: 
`sudo apt-get install build-essential cmake libsndfile1-dev libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default qttools5-dev qttools5-dev-tools synaptic`
2. Clone muse source with command: `https://github.com/muse-sequencer/muse.git`
3. Type `cd muse`
4. Make build directory: `mkdir build`
5. Cd to the build directory: `cd build`
6. Run cmake: `cmake ../muse3`
7. Type `make` and wait for some time :)
8. Type `sudo make install` - this will install muse3 to /usr/local
9. Run it by typing `muse3`

We need also instructions for how to update this development version to the latest one.

Now when I run MusE it shows me one problem:
![problem](https://cloud.githubusercontent.com/assets/3619927/22146127/e78be1bc-df03-11e6-90ec-e1a422aabde5.png)
I thought that I installed jack with those commands on the top? There is no sound. How should I fix this?

Also when MusE is opened I don't see how to open mixer and other things. It shows me only arranger menu bar? Where is the rest of software?
![screenshot from 2017-01-20 11-05-36](https://cloud.githubusercontent.com/assets/3619927/22146359/ad6a305a-df04-11e6-8fb7-b205c812e188.png)

I see new sliders and they are incomparably better than knobs! Thank you for accepting this! They should be on by default, it is newer and better solution. :)

I see a lot of UI and more importantly UX problems which needs new solutions. Barely to know how to find anything in this software, I need so much time to learn, and approach is complicated.
I would try to propose solutions again but on easier way for developing and understanding. One by one thing.

**Comment by terminator356** [comment]
On Friday, January 20, 2017 2:57:29 AM EST Budislav wrote:
> Thank you Tim!
> I install it without a problem so please copy this instructions to README
> file. I hope all is correct, those installation instructions are from
> Andrew.
> 
> 1. Open terminal and type:
> `sudo apt-get install build-essential cmake libsndfile1-dev
> libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default qttools5-dev
> qttools5-dev-tools synaptic` 2. Clone muse source with command:
> `https://github.com/muse-sequencer/muse.git` 3. Type `cd muse`
> 4. Make build directory: `mkdir build`
> 5. Cd to the build directory: `cd build`
> 6. Run cmake: `cmake ../muse3`
> 7. Type `make` and wait for some time :)
> 8. Type `sudo make install` - this will install muse3 to /usr/local
> 9. Run it by typing `muse3`
> 
> We need also instructions for how to update this development version to the
> latest one.
> 
> Now when I run MusE it shows me one problem:
> ![problem](https://cloud.githubusercontent.com/assets/3619927/22146127/e78be
> 1bc-df03-11e6-90ec-e1a422aabde5.png) I thought that I installed jack with
> those commands on the top? There is no sound. How should I fix this?

Go ahead and install the Jack server meta package:

	sudo apt-get install jackd

(According to Synaptic, looks like Jack dev package can be installed 
 /without/ the Jack server itself. That's maybe why you've no Jack right now.)

> Also when MusE is opened I don't see how to open mixer and other things. It
> shows me only arranger menu bar? Where is the rest of software?
> ![screenshot from 2017-01-20
> 11-05-36](https://cloud.githubusercontent.com/assets/3619927/22146359/ad6a3
> 05a-df04-11e6-8fb7-b205c812e188.png)

Ouch! 

First, try this older, special MusE -u command line option:
"-u   Ubuntu/unity workaround: don't allow sharing menus
                                     and mdi-subwins. "

If that does not wotk, then this certainly should:
M Oswald reported the same problem:

"I found the issue, it's a known Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619
Solution:
	sudo apt-get remove appmenu-qt5
Then Muse3 has again it's menu. "

Sorry not a very nice solution but it's all we can do right now.

Let me know if the "-u" option worked for you, I am curious whether 
 that is still the proper solution and if it works OK.

Tim.

> I see new sliders and they are incomparably better than knobs! Thank you for
> accepting this! They should be on by default, it is newer and better
> solution. :)
> 
> I see a lot of UI and more importantly UX problems which needs new
> solutions. Barely to know how to find anything in this software, I need so
> much time to learn, and approach is complicated. I would try to propose
> solutions again but on easier way for developing and understanding. One by
> one thing.

**Comment by spamatica** [comment]
2017-01-20 18:20 GMT+01:00 Tim <notifications@github.com>:

> On Friday, January 20, 2017 2:57:29 AM EST Budislav wrote:
> > Thank you Tim!
> > I install it without a problem so please copy this instructions to README
> > file. I hope all is correct, those installation instructions are from
> > Andrew.
> >
> > 1. Open terminal and type:
> > `sudo apt-get install build-essential cmake libsndfile1-dev
> > libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default qttools5-dev
> > qttools5-dev-tools synaptic` 2. Clone muse source with command:
> > `https://github.com/muse-sequencer/muse.git`
> <https://github.com/muse-sequencer/muse.git> 3. Type `cd muse`
> > 4. Make build directory: `mkdir build`
> > 5. Cd to the build directory: `cd build`
> > 6. Run cmake: `cmake ../muse3`
> > 7. Type `make` and wait for some time :)
> > 8. Type `sudo make install` - this will install muse3 to /usr/local
> > 9. Run it by typing `muse3`
> >
> > We need also instructions for how to update this development version to
> the
> > latest one.
> >
> > Now when I run MusE it shows me one problem:
> > ![problem](https://cloud.githubusercontent.com/assets/
> 3619927/22146127/e78be
> > 1bc-df03-11e6-90ec-e1a422aabde5.png) I thought that I installed jack
> with
> > those commands on the top? There is no sound. How should I fix this?
>
> Go ahead and install the Jack server meta package:
>
> sudo apt-get install jackd
>
> (According to Synaptic, looks like Jack dev package can be installed
> /without/ the Jack server itself. That's maybe why you've no Jack right
> now.)
>
> > Also when MusE is opened I don't see how to open mixer and other things.
> It
> > shows me only arranger menu bar? Where is the rest of software?
> > ![screenshot from 2017-01-20
> > 11-05-36](https://cloud.githubusercontent.com/assets/
> 3619927/22146359/ad6a3
> > 05a-df04-11e6-8fb7-b205c812e188.png)
>
> Ouch!
>
> First, try this older, special MusE -u command line option:
> "-u Ubuntu/unity workaround: don't allow sharing menus
> and mdi-subwins. "
>
> If that does not wotk, then this certainly should:
> M Oswald reported the same problem:
>
> "I found the issue, it's a known Ubuntu bug:
> https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619
> Solution:
> sudo apt-get remove appmenu-qt5
> Then Muse3 has again it's menu. "
>
> Sorry not a very nice solution but it's all we can do right now.
>
> Let me know if the "-u" option worked for you, I am curious whether
> that is still the proper solution and if it works OK.


Wow, this is so unbelievably broken...
I just had to see this so I installed ubuntu with unity in a virtual
machine (yay for ISO installs in VMs, took 20 minutes or so).

MusE is completely nonworking under Unity, atleast in my VM. I know we make
some rather complicated menu tricks in MusE but I'm pretty sure we aren't
the only application suffering from their extremely ignorant way of
overriding menus.
The tricks you mention didn't make any difference for me, -u caused the MDI
to break completely. It would be interesting to know how Michael got it
working..

The only way I found to get it to display correctly was to uninstall
indicator-appmenu. But this removes the menu integration for ALL
applications. Suppposedly you should be able to disable the support per
application but I didn't get that to work.

So for now, the only way I see for you to experience MusE under Unity is by
removing indicator-menu, hopefully Michael has some better trick..

By the way.
I would suggest to run this command also before building MusE. It will
enable more plugins.
sudo apt install liblo-dev dssi-dev lv2-dev libsamplerate0-dev
libsndfile1-dev  git libfluidsynth-dev libgtkmm-2.4-dev

Regards,
Robert

**Comment by spamatica** [comment]
2017-01-20 11:57 GMT+01:00 Budislav <notifications@github.com>:

> Thank you Tim!
> I install it without a problem so please copy this instructions to README
> file. I hope all is correct, those installation instructions are from
> Andrew.
>
>    1. Open terminal and type:
>    sudo apt-get install build-essential cmake libsndfile1-dev
>    libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default qttools5-dev
>    qttools5-dev-tools synaptic
>    2. Clone muse source with command: https://github.com/muse-
>    sequencer/muse.git
>    3. Type cd muse
>    4. Make build directory: mkdir build
>    5. Cd to the build directory: cd build
>    6. Run cmake: cmake ../muse3
>    7. Type make and wait for some time :)
>    8. Type sudo make install - this will install muse3 to /usr/local
>    9. Run it by typing muse3
>
>
I added a slightly edited version of this to the README, thanks!

And I hope you didn't get around to it yet Tim, in which case, sorry!

Regards,
Robert

**Comment by terminator356** [comment]
On Friday, January 20, 2017 10:42:44 AM EST spamatica wrote:
> 2017-01-20 18:20 GMT+01:00 Tim <notifications@github.com>:
> > On Friday, January 20, 2017 2:57:29 AM EST Budislav wrote:
> > > Thank you Tim!
> > > I install it without a problem so please copy this instructions to
> > > README
> > > file. I hope all is correct, those installation instructions are from
> > > Andrew.
> > > 
> > > 1. Open terminal and type:
> > > `sudo apt-get install build-essential cmake libsndfile1-dev
> > > libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default
> > > qttools5-dev
> > > qttools5-dev-tools synaptic` 2. Clone muse source with command:
> > > `https://github.com/muse-sequencer/muse.git`
> > 
> > <https://github.com/muse-sequencer/muse.git> 3. Type `cd muse`
> > 
> > > 4. Make build directory: `mkdir build`
> > > 5. Cd to the build directory: `cd build`
> > > 6. Run cmake: `cmake ../muse3`
> > > 7. Type `make` and wait for some time :)
> > > 8. Type `sudo make install` - this will install muse3 to /usr/local
> > > 9. Run it by typing `muse3`
> > > 
> > > We need also instructions for how to update this development version to
> > 
> > the
> > 
> > > latest one.
> > > 
> > > Now when I run MusE it shows me one problem:
> > > ![problem](https://cloud.githubusercontent.com/assets/
> > 
> > 3619927/22146127/e78be
> > 
> > > 1bc-df03-11e6-90ec-e1a422aabde5.png) I thought that I installed jack
> > 
> > with
> > 
> > > those commands on the top? There is no sound. How should I fix this?
> > 
> > Go ahead and install the Jack server meta package:
> > 
> > sudo apt-get install jackd
> > 
> > (According to Synaptic, looks like Jack dev package can be installed
> > /without/ the Jack server itself. That's maybe why you've no Jack right
> > now.)
> > 
> > > Also when MusE is opened I don't see how to open mixer and other things.
> > 
> > It
> > 
> > > shows me only arranger menu bar? Where is the rest of software?
> > > ![screenshot from 2017-01-20
> > > 11-05-36](https://cloud.githubusercontent.com/assets/
> > 
> > 3619927/22146359/ad6a3
> > 
> > > 05a-df04-11e6-8fb7-b205c812e188.png)
> > 
> > Ouch!
> > 
> > First, try this older, special MusE -u command line option:
> > "-u Ubuntu/unity workaround: don't allow sharing menus
> > and mdi-subwins. "
> > 
> > If that does not wotk, then this certainly should:
> > M Oswald reported the same problem:
> > 
> > "I found the issue, it's a known Ubuntu bug:
> > https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619
> > Solution:
> > sudo apt-get remove appmenu-qt5
> > Then Muse3 has again it's menu. "
> > 
> > Sorry not a very nice solution but it's all we can do right now.
> > 
> > Let me know if the "-u" option worked for you, I am curious whether
> > that is still the proper solution and if it works OK.
> 
> Wow, this is so unbelievably broken...
> I just had to see this so I installed ubuntu with unity in a virtual
> machine (yay for ISO installs in VMs, took 20 minutes or so).
> 
> MusE is completely nonworking under Unity, atleast in my VM. I know we make
> some rather complicated menu tricks in MusE but I'm pretty sure we aren't
> the only application suffering from their extremely ignorant way of
> overriding menus.

According to the report all Qt5 apps such as Qt5Creator were broken.

> The tricks you mention didn't make any difference for me, -u caused the MDI
> to break completely. It would be interesting to know how Michael got it
> working..

Strange, as I undersand it, Unity is out of the question now, 
 isn't Ubuntu using the Gnome3 DE not Unity?

So the second trick should have worked with 16.10.

Ehm, what Ubuntu versions are we all talking about here?
Maybe apples and oranges here?

T.

> The only way I found to get it to display correctly was to uninstall
> indicator-appmenu. But this removes the menu integration for ALL
> applications. Suppposedly you should be able to disable the support per
> application but I didn't get that to work.
> 
> So for now, the only way I see for you to experience MusE under Unity is by
> removing indicator-menu, hopefully Michael has some better trick..
> 
> By the way.
> I would suggest to run this command also before building MusE. It will
> enable more plugins.
> sudo apt install liblo-dev dssi-dev lv2-dev libsamplerate0-dev
> libsndfile1-dev  git libfluidsynth-dev libgtkmm-2.4-dev
> 
> Regards,
> Robert

**Comment by budislav** [comment]
@terminator356 @spamatica 

> Go ahead and install the Jack server meta package: sudo apt-get install jackd (According to Synaptic, looks like Jack dev package can be installed /without/ the Jack server itself. That's maybe why you've no Jack right now.)

I installed jack but it still shows me the same error. I can run jack but I don't know how to make this thing working. If that can't start automatically how I need to do that?

Ubuntu 16.10 is version on which I tried to install.

I installed kubuntu 16.10 in the meantime and menu working fine. I also installed latest kde neon before kubuntu and tried to install MusE but it didn't compiled it, there was a hundred errors..

**Comment by spamatica** [comment]
2017-01-20 20:54 GMT+01:00 Tim <notifications@github.com>:

> On Friday, January 20, 2017 10:42:44 AM EST spamatica wrote:
> > 2017-01-20 18:20 GMT+01:00 Tim <notifications@github.com>:
> > > On Friday, January 20, 2017 2:57:29 AM EST Budislav wrote:
> > > > Thank you Tim!
> > > > I install it without a problem so please copy this instructions to
> > > > README
> > > > file. I hope all is correct, those installation instructions are from
> > > > Andrew.
> > > >
> > > > 1. Open terminal and type:
> > > > `sudo apt-get install build-essential cmake libsndfile1-dev
> > > > libsamplerate0-dev libjack-jackd2-dev ladspa-sdk qt5-default
> > > > qttools5-dev
> > > > qttools5-dev-tools synaptic` 2. Clone muse source with command:
> > > > `https://github.com/muse-sequencer/muse.git`
> <https://github.com/muse-sequencer/muse.git>
>
> > >
> > > <https://github.com/muse-sequencer/muse.git> 3. Type `cd muse`
> > >
> > > > 4. Make build directory: `mkdir build`
> > > > 5. Cd to the build directory: `cd build`
> > > > 6. Run cmake: `cmake ../muse3`
> > > > 7. Type `make` and wait for some time :)
> > > > 8. Type `sudo make install` - this will install muse3 to /usr/local
> > > > 9. Run it by typing `muse3`
> > > >
> > > > We need also instructions for how to update this development version
> to
> > >
> > > the
> > >
> > > > latest one.
> > > >
> > > > Now when I run MusE it shows me one problem:
> > > > ![problem](https://cloud.githubusercontent.com/assets/
> > >
> > > 3619927/22146127/e78be
> > >
> > > > 1bc-df03-11e6-90ec-e1a422aabde5.png) I thought that I installed jack
> > >
> > > with
> > >
> > > > those commands on the top? There is no sound. How should I fix this?
> > >
> > > Go ahead and install the Jack server meta package:
> > >
> > > sudo apt-get install jackd
> > >
> > > (According to Synaptic, looks like Jack dev package can be installed
> > > /without/ the Jack server itself. That's maybe why you've no Jack right
> > > now.)
> > >
> > > > Also when MusE is opened I don't see how to open mixer and other
> things.
> > >
> > > It
> > >
> > > > shows me only arranger menu bar? Where is the rest of software?
> > > > ![screenshot from 2017-01-20
> > > > 11-05-36](https://cloud.githubusercontent.com/assets/
> > >
> > > 3619927/22146359/ad6a3
> > >
> > > > 05a-df04-11e6-8fb7-b205c812e188.png)
> > >
> > > Ouch!
> > >
> > > First, try this older, special MusE -u command line option:
> > > "-u Ubuntu/unity workaround: don't allow sharing menus
> > > and mdi-subwins. "
> > >
> > > If that does not wotk, then this certainly should:
> > > M Oswald reported the same problem:
> > >
> > > "I found the issue, it's a known Ubuntu bug:
> > > https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619
> > > Solution:
> > > sudo apt-get remove appmenu-qt5
> > > Then Muse3 has again it's menu. "
> > >
> > > Sorry not a very nice solution but it's all we can do right now.
> > >
> > > Let me know if the "-u" option worked for you, I am curious whether
> > > that is still the proper solution and if it works OK.
> >
> > Wow, this is so unbelievably broken...
> > I just had to see this so I installed ubuntu with unity in a virtual
> > machine (yay for ISO installs in VMs, took 20 minutes or so).
> >
> > MusE is completely nonworking under Unity, atleast in my VM. I know we
> make
> > some rather complicated menu tricks in MusE but I'm pretty sure we aren't
> > the only application suffering from their extremely ignorant way of
> > overriding menus.
>
> According to the report all Qt5 apps such as Qt5Creator were broken.
>
> > The tricks you mention didn't make any difference for me, -u caused the
> MDI
> > to break completely. It would be interesting to know how Michael got it
> > working..
>
> Strange, as I undersand it, Unity is out of the question now,
> isn't Ubuntu using the Gnome3 DE not Unity?
>

No, Ubuntu Desktop is definitely running Unity, I think it is a big part of
their "experience"
I tracked down the thread from Michael and it seems he was running Ubuntu
Studio with XFCE so it seems not related at all.


>
> So the second trick should have worked with 16.10.
>
> Ehm, what Ubuntu versions are we all talking about here?
> Maybe apples and oranges here?
>

My test was with 16.10 Ubuntu Desktop in a Virtualbox VM. I guess running
it in a VM could have consequences but basically I would say that this is
an extremely common use case so I hope we can find a way to circumvent
unitys madness.

/Robert

**Comment by terminator356** [comment]
On Friday, January 20, 2017 12:16:38 PM EST spamatica wrote:
> > Strange, as I undersand it, Unity is out of the question now,
> > isn't Ubuntu using the Gnome3 DE not Unity?
> 
> No, Ubuntu Desktop is definitely running Unity, I think it is a big part of
> their "experience"
> I tracked down the thread from Michael and it seems he was running Ubuntu
> Studio with XFCE so it seems not related at all.

Ah, so possibly maybe I broke Florian's -u Unity workaround when I 
 fixed all the menus months ago? I didn't have Ubuntu at the time,
 but I seem to recall briefing over Flo's code and thought it would 
 probably still work, it didn't seem deeply related to what I was doing.

Or the -u workaround now needs updating?

T.

**Comment by kybos** [comment]
Unity is dead (fortunately), closing...
