### ISSUE TITLE
One nice GUI theme to be default on every desktop environment

### ISSUE THREAD

**Issue by budislav** [muse-sequencer/muse#556]
Can we have one nice GUI theme on every Linux? 
I noticed on Ubuntu MusE use old GTK+ theme for whole GUI with orange frames does not look nice and for me outdated. I didn't tried on Gnome, but on KDE it looks very nice. I think if we can use new KDE Breeze theme to be default on every Linux distro it would be the best, so we can change it later and have unique look like other modern DAW's. Krita is the best example of this principle.

I think light breeze theme is very nice but we have dark breeze also, we can include bark later when we make everything looks perfect on light (not a big fan of dark breeze it looks black and not so readable, so light is the best option there). This is very very crucial for my next changes I need to make. So this does not include a lot of work right?

This should not be a problem I think but impact is huge. Because I can redesign other smaller parts of UI controls (like sliders, vmaters, arrange background, all parts ..) those are custom in MusE. So it will look like a really nice native application on QT and also beautiful on other distro.

This include one beautiful UI font type like Ubuntu, or new Google Noto font for all languages on the Earth. https://www.google.com/get/noto/

**Comment by ViktorNova** [comment]
+1
I think this is CRUCIAL.
The appearance of MusE is a big hindrance to it being taken seriously, even though it has the features. This would be a huge step.

**Comment by kybos** [comment]
This is essentially implemented in MusE 4. The new UI should look more or less the same on all distros.
If it's "nice" or not, that's certainly a matter of taste... But it can be customized for the most part.
