### ISSUE TITLE
gui tweaks 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#558]
This is a list of gui tweaks I would see.

1 db scale numbers on the sides of led on the mixer  Make the audio amd midi mixers one mixer like ardour's mixer. This is most modern daw.
![big_mixer4](https://cloud.githubusercontent.com/assets/8137561/22267286/de113644-e248-11e6-8b38-5e9842505f97.png)

like ardour mixer 
![bef8507a-51c1-11e6-8dd2-6d97cb14eab5](https://cloud.githubusercontent.com/assets/8137561/22267414/4940f760-e249-11e6-93a7-821902a5270e.png)
muse mixer ^

2 More information/ more typical transport 
Muse main window gui needs to be more like the transport window
![muse1](https://cloud.githubusercontent.com/assets/8137561/22270734/a0d39b1a-e256-11e6-993b-4d66a549b7b7.jpg)

<img width="375" alt="untitled" src="https://cloud.githubusercontent.com/assets/8137561/22270760/b3199658-e256-11e6-91ae-908dc6a9bd1d.png">

3 all of the info should all be in the same area of the transport some what like ardour.
 <img width="924" alt="vtl-a4" src="https://cloud.githubusercontent.com/assets/8137561/22272466/c9b3e66c-e25f-11e6-95cf-af0564978cda.png">

4 muse's transport could all so use a master vu some what ardour or pro 
<img width="49" alt="c9b3e66c-e25f-11e6-95cf-af0564978cda" src="https://cloud.githubusercontent.com/assets/8137561/22274485/6884d40c-e26c-11e6-8831-03ae5900bb33.png">

![pro-tools-12-1200-80](https://cloud.githubusercontent.com/assets/8137561/22274368/c29baf5c-e26b-11e6-8789-abb4dff4fa22.jpg)

5 the plugin preset menu should also be at the top of instrument and fx windows 
6 the mixer mute/solo and record buttons should be above the channel 
7 the pan knob and pan readout should be above the mute/solo and record buttons 
8 the input should be at the vary top of mixer under the name of the track. The output should stay at the bottom of the mixer 
9 the automation should be able to in apart of the track or as a subtrack as in the MusE (evolution branch) (svn) ![mtest](https://cloud.githubusercontent.com/assets/8137561/22855270/1297d5aa-f043-11e6-9733-642400cc56be.png)
this could help with #513  and #525 

10 a preset manger toolbar for all plungins at the top of the window
11 a smart disable option to trun off the plugin when there is nothing on the track this will help with cpu usege
![insetplugindynamicsiii 1](https://user-images.githubusercontent.com/8137561/31049051-d72d9f2c-a5f0-11e7-9360-2b9589ccac22.jpg)

taking over OpenOctave #523  may help.
![insetplugindynamicsiii 1](https://user-images.githubusercontent.com/8137561/31049051-d72d9f2c-a5f0-11e7-9360-2b9589ccac22.jpg)

**Comment by budislav** [comment]
@Reaper10 you maybe know my work for Zyn and LMMS here 
http://budislavtvp.deviantart.com/art/LMMS-UI-UX-Design-Concept-Single-Window-523696539
http://budislavtvp.deviantart.com/art/Zyn-UI-UX-Design-Concept-Fusion-455890191
I started the same kind of project with MusE and you can see some of topics here https://github.com/muse-sequencer/muse/issues/556 and https://github.com/muse-sequencer/muse/issues/557
Like you can assume I have a plan for whole UI/UX including this part but all parts should be merged slowly.
