### ISSUE TITLE
Jack transport configurable [sf#1092284]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#56]
Submitted by spamatica on 2004-12-28 18:49:40

It should be configurable whether jack transport is 
enabled and if MusE is master or slave

**Comment by danboid** [comment]
I think this got done didn't it? MIDI Sync -> JACK Timebase master option?

Whilst we're on the subject of sync, does MusE support MIDI clock?

**Comment by spamatica** [comment]
Closing as this should be working
