### ISSUE TITLE
libinstpatch missing

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#562]
Hi,
When I start muse3 pre2 I get this message at startup -
`LOCALE en_US
initMidiSynth: MESS dlopen(/usr/local/lib/muse-3.0/synthi/fluid_synth.so) failed: libinstpatch-1.0.so.0: cannot open shared object file: No such file or directory
Denormal protection enabled.
`
libinstpatch from memory is related to the swami editor. Is this object file really required?

Thanks,
Chris.

**Comment by terminator356** [comment]
On 2017-02-10 06:41 AM, therealkitman wrote:
>
> Hi,
> When I start muse3 pre2 I get this message at startup -
> |LOCALE en_US initMidiSynth: MESS 
> dlopen(/usr/local/lib/muse-3.0/synthi/fluid_synth.so) failed: 
> libinstpatch-1.0.so.0: cannot open shared object file: No such file or 
> directory Denormal protection enabled.|
> libinstpatch from memory is related to the swami editor. Is this 
> object file really required?
>
> Thanks,
> Chris.
>
>

It can be disabled with the cmake option:
ENABLE_INSTPATCH
Set it to 'no' or don't give it.

This sounds like swami was not built, or packaged, correctly.
MusE's cmake script is dutifully finding libinstpatch-1.0.pc,
  which is installed with swami (developer files), in your
  lib/pkgconfig directory, and that .pc file refers to the file
  libinstpatch-1.0.so, but apparently either libinstpatch-1.0.so
  is missing, or it is not properly linked to the links 
libinstpatch-1.0.so.0
  and libinstpatch-1.0.so.0.0.0.

If libinstpatch-1.0.so is present but the links are not, try manually
  creating the .0 and .0.0.0 links.

Tim.

**Comment by terminator356** [comment]
P.S. I use instpatch to provide automatic drum note names
  in the Drum Editor, when using our fluidsynth MESS synth.

It means you don't have to supply or load your own drum map file,
  it just automatically displays the actual drum note names
  as taken from the soundfont file, using instpatch to do it.

Without instpatch nothing bad happens, just you will have
  to supply and load your own drum map if you want
  meaningful drum note names shown.

Tim.

**Comment by therealkitman** [comment]
Thanks Tim. I forgot that I had tried to install swami/libinstpatch before. But libinstpatch would not build therefore Swami couldn't be built either. I started playing with Polyphone http://polyphone-soundfonts.com/en/ as a Swami alternative.

I will retry building libinstpatch again and recompiling Muse and see what happens.

I will close this one.
Thanks,
Chris.

**Comment by therealkitman** [comment]
Hi, I have noticed that with new release today (midi output feature) that the error messages now are gone.
Will close this one.
Regards.
