### ISSUE TITLE
MIDI Tracks - no notes displayed.

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#564]
Hi,
re: muse3 pre2
This may be a minor cosmetic thing but if I either import a midi file or create a midi track from scratch, the notes are not displayed in their tracks. See image.

![image](https://cloud.githubusercontent.com/assets/14888092/22853866/b4685e2e-f09b-11e6-9055-4c6e05222c82.png)

Regards,
Chris.

**Comment by terminator356** [comment]
On 2017-02-11 07:54 AM, therealkitman wrote:
>
> Hi,
> re: muse3 pre2
> This may be a minor cosmetic thing but if I either import a midi file 
> or create a midi track from scratch, the notes are not displayed in 
> their tracks. See image.
>
> image 
> <https://cloud.githubusercontent.com/assets/14888092/22853866/b4685e2e-f09b-11e6-9055-4c6e05222c82.png>
>
> Regards,
> Chris.
>
>
Ah yes, someone reported that long ago,
  although it was with controller outlines not with notes (!)
  and I have observed it.
If I recall, even saving and reloading does not make them
  appear, which is really puzzling, I didn't get a chance to solve it.

Must get in there and have another look...

Tim.

**Comment by therealkitman** [comment]
Thank you. I usually search the issues if things have already been reported. Since you're aware of it I will close this issue.
Regards...
