### ISSUE TITLE
Feature Request: Midi Remote Control with CC Midi Messages

### ISSUE THREAD

**Issue by the-segler** [muse-sequencer/muse#566]
Hello,

currently the remote control is being implemented with nodes. 
My novation impulse keyboard prefers to send CC messages and doesn't like to diskuss this :) 
As I am shurely not the only one, is it possible to implement also the selection of type?

In my case: 
Backward: CC#112
Forward:   CC#113
Stop:         CC#114
Play:          CC#115
Insert Pause: CC#116
Record:     CC#117

Best regards and thanks for the great job,

MIchael

**Comment by terminator356** [comment]
Hi sorry I missed notification of this one.
Close but no cigar as far as I can see - we support midi remote control 
 in the menu Midi > Input Plugins > Midi Remote Control.
But only for keyboard notes, not CCs. This would be a worthy addition.
Keep this open and we'll see what happens. Can't promise anything immediate though.
Thanks. Tim.
