### ISSUE TITLE
ALT+P: MusE crashes when parts in Arranger Canvas were not selected for a loop region

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#572]
Using the latest development version of MusE (downloaded from the github 
repository last week) under Ubuntu Studio 16.04.2 I detected the following behaviour:

You need to select all necessary parts in the Arranger Canvas with the mouse to define a loop region before applying ALT+P.

If you do not select the necessary parts in the Arranger Canvas before you apply ALT+P, then MusE dissapears from the screen.

This behaviour is reproducable. I detected it in 

a) a med file with a Fluidsynth track and two MIDI tracks

b) a med file with an Input and a Wave track.

Regards,

Jens

**Comment by terminator356** [comment]
Hi, sorry for the long delay.
Fixed in git master.

No crash now.

Operation of Alt+P still seems a little weird,
  may want to press twice to locate to a part.
No time to check it now.

Thanks Jens!
Tim.

**Comment by spamatica** [comment]
Closing as this should be fixed
