### ISSUE TITLE
Opening a med file in an older format: Arranger Canvas not displayed

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#573]
Last week I compiled and installed the latest MusE version from the github 
repository under Ubuntu Studio 16.04.2. I loaded a med file into MusE. I 
created this med file last year using a development version of MusE from that 
time. 

The first time I loaded that med file into MusE, I was told that the med 
file format is from version 2.1 or so, and that it will be converted to the new 
format when I save the loaded file. I saved the loaded med file.

Then I noticed that I cannot see the Arranger Canvas of the opened and converted med file, I only see the left part of the Arranger Window with the specifications for every track. I do not see the parts of the song of that med file.

Workaround:

I managed to resolve the problem: Moving the mouse over the right edge of the 
Arranger Window (where no Arranger Canvas was displayed) turned the mouse 
pointer into a two-sided arrow (an arrow to the left and to the right). I then 
moved the two-sided arrow to the left: Now I can see the Arranger Canvas 
again.

How about fixing this behaviour? I.e like this way:

"If a med file in an obsolete file format version is opened for the first time in 
a current MusE version, then make sure that the upper left corner of the 
Arranger Canvas is displayed at the middle of the vertical screen resolution". 
Example: The vertical screen resolution is 1024 pixels; the upper left corner 
of the Arranger Canvas is then displayed at the vertical screen position of 
512 pixels, seen from the left edge of the screen.

Regards,

Jens

**Comment by kybos** [comment]
The UI has changed, this should no longer be relevant.
