### ISSUE TITLE
muse can't access it's own module libraries

### ISSUE THREAD

**Issue by simonvanderveldt** [muse-sequencer/muse#574]
When I build and install the current 3.0-pre2 or `master` of muse and try to run it I get the following error
```
error while loading shared libraries: libmuse_core.so: cannot open shared object file: No such file or directory
```

This seems to be caused by these libraries getting installed to `/usr/lib64/muse-3.0/modules` (which I believe is the correct location)
```
$ ls -ahl /usr/lib64/muse-3.0/modules 
total 9.3M
drwxr-xr-x 2 root root   23 Jul 10 17:37 .
drwxr-xr-x 5 root root    5 Jul  9 23:35 ..
-rwxr-xr-x 1 root root  47K Jul 10 17:37 libmuse_al.so
-rwxr-xr-x 1 root root 337K Jul 10 17:37 libmuse_arranger.so
-rwxr-xr-x 1 root root 221K Jul 10 17:37 libmuse_awl.so
-rwxr-xr-x 1 root root  43K Jul 10 17:37 libmuse_cliplist.so
-rwxr-xr-x 1 root root 2.7M Jul 10 17:37 libmuse_core.so
-rwxr-xr-x 1 root root 108K Jul 10 17:37 libmuse_ctrl.so
-rwxr-xr-x 1 root root 145K Jul 10 17:37 libmuse_driver.so
-rwxr-xr-x 1 root root 1.1M Jul 10 17:37 libmuse_icons.so
-rwxr-xr-x 1 root root 282K Jul 10 17:37 libmuse_instruments.so
-rwxr-xr-x 1 root root  56K Jul 10 17:37 libmuse_liste.so
-rwxr-xr-x 1 root root  10K Jul 10 17:37 libmuse_lv2_gtk2_support.so
-rwxr-xr-x 1 root root  51K Jul 10 17:37 libmuse_marker.so
-rwxr-xr-x 1 root root 117K Jul 10 17:37 libmuse_master.so
-rwxr-xr-x 1 root root 593K Jul 10 17:37 libmuse_midiedit.so
-rwxr-xr-x 1 root root 501K Jul 10 17:37 libmuse_mixer.so
-rwxr-xr-x 1 root root 180K Jul 10 17:37 libmuse_mplugins.so
-rwxr-xr-x 1 root root 5.5K Jul 10 17:37 libmuse_string.so
-rwxr-xr-x 1 root root  19K Jul 10 17:37 libmuse_synti.so
-rwxr-xr-x 1 root root 158K Jul 10 17:37 libmuse_waveedit.so
-rwxr-xr-x 1 root root 175K Jul 10 17:37 libmuse_widgets_functiondialogs.so
-rwxr-xr-x 1 root root 1.8M Jul 10 17:37 libmuse_widgets.so
```
But `muse3` itself has `lib64/muse-3.0/modules` defined as `RPATH`/`RUNPATH`. Or in other words the prefix is missing:
```
$ objdump -p /usr/bin/muse3 | grep -i path
  RUNPATH              lib64/muse-3.0/modules
```

I'm not really sure why this happens, but it might be that CMake needs some instructions to tell it to correctly set the `RPATH` as [documented here](https://cmake.org/Wiki/CMake_RPATH_handling#Always_full_RPATH)?

**Comment by simonvanderveldt** [comment]
For the modules I managed to fix this by adding `${CMAKE_INSTALL_PREFIX}` to the [`CMAKE_INSTALL_RPATH`](https://github.com/muse-sequencer/muse/blob/master/muse3/CMakeLists.txt#L173)

I have no clue how to fix this for synthi and plugins modules, adding them do `LD_LIBRARY_PATH` doesn't work (i.e. I don't see the synths under the "Add synth" menu).

**Comment by spamatica** [comment]
Hello Simon, haven't looked closer at this yet just wanted to quickly ask what distro you are on, maybe make it possible for us to reproduce this problem?

**Comment by simonvanderveldt** [comment]
@spamatica I'm using gentoo. Ran into this when working on creating an ebuild (gentoo's "package") for muse. The ebuild pretty much just gets the sources, compiles it and then installs it.

It seems `CMAKE_INSTALL_RPATH` is treated differently and doesn't get the "free" `CMAKE_INSTALL_PREFIX` every relative path gets when used in `INSTALL` statements.

When googling this multiple hits came up, one of them this one which relates to ubuntu and debian https://bugs.launchpad.net/ubuntu/+source/muse/+bug/1596486

Their fix of setting `LIB_INSTALL_DIR` to `/usr/lib` works because `LIB_INSTALL_DIR` is then an absolute path, which means no free prefix when installing and thus it matches with the value in `CMAKE_INSTALL_RPATH`
