### ISSUE TITLE
GUI language unequal to English

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#575]
Second last week I compiled and installed the latest MusE version from the github
repository under Ubuntu Studio 16.04.2. 

The default (local) language in my Ubuntu Studio installation is German.

The language in the GUI of my compiled MusE development version is for 99% German. But I did not want German to be the GUI language. While I configured the source code of MusE, I set the flag for UPDATE_TRANSLATIONS to OFF.

I do not know how to change the current GUI language (German) to English within MusE. 

My suggestion is either to ensure that MusE alsways gets compiled with English as the GUI language, if UPDATE_TRANSLATIONS has been set to OFF, as it was the case last year and possibly earlier. Or there is a possibility to change the GUI language within MusE, from the local language to English, like in the global MusE settings dialog window.

**Comment by terminator356** [comment]
On 07/11/2017 06:38 AM, Jens Radloff wrote:
>
> Second last week I compiled and installed the latest MusE version from 
> the github
> repository under Ubuntu Studio 16.04.2.
>
> The default (local) language in my Ubuntu Studio installation is German.
>
> The language in the GUI of my compiled MusE development version is for 
> 99% German. But I did not want German to be the GUI language. While I 
> configured the source code of MusE, I set the flag for 
> UPDATE_TRANSLATIONS to OFF.
>
> I do not know how to change the current GUI language (German) to 
> English within MusE.
>
> My suggestion is either to ensure that MusE alsways gets compiled with 
> English as the GUI language, if UPDATE_TRANSLATIONS has been set to 
> OFF, as it was the case last year and possibly earlier. Or there is a 
> possibility to change the GUI language within MusE, from the local 
> language to English, like in the global MusE settings dialog window.
>

Hi Jens, have you tried the -l (lower case L) command line switch?
Type muse3 -h to see what languages are available.
Try muse3 -len.

Tim.

**Comment by jensplixplox** [comment]
Hi Tim,

"muse3" returns:

> xxx@samba:~/Schreibtisch$ /opt/muse_dev_release_version/bin/muse3
Config File </home/xxx/.config/MusE/MusE.cfg>
LOCALE de_DE
Denormal protection enabled.
...

"muse3 -l en" returns:

> xxx@samba:~/Schreibtisch$ /opt/muse_dev_release_version/bin/muse3 -l en
Config File </home/xxx/.config/MusE/MusE.cfg>
LOCALE en_US
Denormal protection enabled.
...

=> The GUI language in MusE is English.

Thanks, Tim. 

I am not sure if this is a bug. The shortcut symbol (its properties) for muse3 on my XFCE desktop does not allow me to add the "-l en" option to the command "/opt/muse_dev_release_version/bin/muse3". So I would be forced to always start MusE with the "-l en" option from the console to use MusE with English as the GUI language, which is not handy.

Regards,

Jens

**Comment by spamatica** [comment]
Arguments are handled the way it is handled by all executables so I have a hard time seeing as this is a bug in MusE, maybe there is another way to set the argument in the XFCE shortcut?

I guess an improvement would be to have a setting in the UI. Not sure if that is feasible but I will the bug open for now, maybe someone finds a way.
