### ISSUE TITLE
New feature suggestion: Possibility to clear the entries in the med file history

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#576]
Second last week I compiled and installed the latest MusE version from the github
repository under Ubuntu Studio 16.04.2. 

It should be possible to clear the file history in Menu File => Open Last Song. I do not know how to do that within MusE. 

The possiblity to clear this file history should not be provided in the file history itself, in Menu File => Open Last Song, because this would be too dangerous. By coincident one could delete the file history there, although one wanted to open a song within that file history. Instead, the global MusE settings could provide the possibility to clean this file history.

Background: Today I deleted several folders containing med files, outside MusE. It was my intention to delete these med files. These med files are still shown in the file history in Menu File => Open last song. The entries there belonging to these med files are thus orphaned.

**Comment by jensplixplox** [comment]
As it seems, MusE automatically clears this file history if MusE is restarted after a session in which a med file has been deleted by hand: MusE then, when restarted, only shows song files in this file history which are not orphaned.

**Comment by kybos** [comment]
The code shows that files are checked for existence now before displaying the Open recent menu.
