### ISSUE TITLE
Copying several parts: Only one part is pasted at new song position

### ISSUE THREAD

**Issue by jensplixplox** [muse-sequencer/muse#577]
Second last week I compiled and installed the latest MusE version from the github
repository under Ubuntu Studio 16.04.2. 

If several parts, located next to each other, in the Arranger Canvas are selected with the mouse, then copied, and if then these several parts are intended to be pasted at another position in the song (here: at the end of the song), then only one part of them gets pasted at this other position. This behaviour affects both several parts which are arranged directly next or directly below (to) each other.

I noticed this behaviour in a newly created song with 3 Midi tracks, where one Midi track is a drum track.

**Comment by terminator356** [comment]
On 07/11/2017 06:58 AM, Jens Radloff wrote:
>
> Second last week I compiled and installed the latest MusE version from 
> the github
> repository under Ubuntu Studio 16.04.2.
>
> If several parts, located next to each other, in the Arranger Canvas 
> are selected with the mouse, then copied, and if then these several 
> parts are intended to be pasted at another position in the song (here: 
> at the end of the song), then only one part of them gets pasted at 
> this other position. This behaviour affects both several parts which 
> are arranged directly next or directly below (to) each other.
>
> I noticed this behaviour in a newly created song with 3 Midi tracks, 
> where one Midi track is a drum track.
>
> —
>
I could not reproduce this. I tried pasting at the end of the song and 
elsewhere.
I tried midi and drum parts, both beside and below each other.
What keys and/or menu items are you using to copy + paste?

Tim.

**Comment by jensplixplox** [comment]
Hi Tim,

> What keys and/or menu items are you using to copy + paste?

I am using both CTRL+C and CTRL+V, and the menu items ("copy" and "paste").

I just tried to copy several parts, located next to each other, to the end of my song: Does not work; only one part gets inserted at the end of the song.

My song contains parts with two different beats: a 22/4th and a 16/4th beat. I tried to copy several 16/4th beat-based parts to the end of the song, but no matter which beat I declare at the end of the song (1/4th or 4/4th or 16/4th or 22/4th), only one part gets inserted there.

I could send you my med file by mail. My song uses one Fluidsynth instance which is linked to the FluidR3.sf2 soundfont. 

Regards,

Jens

**Comment by drautzburg** [comment]
Slightly related: I am having a hard time copying multiple parts one after the other with Ctrl-C. It works okay with the first part. When I try to copy&paste the second part via Ctrl-C/Ctrl-V, then (sometimes) the first part gets pasted again. When I use the menu things seem to be okay. BTW, in this case the originals were clones, in case this makes a difference.

**Comment by spamatica** [comment]
Going through tickets.. I haven't seen this happen. I recall there were some other error that maybe was related to Qt, could this be the same?
Will close in a bit unless there is some development..
