### ISSUE TITLE
error: cannot use 'try' with exceptions disabled

### ISSUE THREAD

**Issue by yurivict** [muse-sequencer/muse#583]
CMakeLists sets --no-exceptions but the code later uses exceptions.
454ebcc

**Comment by spamatica** [comment]
Again, this should have been adressed long ago... 
I see this as more of a comment than an actual bug. A configuration bug maybe. In any case. I do believe we have some places where exceptions are used due to inheriting external libraries, so the option should no longer exist in CMakeLists
