### ISSUE TITLE
Misbehaving windows [sf#1092322]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#59]
Submitted by spamatica on 2004-12-28 19:29:11

Several windows are differently designed with respect to 
buttons etc. This should be fixed to improve conformance 
and thus user acceptance. 

Examples: 
"midi remote control" has no "ok" or "cancel" button 
"midi transform" got "dismiss"  
"midi transpose" no close or ok button 

other dialogs are even diffrent but most don't even have 
a close button at all.

**Comment by spamatica** [comment]
Very old bug. Still has some merit in that midi plugins have some nonstandard UIs but most other windows and dialogs follow a very similar pattern so will close this as the importance is quite low.
