### ISSUE TITLE
MusE doesn't record some controllers

### ISSUE THREAD

**Issue by songo** [muse-sequencer/muse#592]
Hi,
it seems that recent git versions don't record some controllers (events from external MIDI devices). Events that **aren't** recorded: Pitch Bend, Aftertouch, Program Change. Some other controllers (eg., Modulation, Volume) are recorded flawlessly. MIDI engine used (ALSA or JACK) doesn’t matter here. It seems that events are received and even passed to output ports but never get recorded. Part of muse -A -M -m output which shows that these events (`SND_SEQ_EVENT_PITCHBEND` and `SND_SEQ_EVENT_PGMCHANGE`) indeed are present and processed:
```
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056220451 port:0 chan:2 type:0xe0 a=-641 b=0
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_PITCHBEND chan:1 value:-641                                                                    
ALSA MidiIn driver: SND_SEQ_EVENT_PITCHBEND chan:1 value:0                                                                                                     
MidiInput: time:965187 port:0 chan:2 type:0xe0 a=0 b=0                                                                                                         
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056221103 port:0 chan:2 type:0xe0 a=0 b=0                                                          
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_PITCHBEND chan:1 value:0                                                                       
ALSA MidiIn driver: SND_SEQ_EVENT_SENSING                                                                                                                      
ALSA MidiIn driver: SND_SEQ_EVENT_CONTROLLER chan:1 param:0 value:0                                                                                            
MidiInput: time:965202 port:0 chan:2 type:0xb0 a=0 b=0                                                                                                         
ALSA MidiIn driver: SND_SEQ_EVENT_CONTROLLER chan:1 param:32 value:0                                                                                           
MidiInput: time:965230 port:0 chan:2 type:0xb0 a=32 b=0                                                                                                        
ALSA MidiIn driver: SND_SEQ_EVENT_PGMCHANGE chan:1 value:5                                                                                                     
MidiInput: time:965257 port:0 chan:2 type:0xc0 a=5 b=0                                                                                                         
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056228692 port:0 chan:2 type:0xb0 a=32 b=0                                                         
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_CONTROLLER chan:1 param:32 value:0                                                             
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056228719 port:0 chan:2 type:0xc0 a=5 b=0                                                          
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_PGMCHANGE chan:1 value:5                                                                       
ALSA MidiIn driver: SND_SEQ_EVENT_SENSING                                                                                                                      
ALSA MidiIn driver: SND_SEQ_EVENT_CONTROLLER chan:1 param:0 value:0                                                                                            
MidiInput: time:965193 port:0 chan:2 type:0xb0 a=0 b=0                                                                                                         
ALSA MidiIn driver: SND_SEQ_EVENT_CONTROLLER chan:1 param:32 value:0                                                                                           
MidiInput: time:965220 port:0 chan:2 type:0xb0 a=32 b=0                                                                                                        
ALSA MidiIn driver: SND_SEQ_EVENT_PGMCHANGE chan:1 value:6                                                                                                     
MidiInput: time:965248 port:0 chan:2 type:0xc0 a=6 b=0
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056248139 port:0 chan:2 type:0xb0 a=32 b=0
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_CONTROLLER chan:1 param:32 value:0
ALSA MidiOut pre-driver: <M Audio Delta 1010LT MIDI>: time:1056248167 port:0 chan:2 type:0xc0 a=6 b=0
ALSA MidiOut driver: <M Audio Delta 1010LT MIDI>: SND_SEQ_EVENT_PGMCHANGE chan:1 value:6
```

Some bisecting led me to 0f89e406a8fc1e5858893114a11800949df09b41 which probably introduced the regression. Any compilation prior to this commit works fine.

Hope it can be fixed soon as I'm in the middle of recording. :)

**Comment by terminator356** [comment]
Testing... hang in there.

Tim.

**Comment by terminator356** [comment]
Hi, try it now.
I cherry picked a fix from my branch midi_engine_fixes_2017.
I was aware of this issue soon after starting the branch and
  had fixed it there, hoping to merge soon at the time, but
  long time has passed now.

Apologies for any hassle.
And for accidentally closing the issue, simply by including
  the words "Fix #592" in my commit line. Hmm, kinda neat,
  it highlights the word "Fix" in the Git browser and takes you
  right to the fix.

Feel free to reopen!

Tim.

**Comment by songo** [comment]
Hello,

05.11.2017, 21:44:55, Tim wrote:
> Hi, try it now.

Patched, compiled and tested. All problematic controllers are recorded
now. Wow, that was fast! I always knew that MusE has an excellent
support! Funny, I just started to investigate that exact part of the
code but without a solid understating of MusE internals it was hard to
provide working patch.

> I cherry picked a fix from my branch midi_engine_fixes_2017.
> I was aware of this issue soon after starting the branch and
> had fixed it there, hoping to merge soon at the time, but
> long time has passed now.

So what about merging that and doing official MusE release soon? From my
point of view (thanks to latest commits) it's getting pretty stable now.
Last official release is quite dated and muse_3_0_pre2 has lots of bugs
comparing to master… 

> Apologies for any hassle.
> And for accidentally closing the issue, simply by including
> the words "Fix #592" in my commit line. Hmm, kinda neat,
> it highlights the word "Fix" in the Git browser and takes you
> right to the fix.

Yeah, some sophisticated AI stuff for everyone. :)

Thanks and best regards,

     k.
-- 
Krzysztof Gajdemski | songo (at) debian.org.pl | KG4751-RIPE
Registered Linux User #133457 | BLUG Registered Member #0005
PGP key at: http://s.debian.org.pl/gpg/gpgkey * ID: D3259224
Szanuję was wszystkich, którzy pozostajecie w cieniu - Snerg

**Comment by terminator356** [comment]
On 11/05/2017 06:17 PM, Krzysztof Gajdemski wrote:
> Hello,
> 
> 05.11.2017, 21:44:55, Tim wrote:
>  > Hi, try it now.
> 
> Patched, compiled and tested. All problematic controllers are recorded
> now. Wow, that was fast! I always knew that MusE has an excellent
> support! Funny, I just started to investigate that exact part of the
> code but without a solid understating of MusE internals it was hard to
> provide working patch.
> 
>  > I cherry picked a fix from my branch midi_engine_fixes_2017.
>  > I was aware of this issue soon after starting the branch and
>  > had fixed it there, hoping to merge soon at the time, but
>  > long time has passed now.
> 
> So what about merging that and doing official MusE release soon? From my
> point of view (thanks to latest commits) it's getting pretty stable now.
> Last official release is quite dated and muse_3_0_pre2 has lots of bugs
> comparing to master…

[ Pardon the CC to our dev list, not sure who receives what. ]

Merge may happen soon. As of today I finished some more heavy work.
It compiles, plays complex test songs, and record tests OK.

I rewrote my clumsy multi-writer-thread MPSC ring buffer template class.
It's not a ring buffer, per se:

One item array.
One atomic bool inUse array.
One atomic bool hasData array.

No counters, pointers, increments, modulos etc. Just 'bins' !

The trick is, thankfully, for safety and assurance the reader side
  needed to sort what it read from the buffer, by midi event timestamp.
So it simply empties the event 'bins' into a sorted memory-pooled set.

Now for the first time I just stress tested my branch.
So far solid no concurrency issues. Wish me luck...

Cheers.
Tim.

**Comment by songo** [comment]
Jest 06.11.2017, właśnie wybija 00:42:49, Tim pisze:
> On 11/05/2017 06:17 PM, Krzysztof Gajdemski wrote:
> > 05.11.2017, 21:44:55, Tim wrote:
> > > I cherry picked a fix from my branch midi_engine_fixes_2017.
> > > I was aware of this issue soon after starting the branch and
> > > had fixed it there, hoping to merge soon at the time, but
> > > long time has passed now.
> > So what about merging that and doing official MusE release soon? From my
> > point of view (thanks to latest commits) it's getting pretty stable now.
> > Last official release is quite dated and muse_3_0_pre2 has lots of bugs
> > comparing to master…
[ ... ]
> Merge may happen soon. As of today I finished some more heavy work.
> It compiles, plays complex test songs, and record tests OK.
> I rewrote my clumsy multi-writer-thread MPSC ring buffer template class.
> It's not a ring buffer, per se:
> One item array.
> One atomic bool inUse array.
> One atomic bool hasData array.
> No counters, pointers, increments, modulos etc. Just 'bins' !
> The trick is, thankfully, for safety and assurance the reader side
> needed to sort what it read from the buffer, by midi event timestamp.
> So it simply empties the event 'bins' into a sorted memory-pooled set.
> Now for the first time I just stress tested my branch.
> So far solid no concurrency issues. Wish me luck...

Great news! The exact name of the branch you mentioned is
`engine_fixes_2017`, isn't it? Just tested MusE from this branch.
Initially it failed to compile on Debian Stretch/gcc 6.3.0:

```
In file included from
/home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/synti/libsynti/gui.h:28:0,                                
                 from
/home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/synti/libsynti/gui.cpp:25:                                
/home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/muse/mpevent.h:281:13:
error: ‘ptrdiff_t’ does not name a type                  
     typedef ptrdiff_t difference_type;                                                                                                                        
             ^~~~~~~~~                                                                                                                                         
/home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/muse/mpevent.h:324:13:
error: ‘ptrdiff_t’ does not name a type                  
     typedef ptrdiff_t difference_type;                                                                                                                        
             ^~~~~~~~~
```

But after uncommenting just one include (as in attached trivial patch)
all passed without errors. Did rough tests and everything seems to work
fine so far. Good job!

Best,

      k.
-- 
Krzysztof Gajdemski | songo (at) debian.org.pl | KG4751-RIPE
Registered Linux User #133457 | BLUG Registered Member #0005
PGP key at: http://s.debian.org.pl/gpg/gpgkey * ID: D3259224
Szanuję was wszystkich, którzy pozostajecie w cieniu - Snerg

**Comment by terminator356** [comment]
On 11/06/2017 02:28 PM, Krzysztof Gajdemski wrote:
> Jest 06.11.2017, właśnie wybija 00:42:49, Tim pisze:
>  > On 11/05/2017 06:17 PM, Krzysztof Gajdemski wrote:
>  > > 05.11.2017, 21:44:55, Tim wrote:
>  > > > I cherry picked a fix from my branch midi_engine_fixes_2017.
>  > > > I was aware of this issue soon after starting the branch and
>  > > > had fixed it there, hoping to merge soon at the time, but
>  > > > long time has passed now.
>  > > So what about merging that and doing official MusE release soon? 
>  From my
>  > > point of view (thanks to latest commits) it's getting pretty stable 
> now.
>  > > Last official release is quite dated and muse_3_0_pre2 has lots of bugs
>  > > comparing to master…
> [ ... ]
>  > Merge may happen soon. As of today I finished some more heavy work.
>  > It compiles, plays complex test songs, and record tests OK.
>  > I rewrote my clumsy multi-writer-thread MPSC ring buffer template class.
>  > It's not a ring buffer, per se:
>  > One item array.
>  > One atomic bool inUse array.
>  > One atomic bool hasData array.
>  > No counters, pointers, increments, modulos etc. Just 'bins' !
>  > The trick is, thankfully, for safety and assurance the reader side
>  > needed to sort what it read from the buffer, by midi event timestamp.
>  > So it simply empties the event 'bins' into a sorted memory-pooled set.
>  > Now for the first time I just stress tested my branch.
>  > So far solid no concurrency issues. Wish me luck...
> 
> Great news! The exact name of the branch you mentioned is
> `engine_fixes_2017`, isn't it? Just tested MusE from this branch.
> Initially it failed to compile on Debian Stretch/gcc 6.3.0:
> 
> ```
> In file included from
> /home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/synti/libsynti/gui.h:28:0, 
> 
> from
> /home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/synti/libsynti/gui.cpp:25: 
> 
> /home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/muse/mpevent.h:281:13:
> error: ‘ptrdiff_t’ does not name a type
> typedef ptrdiff_t difference_type;
> ^~~~~~~~~
> /home/songo/src/debian/muse/muse-3.0.0git2017-11-06.1.engine-fixes-2017-1~son1/muse/mpevent.h:324:13:
> error: ‘ptrdiff_t’ does not name a type
> typedef ptrdiff_t difference_type;
> ^~~~~~~~~
> ```
> 
> But after uncommenting just one include (as in attached trivial patch)
> all passed without errors. Did rough tests and everything seems to work
> fine so far. Good job!

Missing the attachment, but I got it thanks a lot, it was missing
include <cstddef>

You'll notice a whole load of debug messages with this branch,
  that'll disappear.

Tim.
