### ISSUE TITLE
programing a synth 

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#594]
i'm looking in programing a the muse native string synths #593 with pure data is it possible to make a muse native synth using pure data?

**Comment by spamatica** [comment]
Hi, I'm not that aware of what you can do with puredata but as it is an
engine in itself that you create instruments in, I'm not so sure it is
possible to create something that can be integrated into MusE.
There is Faust which definitely can be used to create synths as plugins,
and possibly ChucK. They are probably harder than puredata for creating the
actual synth though.

--

I see the bug you created, I suppose you want synths that are installed
when you install MusE, I'm wondering if this is really necessary though. I
mean, synth plugins in general and VST instruments in particular are so
well known in the music industry, I think most music creators would be fine
with getting the synth they prefer from another source. For instance
ZynAddSubFX can be used as a plugin with MusE. When the VST or LV2 version
is installed it should appear in the softsynth menu of MusE automatically.


2017-11-26 4:09 GMT+01:00 Reaper10 <notifications@github.com>:

**Comment by Reaper10** [comment]
well i gong try to learn. i want to help more but i use window 10

**Comment by spamatica** [comment]
That is very nice of you and I wish you good learning. That said I think it
will be hard while you are using Windows 10.
I'm sure you have your reasons to stick to Windows but I would recommend
you to atleast create a dual boot on your computer so you can start MusE
from scratch.


2017-11-27 16:59 GMT+01:00 Reaper10 <notifications@github.com>:
