### ISSUE TITLE
bring a software sampler back from the dead to live again as a part of muse

### ISSUE THREAD

**Issue by Reaper10** [muse-sequencer/muse#596]
i think muse need a native sampler for keyboard players like all of these 

https://www.youtube.com/watch?v=lGhR-2v1y90
https://www.youtube.com/watch?v=RBEXXNvysmo
https://www.youtube.com/watch?v=Z9bwpn77Nq0
https://www.youtube.com/watch?v=nnxFQfxuta0
https://www.youtube.com/watch?v=Mb4EEWedQKM

for the Granular Synthesis can be made out this
https://github.com/passivist/GRNLR

![snapshot1](https://user-images.githubusercontent.com/8137561/33452763-e57cb2c6-d5d8-11e7-8cb2-893584d8694e.png)

[cheesetracker-0.9.9.tar.gz](https://github.com/muse-sequencer/muse/files/1519339/cheesetracker-0.9.9.tar.gz)
[chionic-1.0.1.tar.gz](https://github.com/muse-sequencer/muse/files/1519340/chionic-1.0.1.tar.gz)
This sampler isn't  realistic instruments like fulidsyth or Linux sampler are. This sampler is making new sounds using samples.  The heart of this sampler is the dead cheesetronic  sampler. This sampler should be able to read files like ACID or rex files. The built in  sound editor could be made out of parts of #581 
this replace #561 #504

**Comment by Reaper10** [comment]
why close this? muse needs sampler

**Comment by terminator356** [comment]
Reaper10 I told you before: Get serious.

Other projects have angrily called you out for doing this shit.
You are clogging our list with this crap.

One more word out of you which is NOT an actual bug report and
 I will report you to GitHub for inappropriate posting.

What you are doing is the equivalent of driving by someone's house
 and shouting "Hey, nice house but I think you should add this.."
 when in fact you've never set foot IN the house. Or even looked
 closely AT the house.

Get it? Shut up.

**Comment by Reaper10** [comment]
i'm so so so sorry

**Comment by terminator356** [comment]
Hi Reaper10 if you are still out there I am sorry for getting angry but this was not the place
 for these kinds of posts.
Our old forum is dead. We have a new forum at linuxmusicians.com. Look for the MusE forum.
You are welcome to start some topics there. The forum would be the place to post your ideas.
Some of these ideas would be very difficult to add, and may overlap with existing features.
Try to run MusE, see what it is all about, and help report bugs.
