### ISSUE TITLE
latest git update won't build on Arch64

### ISSUE THREAD

**Issue by funkmuscle** [muse-sequencer/muse#597]
hey, was just updating on Arch64 and ran into this:

`[ 83%] Building CXX object muse/CMakeFiles/core.dir/app.o
/home/harv/muse/muse3/muse/app.cpp: In member function ‘virtual void MusEGui::MusE::closeEvent(QCloseEvent*)’:
/home/harv/muse/muse3/muse/app.cpp:1579:17: error: ‘exitRtAudio’ is not a member of ‘MusECore’
       MusECore::exitRtAudio();
                 ^~~~~~~~~~~
/home/harv/muse/muse3/muse/app.cpp:1579:17: note: suggested alternative: ‘exitJackAudio’
       MusECore::exitRtAudio();
                 ^~~~~~~~~~~
                 exitJackAudio
make[2]: *** [muse/CMakeFiles/core.dir/build.make:551: muse/CMakeFiles/core.dir/app.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:519: muse/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
`

**Comment by spamatica** [comment]
A missing #ifdef, added now.
Another solution is to install the rtaudio devel package, then MusE will gain the ability to output to Pulse audio directly.

**Comment by funkmuscle** [comment]
I've installed RTaudio and now this:

[ 64%] Building CXX object muse/driver/CMakeFiles/driver.dir/rtaudio.o
/home/harv/muse/muse3/muse/driver/rtaudio.cpp: In member function ‘virtual
void MusECore::RtAudioDevice::start(int)’:
/home/harv/muse/muse3/muse/driver/rtaudio.cpp:506:27: error: exception
handling disabled, use -fexceptions to enable
   } catch ( RtAudioError& e ) {
                           ^
/home/harv/muse/muse3/muse/driver/rtaudio.cpp:508:5: error: ‘e’ was not
declared in this scope
     e.printMessage();
     ^
/home/harv/muse/muse3/muse/driver/rtaudio.cpp: In member function ‘virtual
void MusECore::RtAudioDevice::stop()’:
/home/harv/muse/muse3/muse/driver/rtaudio.cpp:520:5: error: ‘e’ was not
declared in this scope
     e.printMessage();
     ^
make[2]: *** [muse/driver/CMakeFiles/driver.dir/build.make:200:
muse/driver/CMakeFiles/driver.dir/rtaudio.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1086:
muse/driver/CMakeFiles/driver.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by spamatica** [comment]
I think this can happen when the build wasn't cleaned.
If you delete the contents of the build folder and try again it should be
fine.

We probably should be able to handle this in the build script but I'm not
sure how.



2017-12-21 19:25 GMT+01:00 funkmuscle <notifications@github.com>:

**Comment by funkmuscle** [comment]
that did it. cleaned out the build directory and it build. thanx! guess I can close this so I will.
