### ISSUE TITLE
Zynaddsubfx LV2 not working in Muse

### ISSUE THREAD

**Issue by therealkitman** [muse-sequencer/muse#599]
Hi,
as discussed in the mailing list, there may be an issue with Muse master `08806f44` with LV2 version of Zynaddsubfx v3.0.3.

Muse will load the plugin but when I open the native gui Muse puts it into the top left of my screen but I cannot move the dialogues box nor open any of zyn's boxes to edit instruments etc after trying to open zyn's virtual keyboard. I need to kill zyn.

I loaded the same LV2 of zyn into Carla and jalv without issues and runs ok. From memory versions of zyn prior to v3.0.3 were ok in Muse.

There wasn't much in the way of logs -

```
unknown NRT Msg 0x01
dump 4
7e 7f 09 01 
lo server running on 14511
Now respawning at 'osc.udp://localhost:14511/', using winId '37748937'
ext client running on 17524
midi list updating...
renameLink('/part0/ctl/pitchwheel.bendrange','/part0/ctl/pitchwheel.bendrange',0x2746430)
NOTICE: Child process exited while idle
LV2PluginWrapper_Window::~LV2PluginWrapper_Window()
```
but happy to debug as directed.

Thanks,
Chris.

**Comment by terminator356** [comment]
Hi, I just built and installed Zyn 3.03 but I cannot get ANY of the plugin
 guis to open. Not the DSSI, nor the linuxVST, nor the LV2.
In MusE all the 'native gui' popup menu selection are greyed out.
I configured with all options, nothing was missing (except tests).
Same problem in Ardour, no guis at all.

How did you manage to get it to work? What configure options? Etc.
Note that Yoshimi builds and works fine here with all plugins versions.

Thanks.
Tim.

**Comment by therealkitman** [comment]
Hi,
This is my build script for zyn - nothing special though it was the first time I saw documented that I had to download additional resources

```
cd ~/Downloads/git
git clone https://github.com/zynaddsubfx/zynaddsubfx.git zynaddsubfx
cd zynaddsubfx

#Download additional resources
git submodule init
git submodule update

mkdir build
cd build
cmake .. #don't build documentation.
ccmake .
make -j8
sudo make install
```

I have issues with the DSSI version, when loaded the dialogue box below if stuck in the upper left hand of the screen but no other settings for zyn are available.
![screenshot_20180103_101550](https://user-images.githubusercontent.com/14888092/34507266-5f9ea7de-f06f-11e7-8494-a8ed23430c9c.png)

This is what the LV2 looks like, again stuck in the upper left of the screen.
![image](https://user-images.githubusercontent.com/14888092/34507343-ffab5ca4-f06f-11e7-95da-973ff50e5985.png)

Hm, there is no DSSI gui available in carla either - must check that as I only focus on LV2 and VST. The VST is ok in carla too.

Only the VST version behaves properly in muse and is fully functional.

The cmake config results are here [https://pastebin.com/LECsUG49](url)
The ccmake config is here [https://pastebin.com/a7sYsnxw](url)

Regards,
Chris.

**Comment by therealkitman** [comment]
Also, for your interest, I compiled the latest version of helm and it loads as a LV2 in muse and functions ok. 

It must be murder to isolate a particular error for a particular plugin as spamatica mentioned in the mailing list.

> We had a problem some years ago with Zyn exposing some internal data which
> caused a conflict in MusE, if I recall correctly. Tim eventually found the
> cause after some arduous bug hunting. Could be that we have a similar
> problem again.

**Comment by terminator356** [comment]
Confirmed. LV2 not OK + VST OK in MusE, and LV2 OK in QTractor and Ardour, with today's git. 
The LV2 works OK in MusE on first open but after that does not show correctly.
Suspect need more work in recent commit which fixed lv2 gtk gui closing crash. The closing code.

**Comment by terminator356** [comment]
Sorry that's not gtk code. When configured for Non-ToolKit (ntk), that's an X11UI gui.
That's a slightly different section of MusE LV2 gui code.
Which makes me optimistic 'cause I've _not_ had to touch that section yet. Qt and Gtk yes.

**Comment by therealkitman** [comment]
That is interesting. I recompiled zyn with fltk and now I don't get a LV2, VST or DSSI gui in any host. But the binary of zyn works ok.
Food and sleep first :)

**Comment by therealkitman** [comment]
Ok, fed and rested :)

I pulled the previous version of zyn (3.0.1) that worked for me a year ago and compiled for fltk gui. The binary works fine but the LV2 gui just won't displau in muse or carla. Yoshimi fltk gui works ok.

This has to be either a zyn issue or I am missing something in my OS files. Will do a slow check on things over the next week.

PS. As a side test I downloaded the new beta zyn-fusion's LV2 as well and it has display issues too in muse and carla whereas the binary was fine (but with other issues).

**Comment by terminator356** [comment]
Pushed a failed attempt to fix the problem. Switched from using a QWindow to a QMainWindow
 parent container. Drawing is better but same problem - still won't open after the first time...

**Comment by terminator356** [comment]
All righty then...
Try 'er out now. I believe it should work. See the ChangeLog for details.
It ain't perfect with these types of GUIs, but seems the same as Adour and QTractor.

**Comment by therealkitman** [comment]
I've lodged the problem to zynaddsubfx dev team as I can't get any zyn 
plugin gui to work.

Still trying to sort out if something went 'pear shaped' on my system. 
Going to spend the weekend building all key audio libraries (lv2, suil, 
sord etc) into packages for easier management and hopefully will find 
something.

**Comment by therealkitman** [comment]
Excellent. Will test this out after I have cleaned my libraries up a bit.

**Comment by spamatica** [comment]
Reopen if this still is an issue
