### ISSUE TITLE
Save dialog values for metronome etc [sf#1092421]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#60]
Submitted by lunar_shuttle on 2004-12-28 22:59:03

When using pianoroll + drumeditor functions that issue 
commands in the canvas, values are not stored correctly (f.ex. 
when using modify velocity - the selection 'apply to selected 
events' is not preselected next time)

**Comment by kybos** [comment]
Obviously corrected in the meantime, it's working now.
