### ISSUE TITLE
Crashes during plugin loading --> FEATURE:plugin cache

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#608]
MusE should get a dedicated plugin cache update process externally to muse (like most other softwares do it) since plugins tend to be buggy and touching _all_ of them at startup is a recipe for disaster.

Been looking at it and it looks a bit daunting to support all plugin formats though..
I'm thinking to use the plugin-load functions from a separate application and for each loaded plugin store it's metadata in a persistent file (that can be read by muse to recreate the plugins and synths lists).
 
While loading a specific plugin create a file with the path to the currently loading plugin which is removed when it is finished, this way, if such a file exists upon startup of this application we black-list the plugin in the file as it most definitely crashed the program.

**Comment by windowsrefund** [comment]
I probably have no idea what you're talking about but will ask if [Carla ](http://kxstudio.linuxaudio.org/Applications:Carla) can/should fit in here?

**Comment by spamatica** [comment]
If you wish you can use Carla as a plugin host and interface Carla from MusE, that is true, but for many use cases I think that would be too clunky, requiring a lot of extra work to use plugins.

**Comment by spamatica** [comment]
The basics of this is very much in place now and crashes are very far between now :)
