### ISSUE TITLE
feature request: make hard-coded quarter note values optional

### ISSUE THREAD

**Issue by windowsrefund** [muse-sequencer/muse#618]
When working within Piano Roll & Drum Editor, I really find the hard-coded (2, 3,4) that repeats inside every measure to be really distracting. Can the display of these numbers be made optional?

http://imgur.com/IfF1LT1l.png

**Comment by kybos** [comment]
This is already possible with the font settings:
Appearance->Fonts->Set the size of font no.4 to 1
