### ISSUE TITLE
Tempo jumps randomly when adding Drumgizmo LV2 plugin

### ISSUE THREAD

**Issue by windowsrefund** [muse-sequencer/muse#619]
MusE version: latest git master compiled this evening
MusE global settings > Audio > Audio Backend = Jack Audio (default)
Jack is running and not throwing Xruns, etc..

Steps to reproduce:

1. Start new project (tempo defaults to 120bpm)
2. Create a single drum track
3. Draw a region of 8 bars on the drum track
4. Set loop markers for measures 1 through 8
5. Play the (empty) loop with metronome activated

At this point, metronome is in time and bpm can be modified in real-time. All good...

Tempo is now at 110bpm

Next, add a new Synth; select Drumgizmo (latest version) LV2 plugin
The project's tempo now jumps back to 120bpm (I didn't touch it)

Start the loop playback. Attempts to increase or decrease the temp now results in the bpm jumping randomly.

Worth noting is the following:

$ ls -l /dev/rtc
lrwxrwxrwx 1 root root 4 Aug  4 05:09 /dev/rtc -> rtc0
$ ls -l /dev/rtc0
crw-r----- 1 root audio 249, 0 Aug  4 05:09 /dev/rtc0
$ ls -l /dev/hpet
crw-r----- 1 root audio 10, 228 Aug  4 05:09 /dev/hpet
$ groups | grep -q audio && echo "yup"
yup
$ cat /sys/class/rtc/rtc0/max_user_freq 
3072

Feel free to let me know of any additional information that would be useful

**Comment by windowsrefund** [comment]
I guess I did not have the "use tempo master track" button pushed down. I thought when it was green, it would have been activated. I guess it is when it's dark.

**Comment by terminator356** [comment]
Er, actually it's the other way around.
Green for master track enabled.
I have not tested the new tempo fixes (of a few months back) with DG yet, 
lemme know if you still have trouble and I will try it out.
