### ISSUE TITLE
feature request: keybindings used to open panels should toggle

### ISSUE THREAD

**Issue by windowsrefund** [muse-sequencer/muse#620]
For example, assuming the user binds F2 to open the Piano roll...

User presses F2, Piano Roll is displayed

User works...

User presses F2 again and Piano Roll closes

Ideally, this work-flow would scale to all panels that can be assigned to open via key bindings.

Of course, I can envision some questions such as what would/should happen if a panel is open and the user wants another panel (the same type) opened for a different track? Perhaps this means the key binding would only toggle against a particular panel if that panel has the focus?

**Comment by windowsrefund** [comment]
Just wanted to add I've noticed the Esc key does close some windows and whatever I bind to some other panels does act as a toggle (to close). It's not consistent however and I'm not in front of my DAW to provide a complete list.

**Comment by spamatica** [comment]
All the windows in the View menu should now toggle open/close with their shortcuts (except Clip list but it is as yet useless)
Most dialogs are closed with ESC.
Editors are also a special case, as you mention there is the question what would happen if you want multiple editors. The solution for the moment is to close with ESC as with dialogs.

There are some minor windows, like midi-plugins that do not behave uniformly. 
We should maybe improve this further, leaving open for now..
