### ISSUE TITLE
carla-* lv2 plugins

### ISSUE THREAD

**Issue by windowsrefund** [muse-sequencer/muse#622]
Latest MusE is compiled from master.

Carla plugins from the kxstudio repo
```

$ dpkg -l | grep carla
ii  carla-data                                    2:1.9.9+git20180824v5                  all          audio plugin host (common data)
ii  carla-git                                     2:1.9.9+git20180824v5                  amd64        audio plugin host
ii  carla-lv2                                     2:1.9.9+git20180824v5                  amd64        audio plugin host (LV2 plugin)
```

LV2 plugin loads fine. Here's what I see when I add a track pointing to the Carla-patchbay lv2

[show native gui](http://i.imgur.com/6dkVUSJ.png)

However, maximizing renders this:

[Maximized](http://i.imgur.com/LTYIorO.png)

Same thing goes for Carla-rack

**Comment by kybos** [comment]
Working in current master, closing...
