### ISSUE TITLE
Issues compilation Muse 3

### ISSUE THREAD

**Issue by PabloTassi** [muse-sequencer/muse#625]
Hi guys,
I'm having some issues when I compile the trunk version of Muse. Please find below the error message, where compilation stopped at 92%. The uname -a gives: 
Linux pablo 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Is there maybe any library missing? Do you have any hint?
Many thanks for your help,
Cheers,
Pablo

[ 91%] Building CXX object muse/CMakeFiles/core.dir/vst.o
[ 92%] Building CXX object muse/CMakeFiles/core.dir/vst_native.o
/home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp: In member function ‘virtual void MusECore::VstNativeSynthIF::showNativeGui(bool)’:
/home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp:1525:25: error: invalid conversion from ‘unsigned int’ to ‘Qt::WindowType’ [-fpermissive]
                   | Qt::WindowCloseButtonHint;
                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1102:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdir.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDir:1,
                 from /home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp:28:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:111:29: note:   initializing argument 1 of ‘constexpr QFlags<T>::QFlags(Enum) [with Enum = Qt::WindowType]’
     Q_DECL_CONSTEXPR inline QFlags(Enum f) Q_DECL_NOTHROW : i(Int(f)) {}
                             ^
/home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp: In member function ‘virtual void MusECore::VstNativePluginWrapper::showNativeGui(MusECore::PluginI*, bool)’:
/home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp:3612:41: error: invalid conversion from ‘unsigned int’ to ‘Qt::WindowType’ [-fpermissive]
                                   | Qt::WindowCloseButtonHint;
                                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1102:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qdir.h:37,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QDir:1,
                 from /home/pablo/MusicStudioPablo/applications-git-install/muse/muse3/muse/vst_native.cpp:28:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qflags.h:111:29: note:   initializing argument 1 of ‘constexpr QFlags<T>::QFlags(Enum) [with Enum = Qt::WindowType]’
     Q_DECL_CONSTEXPR inline QFlags(Enum f) Q_DECL_NOTHROW : i(Int(f)) {}
                             ^
muse/CMakeFiles/core.dir/build.make:1723: recipe for target 'muse/CMakeFiles/core.dir/vst_native.o' failed
make[2]: *** [muse/CMakeFiles/core.dir/vst_native.o] Error 1
CMakeFiles/Makefile2:598: recipe for target 'muse/CMakeFiles/core.dir/all' failed
make[1]: *** [muse/CMakeFiles/core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by terminator356** [comment]
Hello. Thank you for the report.
A fix has been pushed to git master. Try it now !

Also one more thing: I noticed this line above:
[ 91%] Building CXX object muse/CMakeFiles/core.dir/vst.o
Strange. I think that is our very old vst module. Not sure how it built without errors for you,
 because it depends on the ancient 'fst' package. Is it possible you have ENABLE_VST
 set when you configure cmake? It ususally should not be set, unless you somehow
 managed to get the ancient 'fst' package to install. (If so, how did you do that?)

Thanks.
Tim.

**Comment by PabloTassi** [comment]
Hello Tim,
Many thanks for this correction. It compiles perfectly now, I'll close this issue.
Regarding the point that you noticed at 91%, I really don't have any idea...I just followed the instructions for compilation and installation from the README.

Best wishes,

Pablo
