### ISSUE TITLE
Mastertrack listeditor undo handling behaves strange [sf#1094264]

### ISSUE THREAD

**Issue by Windfisch** [muse-sequencer/muse#63]
Submitted by lunar_shuttle on 2005-01-02 02:03:07

The undo handling for the mastertrack listeditor behaves 
strange (especially for time signature events). This probably 
has to do with tick-values changing after events are deleted or 
added etc + internal list handling. Applies to both HEAD and 
REL07.

**Comment by kybos** [comment]
Confirmed.
The master list editing is generally quite buggy and even leads to crashes.

**Comment by kybos** [comment]
I had fixed most of the editing bugs and crashes. I see no apparent problem with the undo, so closing this.
This editor seems to be hardly used anyway, as nobody complained about the many existing problems.
