### ISSUE TITLE
GCC 8.2, jack2, python 3.7

### ISSUE THREAD

**Issue by aquilarubra** [muse-sequencer/muse#631]
Hi, the build in Arch was a bit outdated, so I updated it. In the middle of that, I upgraded GCC to 8.2 (I don't know why it was requesting gcc 6) and to jack2. I also patched the package to allow python 3.7. It all worked well. I attach the PKGBUILD below. You can see the "sed" instruction to enable python 3.7 and you may want to update MusE code.
Some systems (notably Debian) seem to have some issues with GCC 8.2, but that's SID anyway. It will be probably fixed in the future.

[PKGBUILD.txt](https://github.com/muse-sequencer/muse/files/2612892/PKGBUILD.txt)

**Comment by terminator356** [comment]
Going over some old stuff:
Hey @spamatica and @kybos, what should we do with this?

**Comment by kybos** [comment]
Ask the OP to provide a pull request if it's still relevant?

I assume "python" means the python remote API here? According to the README/wiki, it is already compatible with python 3.
The first two sed commands add #includes to python-unrelated files - why should that be necessary?

**Comment by spamatica** [comment]
As I was just dipping my toes into packaging. I at least added it to the packaging folder in git. Arch tend to stay fresh so they probably have more recent build scripts now.

**Comment by dvzrv** [comment]
@spamatica I would abstain from adding package scripts to this repository.

All distributions take care of their package scripts in separate infrastructure anyways. Tracking them here is redundant and potentially error-prone.

**Comment by spamatica** [comment]
That is true... 
Though as I have a long term plan to provide daily build packages we need to keep packaging files somewhere, any suggestions how to do this in a packager friendly way?

**Comment by dvzrv** [comment]
The way to go there would be to e.g. use the [muse-git PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=muse-git) as is offered in the AUR and build from that.
Then publish your package in a [custom user repository](https://wiki.archlinux.org/index.php/Unofficial_user_repositories), that users can use with the package manager.

This at least would be the way for Arch Linux. For Ubuntu et. al there is custom ppas for this purpose.

**Comment by kybos** [comment]
What is left to be done here?
Remove the obsolete arch build script from MusE repo and close this issue?
I agree with @dvzrv that the MusE repo is not the right place for it..

**Comment by spamatica** [comment]
If that is the consensus might a swell remove it. Guess it goes for all other package creation files in there too? 
What about the AppImage, it is there too right?

**Comment by kybos** [comment]
I meant only the arch subdir, which hardly makes sense here.
As for ubuntu/debian: I think those were your experiments - if you want to proceed with them, I see no harm in keeping the files. If not, feel free to delete them.
The main "packaging" dir should remain, as some metadata (I think there are no scripts) from there is needed by the AppImage and also the Flatpak, AFAIK.

**Comment by spamatica** [comment]
I'm probably dense but why does the arch package file not make sense and the ubuntu one is ok, aren't both configuration for creating a package?

**Comment by dvzrv** [comment]
@spamatica I can only speak for the Arch situation: As mentioned [here](https://github.com/muse-sequencer/muse/issues/631#issuecomment-647570780), the PKGBUILD would ideally be maintained in the [AUR](https://aur.archlinux.org), not here.

I don't know if Ubuntu et al offer similar infrastructure for hosting build scripts for packages in custom binary repos. However, something like openSUSE's [OBS](https://openbuildservice.org/) comes to mind.

Build scripts for packaging are generally best kept separate from the source code, as they introduce extra merges on the repo (but might depend on how you like to maintain things of course).

**Comment by kybos** [comment]
Yes, there is no central infrastructure (like AUR) for .deb packages. At least to my understanding, .deb packages are usually maintained (and distributed) by the software owners themselves, presumably from their original repos in most cases.
For Ubuntu PPAs it's a little different, but I think that's not the question here.

**Comment by spamatica** [comment]
Ok, I understand the logic. Don't necessarily agree but I don't feel strongly enough about it to argue ;) 
The arch package is now removed so this should conclude the issue, closing.
