### ISSUE TITLE
Text too small on HiDPI

### ISSUE THREAD

**Issue by hfiguiere** [muse-sequencer/muse#638]
Some of the text is way too small on some UI like "select plugin" dialog.

![image](https://user-images.githubusercontent.com/114441/52459885-af8c9d80-2b35-11e9-902c-f50139649a69.png)

**Comment by kybos** [comment]
I'm just trying to fix that on my local copy of MusE:
![image](https://user-images.githubusercontent.com/10009541/67892034-28180c00-fb54-11e9-8544-9d307965b841.png)
I know of this dialog ("select plugin"), and the Track name change dialog. Are there more of this kind (with too small fonts)?
I will try and learn about that pull request business and then perhaps propose the fixes to the upstream.

**Comment by kybos** [comment]
Fixed in master.
