### ISSUE TITLE
metronome don't work correctly

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#643]
Bonjour,

When setting bar to 6/8, midi metronome don't give a bar sound, just the beat ones. When using audio, it's the same except when selecting old fashion metronome with two samples.

On an other hand, it would be nice for bars like 6/*, 9/*, 12/* (where * means 4 or 8 or 16 or why not 32 )  that the bar sound apply to each time  (2 for 6/*, 3 for 9/* and so on) and not only on the first beat of the bar. I said «time» but perhaps it's not the right english word. I put in bold the times I would like to listen  as a bar sound in 6/8 : **1** 2 3 **4** 5 6

cordialement,

**Comment by terminator356** [comment]
Observed !
I also observed some other strange problems.
Please wait... checking....
Thank you.

**Comment by terminator356** [comment]
Hey there! I fixed some things. In git master now. Metronome super-makeover:
Please see this announcement for details (with pictures), or just get the git master:
https://linuxmusicians.com/viewtopic.php?f=61&t=19795

Hopefully it will do what you want now.
I thought about making the beats user-selectable as well,
 but for now only the accents are done, we'll see if we can add more later.
Check it out.
Thanks.
Tim.

**Comment by moebius1** [comment]
Bonjour,

Thank for the job : I'm going to test that as soon as possible.

Bon dimanche,


Le 23/03/2019 à 23:27, Tim a écrit :

**Comment by moebius1** [comment]
Metronome works fine now, thank you for the job

cordialement,

**Comment by spamatica** [comment]
Closing as the issue was taken care of
