### ISSUE TITLE
Auto return?

### ISSUE THREAD

**Issue by pdesaulniers** [muse-sequencer/muse#644]
Hi!

Does MusE support something like Ardour's "Auto Return" feature? If so, I couldn't find it in the program.

When this mode is enabled, stopping the playback should also move the playhead back to wherever it was when the playback was started.

In case MusE does not support this feature already, I think it would be a nice addition.

**Comment by pdesaulniers** [comment]
OK, it seems like this feature is not supported, so I have implemented it in a fork: https://github.com/pdesaulniers/muse/commit/61358dc4c0d3989d4719579a943c7c3352162b10

Should I expose this feature in the UI and send a pull request? If so, what would be the preferred way of exposing this feature in the UI?

**Comment by terminator356** [comment]
Sorry for the delayed reply. Looks OK to me, seems would do no harm if turned off.
First impulse is to throw it into the 'GUI Behaviour' tab of the Global Settings,
 where a lot of things end up.
But it's not really a GUI behaviour thing.
Nor is it specifically an Audio or Midi tab candidate.
Hmm... Probably the Audio tab under 'Mixer'. If not then the GUI Behaviour tab.
Either way it won't be obvious to the user.

So I would not complain if you made a new tab 'Transport' or 'Transport Behaviour'.
It would be a lonely entry for this new tab so we could move a couple of other things 
 in there as well to 'fill it out' a bit. For example the 'Try to use Jack freewheel' setting...
I can take care of that if you wish.

Feel free to submit a pull request when ready.

**Comment by spamatica** [comment]
This is implemented in master now. Sadly I didn't pay attention that there was already an implementation for it here so I did it from scratch.. oh well.
