### ISSUE TITLE
Enhance shortcut conflict detection

### ISSUE THREAD

**Issue by drautzburg** [muse-sequencer/muse#647]
In short, it is quite difficult to define a Global Keyboard Shortcut.

I tried to define shortcuts for `goto previous/next marker`. MusE faithfully warned me, if the key combination was already used for another shortcut. I finally settled for **alt+left** and **alt+right**.

This worked fine when one of the following views were open and focused:
- Edit Instrument
- Bigtime Window
- Cliplist
- Marker View

but it did not work fin the arranger view.  Since I suspected that these key-combinations were already taken by something else, I changed them to **Ö** and **Ä** and this did work in the arranger view. However they don't work in the Marker view. I don't know why.

Apparently the conflict detection is too simplistic. E.g. you can define **alt+F** as a shortcut even though in the arranger, this is already taken for the **File** menu.

**Comment by kybos** [comment]
Tested - Alt+left/right for goto markers works fine in Arranger (and other editors).

As for the missing conflict check between access keys/mnemonics and shortcuts: It's not nice but I don't think this can be done. They are technically unrelated and even Qt's own QtCreator can't do it. 
The same goes for conflicts with various Window managers, which occur quite often with Alt/Meta/Super+ shortcuts in Linux.
