### ISSUE TITLE
Playback after loading start a little bit after

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#648]
Bonjour,
This is a longtime behavior that I never took time to mention.
In fact, when loading a song and positioning play cursor to the beginning and then click start, the song playback don't start at beginning but a little bit (one bar it seems) after. But, when doing same things next times, everything is OK. The bug comes only just after loading the song.
Another thing : this happens only if there's no active midi tracks, just audio ones. The muse version has been compiled today after cloning git repository.

Thank for the great job you make.

cordialement,

**Comment by terminator356** [comment]
You may be experiencing a long-time bug concerning our audio wave prefetch cache FIFO.
If you run MusE in a terminal and you see messages like this when pressing 'Play',
 then it is the bug:
`
FIFO 0xda8d600 underrun
WaveTrack::getData(Playback track) (A) fifo underrun
`
I hope to have a fix for this relatively soon. Keep the issue open for now.

A workaround for now, which is **guaranteed** to work:
After loading a song, please grab the red play head cursor
 and move it back and forth, roughly about 2 or 3 bars.
This forces our wave FIFO prefetch cache to re-load the correct portions.
Then the error messages should not appear.

Thank you.
Tim.

**Comment by moebius1** [comment]
Bonjour,
Thank, I'll do that ; anyway, it's just a micro problem.

cordialement,


Le 15/05/2019 à 00:59, Tim a écrit :

**Comment by terminator356** [comment]
Hello. I have finally fixed the 'fifo' bug that I mentioned above. In git master now.
Hopefully it fixes your reported issue.
The 'fifo' error messages should not appear any more after loading a song and playing it.

**Comment by moebius1** [comment]
Bonsoir,
Fine, thank you a lot.
cordialement,
