### ISSUE TITLE
https://muse-sequencer.org/ has some phpBB school forums site, and has a broken https certificate

### ISSUE THREAD

**Issue by yurivict** [muse-sequencer/muse#654]
It would be better if https://muse-sequencer.org/ was the muse sequencer's page.

**Comment by terminator356** [comment]
This is a task for Robert (or Andrew?).

**Comment by spamatica** [comment]
Andrew has added a working certificate now so we can use the https url.
There are some links internally in the wiki that point to http resources which cause the brower to report 'not fully secure' for some pages. This will be dealt with over time. Closing as the certificate has been fixed.
