### ISSUE TITLE
Feature Request: Add non session management capability

### ISSUE THREAD

**Issue by alextone** [muse-sequencer/muse#657]
This is an FR suggesting Non Session Management capability is added to Muse to enable full session control.

http://non.tuxfamily.org/wiki/Non%20Session%20Manager

**Comment by grammoboy2** [comment]
+1

It's the session manager which is supported by the JACK developer now.
http://non.tuxfamily.org/nsm/API.html

**Comment by terminator356** [comment]
> It's the session manager which is supported by the JACK developer now.

Is that official?
I read some proposals of them removing Jack Session because no one was using it.
But what does this mean? Is NSM built in to Jack now?

**Comment by grammoboy2** [comment]
On 23-02-2020 19:09, Tim wrote:
>
>     It's the session manager which is supported by the JACK developer now.
>
> Is that official?
> I read some proposals of them removing Jack Session because no one was
> using it.
>
It means that the JACK developer recommends developers to add nsm
support instead of jack-session.

https://media.ccc.de/v/sonoj2019-1902-jack-past-present-future


> But what does this mean? Is NSM built in to Jack now?
>
No, there is no such magic unfortunately. :)

There are examples (python, C, C++) available I think, but you've to do
the work yourself.

(Python here: https://github.com/diovudau/pynsm2)

(/This file represents a reference implementation of the client
interface in the form of a single C header file (permissively licensed)
which can be copied into your project's source tree:/

http://git.tuxfamily.org/non/non/?p=non/non.git;a=blob_plain;f=nonlib/nsm.h;hb=HEAD


)

Other examples here:

http://non.tuxfamily.org/wiki/Non%20Session%20Manager

**Comment by terminator356** [comment]
Gotcha. Thanks for the references.
Been following NON (from a distance) since day one when it was announced.
NSM did seem like the better choice over Jack Session.

**Comment by grammoboy2** [comment]
Ah cool to hear that you're positive about it.  Jack-session was just
too limited and just didn't solve the 'session problem' well enough for
users. NSM does what it should do and does it well I think.

**Comment by terminator356** [comment]
Late reply. This is still on the radar.
Some investigations, done some months ago:

First, we have OSC support. Currently it's used for DSSI. Obviously it needs to respond
 to more commands, in the nsm domain, beyond the dssi domain in our DSSI support,
 and then our callback will marshall them out to either our dssi or nsm code.
Should be straightforward. I read the recommended nsm example is IIRC to use 'server' 
 paths and calls, so I saw that we do need to **switch** our calls over to the 'server' variants.

Next, nsm rules and guidelines:
As expected with any session manager, there are rules and nsm lays them all out.
There are strict rules. We currently support LASH and it has fewer rules.
An careful examination of the current flow of code and how each nsm rule would fit in
 revealed it's certainly achievable and we do already adhere to some of the rules,
 but there's not so simple work to be done.

Finally, I saw QTractor apparently supports both nsm and jack session at the same time.
I wondered if nsm and LASH could co-exist. But it appears not.
So I think we may need to make our nsm and LASH support, and their cmake options,
 mutually exclusive. Or completely remove LASH. It's old, but still supported by LADISH
 emulation, but the worry is users with archived song projects and sessions out there
 might want it.

**Comment by grammoboy2** [comment]
Which is nice, but you'd probably want to discuss it with @falkTX or @diovudau.

**Comment by grammoboy2** [comment]
About :switch: 
https://linuxmusicians.com/viewtopic.php?f=44&t=21404

**Comment by falkTX** [comment]
you dont need to remove one for the other, why do you that is the case here?
but, it would perhaps be a good idea to remove lash in a "new feature" release at some point, when nsm is implemented.
nsm is quite handy for session management, and now basically the chosen SM from the devs still working on such things.
as the current JACK maintainer, I can tell you that now with new-session-manager announced, I am quite comfortable setting the jack-session API has deprecated, leaving a note in the official API to use NSM instead. Will do that for next release of jack2 already

the more applications we get on-board with nsm, the better.
having to wonder what apps support which SM and which don't is really a pain and very frustrating.

if you have any questions regarding NSM, I am available to answer.
I did a both a client and server implementation of it, so I know it reasonably well by now.

**Comment by diovudau** [comment]
Right, there is no need to keep LASH, Jack-Session nor LADISH around. All are either abandoned or explicitly deprecated.

**Comment by terminator356** [comment]
Thanks for the help! Can't promise anything soon 'cause we're always
 up to our necks in bug doo-doo. But... ye just never know with me....
