### ISSUE TITLE
What the hell is the application file?

### ISSUE THREAD

**Issue by mightycoffee** [muse-sequencer/muse#658]
There's like a million files in this thing, and I can't find one that opens the program.

**Comment by terminator356** [comment]
???
Are you sure you've posted to the right project?
We don't have such a thing.
Are you talking about AppImage? We don't have an AppImage yet.

**Comment by spamatica** [comment]
It is true that there are a lot of files here but as it is unclear what the submitter meant and no further communication has occured, I'm closing.
