### ISSUE TITLE
Didn't succeed to sync my hardware from muse

### ISSUE THREAD

**Issue by MikHulk** [muse-sequencer/muse#661]
Hi,

I run Muse on Arch linux from AUR https://aur.archlinux.org/packages/muse/.

I have some issues to synchronize my hardware from.

First I didn't get the screen wich is documented here: http://muse-sequencer.org/index.php/Window_Reference_Guide#Midi_Sync . It is another 

Second, I tried to configure it, thanks to tooltip, but I got no midi clock. However, midi sync on another software on the same system. How can I configure a midi sync cout ? 

Thx

**Comment by terminator356** [comment]
Hello. Some parts of the manual are far too old :-(
Let's have a look at the current state:

![Midi syc 5](https://user-images.githubusercontent.com/5422362/62882541-1c107100-bd00-11e9-9ca1-c721d67d098b.jpg)

Steps for synchronizing MusE to/from external hardware:

1) Decide whether you want to sync MusE from external hardware (MusE is **slave**)
or sync external hardware to MusE (MusE is **master**).

2) Decide which midi protocols to use: Real Time, MMC, or MTC.
Most decent midi hardware supports Real Time. Some might support MMC or MTC.

3) Open the Midi Sync dialog and set up the table:
Some columns "c k r m t type" are simply 'indicators' while others are checkable.
In the picture shown, my external drum machine is connected to 
 MusE port 1 "MidiSport 2x2 Midi 1".
Click the "s" column for the row of your desired device.
The **red** light shows that if MusE is to be a **slave**, then MusE will sync
 to port 1's midi clock (or MTC quarter-frame). ('A' in the picture.)
My drum machine continuously sends out midi clock, always. Some hardware only
 sends clock when playing. The picture shows that indicator column "c" is checked
 indicating yes, we are receiving clock from port 1.

The columns "r m t" flash briefly when Real Time, MMC, or MTC commands
 have been detected from the device. Press a few buttons such as play or rewind
 on your external device and notice they flash.

The columns "rc rr rm rt" are checkable.
If you want to recognize midi clock from the device, click "rc".
If you want to recognize Real Time commands such as play, stop etc, click "rr".
If you want to recognize MMC or MTC commands, click "rm" or "rt".
('B' in the picture.)

Similarly, the columns "tc tr tm tt" are checkable.
If you want to transmit midi clock to the device, click "tc".
If you want to transmit Real Time commands such as play, stop etc, click "tr".
If you want to transmit MMC or MTC commands, click "tm" or "tt".
('C' in the picture.)

And finally, the checkbox "Slave to external sync" actually switches MusE
 into **slave** mode and if the table is correct, it will respond to all that is checked.
But it sounds from your post that you want **master** mode.
So you would leave "Slave to external sync" unchecked in this case.
('D' in the picture.)

In **slave** mode, all the "r*" columns are relevant.
In **master** mode, all the "t*" columns are relevant.

For quick access, the "Slave to external sync" function is duplicated
 in MusE's Transport Panel (shown as a 'clock' icon in recent MusE).

Good luck...

**Comment by MikHulk** [comment]
Hello,

Very thank you for this detailed explanation. I am going to try it.

**Comment by MikHulk** [comment]
Ok It works if midi sync go directly through ALSA, but not if I pass through a2jmidid. I had to create an alsa device in muse. I need to use a2jmidid for note on/note off however. I made a short test I will retry this weekend. thx

**Comment by terminator356** [comment]
Wait ! Looks like a bug !

Tested: Our Jack Midi devices are **not** sending midi clock unless the 'ALSA' button
 is clicked in our Midi Ports / Soft Synth Configuration dialog.
When the 'ALSA' button is clicked, a2jmidid and our Jack devices work OK.
Tested OK with my drum machine through a2jmidid.
The listed ALSA devices do not even have to be assigned to any MusE ports,
 just the ALSA button clicked.

This sure looks like a bug. Please wait... checking...
Thanks !

**Comment by terminator356** [comment]
Ah! I think I know what's wrong.
Several years ago I made ALSA support optional.
So I added the ALSA button, and it completely disconnects MusE from ALSA.
But there's the problem, I believe.
I never got around to providing true native Jack midi clock - it is driven
 by our ALSA timer, which is disabled when the ALSA button is unchecked !

D'oh! I should have finished that Jack midi clock code...
Please wait, it may take some time to fix.

For now, please simply make sure the ALSA button is clicked in the midi config dialog ;-)

Thanks.
Tim.

**Comment by MikHulk** [comment]
Hi,
I'm glad I found this bug. I will check Alsa button. Thank you for your help. I will try this next weekend.

Thanks again
