### ISSUE TITLE
Select background color freezes muse

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#662]
If I go to

Settings > Appearance Settings > Colors

and then

Arrange > Part Colors > part.canvas.background

and then click

Choose color... (or click the big color box)

Muse freezes and I get the following in terminal:

(muse3:2612): GLib-GObject-WARNING **: 08:32:31.442: cannot register existing type 'GtkWidget'
(muse3:2612): GLib-GObject-WARNING **: 08:32:31.442: cannot add class private field to invalid type '<invalid>'
(muse3:2612): GLib-GObject-WARNING **: 08:32:31.442: cannot add private field to invalid (non-instantiatable) type '<invalid>'
(muse3:2612): GLib-GObject-CRITICAL **: 08:32:31.442: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(muse3:2612): GLib-GObject-WARNING **: 08:32:31.442: cannot register existing type 'GtkBuildable'
(muse3:2612): GLib-GObject-CRITICAL **: 08:32:31.442: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
(muse3:2612): GLib-CRITICAL **: 08:32:31.442: g_once_init_leave: assertion 'result != 0' failed
(muse3:2612): GLib-GObject-CRITICAL **: 08:32:31.442: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
(muse3:2612): GLib-GObject-CRITICAL **: 08:32:31.442: g_type_register_static: assertion 'parent_type > 0' failed
(muse3:2612): GLib-GObject-WARNING **: 08:32:31.442: cannot add private field to invalid (non-instantiatable) type '<invalid>'

Muse version: 3.1.0pre1 (I run with "muse3 -A")
Debian 10 Buster stable with XFCE4
![muse3crash](https://user-images.githubusercontent.com/33361311/64917859-d549e700-d795-11e9-8f8f-6138e466a7bc.png)

**Comment by spamatica** [comment]
Hej Staffan,

The errors in the console suggest that you are using a style based on Gtk
and it's that style that is misbehaving. I tried here but could not
reproduce the problem.
Please try to switch to another style and see if the problem persists.
In the next tab you can select another style (active after you pressed
Apply and MusE has restarted).

Den sön 15 sep. 2019 kl 08:50 skrev StaffanMelin <notifications@github.com>:

**Comment by StaffanMelin** [comment]
Thank you for your quick answer!

I have tried all three styles, "Keep QT system style", "Windows" and "Fusion", and pressed Apply and restarted before trying to change that background color. Yet Muse still freezes.

Junk left in my configuration file? Can I reset it somehow? Or something to do with my XFCE4 theme -- I use it with the standard XFCE theme.

**Comment by terminator356** [comment]
Hello.
You can try deleting ~/.config/MusE/MusE.cfg and/or MusE-qt.conf.
MusE will re-create them.

Other users have been having problems with Gnome and/or XFCE.
The user drautzburg reports problems with the Project Save Dialog, 
 and our fluidsynth MESS synth's soundfont loading dialog,
 with details to reproduce the freezing.
Please see https://github.com/muse-sequencer/muse/issues/646

Can you reproduce the complaints given there?

It looks like a Gnome lib or Gnome window manager problem.
Some research indicated the errors are a common problem with some other apps too.
Not sure how much XFCE has to do with it.
I cannot install a new distro at the moment. I wish I could, I'd like to see what is going on.

Tim.

**Comment by StaffanMelin** [comment]
Hi!

Delted configs, still freezes.

Tried to replicate  drautzburg's 2 problems (Save project and Load soundfont) but both work fine on my system.

I next removed the package qt5-gtk-platformtheme. Problem disappears and I can see the color picker.

Running on a new installation of Debian 10.1, stable, with XFCE.

**Comment by terminator356** [comment]
Ah, so qt5-gtk-platformtheme really was the problem?
Now I remember: Some research indicated that package is causing problems for other apps too.
Strange how it affects users differently.
Good to hear that it works for you now.

**Comment by StaffanMelin** [comment]
Thank you for your help!
