### ISSUE TITLE
Feature Request: Make mouse action for set left loop-point definable by user

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#663]
Hi!
Set Left Loop point is controlled by Middle Mouse click.
I often run MusE on a laptop, so I can't middle click. Alt-P is useful, and I know I can set the loop point manually using Transport.
But I would like to use something like Ctrl+Left click.

**Comment by spamatica** [comment]
Not 100% the way you want it but there is a setting already in the
GlobalSettings->GUI Behaviour to change it to Ctrl+Right click.


Den mån 16 sep. 2019 kl 16:01 skrev StaffanMelin <notifications@github.com>:

**Comment by StaffanMelin** [comment]
That is great, thanks!
