### ISSUE TITLE
Program crash (segfault)

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#666]
Hello,
I get a consistent crash on doing the following:

1. Open MusE with default template.
2. Add any soft synth track (e.g. Deics).
3. Add a midi track.
4. Right-click "DeicsOnze..." (=Instrument) in the mixer strip on the left.
5. Click "Prefer knobs, not sliders"

I get the same crash on various systems (Ubuntu, Mint) so I suppose it can be easily reproduced. If not, I will be glad to supply more information.
I've just compiled MusE from current git master, by the way, so it's up-to-date.

Best regards,
Kybos

**Comment by terminator356** [comment]
Changed delete to deleteLater() in ComponentRack::clearDelete()
Disabled label was trying to call clearDelete() which deletes itself.

In github master now. Thanks for the report!
Tim.

**Comment by kybos** [comment]
No crash any more, thanks.
Kybos

**Comment by spamatica** [comment]
I'm kind of sad that bug 666 didn't live longer :P 
oh well. as you were.

**Comment by terminator356** [comment]
LOL.
Really some of the other bugs I've worked on deserve that... that... number.
