### ISSUE TITLE
Bug: Automatic restart after style change fails

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#667]
Hi,
After changing a style (in Appearance settings menu), a question pops up if MusE should be restarted. When Yes is clicked, MusE ends and seems to restart, but then keeps hanging with an empty window frame.
Tested on Ubuntu and Mint, both on HD and HiDPI monitors. Always the same behaviour.
Cheers,
Kybos

**Comment by terminator356** [comment]
Fixed in git master now.
Neglected to reset jackStarted upon restart.
Thanks for the report. Try it out and close if all is good.

**Comment by kybos** [comment]
Works perfectly now, thanks.
