### ISSUE TITLE
Soft synth track add - inconsistent behaviour

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#668]
Hi,
When adding a soft synth track, most synths are inserted quietly, with two exceptions: MESS vam and MESS organ, which both open the GUI. Is that intended?
Cheers,
Kybos

**Comment by terminator356** [comment]
Probably just an oversight.
They all used to open until someone quieted them.
I'll keep my eyes open for the cause, thanks.

**Comment by kybos** [comment]
I personally would very much prefer if the (native) GUI did NOT open at inserting. Especially because some synths crash the complete application immediately. Or perhaps make it a setting?

**Comment by spamatica** [comment]
Indeed it should not. I think I tried to fix this at atleast one point but couldn't figure out what was going on.. I'll have a look again

**Comment by spamatica** [comment]
Fixed in master
