### ISSUE TITLE
Advanced routing dialog with Ardour theme (unreadable fonts)

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#669]
The dialog looks quite bad with the Ardour theme:

![image](https://user-images.githubusercontent.com/10009541/67971363-f0b96600-fc0c-11e9-92a6-d8097aa18409.png)

It can be made a lot better adding this to Ardour.qss:

 QTreeView {
    alternate-background-color: rgb(127,127,137);
}

Then it looks like this:

![image](https://user-images.githubusercontent.com/10009541/67971750-a1276a00-fc0d-11e9-980f-8c98567f0146.png)

But I am not able to change the section titles colour (like "Jack:", "Midi Ports:", "Tracks:" etc.) - these texts are still unreadable. Can you help?

Also, could the dialog be made a little larger as a default (or the size kept between sessions)?

Thanks,
Kybos

**Comment by kybos** [comment]
Addition: This should be added to Ardour.qss:

QTreeView, QListView {
    alternate-background-color: rgb(127,127,137);
}

Because also the lists are affected by this issue.

**Comment by terminator356** [comment]
Thanks. Some of our drawing in MusE uses custom painting with
 colours not easily found in a palette or in standard stylesheet syntax.
I will try to expose a new property for that particular colour.
Also must ensure this particular TreeView control has an object name.
That way we can use the 'object property' feature of stylesheets (since Qt 4.3).
There will certainly be other MusE widgets that will need to be done as well.

Please hang in there, quite busy at the moment...

**Comment by terminator356** [comment]
Heya! Got some help for you.
Pardon me if I reopen this just for wee while so we can remember it.

Advanced router stylesheet support: New property 'RouteTreeWidget::categoryColor'
You can now set that 'category' item colour.

**Did you know...**
You can access any specific MusE sub classes of QWidget.
All of our custom widgets are housed in a C++ namespace "MusEGui".
Therefore to access any of our widgets, you must use "MusEGui--<classname>"

Set this new property like this:

`MusEGui--RouteTreeWidget {`
`      qproperty-categoryColor: blue;`
`      background-color: green;`
`      color: cyan;`
`      alternate-background-color: orange;`
`     ## etc etc.
`}`

In addition the two specific instances of that class use now have IDs:
"Router_input_tree" and "Router_output_tree".
You're _supposed_ to be able to access them like this, but I couldn't get it to work:
`MusEGui--RouteTreeWidget#Router_input_tree {`

Cheers!

**Comment by terminator356** [comment]
You can of course set those other properties using say QTreeWidget or QTreeView like
 you already have in Ardour.qss, and use the more specific MusEGui--RouteTreeWidget
 just for that one missing colour.

Stylesheets are rather disappointing in built-in choice of colour properties.
Just foreground, background, and alternate background.
So this extra property was required :-(

**Comment by kybos** [comment]
Thanks for that, works perfectly:

![image](https://user-images.githubusercontent.com/10009541/69478309-425ea600-0df1-11ea-9697-b85ba6681835.png)

By the way: "MusEGui--RouteTreeWidget#Router_input_tree {...}" does nothing for me either, but that's no problem, it looks OK as it is.

**Comment by terminator356** [comment]
It's a shame we don't some kind of 'cheat sheet' listing all the available
 properties from our **own** custom widgets (not standard Qt ones which we already know).
Nobody would know for example that our knobs have all the colours available as properties.

I am trying to think of a way to do it - to print out a listing to help stylesheet writers.

**Comment by kybos** [comment]
True, that would be really good.

**Comment by terminator356** [comment]
> Nobody would know for example that our knobs have all the colours available as properties.

Oops. That's because they aren't.
Fixed in git master, and added some more to knobs and sliders.
Also... Introducing **The Snooper**:
Hope it helps! Cheers.
https://linuxmusicians.com/viewtopic.php?f=61&t=20728

**Comment by kybos** [comment]
Looks good, thanks!

**Comment by kybos** [comment]
But now I can't compile current master:

muse3/muse/components/snooper.h:37:10: fatal error: ui_snooperbase.h: No such file or directory
 #include "ui_snooperbase.h"
          ^~~~~~~~~~~~~~~~~~

I deleted the build directory, rebuilt everything etc., but I always get that error...

**Comment by spamatica** [comment]
Seems to be a dependency problem. lv2 (for me atleast) relies on this file having been created but it doesn't happen until components are built.
As a workaround you can build components by hand with 'make components' and then proceed with the regular build.

**Comment by kybos** [comment]
That helped, thanks.

**Comment by terminator356** [comment]
Sorry 'bout that. Will check... Yeah that happens sometimes. Hate it.
Sometimes you have to wipe the build clean and 'prune' the cmake config
 and build from scratch.

**Comment by kybos** [comment]
No problem.

> Sorry 'bout that. Will check... Yeah that happens sometimes. Hate it.
> Sometimes you have to wipe the build clean and 'prune' the cmake config
> and build from scratch.

I had done all that, but still the error remained, no idea why...
But the workaround with "make components" saved me ;-).

**Comment by terminator356** [comment]
FYI: Snooper flash color is now exposed.
Changed in Ardour and Dark themes.
Likely you couldn't see the text very well in Ardour theme, eh?
I used the same colours you used for the route tree.

**Comment by kybos** [comment]
Perfect, thanks.

**Comment by terminator356** [comment]
Do you mean even after my fix here?
That's strange. I tested it and the colour is certainly not orange here in Ardour theme.
Also Dark theme works here too.

**Comment by kybos** [comment]
Oh, sorry, my mistake, I was not using the default Ardour stylesheet in the settings.
Everything OK now, thanks.
