### ISSUE TITLE
Bug (?): Some lv2 soft synths do not produce sound

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#677]
From the approx. 20 lv2 synths I have, they are two that do not produce any sound: Helm (lv2) and Noize Mak3r (Helm vst has no issues, though).
Patch selection works for both.
I tested them with Ardour, QTractor and Carla, no issues there.

**Comment by terminator356** [comment]
Hm, yeah no sound from Helm LV2. I managed to get the UI keyboard to make sound but
 not when driven from a track or midi input.
Bah!

**Comment by terminator356** [comment]
Update: It's a transport problem (LV2 transport, not Jack transport).
And it likely affects synths that use the LV2 transport features.
Yes, our code is continually sending transport atoms to the synth,
 but something seems wrong about them, as we can see.
I needed to interrupt that flow to see if it solved anything.
So I simply removed this final line from LV2Synth::lv2audio_SendTransport():
`buffer->write(...)`
It worked. Sound.

Stay tooned... Seems maybe the composition of the transport atoms is not right...?
It doesn't even work in play mode, which I thought would at least work.
Andrew (the author) has a line in there:
   //send transport/tempo changes always
   //as some plugins revert to default settings when not playing
Don't think that's the problem though.

**Comment by terminator356** [comment]
OK Here we go:
[https://linuxmusicians.com/viewtopic.php?f=61&t=20692](url)
Try 'er out. Thanks for the report!

**Comment by spamatica** [comment]
As I understand this is fixed now?

**Comment by terminator356** [comment]
Correct. Confirmed by kybos.
