### ISSUE TITLE
Keyboard affectation 

### ISSUE THREAD

**Issue by Saturnin512** [muse-sequencer/muse#680]
Could it be possible to set up the numeric pad for the cursor moves ?
Home/End: Cursor at the Start/End of the track
7: Left point marker
9: Right point marker
3: Move left by step
1: Move right by step
0: set up recording
Enter: Start recording
. (dot): Stop recording
Space: Start/Stop playback

Thank you.

**Comment by spamatica** [comment]
Hi, I thought I would try fixing this. I have some questions though.

To be clear, I will not bind these exact keys to each operation, instead I will make them available in the keyboard shortcut dialog so you can bind them yourself to any free key you want.

Home/End: Cursor at the Start/End of the track
Cursor to the Start has a shortcut (w by default), End might be missing, I will try to add that.

7: Left point marker
9: Right point marker
I'm guessing this means to move to the left point marker? Then they already have a keyboard shortcuts, (END and PGDN by default).

3: Move left by step
1: Move right by step
These seem to be missing I will add them

0: set up recording
Do you mean to rec-enable the selected track?
If it is only one track the selected track will be rec enabled automatically when 'start recording' is enabled.
I'll see if I can add a specific shortcut.

Enter: Start recording
. (dot): Stop recording

Start and stop recording is the same shortcut so cannot be set exactly like that (* on keypad by default)

Space: Start/Stop playback
Already works like that

**Comment by spamatica** [comment]
Also note that the PgDn shortcut did not work. Fixing this just now, some keys were apparently ignored for whatever reason..

**Comment by Saturnin512** [comment]
Hi, 

Thank you for your interest about my request. I used for ages Cubase Audio Falcon Atari and it seems to me the use of the numeric keypad for all the move through a track including record and playback was very convenient. Your solution, "I will make them available in the keyboard shortcut dialog so you can bind them yourself to any free key you want", suits me well. 

Best regards. 

Robert 

----- Mail original -----

De: "spamatica" <notifications@github.com> 
À: "muse-sequencer/muse" <muse@noreply.github.com> 
Cc: "Saturnin512" <robert.morelli@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Samedi 23 Novembre 2019 16:21:43 
Objet: Re: [muse-sequencer/muse] Keyboard affectation (#680) 



Also note that the PgDn shortcut did not work. Fixing this just now, some keys were apparently ignored for whatever reason..

**Comment by spamatica** [comment]
I have checked in shortcuts for 
Transport: move to end (default shift+w)
Transport: arm current track (default ctrl+return)

Let me know if I misunderstood the intention of any function (or if there is some trouble with binding it to the key you want, there are issues that are hard for us to fix, global shortcuts etc)

**Comment by Saturnin512** [comment]
No problem if we can mapping the short key.

Robert

⁣Télécharger BlueMail pour Android ​

Le 23 nov. 2019 à 17:53, à 17:53, spamatica <notifications@github.com> a écrit:
