### ISSUE TITLE
first note missing on start of playback

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#682]
Testing 3.1pre3. 
When clicking play, notes (and metronome) that are on the same position as we start playing are not played.

**Comment by terminator356** [comment]
Is that with latency correction/compensation enabled?
Yes, that's a known problem to be worked on.
Otherwise should not happen, works OK here, didn't notice any trouble.

**Comment by Gnlfz007** [comment]
Just a reminder that this bug is still alive in 3.1.1, even with latency correction/compensation _disabled_. This is a really annoying one that cannot be ignored for a serious DAW like MusE! ;-) ;-) ;-)

**Comment by kybos** [comment]
Here too, only reproducible when latency correction is on.
