### ISSUE TITLE
Score editor issues

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#685]
Just clicking around in the score editor a little gives strange results:

![image](https://user-images.githubusercontent.com/10009541/69007527-0afa8000-093f-11ea-935a-6e797b4dca1b.png)

Is the score editor finished/maintained/reliable? Is it productively used by anyone? Does it make sense to file bugs for it?

**Comment by terminator356** [comment]
Looks OK to me. I think the orange means the notes are selected.
I've not noticed any trouble with it. Something wrong?
The score editor was entirely developed and added by Florian (flo93).
We had a wish for something like it, even just a display of notes,
 but none of us wanted to tackle it, given the enormity of the task.
I think he did a pretty amazing job. It does what it's supposed to.
It doesn't rival Rosegarden or Lilypond, but it suits us fairly well.
I do maintain it when required, and even add a few tweaks here and there.
But obviously I have no plans at the moment to even go anywhere near
 expanding on its features.
It is very complicated... A special 'View' class all of its own was required.

**Comment by spamatica** [comment]
To expand on this.
I have no idea if anyone actually uses it to compose. I would consider it
unlikely but then again, people find ways :)

Personally I do not read score and have almost never opened it.

Den sön 17 nov. 2019 kl 19:52 skrev Tim <notifications@github.com>:

**Comment by terminator356** [comment]
Oh hi! Just edited my comment.
Yeah, true, I've never used it. But I think it is important to at least
have the display of the notes as I originally suggested - he went above and beyond with
 editing which is great.
I think a serious composer would use another app (MuseScore? He he) to compose,
 then import to MusE for tweaking, recording performed midi and audio, effects etc.

**Comment by terminator356** [comment]
Well, except for one thing: Our drum editor is pretty cool I think. I am fond of it because
 I use it so much to provide drums for my recorded audio tracks.
We've taken great care with it.
One goal to maybe try to reach: Unify midi and drum editor so that
 drum note lengths can be edited easily. (This was done in original MusE-2
 by Werner, found in our git attic). Yes, we have a popup action that switches
 a midi track to a drum track and vice versa, but integration into one editor would be nicer.

**Comment by kybos** [comment]
Thanks for your comments.

@terminator356: Yes, there is a lot wrong about this one bar. This is supposed to be a 4/4 bar, but I was able to input 7 1/2 beats into it. And there is the out-of-place eighth note rest at the beginning... And this is just a small example. 

I was just asking myself what the status and the purpose of the score editor in MusE was, and if anybody was really using it.
Yes, I know how extremely complex a score editor is. Even Cubase was really bad in this respect, at least in its beginnings on Atari ST, long time ago... At some point I had to buy Finale, when I really needed a sensible score editor, and there was no real alternative at that time...

I think a combination of MusE and MuseScore could be a good thing, if one prefers the more classical approach...

**Comment by terminator356** [comment]
Ah, I think you have to be very careful where you click to add the notes.
Click right where the stem **should** be.
If you're off to the right or left a little too much, it tries to add the note in an
 accommodating way but at a different position which may seem odd
 but I think it seems to be working.
I took a good look score editor's behaviour recently, but found that,
 mm, yeah it _seemed_ to be OK

**Comment by Windfisch** [comment]
Look at what you did in the piano roll view ;)
This looks a bit odd, but you have created four 4ths that are on-beat, and another "voice" of four 4ths which start off-beat. This explains the odd-looking 8th rest at the beginning. Generating scores from MIDI only isn't a trivial thing to do, and in MusE, we use a rather simple heuristic rather than the extended capabilities that MuseScore offers. Feel free to improve on this, however :)

**Comment by kybos** [comment]
Thanks for your comment.
My example is a direct mouse input, it was not generated from existing MIDI events.
Your explanation with the second voice makes sense, but it is not obvious to the user (normally the stems would show in opposite directions in this case) so I think polyphonic input of this kind should not be possible (as a default at least). To support it properly would add another level of complexity, I suppose...

**Comment by Windfisch** [comment]
Yes, opposite stems were a planned feature years ago, but I never got around actually implementing it.
The score editor still can be thought to have a raster similar to the piano roll. Depending on where you click when creating a note, you are getting a syncopated one or an on-beat-note. The small rest is the only way to find out (apart from the horizontal position of the note head) which case happened.

**Comment by kybos** [comment]
So perhaps it would help to have a visible raster/grid also in the score editor, to make it more obvious and give the user better orientation?

**Comment by kybos** [comment]
Works as designed, so closing this.
