### ISSUE TITLE
Clip list editor is... useless

### ISSUE THREAD

**Issue by terminator356** [muse-sequencer/muse#691]
Yeah no kidding.
Just to warn: I am sort of fixing that in another branch. Trying hard to finish it and merge.
Beginnings of an actual clip list thing. Actual clips.

**Comment by spamatica** [comment]
Some background: as MusE was modelled after Cubase in the beginning, I
believe the clip list was added as as something similar existed there. For
some reason the design was changed and the editor was left dangling without
a purpose. (that's how I recall things anway..)

If Tim is giving it a purpose that's awesome, though if that doesn't pan
out maybe we should think about removing it or hide it better..

Speaking of old things and history.. I tried to find a source for it but
haven't been able to, I believe however that MusE turns 20 now in December
:) We need some kind of celebration :) Only what, apart from a new
release... I'm thinking MusE's own beer!  :D

Den sön 17 nov. 2019 kl 21:21 skrev Tim <notifications@github.com>:

**Comment by spamatica** [comment]
Heh... didn't mean to talk about you in third person, I was confused and thought it was kybos who created the ticket :D 
Good idea to open tickets for ongoing work.

**Comment by terminator356** [comment]
Oops, neglected assignee. Will do.

Yeah really eh? 20 years. Amazing.
Remind Werner. Maybe ask him to ... muse... about how it started etc. Post his thoughts.
MusE Beer brand. Now that's something I can dig. Hey, there was a Microsoft beer.

**Comment by spamatica** [comment]
Good idea, I can try to get hold of him :)

**Comment by Windfisch** [comment]
Isn't Werner german? I could even drink a real beer with him if he attends 36C3 :'D

totally off-topic, but: nice to see there's still progress on MusE! :)

**Comment by terminator356** [comment]
Hi! Long time no talk, eh? Having a blast here with MusE, as always.
