### ISSUE TITLE
Metronome icon inconsistent

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#704]
I was thinking about replacing the pixelated metronome icon on the main toolbar (and also the other one in the Settings menu) by an SVG one, but at some point I noticed that there already exists an SVG version of it, but it is only used in the transport window. Is that intended? And is it really necessary to have a different metronome icon for the settings menu? It looks more like an inconsistency from user perspective, I think.
I would suggest to replace all these old pixmap icons by the "metronome on" SVG icon that is used in the transport.

**Comment by terminator356** [comment]
Hm, I never noticed the one in the settings was different!
Yes, I was wanting to replace them but what stopped me was I realized that
 each neighboring icon would likely have to be done as well (leading to the whole lot),
 for fear of inconsistency. Specifically in the case of the metronome SVG icon
 it is 'fuzzier' than the bitmap version and the other icons.

I was worried about the look.
But, I suppose that's silly. Go ahead and replace it.
It's Likely we're gonna be (slowly or not) redoing most of the icons anyway.

When creating replacements I usually try to make them look like the originals,
 'cause you know, some of them look pretty neat.
On the other hand I have to also be conscious of how they mesh with my fresh new ones
 with their somewhat obtuse 'geometric' look. Hard to make an SVG look detailed like pixels.

**Comment by terminator356** [comment]
Everyone is waiting for those 'dated' track type icons to change.
We've had a few comments over the years, ha ha.
One fork even removed all that and all customizable colours in favour of stylesheets.

I've racked my brains several times:
What could we draw in SVG to replace them?
How to give meaning to say, Group Track vs. Aux Track. Or Synth Track.
It was hard enough with bitmaps.
Still, I sit firmly in the camp that believes coloured, somewhat detailed icons are
 very important visual cues for users, especially with a lot of icons.
Not a big fan of Breeze's 'black outline' thing. Was shocked when I saw it.

**Comment by kybos** [comment]
> Everyone is waiting for those 'dated' track type icons to change.

Funny, I find them perfectly OK. The worst looking for me are e.g. the MIDI, step input, metronome icons and a couple of others. HiDPI for sure makes it no better, as they are being upscaled from the 18px pixmaps.
 
> I've racked my brains several times:
> What could we draw in SVG to replace them?
> How to give meaning to say, Group Track vs. Aux Track. Or Synth Track.
> It was hard enough with bitmaps.

Yes, not easy to create "speaking" icons for everything.

> Still, I sit firmly in the camp that believes coloured, somewhat detailed icons are
> very important visual cues for users, especially with a lot of icons.
> Not a big fan of Breeze's 'black outline' thing. Was shocked when I saw it.

Absolutely. I think colourful icons are compulsory in MusE, to sufficiently stand out on all three default themes. 
That's why I don't like the option "Use theme icons if available", because it gives the UI an inconsistent look. At least It should not be the default, IMHO... And it makes the relevant code (icon.cpp) quite inefficient, with all the conversions from icons to pixmaps and vice versa, and requesting all icons from the system theme, although for most of them there never will be a corresponding system icon...
