### ISSUE TITLE
MusE starts with broken UI when Jack is not properly running

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#709]
Possibly a similar problem to #667.

I had this many times already, but it was not easily reproducible.
When there is a problem with Jack, MusE sometimes display some error messages but then starts all the same, but the UI is broken (only small area of the screen is drawn), scrollbars etc. are not visible, and mostly it is necessary to kill the app to close it.

Now I was able to reproduce it simply running MusE with the -a option, the same happens there.
I don't know if it's related to HiDPI, but I don't think so.

**Comment by spamatica** [comment]
Oh, wierd. I run it with -a all the time (as an easy way to get it up and running when testing ui stuff). I'm guessing there are no errors in the terminal to give any hints?

**Comment by kybos** [comment]
No, not really:

Debug Information$ muse3 -a
qt5ct: using qt5ct plugin
Config File </home/miro/.config/MusE/MusE/MusE-seq.cfg>
LOCALE en_US
qt5ct: custom style sheet is disabled
qt5ct: D-Bus global menu: no
Denormal protection enabled.
Force Dummy Audio driver
Trying RTC timer...
fatal error: open /dev/rtc failed: Permission denied
Trying ALSA timer...
AlsaTimer::initTimer(): best available ALSA timer: system timer
got timer = 26
Initializing Native VST support. Using VESTIGE compatibility implementation.
INFO: Could not get the wanted frequency 1024, got 250, still it should suffice.
Acquired timer frequency: 250
starting with template /usr/local/share/muse-3.1/templates/default.med
INFO: Could not get the wanted frequency 1024, got 250, still it should suffice.

It looks like that:

![image](https://user-images.githubusercontent.com/10009541/69873890-e1841180-12b9-11ea-968a-bbb5c9e0894e.png)

I guess then it's either the HiDPI or another local problem, will try to check myself.

**Comment by terminator356** [comment]
Is LASH installed? Do you have the -L disable option? Try it.
And what about qt5ct? Could that be causing trouble?
I have no problem ever running with -a. It's not supposed to do anything bad.

**Comment by kybos** [comment]
Thanks for the hints.
I've noticed that the problem only occurs on one of my PCs. LASH is not installed, I will try playing with the UI settings when I am at the other PC again next week.

**Comment by kybos** [comment]
A local issue indeed, closing...
