### ISSUE TITLE
dB value during automation editing is wrong

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#715]
a recent dB textual change reminded me that the visual cue of which value you are at during automation editing is wrong.
After the editing is done and hovering over the automation point the value is right so the fix might be simple.

This applies to dB values not sure about other value types. 
An easy test is to draw an automation point for Volume and comparing the value on the slider and the reported value for the point. 
Coincidentally this test relies on another bug... Upon drawing the first automation point the slider will follow along even though it might be at a point where the line does not move.

**Comment by kybos** [comment]
Haven't you fixed that in your recent commit?

**Comment by spamatica** [comment]
Oh, yeah. Did not remember there was a ticket. Thanks, closing!
