### ISSUE TITLE
First automation point affects from the start even if it is not at the start

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#716]
When drawing a first automation point somewhere on a track it will affect the data already at the beginning of the track.
Visually it seems there is an initial value which is still at the original value but during playback only the added value is used.

**Comment by kybos** [comment]
There is the same problem when editing the first part of the line in this case. The line shows to the start/default value, but it can't be edited, it behaves as if the first point were the start value. 
So there is apparently a design conflict, not sure what is right/intended.

**Comment by kybos** [comment]
I assume the playback (and the drawing cross) behaviour is correct, I checked in Ardour and it's the same there. The first point is valid from the beginning, the same as the last one is valid to the end.
I fixed the line drawing accordingly.
