### ISSUE TITLE
It is possible to record without having any tracks ARMed

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#717]
This is of course rather silly and has led to wasted takes.
The rec button should not be possible to enable without at least one track having been successfully ARMed.

**Comment by kybos** [comment]
Looking at the code: If no track is armed, then the selected track is armed automatically (this behavior can't even be switched off). So what you describe is practically impossible, unless you explicitly de-select all tracks. I added a warning message for this special case now.
Or did you have something else in mind?

**Comment by kybos** [comment]
This is now fixed in master.
From changelog:

    - Fix #717: Record button mustn't be activated when no track is record-armed
        (a warning message is displayed now). 
        Record button is automatically deactivated when no track is armed.

**Comment by spamatica** [comment]
Yikes, I'm slow. Thanks for adding the dialog.

Yes, auto arming is done, but it only works if you actually have a recordable track selected. 
I know my shortcuts, sometimes too well, so I don't pay attention if I mistakenly moved the selection.

**Comment by terminator356** [comment]
Hm, I thought we had a setting for auto-arming a selected track when record is pressed. But I don't see it.

We do have Global Settings > GUI > Move single armed track with selection.
It still works, but I noticed it will arm even Audio Output tracks (bounce) when the selection is moved.
Do we want that?

**Comment by kybos** [comment]
> Hm, I thought we had a setting for auto-arming a selected track when record is pressed. But I don't see it.

I would have expected it too, but there is no setting, it's hard-coded. I was thinking about adding it, but then wasn't sure if it's really needed, as nobody seemed to mind (except me ;-) ). It would only make sense to add if it were off by default IMO (otherwise nobody will look for it or care about it anyway).

> We do have Global Settings > GUI > Move single armed track with selection.
> It still works, but I noticed it will arm even Audio Output tracks (bounce) when the selection is moved.
> Do we want that?

Certainly not. I had fixed similar problems in other places already, but did not notice that one as the option is off by default and I never use it.

**Comment by kybos** [comment]
> > We do have Global Settings > GUI > Move single armed track with selection.
> > It still works, but I noticed it will arm even Audio Output tracks (bounce) when the selection is moved.
> > Do we want that?
> 
> Certainly not. I had fixed similar problems in other places already, but did not notice that one as the option is off by default and I never use it.

I fixed it in master (it was arming/trying to arm all types of tracks, not only audio outputs). I don't see much sense in this option to be frank, as half of the track types can't be armed anyway, so the behavior is quite random from the user perspective. It's good it's off by default...

**Comment by spamatica** [comment]
As is with several of these kinds of settings, I added them out of personal preference and didn't look too deep at the error cases... Most of the time I have had the common sense to make them optional at least, but rest assured it is being used, by me ;)

The thing is that while recording (otherwise too) I completely work through keyboard shortcuts, and if I prepare for recording and notice that I armed the wrong track (not often but it happens), I don't have to undo the process but simply CTRL+arrow until I get to the right track and hit space to continue.
