### ISSUE TITLE
Mixer A sometimes does not show all tracks

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#718]
Posting a ticket here while I remember it, was meaning to have a look at this.

Sometimes I have found that Mixer A is missing a lot of tracks. In this case the mixer also gets very crashy if I try to reorganize it or similar.
Mixer B for some reason always seem to show all tracks. 
No clue if this is just a coincidence or if there is some relevant difference between A and B that could cause this.

**Comment by terminator356** [comment]
Just to bump up: Any problems still even after all the recent fixes and my
  "fix blank mixers after auto-restart" of 04/06?

**Comment by spamatica** [comment]
I think I have still seen problems (both completely empty mixer and missing tracks) after updating to that fix, but I haven't done enough museing after that to say for sure.

The missing track scenario feels very related to when you are in a high cpu-load scenario. E.g. working on a song that already has lots of tracks and effects. Added tracks then often do not end up in the mixer.

The difference between mixer A and B is probably due to B often not being initialized so there is a different mechanism when it is populated upon open. Though I have seen issues with B too when trying to provoke it.

**Comment by MyLoFy** [comment]
I can reproduce this on Mixer B (Archlinux, MusE 4.0.0-pre1-127-g381f20da) with only audio tracks (all synths deactivated). Workaround: Create a new empty wave track and all missing tracks pop up.

**Comment by kybos** [comment]
It there any way to reproduce this problem reliably? I'm not able to, even with audio only. For me it occurs quite randomly, which makes a fix pretty impossible...

**Comment by MyLoFy** [comment]
I can reliably reproduce this on the attached session. When playing the session my DSP load gets to 100%. 
[mixertest.zip](https://github.com/muse-sequencer/muse/files/5757017/mixertest.zip)

Steps to reproduce:
- Open session (do not open the mixer. If the mixer is opened before adding a track the bug won't occur)
- Add any track type
- Open Mixer A or B: New track is missing
- Add any track type
- All missing tracks pop up

Interestingly this only happens on a mixer that hasn't been opened before. So if you open Mixer A before those steps the bug will only appear in Mixer B and vice versa. 

https://user-images.githubusercontent.com/70516194/103406565-65fb3080-4b5b-11eb-9ed3-5d48407bf2b9.mp4

**Comment by kybos** [comment]
I could reproduce the problem in debugger. The mixer strip output it not based on the track list (any more), but on another list which is apparently out of sync - it doesn't contain the newly added track (amixer.cpp, line 785):

``` 
 // NOTE: stripConfigList is the replacement for obsolete stripOrder string list.
  else if (!cfg->stripConfigList.empty()) {
    const int sz = cfg->stripConfigList.size();
    for (int i=0; i < sz; i++) {
      const MusEGlobal::StripConfig& sc = cfg->stripConfigList.at(i);
      DEBUG_MIXER(stderr, "processing strip #:%d [%d][%d]\n", i, sc._serial, sc._visible);
      if(!sc._deleted && !sc.isNull()) {
        const MusECore::Track* t = tl->findSerial(sc._serial);
        if(t)
          addStrip(t, sc);
        }
    }
  }
``` 

@terminator356 
Tim, it seems to be quite a recent addition of yours (acc.to git), so I guess you will know better how to fix it quickly.

**Comment by kybos** [comment]
I noticed another problem (apart from 2 of 5 track being missing in my case): The strips in the mixers are not selected on first display (the yellow border is not shown):

![image](https://user-images.githubusercontent.com/10009541/103454163-73dabe00-4ce1-11eb-97f4-ad35cd0fd4cc.png)

**Comment by kybos** [comment]
Fix is now in master.
