### ISSUE TITLE
Crash when loading sf3 sound font into MESS FluidSynth

### ISSUE THREAD

**Issue by kybos** [muse-sequencer/muse#740]
MusE invariably ends with a segfault when I try to load a sf3 sound font into the default MESS FluidSynth loader.

**Comment by terminator356** [comment]
Hm which file? All I did was enable *.sf3 in the file dialog.
The rest is up to fluidsynth.
Unless... Do you have the Instrument Patch Library installed? (cmake ENABLE_INSTPATCH)
Try disabling. Maybe version conflicts with fluidsynth.
The two are separate libraries now, maybe some lag?
Got latest versions of both installed?

**Comment by kybos** [comment]
I used the default fluidsynth bank: default-GM.sf3, but also tried with others and it was the same.
I now deactivated ENABLE_INSTPATCH - it works, no crashes anymore. 

The issue was not discovered by me, but by someone running Ubuntu studio 19.10, so it should be pretty current. I could reproduce it on my machine with Mint 19.2. So it means the problem is there on the default installation (from master of pre4), because ENABLE_INSTPATCH is active in the default configuration. 
How to solve? Disable sf3 in FluidSynth loader? Or disable the cmake flag in the default config?

**Comment by terminator356** [comment]
Or do nothing for now. It's not a show-stopping bug.
I would tend to rather support the folks for whom it will just work.
Then maybe if/when package updates come down the line for those with the crash,
 it might start working.
Question: Is libinstpatch installed by default on these distros?
If not, that's another argument to maybe leave it alone for now...

**Comment by kybos** [comment]
libinstpatch is apparently not installed by default on Ubuntu, but it is installed as a build dependency when you compile MusE, so it's there then.
According to its README, it only supports SoundFont 2, even in the newest version.

**Comment by terminator356** [comment]
Huh? Installed as a build dependency when you compile MusE? How?

Only sf2 eh? I see. Hm... What to do....
I spoke to the libinstpatch author who very kindly provided me with examples.
He said it was being replaced by GIntrospection mechanisms.
But it wasn't quite ready at the time. Maybe time to revisit...

**Comment by kybos** [comment]
I did mean it's installed automatically, but it's part of the instructions for Ubuntu from the README:
...
1. Open terminal and type (either on one line or with several 'sudo apt-get install <packages'):
        sudo apt-get install build-essential cmake libsndfile1-dev libsamplerate0-dev\
            libjack-jackd2-dev ladspa-sdk qt5-default qttools5-dev qttools5-dev-tools\
            liblo-dev dssi-dev lv2-dev libsamplerate0-dev libsndfile1-dev git\
            libfluidsynth-dev libgtkmm-2.4-dev librtaudio-dev libqt5svg5-dev\
            **libinstpatch-dev**
...

**Comment by terminator356** [comment]
Ah I see, sorry. Hm. Tough situation...

**Comment by terminator356** [comment]
Looking at code. Looks like this might be our fault.
I will try examining the extension and exiting out of our instpatch code
 if it's an sf3 file. That should hopefully satisfy all.

**Comment by terminator356** [comment]
Should be fixed now. Thanks for the report.
Nothing wrong with the library. It dutifully returns if the SF file version is unsupported.
We, on the other hand, were not checking returned pointers !
Although I did not observe the crash, stepping through the code clearly revealed the problem.
Try 'er out.

**Comment by terminator356** [comment]
Bizarre. Simply by writing '#' and the issue number in the ChangeLog,
 automatically closes the issue.
I've seen that before. That's why I'm always hesitant to write the '#' in the ChangeLog.
Re-open if required. Thanks.

**Comment by kybos** [comment]
Thanks, I will test.
The auto-closing of issues is documented here:
https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords

**Comment by spamatica** [comment]
Don't fear the auto close, embrace it ;) The issuer of the ticket can still comment and reopen if they feel the need.

**Comment by kybos** [comment]
Tested, works, thanks.
