### ISSUE TITLE
Can't build from AUR under Manjaro Linux

### ISSUE THREAD

**Issue by Rencer** [muse-sequencer/muse#746]
I tried to build Muse from AUR, but after som time I get this error:

In file included from /usr/include/fluidsynth.h:97,
                 from /home/gofri/.BUILDTEMP./yaourt-tmp-gofri/aur-muse/src/muse-3.0.2/synti/fluidsynth/fluidsynti.h:36,
                 from /home/gofri/.BUILDTEMP./yaourt-tmp-gofri/aur-muse/src/muse-3.0.2/synti/fluidsynth/fluidsynti.cpp:44:
/usr/include/fluidsynth/synth.h:236:45: note: declared here
  236 | FLUID_DEPRECATED FLUIDSYNTH_API const char *fluid_synth_error(fluid_synth_t *synth);
      |                                             ^~~~~~~~~~~~~~~~~
make[2]: *** [synti/fluidsynth/CMakeFiles/fluid_synth.dir/build.make:93: synti/fluidsynth/CMakeFiles/fluid_synth.dir/fluidsynti.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2326: synti/fluidsynth/CMakeFiles/fluid_synth.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build .

**Comment by terminator356** [comment]
Hello. This was fixed after MusE 3.0.2 was released, on 19.12.2018 in the ChangeLog.
You need release MusE 3.1.0pre1 or higher.
(The latest available release is MusE 3.1.0pre4.)

**Comment by Rencer** [comment]
Thanks.
Currently the relaease in AUR is still 3.0.2, so I have to wait for the update in AUR.
I see there is a  **_muse-git 4.0.0-1_** version too, but that is not a latest stable version right?

**Comment by terminator356** [comment]
Some of us noticed that as well.
We weren't sure what it was - there is no version "4" of MusE.
But it seems to be a recent (unstable) git version.

**Comment by Rencer** [comment]
Oh, ok. I thought it just me, who can't find that version here. I skip that "whoknowswhat" version.
Maybe I should compile by myself a stable, official version from here.
As you sad it is alredy fixed. I close it now.
Thanks.
