### ISSUE TITLE
Ctrl+Drag in piano roll editor should only select new event

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#747]
Small usability suggestion in MIDI editor/piano roll.

When I use the Ctrl key to make a copy of an event and drag it to another location, the original stays selected. I think only the new event should be selected.

My reason for this is that I usually start with a "live" MIDI recording, then drag around copies of the events and move and change the length of them. Now I have to de/reselect all the time.

This will also make it more consistent with other software, for example LibreOffice Draw.

![muse3_ctrl_drag](https://user-images.githubusercontent.com/33361311/71673849-1d5b3c80-2d7a-11ea-8964-9ae245daaac8.png)

**Comment by spamatica** [comment]
I believe this is actually a rather recent change in behaviour and it's
bothered me too so I think you are right. I'll see what I can do

Den tors 2 jan. 2020 kl 16:08 skrev StaffanMelin <notifications@github.com>:

**Comment by kybos** [comment]
Fixed in current master.
