### ISSUE TITLE
Feature request: Change length of all selected notes

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#748]
Piano roll. When I have several selected notes and edit the length with the Pencil (by dragging), the length of all selected notes should be affected/adjusted. Now only the note that I change, gets changed.

**Comment by kybos** [comment]
Added in master, please test.
Improved selection possibilities in edit mode too, see change log for details.

**Comment by StaffanMelin** [comment]
It works beautifully! Thanks a lot kybos! It will speed up my work flow a lot! (The exclusive selection is great too!)

**Comment by kybos** [comment]
You're welcome ;-)
