### ISSUE TITLE
Latency correction, midi noteon/noteoff order issue

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#779]
During some collaboration with MusE user oscillator I disovered the reason for an issue I noted earlier on.
Basically, when Latency correction is enabled midi notes that are player back to back will (sometimes it seems) not always sound correctly.
A melodyline where the same note was played over an over the new note starting on the same beat as the first one stopped will sometimes only make a very short sound like it is playing but then immediately silenced.
So my thought was that the noteoff might not be sorted correctly so it is played after the noteon.
An additional little discovery is that it seems to work correctly when I use RtAudio as backend instead of jack. No idea if that makes any sense.

Anyway, I know there are some issues with Latency correction, maybe this is related.

**Comment by terminator356** [comment]
Going over some older issues, found this.

Observed! Wow, sorry about that, investigating...
The notes appear to require a minimum 18 ticks separation to sound.

**Comment by terminator356** [comment]
Fixed in master now. Tested OK with/without latency correction, and with Jack and Rt Pulse.
Sad that it's been like that for about two years ever since my latency code, and now in version 4.
Ugh, I missed that code section.

**Comment by spamatica** [comment]
Alright, cool. No worries, I'm sure we would have had more complaints if more people were hit.
But I guess it's getting time to make the 4.0.1 release :)

**Comment by terminator356** [comment]
Lemme get that wave left-border resizing thing done before considering release.

**Comment by terminator356** [comment]
I guess I fixed this one. Closing for now.
