### ISSUE TITLE
Account for cmake "missing ladspa.h" error

### ISSUE THREAD

**Issue by Dummynosrev** [muse-sequencer/muse#783]
> Same here with Debian 8
> 
> cmake complains for missing ladspa.h despite it can be found in /usr/include, strange..
> 
> As workaround, in CMakeLists.txt insert
> 
> ```
> include_directories(/usr/include)
> ```
> 
> before
> 
> ```
>  CHECK_INCLUDE_FILE(ladspa.h HAVE_LADSPA_H) 
> ```
> 
> delete everything in the build directory and retry
> 

_Originally posted by @luxigo in https://github.com/muse-sequencer/muse/issues/373#issuecomment-162145757_

I spent two hour trying to fix this and questioning my self before coming across this so I wanted to revive this issue so that no one else falls into the same fate. :(

**Comment by spamatica** [comment]
Woops, wrote on the wrong ticket...
---
I'm not doubting that this problem exists but it is very puzzling.
I tried to reproduce it but failed this far. Installed debian 8 in a VM and both muse-2.2 and muse-3.0 compiled without any issues.
muse-3.1 requires too new Qt version, I don't know if there is a debian way to upgrade it.

I double checked that ladspa.h only seems to be at /usr/include/ladspa.h
cmake version is 3.0.2

Thanks for listing the workaround anyway.

**Comment by spamatica** [comment]
Which MusE version were you trying to compile and what cmake version? And any other versions that may be of interest?

**Comment by Dummynosrev** [comment]
The work around was posted by some one else but I forgot to put in quote, I'm sorry. 
I tried to compile Muse version 3.1. Running elementary OS hera (Ubuntu 18.04.3 LTS) Cmake version is 3.10.2, ladspa-sdk version 1, I think.

**Comment by kybos** [comment]
Just experienced that exact problem myself when setting up a new VM.
It happens when you run cmake, it doesn't find all the libs, then you install the libs and re-run cmake.
Apparently you have to delete the cmake cache manually in that case (CMakeCache.txt), or delete the build folder.
Or in QtCreator simply do Build->Clean CMake Configuration.
