### ISSUE TITLE
[Feature Request] Improve generic LV2 UIs

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#785]
I was trying the new tamgamp.lv2 announced on linuxmusicians forum the other day, very nice guitar amp sim but when run in MusE it lacks a gui and the parameters aren't that straight forward.

I tried it in qtractor and I think it doesn't have a native gui there either, but there must be a lot of meta-data that we don't bother displaying as the controls make more sense there.
For instance, text values are updated to reflect settings, and it's not possible to set decimal values on values that have set values.

**Comment by gauderbock** [comment]
Just to add another example, with sfizz lv2 on MuSe there's no option in the gui to load an SFZ file (as far as I can see) making the plugin unusable. The option is there on qtractor.

**Comment by kybos** [comment]
The current version of sfizz already includes a native GUI (built with VSTGUI, so no HiDPI support on Linux).
And there is always the possibility to use Carla as plugin host in MusE.

**Comment by kybos** [comment]
The LV2 metadata is now evaluated and the generic GUIs are created with the appropriate widgets.

Tamgamp should look like this:
![image](https://user-images.githubusercontent.com/10009541/103151192-2bb91a00-477c-11eb-9847-e408bc0e6dd0.png)

> Just to add another example, with sfizz lv2 on MuSe there's no option in the gui to load an SFZ file (as far as I can see) making the plugin unusable. The option is there on qtractor.

This is quite a different thing, it's part of a separate LV2 extension that defines free (non-RT) properties. I started to look into it but it's lot of effort to implement and it's usefulness is very restricted IMO (sfizz has its own gui now and I guess there are not many plugins that rely on it in such a way). Not even Carla supports this extension, AFAICS.

**Comment by terminator356** [comment]
I should point out something rather important that has been forgotten, possibly warranting a ticket:
When Andrew added LV2 support, and with all the work that I have done, we never actually got around to
 adding proper **ranges** to all LV2 parameters ! Eek !

In other words, with the other plugin systems we obey boolean vs. integer vs. floating point numerical ranges.
With LV2 we never got around to adding that. Thus all parameters are in floating point !

The sticky issue in the code was how to represent the ranges - do we use our existing LADSPA range system,
 and try to shoehorn the LV2 range stuff into that.
