### ISSUE TITLE
Duplicated entry in edit menu

### ISSUE THREAD

**Issue by moebius1** [muse-sequencer/muse#791]
Bonjour,
I've notice that, in edit menu, there's two entries that does same thing : 'add track' and 'insert track'.
Both sub-menus are the same.
cordialement,

**Comment by kybos** [comment]
Add Track appends the new track to the end of the track list, Insert Track inserts it before the current track.

**Comment by moebius1** [comment]
Bonjour,
AAAhh, I understand, sorry for the noise ! 
cordialement,

**Comment by spamatica** [comment]
No problem, users that want to help is good :)
Possibly the names of the menu alternatives could be better
