### ISSUE TITLE
Can't sync with Hydrogen

### ISSUE THREAD

**Issue by lpgasparotto** [muse-sequencer/muse#793]
I'm trying to sincronize MuSE and Hydrogen setting MuSE as master and Hydrogen as slave and Hydrogen is slighlty behind the audio track I imported to MuSE. I was able to confirm that exporting the Hydrogen song as wave file, importing that wave file and then playing Hydrogen and MuSE together, in this case the delay was even more noticeable, kinda "flam" all the time. I did the same experiment with Ardour and QTractor, it worked nicely on Ardour but with the same delay on QTractor, Is there something I could do to solve it? Or it's something to live with?

**Comment by lpgasparotto** [comment]
Hi, 
I discovered that disabling Latency Compensation Hydrogen plays perfectly in sync with the audio tracks.

**Comment by terminator356** [comment]
Hello, apologies for lack of reply on this one. Quite backed up at the moment.
I did see your first report on this. Keeping an eye on the situation.

I recall that I did not finish one particular piece of the puzzle: The amount of latency
 that MusE **itself** reports to Jack. In other words the total latency from MusE inputs 
 to outputs that **other** clients will see, as if MusE was just a plugin.
(It was not going to be an easy thing to code so I left it alone for now...)
Not sure if that could be the problem. I'll try to recreate the setup if I get a chance.

Thanks.

**Comment by lpgasparotto** [comment]
Thank you very much for your reply. In an ideal world I should be capable to record and audio track over a previously recorded track while Hydrogen plays in syncro and after recording the latency of the recorded clip should be compensated by offsetting it for a certain number of frames. But that's not a big problem because I can export Hydrogen song as a WAV file, import it on MusE, turns "latency compensation" ON an then record over that. 
If helps you to reproduce the problem I could upload to my Google Drive the project and the files I used when I noticed it.
Best regards,
Luis Pablo

**Comment by theGreatWhiteShark** [comment]
Hey @lpgasparotto,

This sounds like a problem of Hydrogen not of MusE. There had been quite a number of synchronization problems. But these should be fixed with the latest releases of version [1.0.2](https://github.com/hydrogen-music/hydrogen/releases/tag/1.0.2) or [1.1.0-beta](https://github.com/hydrogen-music/hydrogen/releases/tag/1.1.0-beta1).

**Comment by terminator356** [comment]
Oops. Sorry, one year already passed on this one, and I still have not had a chance to complete our
 remaining latency issues. So MusE might still actually be part of the problem. Been so busy...
