### ISSUE TITLE
Could not find a package configuration file provided by "Qt5UiTools"

### ISSUE THREAD

**Issue by rchastain** [muse-sequencer/muse#794]
Hello!

I would like to compile MusE 3.1 under Linux Mageia, but I get an error.

```
[roland@localhost muse-3.1]$ mkdir build
[roland@localhost muse-3.1]$ cd build
[roland@localhost build]$ cmake -L ..
-- The C compiler identification is GNU 8.4.0
-- The CXX compiler identification is GNU 8.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.1") 
 vst header path: /home/roland/Téléchargements/muse-3.1/vestige
No CMAKE_BUILD_TYPE specified. Setting to RelWithDebInfo.
-- Found Git: /usr/bin/git (found version "2.21.1") 
Unix (probably linux) found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:231 (find_package):
  By not providing "FindQt5UiTools.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5UiTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5UiTools" with
  any of the following names:

    Qt5UiToolsConfig.cmake
    qt5uitools-config.cmake

  Add the installation prefix of "Qt5UiTools" to CMAKE_PREFIX_PATH or set
  "Qt5UiTools_DIR" to a directory containing one of the above files.  If
  "Qt5UiTools" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeOutput.log".
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeError.log".
-- Cache values
CMAKE_BACKWARDS_COMPATIBILITY:STRING=2.4
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
ENABLE_ALSA:BOOL=ON
ENABLE_DSSI:BOOL=ON
ENABLE_EXPERIMENTAL:BOOL=OFF
ENABLE_FLUID:BOOL=ON
ENABLE_INSTPATCH:BOOL=ON
ENABLE_LASH:BOOL=ON
ENABLE_LRDF:BOOL=ON
ENABLE_LV2:BOOL=ON
ENABLE_LV2_DEBUG:BOOL=OFF
ENABLE_LV2_GTK2:BOOL=ON
ENABLE_LV2_MAKE_PATH:BOOL=OFF
ENABLE_MIDNAM:BOOL=ON
ENABLE_OSC:BOOL=ON
ENABLE_PYTHON:BOOL=OFF
ENABLE_RTAUDIO:BOOL=ON
ENABLE_RUBBERBAND:BOOL=ON
ENABLE_VST:BOOL=OFF
ENABLE_VST_NATIVE:BOOL=ON
ENABLE_VST_VESTIGE:BOOL=ON
EXECUTABLE_OUTPUT_PATH:PATH=
LIBRARY_OUTPUT_PATH:PATH=
LIB_SUFFIX:STRING=
MODULES_BUILD_STATIC:BOOL=OFF
Qt5Core_DIR:PATH=/usr/lib64/cmake/Qt5Core
Qt5Gui_DIR:PATH=/usr/lib64/cmake/Qt5Gui
Qt5UiTools_DIR:PATH=Qt5UiTools_DIR-NOTFOUND
Qt5Widgets_DIR:PATH=/usr/lib64/cmake/Qt5Widgets
UPDATE_TRANSLATIONS:BOOL=OFF
VST_HEADER_PATH:PATH=/home/roland/Téléchargements/muse-3.1/vestige
[roland@localhost build]$ 
```

Could you help me to solve it?

Regards.

Roland

**Comment by spamatica** [comment]
Hello Roland,
Not familiar with packages for Mageia and the Qt packaging is a bit complicated.
I see there is a package qttools5 maybe that or if there is a devel version.

Another way isto install qt-creator it might pull in the needed packages...

Mostly guesses I'm afraid. If I have time I can try to bring up a virtual install of mageia

**Comment by rchastain** [comment]
@spamatica 
Thank you for your answer.
The following packages are already installed:

```
lib64qt5core-devel
lib64qt5core5
lib64qt5gui-devel
lib64qt5gui5
qt-creator
qttools5
```

I don't see a "qttools-dev" in the list.

Regards.
Roland

**Comment by terminator356** [comment]
Hello. According to some random research, this page:
[https://fr.rpmfind.net/linux/RPM/mageia/7/i586/media/core/release/libqt5designer-devel-5.12.2-3.mga7.i586.html](url)
 shows that this package contains the file you need:

libqt5designer-devel

Try that one.

**Comment by terminator356** [comment]
Also, you might want to change your command from:
`cmake -L ..`
to
`cmake -L -DCMAKE_BUILD_TYPE=release ..`
or use our 'compile_muse.sh' script

Otherwise it will build with RelWithDebInfo as shown in your post,
 which you probably do not want.

**Comment by rchastain** [comment]
> Hello. According to some random research, this page:
> [https://fr.rpmfind.net/linux/RPM/mageia/7/i586/media/core/release/libqt5designer-devel-5.12.2-3.mga7.i586.html](url)
> shows that this package contains the file you need:
> 
> libqt5designer-devel
> 
> Try that one.

Thank you for your help. I installed lib64qt5designer-devel and now I get a new error message, so there is a progress. :)

Here is the new error message:

```
[roland@localhost muse-3.1]$ sh compile_muse.sh
Build dir already exists
 vst header path: /home/roland/Téléchargements/muse-3.1/vestige
Unix (probably linux) found
CMake Error at CMakeLists.txt:232 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeOutput.log".
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeError.log".
[roland@localhost muse-3.1]$ 
```

Unfortunately I don't find which package I should install now. With the keyword 'linguist' I only find this:

`qt4-linguist`

I installed it but it doesn't solve the problem.

**Comment by terminator356** [comment]
According to this post:
[https://forums.mageia.org/en/viewtopic.php?f=7&t=12499](url)

the desired package is 

lib64qt5help-devel
or
libqt5help-devel
(depending on whether your platform is 64-bit or not. It seems to be 64-bit, so try that one).

Avoid installing Qt4 stuff. You might want to uninstall qt4-linguist, probably do not want that one.

Also according to that web page above, in Mageia you can search for any further
 missing files with something like this:
`urpmf Qt5LinguistToolsConfig.cmake`
and it will tell you which package contains the missing file.

**Comment by terminator356** [comment]
Some further advice: Most distros have some convenient 'meta' packages,
 which allow you to install several packages from just one package,
 so that you don't have to manually install all of them them yourself.

In Mageia, such a package that contains several common packages
 for building and developing Qt programs is:

lib64qt5base5-devel

According to this page:
[https://mageia.pkgs.org/cauldron/mageia-core-release-aarch64/lib64qt5base5-devel-5.14.1-8.mga8.aarch64.rpm.html](url)
that meta package brings in several common Qt developer packages.

So it is a good idea to ensure that package is installed, to try to avoid further build errors.

**Comment by terminator356** [comment]
Internal memo:
@spamatica Wondering why we default to RelWithDebInfo mode as shown.
Should be Release mode by default? Maybe let's check it and change it?

**Comment by rchastain** [comment]
> According to this post:
> [https://forums.mageia.org/en/viewtopic.php?f=7&t=12499](url)
> 
> the desired package is
> 
> lib64qt5help-devel
> or
> libqt5help-devel
> (depending on whether your platform is 64-bit or not. It seems to be 64-bit, so try that one).
> 
> Avoid installing Qt4 stuff. You might want to uninstall qt4-linguist, probably do not want that one.
> 
> Also according to that web page above, in Mageia you can search for any further
> missing files with something like this:
> `urpmf Qt5LinguistToolsConfig.cmake`
> and it will tell you which package contains the missing file.

Thank you for your help. I learned many things. The Qt problem seems to be solved now. But there is another error:

```
[roland@localhost muse-3.1]$ sh compile_muse.sh
Build dir already exists
 vst header path: /home/roland/Téléchargements/muse-3.1/vestige
Unix (probably linux) found
CMake Error at CMakeLists.txt:266 (message):
  ** ERROR: header file ladspa.h is required, but was not found.


-- Configuring incomplete, errors occurred!
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeOutput.log".
See also "/home/roland/Téléchargements/muse-3.1/build/CMakeFiles/CMakeError.log".
[roland@localhost muse-3.1]$ l
```

But I already installed ladspa-devel, and the file ladspa.h doest exist.

```
[roland@localhost muse-3.1]$ locate ladspa.h

/usr/include/ladspa.h
[roland@localhost muse-3.1]$ 
```

**Comment by terminator356** [comment]
> /usr/include/ladspa.h

Yes, it exists and locate shows it is there, but cmake is not finding it.

We have seen this happen a few times.
Sometimes the build folder becomes confused or something.
We recommend deleting the build folder and starting over, from scratch. It should work.
If you have already done that, then I do not know what is wrong. cmake is
 supposed to find it :-(

**Comment by rchastain** [comment]
> > /usr/include/ladspa.h
> 
> Yes, it exists and locate shows it is there, but cmake is not finding it.
> 
> We have seen this happen a few times.
> Sometimes the build folder becomes confused or something.
> We recommend deleting the build folder and starting over, from scratch. It should work.
> If you have already done that, then I do not know what is wrong. cmake is
> supposed to find it :-(

You were right! After I deleted the build directory, the problem was solved. After that, I installed some other missing packages, and now MusE is building.

**Comment by terminator356** [comment]
Tick tick tick... The suspense builds too ;-)
Good to hear.
If successful, have fun, visit the web site for the wiki, maybe a few tutorials there.
I'm done for the night. Back later. zzzzzz

**Comment by rchastain** [comment]
Build and installation successful. Thank you for your help.

> If successful, have fun, visit the web site for the wiki, maybe a few tutorials there.

OK, I will do that.

Regards.

Roland

**Comment by spamatica** [comment]
Den fre 10 apr. 2020 kl 21:43 skrev Tim <notifications@github.com>:

> Internal memo:
> @spamatica <https://github.com/spamatica> Wondering why we default to
> RelWithDebInfo mode as shown.
> Should be Release mode by default? Maybe let's check it and change it?
>

I usually use Release when building an optimized binary myself... though,
now reflecting on it, why?

RelWithDebInfo is still optimized and it has debug symbols, potentially
making it possible to pinpoint crashes during normal usage.

I guess it takes up a bit more memory but maybe not that much. And I didn't
look in the build system, maybe we don't set up things as good as we should
for this target.

And of course, we don't have any mechanism for catching back traces. But I
know there is a feature in kubuntu (or if it's kde) to catch and report
crashing programs. Haven't been paying attention to if it happens for MusE
(crashes are pretty far between).
And, yeah, I guess it has to be started from the menu.. which I seldom do.
