### ISSUE TITLE
Provide the main icon in svg (or 128x128 pixels)

### ISSUE THREAD

**Issue by hfiguiere** [muse-sequencer/muse#795]
The current muse-sequencer application is a png. 64x64 pixels.

Flathub prefer (require) 128x128. A svg would be resized automatically so it's better.
https://github.com/flathub/flathub/wiki/App-Requirements#application-icons

(yes I understand that the original icon soucre might not be suitable)

**Comment by kybos** [comment]
Not sure what you mean - the harp icon used as application icon? 
In MusE it's an .xpm with 32x32.
A png with 64x64 is used on the web page.

I found this one in the old wiki:

![harp](https://user-images.githubusercontent.com/10009541/79632773-ab103b80-8161-11ea-860c-edb4438030b3.png)

The resolution is high enough but the background is too dark to be used as icon. But it looks like it was created in Blender originally - has one of the devs the original .blend file by any chance?

**Comment by spamatica** [comment]
Sadly no, I believe it has been lost since a long time :(



Den lör 18 apr. 2020 kl 10:47 skrev kybos <notifications@github.com>:

**Comment by hfiguiere** [comment]
Yes the harp icon used for the app.

**Comment by kybos** [comment]
There is now a 128x128 icon, I made it from the logo found here on github:

![image](https://user-images.githubusercontent.com/10009541/99652101-b01acd80-2a57-11eb-81eb-ff8bb55a9584.png)

I also updated the packaging data to reflect the new release.
