### ISSUE TITLE
VST3 support

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#797]
Hello,

since the VST3 SDK is licensed under the GPLv3 (https://github.com/steinbergmedia/vst3sdk), I think it'd be nice to have VST3 support in MusE, especially considering that VST2 is officially discontinued.

**Comment by kybos** [comment]
It should be possible to use VST3 plugins through Carla. Or are there known issues with Carla in MusE? Generally I would expect it to work, as for example LMMS relies completely on Carla in that respect, AFAIK.
