### ISSUE TITLE
mono track into stereo plugin only feeds the left channel

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#799]
Not sure if this is by design, I don't think it used to be like that anyway.

**Comment by terminator356** [comment]
Carefully read the README.effect-rack.
Does the behaviour counter anything mentioned in there?

Hm. Maybe I should actually feed both inputs...
Wonder, could the logic be wrong there?

**Comment by kybos** [comment]
Or the wiki ;-)

https://github.com/muse-sequencer/muse/wiki/understanding-the-effects-rack

**Comment by spamatica** [comment]
Ah, there's documentation, who knew? :D ?

So it's by design, the input did go to both tracks previously but I'm not sure that both outputs where merged on the other end.

I might be wrong but I think some plugins can behave wierdly in this situation, if not both channels are fed. I got no concrete evidence though so I can see if I find some... no hurry.
