### ISSUE TITLE
[Feature Request} Play sound even when dragging several notes

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#807]
Piano roll editor (but I guess this applies to the Drum editor also).

With "Play events" checked, dragging one MIDI note makes a sound.

When several notes are selected, no sound is made. It would be great if the first note is sounded when dragging.

**Comment by kybos** [comment]
What is "the first note" if several notes are selected?

**Comment by StaffanMelin** [comment]
For me it is the first not time-wise, ie to the left. If it is a chord, ie several notes who are earliest, all notes should be played. If not possible, play the highest one.

It's great that you are looking into this one! :)

**Comment by terminator356** [comment]
I'm looking into this as well.
At the very least, I will try to fix a few things so that it will be in fact **possible**
 to play multiple notes when dragging them.
Whether or not this is a good thing, and would be enabled, will be seen.
I'm testing a few scenarios...

**Comment by kybos** [comment]
I played with it a little. For me a logical behaviour would be to always play the note under the mouse pointer. That would offer maximum flexibility to the user (you could explicitly choose which note to play when dragging multiple selection).
To play whole intervals/chords if they are any on the same tick would be perhaps a nice gimmick, but IMO not really necessary. Opinions can differ however...

**Comment by StaffanMelin** [comment]
> I played with it a little. For me a logical behaviour would be to always play the note under the mouse pointer. That would offer maximum flexibility to the user (you could explicitly choose which note to play when dragging multiple selection).

I like your idea!

**Comment by terminator356** [comment]
Meanwhile...
Locally I have it working sounding multiple notes at the exact same position (chords).
Several areas needed to be changed to support it.
With a change of one single line, it can instead do what kybos said - play only
 the note that is being moved with multiple notes.

I like both ideas.
However, with chords keep in mind that for musicians that record a live performance
 or program a song with notes having 'human offset', chord notes are not always
 going to line up at the same tick position.
For those users, they will move a chord but perhaps only a few notes will sound.
Also, even if the chord notes do line up, still it might confuse a new user as to why
 some notes are heard and others not.
Still, given that most chords are say, 10 notes or less and are built to be musical (?), I 
 might not find it so offensive if multiple notes were played (that was one of my worries
 when I last visited this code - must be careful of too many annoying moving notes' sounds).

Hm. Which way to go. Yet another user option, for this, hidden away in Settings? Meh...

**Comment by StaffanMelin** [comment]
I am very impressed and grateful for the time and effort you two spend on this and similar workflow issues that I have reported. I move a lot of notes around when I compose ("program") songs, so every little shortcut and improvement in this area means a lot to me (and others, I am sure).

I think an option in Settings is fine. Or, if the pointer is not on a note, play the chord. If it is, only the note.

**Comment by kybos** [comment]
> Or, if no Setting: If the pointer is not on a note, play the chord. If it is, only the note.

I believe the pointer must always be on a note - if you click outside, then the notes are deselected (as expected). Or did I get you wrong?

**Comment by StaffanMelin** [comment]
> > Or, if no Setting: If the pointer is not on a note, play the chord. If it is, only the note.
> 
> I believe the pointer must always be on a note - if you click outside, then the notes are deselected (as expected). Or did I get you wrong?

No, you are absolutely right! Sorry!

**Comment by terminator356** [comment]
Aaalllrighty then. In git master now:

New - PianoRoll Speaker button has two selectable modes: Single note and chords.
See the small drop-down arrow to the right of the button.
In chord mode, notes of a chord must be at the same position as the **note that is being dragged**.
Note that when dragging, sometimes you may see chord notes 'flip-flop' between x-positions.
This is normal. Only the notes at the same position as the dragging note will sound.

Also fixed Drum Editor single note mode when multiple notes moving.
Give it a try. Lemme know if any trouble.
That's all I have time for at the moment. Big bugs await...

**Comment by StaffanMelin** [comment]
You are awesome! Works beautifully!!! This is a big workflow improvement!

Works in both single note and chord "mode", as well as in drum editor (for single notes).

Wow!

**Comment by terminator356** [comment]
Sadly I did not have time to make the setting 'persistent'.
You'll have to set it each time a PianoRoll is opened or re-opened.
I'll see if there's time later to do it.
Leave this issue open for a while as a reminder.
