### ISSUE TITLE
[Feature Request] Ctrl-dragging part on Arranger should select new copy

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#808]
Arranger window.

When I Ctrl-drag a part to make a copy in a new place, the original is still selected.

Wouldn't it be more consistent with how other applications work if the copy would be selected after the action? Eg LibreOffice Draw,

**Comment by kybos** [comment]
Yes, I changed that already in the midi editors some time ago. The arranger would be next, it's on my list.

**Comment by StaffanMelin** [comment]
> Yes, I changed that already in the midi editors some time ago. The arranger would be next, it's on my list.

That sounds awesome, thanks a lot! :)

**Comment by kybos** [comment]
Done in master, please test.

**Comment by StaffanMelin** [comment]
Awesome kybos! I will test it tomorrow! :) This will really speed up my workflow!

**Comment by StaffanMelin** [comment]
Works as I want to! :) Many thanks for fixing this!
