### ISSUE TITLE
Can't add lv2 and other plugins path in muse 3.1

### ISSUE THREAD

**Issue by arnab20** [muse-sequencer/muse#819]
I've downloaded it from flathub and I'm using Manjaro Linnux. The problem is that can't add lv2 or any other plugins path in Muse 3.1, whenever I'm trying to add a new path for plugin it is not showing the desired folder. Please see into it. Thank you.

**Comment by kybos** [comment]
The flatpak version is not provided by the MusE team (I think it's by @hfiguiere ). 
Generally I would say it's the nature of flatpaks and similar technologies that they don't have access to the OS by default.
Just use your preferred search engine, there is a lot of information on that and what can be done, e.g.:

https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

**Comment by hfiguiere** [comment]
LV2 plugins needs to be flatpak packaged because everything is sandboxed, and the application is restricted to accessing the home directory. It might be possible to load a lv2 plugin from it, but there is no guarantee it will work.

However, there is a certain number of plugins that do exist on flathub. Their discoverability is not great though (it needs to be improved).

**Comment by hfiguiere** [comment]
Also I think there is a bug in Muse3 as `LV2_PATH` is ignored if the settings have already been initialized. Make sure that `/app/extensions/Lv2Plugins/lv2` is set in the LV2 plugin path.

I should actually file a bug. `LV2_PATH` should always be honoured.

**Comment by hfiguiere** [comment]
BTW while we are at it, which LV2 plugins are you looking to install?

**Comment by autumncheney** [comment]
i'm having this issue too, except i built muse from source

@hfiguiere, how do do i set the lv2 plugin path?

**Comment by hfiguiere** [comment]
Set `LV2_PATH` environment, it is only used on first startup. Otherwise, editing the settings in the UI.

Flatpak was the case of the original report, which is not standard as it has sandboxing, and is something that actually work.
