### ISSUE TITLE
MusE fails to handle compressed project files

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#831]
Scenario:
- create new project with one MIDI track and one part, draw some notes
- save as "gzip compressed med Files (*.med.gz)", provide a song info
- close file
- open the compressed file again

The song info appears, but the MIDI track is missing in the arranger. The same scenario works of course if "Uncompressed med Files (*.med)" is selected when saving the project.

The .med.gz project file can be opened again if it is uncompressed manually with "gunzip" to .med, so the content of the compressed project file seems to be OK.

**Comment by terminator356** [comment]
A fix has been applied in git master.
Thanks for the report. Was my fault, regression at 1/1/20.
Let me know if any trouble. A maintenance release is in the works soon.

**Comment by Gnlfz007** [comment]
Yep, rebuilt from master branch, works for me.
