### ISSUE TITLE
Shortcut for "Rewind on stop" (toggle) should be available in the editors too

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#839]
The shortcut "Shift-Ctrl-R" is not available in the panio roll or drum editor. This is annoying because I would like to toggle this many times when fixing longer midi parts. Now I have to bring up the main window to select the menu entry "Settings / rewind on stop" every time.
Would it be possible to make this shortcut global?

**Comment by kybos** [comment]
Not reproducible here, for me it works in both midi editors (current master).

**Comment by Gnlfz007** [comment]
Tested again with 3.1.1 and ~/config/MusE removed:
"Shift-Ctrl-R" is neither functional in the piano roll editor nor in the drum editor. It is functional in the main window.

Are we talking of the same function? I expect that after restart (<space> to stop, <space> to restart) 

- playback starts at the very first start position over and over again ("rewind")
       or, after Shift-Ctrl-R,
- playback continues where it left off ("no rewind").

... and all this _within_ the editors.

Sorry for the over-detailed description, but how can it be possible that this works for you?! Are you on Windows? Are there issues with the keyboard layout? I'm running 3.1.1 on Linux with DE layout.

**Comment by Gnlfz007** [comment]
Tested once againt, with MusE built from current master branch instead of 3.1.1 - no change.

Acceptable workaround (Linux only):
- configure desktop to no-focus-follows-mouse and no-auto-raise-window-on-focus (my prepared mode anyway)
-  leave a little are of the main window visible, i.e., don't used editors in full screen mode
- move mouse to this area and press Shift-Ctrl-R
- and move mouse back to editor...

(Malicious joke - don't take serious: DAW = Digital Audio Workaroundstation ;-) )

**Comment by kybos** [comment]
I should have mentioned that I use Muse in the MDI/Cakewalk-like mode, perhaps this is the reason it works for me, as everything happens in one central MDI window.

If this could be an option for you, here is how to set it up:

Global Settings->GUI Style (last tab)->Press Cakewalk-like MDI

Also recommended:
Global Settings->GUI Tweaks->check Open MDI subwindows maximized

**Comment by Gnlfz007** [comment]
That's a really good explanation. I'll try the MDI interface, but most likely I will fall back to the default interface because of the multi monitor setup.

**Comment by spamatica** [comment]
As I'm responsible for halfassing this and actually Has missed this functionality I will try to fix it.

**Comment by Gnlfz007** [comment]
git pull - make install - run and test in piano roll editor - works fine!
Thanks a lot, this was an incredibly quick fix!

**Comment by kybos** [comment]
@spamatica 

So the shortcut was defined for the Arranger only before?
Is it not strange (and wrong) then that it worked in the MIDI editors as well in the MDI mode?
