### ISSUE TITLE
Crash if part's left boundary is expanded to the left

### ISSUE THREAD

**Issue by Gnlfz007** [muse-sequencer/muse#842]
Scenario:
- New song
- Create part with arbitrary length at bar #1 and draw a note, starting at the very left, at beat 1.
- With the same draw tool, try to expand the left boundary of the part to the left.
Boooooom bang bye!

Of course this is not a major issue (just don't expand bar1 to the left), but a DAW should not crash that willful. As said before, it is OK for me to be the tester ;-)

And no, I don't find the mistakes out of malice. I wanted to add a count-in to the left of the song because I do not like the restrictive metronome. I just failed to move the entire song one bar to the right before.

**Comment by spamatica** [comment]
I'm not doubting you but I can't recreate. 
1. I started muse
2. drew a part at the beginning of the empty song.
3. opened the part and drew a note in the beginning
4. went back to the arranger and tried to extend the part beyond the start (to the left)
5. Nothing bad happens.
Am I misunderstanding?

No worries, reporting bugs (especially crashing bugs) is common sense and you are quite welcome to do it :)

**Comment by Gnlfz007** [comment]
>     5. Nothing bad happens.
>        Am I misunderstanding?

No, that's exactly what I did.

**Comment by spamatica** [comment]
Okay, will test some more, must be some other variable at work. 
If you find out let me know.

**Comment by Gnlfz007** [comment]
> gdb  -ex run --args /usr/local/bin/muse3 -a -d
[Thread 0x7fffe5231700 (LWP 11121) exited]
[New Thread 0x7fffe5231700 (LWP 11132)]
[New Thread 0x7fffe5a32700 (LWP 11133)]
INFO: Could not get the wanted frequency 1024, got 250, still it should suffice.
[New Thread 0x7fffe4a30700 (LWP 11134)]
midi thread 11106 _NOT_ running SCHED_FIFO
... and now doing the bad move ...
Thread 12 "muse3" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe5231700 (LWP 11132)]
0x00007ffff65f8909 in std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb)

If still in doubt, I _could_ provide a screen cast, but I'd prefer to make some music ;-)

Not a really urgent bug; it just should make it to the ToDo list for 3.1.2.

**Comment by Gnlfz007** [comment]
**UPDATE:** This applies to any part of a track, not just to the first part located at bar#1!

While I do _not_ consider it necessary to extend parts to the left,  just one accidental click in the arranger is able to crash MusE.
This issues should become highest priority, I think.

**Comment by Gnlfz007** [comment]
Nobody able to reproduce this?!

**Comment by hippie403** [comment]
MusE 3.1.1 running on Raspberry Pi OS (ARM Debian Buster 32bit) ,  crash every time a part is expanded to the left.

**Comment by spamatica** [comment]
I can reproduce this now! Just need to figure out what goes wrong.

**Comment by spamatica** [comment]
Hopefully fixed this now in master. If possible, please test.

**Comment by hippie403** [comment]
Built and installed muse-master on Raspberry Pi4 Raspberry Pi OS 32bit.  I can no longer cause a crash expanding a part to the left. Goodness me it takes a long time to build on a Pi4!

**Comment by terminator356** [comment]
> Built and installed muse-master on Raspberry Pi4 Raspberry Pi OS 32bi

Oh, you can do that? Cool. I think @spamatica was experimenting with that too.
How does it work?

**Comment by spamatica** [comment]
Indeed, I've run muse on raspberry pi but it was a very long time ago, might have been on Raspberry pi 1 even :D
Good that the crash can't be reproduced, might warrant a 3.1.2 release.

**Comment by Gnlfz007** [comment]
Yep, no crash anymore with MusE rebuilt from master branch. Thanks, you killed my bug.
