### ISSUE TITLE
SimpleDrums: Send Effects can only load LADSPA

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#851]
When clicking Send Effects and the "L" button, only LADSPA plugins are available. It would be nice if LV2 plugins were available, as SimpleDrums is bundled and useful.

**Comment by kybos** [comment]
Sorry Staffan, I think this one is not realistic. Plugin in plugin is quite a hack, and adding such a complex thing as LV2 doesn't seem feasible.

**Comment by StaffanMelin** [comment]
I totally understand! No problem, there are plenty of other options!
