### ISSUE TITLE
Feature request: Piano roll editor should show start of part

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#852]
When editing a part (inset and outlined in red) in the Piano roll editor (by double clicking it with the Pointer), I'd rather like to see the start of the sequence than the end.

![muse_selectedarranger](https://user-images.githubusercontent.com/33361311/92002941-b8107e80-ed40-11ea-8b28-663a7b36389d.png)

**Comment by Gnlfz007** [comment]
+1
I also noticed this, but I complained way to often to report yet another minor issue. Make friends, not enemies ;)

**Comment by StaffanMelin** [comment]
> I also noticed this, but I complained way to often to report yet another minor issue. Make friends, not enemies ;)

I'n my opinion I think a well written bug report or feature request can only help the developers. Usability issues are hard to spot because we all use software in a personal way.

MusE has really improved during my 1+ year of using it, the developers have addressed several of my "issues", and I am very grateful for this. Right now I am giving back by writing a tutorial, hopefully it will be included in the wiki.

**Comment by terminator356** [comment]
The part opens where you double-clicked it.
Thus if you double-clicked at bar 20 on a 50 bar long part, the pianoroll editor should open the part at, or around, bar 20.

**Comment by StaffanMelin** [comment]
> The part opens where you double-clicked it.
> Thus if you double-clicked at bar 20 on a 50 bar long part, the pianoroll editor should open the part at, or around, bar 20.

Oh, great! Tested -- it works! Thanks a lot!

**Comment by StaffanMelin** [comment]
To open at start, double click part at start.

**Comment by terminator356** [comment]
Yes, it may seem a little weird with short parts, having to double-click at or near the start of the part,
 but with long parts we see the benefit of being taken directly to, or near, the place that was double-clicked.

I keep saying "at or near the place that was double-clicked", because I think the pianoroll
 tends to 'round off' the opening place to the nearest bar. That is why it may **seem** sometimes a little bit off-place
 from where you actually double-clicked.

**Comment by StaffanMelin** [comment]
> I keep saying "at or near the place that was double-clicked", because I think the pianoroll
> tends to 'round off' the opening place to the nearest bar. That is why it may **seem** 
>sometimes a little bit off-place from where you actually double-clicked.

For me, rounding off to a bar is preferable, so I am happy! :)
