### ISSUE TITLE
A small improvement: Better octave numbers

### ISSUE THREAD

**Issue by uzr123x** [muse-sequencer/muse#869]
I mean piano roll's C3, C4, C5 etc. They look oddly stretched, perhaps replace them with a different font that's more up to standard

**Comment by kybos** [comment]
The MusE version and possibly a screenshot would be helpful.

**Comment by userabc123xyz** [comment]
in MusE 3.1.1, but actually in any version, when you zoom in or out in the piano roll and use any zoom level other than the default one, note names become either stretched or squeezed and plain unreadable.

**Comment by kybos** [comment]
Not sure about 3.1.1, but in current master the font is pretty readable, even in the extreme zoom levels. The whole piano drawing has been reimplemented recently. Nevertheless, the font is still zoomed together with the view so it is stretched in high zoom levels, just like everything else in the view. But that shouldn't impair readability.
Possibly a font was used that doesn't exist on your system and you got a bad font substitution. I changed that so the current system font is used now for the piano keys.

**Comment by uzr123x** [comment]
But why does octave name text have to be stretched together with the keyboard? Shouldn't it just gradually become larger without any vertical distortions?

**Comment by terminator356** [comment]
Do you mean expand equally horizontally as well as vertically, which keeps the aspect ratio?
Looking at the white key space, it seems that might be possible, even if the text has to be moved down a bit.

Or, perhaps better, @kybos could we limit the expanded size to that found at zoom level '3' or '4' ?

**Comment by uzr123x** [comment]
> Do you mean expand equally horizontally as well as vertically, which keeps the aspect ratio?

Yes, of course. To put it simply, just make octave name font larger or smaller in accordance with the current zoom level, without any unnecessary visual distortions.

**Comment by kybos** [comment]
> Or, perhaps better, @kybos could we limit the expanded size to that found at zoom level '3' or '4' ?

In my opinion we should remove the two highest zoom levels in the pianoroll in the first place. They look ridiculously huge (and yes, then also the font is visibly distorted), I can't imagine that anybody uses it in practice, and it makes it harder to select the right zoom level with the slider in the scrollbar.

**Comment by terminator356** [comment]
Sounds OK. Can't think of a reason why we need those levels... so far.
If changing it, try to ensure that a user's existing setting is capped and limited upon starting up after the changes.
