### ISSUE TITLE
AppImage fails to run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [muse-sequencer/muse#873]
Thanks for making an AppImage for Linux :+1: 

However, it currently fails on the oldest still-supported Ubuntu release:

```
AppRun.wrapped: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /run/firejail/appimage/.appimage-9309/usr/lib/libmuse_core.so)
```

Please build on a distribution no newer than xenial on order to produce binaries that can run on all still-supported distributions. 

Should it not be possible to build on xenial, please let me know so that we can dicuss other options.

Thank you for your consideration.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2370

**Comment by kybos** [comment]
No idea how you found it, but it's just an experiment ATM (for both AppImage and github Actions) and subject to testing. Unstable by definition anyway, just the current master. So we should be careful with publishing.
I know it doesn't run on xenial (I did not use your linuxdeployqt, obviously), the main reason being many libraries used by MusE itself do not meet the version requirements there.

**Comment by probonopd** [comment]
Hi @kybos, thanks for letting me know. Should you ever be interested in having it published on AppImageHub then it needs to pass the test on the oldest still-supported Ubuntu release which currently is xenial.

**Comment by kybos** [comment]
Yes, I understand, thanks.
