### ISSUE TITLE
Crash when recording audio

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#889]
I have experienced this a few times over the months.

While recording a song. I have one Audio Input, one Audio Wave track. Suddenly, in the middle of recording, MusE crashes.

Message in terminal:

```
MidiJackDevice::queueEvent() evTime:8489754 < syncFrame:8491008!!
unknown NRT Msg 0x01
dump 4
7e 7f 09 01 
Segmentation fault

```

**Comment by kybos** [comment]
There was an array pointer getting out of bounds in the dump loop.
Not sure if this was really causing this dump, as I can't reproduce it.

Please reopen this if the issue occurs again.

**Comment by caoba1** [comment]
Td to tt
