### ISSUE TITLE
Feature Request/GUI Upgrade: Better scrollbars

### ISSUE THREAD

**Issue by uzr123x** [muse-sequencer/muse#892]
I think MusE's scrollbars look somewhat crude and out of place,  maybe it's time to change them to something that's a bit more modern-looking, in light of how MusE has upgraded its appearance in recent years?

**Comment by kybos** [comment]
The scroll bars and other such widgets depend on your system style in the current stable version of MusE. 
This will be a little different with the new version, but then you can customize the scroll bars to your liking by means of Qt style sheets.
See https://github.com/muse-sequencer/muse/wiki/ui-customizing for details.

**Comment by uzr123x** [comment]
that's cool, kybos
