### ISSUE TITLE
Inconsistent tagging

### ISSUE THREAD

**Issue by dvzrv** [muse-sequencer/muse#901]
Hi! I package muse for Arch Linux.
For packaging purposes I use [nvchecker](https://github.com/lilydjwg/nvchecker) to keep track of all of my upstreams.

Unfortunately muse tends to have a very inconsistent tagging scheme, that requires me to add a lot custom regular expressions to be able to track the stable releases (by excluding the non stable releases): `(v|muse|)([\\d._]+)(|)(pre|rc|RC|alpha|beta)(-[\\d.]+|[\\d.]+|)|(2.2beta2|muse2_20110914_last_rev_without_MDI_interface|muse-3_0_2|muse-3_0_1)`

Usually something such as the following is enough when a project follows semver: `(v|)([\\d.]+)(|)(pre|rc|RC|alpha|beta)(-[\\d.]+|[\\d.]+|)`

There are now 5 or more different types of tags in this repository:

* `<major>.<minor><prerelease>`
* `muse-<major>_<minor>_<patch>`
* `muse_<major>_<minor>_<patch>`
* `muse_<major>_<minor>_<patch>_<prerelease>`
* `muse2_<date>_<words>`
* `latest` (?)

See `git ls-remote --tags https://github.com/muse-sequencer/muse` for reference.

This is extremely confusing and I would like to urge you to choose a streamlined approach and then stick to it (e.g. plain [semver](https://semver.org)).

**Comment by spamatica** [comment]
Yeah, guilty party here..  a bit clueless naming.

Our most common one is:
muse_<major>_<minor>_<patch>
and
muse_<major>_<minor>_<patch>_<prerelease>

Would adding a muse_4_0_0_pre1 tag improve the situation? And sticking to that naming going forward of course.

**Comment by spamatica** [comment]
I think (raking my brain) the use of underscores is a left over from the svn days.
I guess you would prefer that we switched to 4.0.0pre1. 
Maybe that won't be so bad, it introduces one more naming but it's standardized and you will only care about the most recent tag if I understand you correctly?

**Comment by kybos** [comment]
As for the "latest" tag (my addition):

This is created by the automatic build process and is quite standard these days - some call it "latest", some "continuous" etc. 
It does not fit into the semver schema of course, as it's independent of any version, just a snapshot of the current master. 

You could exclude it explicitly in your regex, or better, you should ignore all lightweight tags (without "^{}" at the end) in the "ls-remote --tags" output. That would get rid of "latest" and other irrelevant things automatically.

@spamatica 
I understand that he wants to get the last stable release.
I am always for standardization where possible, especially in cases like this when there are processes that depend on it. Makes life easier for everybody ;-). So I think we should stick to the semver naming convention, which is a kind of standard.

BTW: I think it should be "4.0.0-pre1" for the current pre-release, if my understanding is correct.

**Comment by spamatica** [comment]
Alright, so we go with semver compatible tagging from now on (at least where applicable).
Closing
