### ISSUE TITLE
MESS Fluidsynth Soundfont loader doesn't save gain (Volume)

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#905]
Enter the Native GUI of MESS Fluidsynth soundfont loader.

Set gain to something else than the (very low) default.

Save your song.

Reload your song.

The Gain is back to default.

**Comment by kybos** [comment]
I see in the code that none of the slider values are saved, it's simply not implemented, not really a bug. I can't tell if there is a reason behind it, but it should be possible.

**Comment by StaffanMelin** [comment]
Thank you for investigating!

For making music with sf2, I have two choices, the MESS Fluidsynth or the CALF Fluidsynth player.

For my latest batch of songs I used the MESS FL, so every time I get back to a project I have to adjust the Gain, because the default is very low.

This has made me want to use the CALF FL player as the state seems to be saved.

If I think out of the box, why ship any synths with MusE. They have limitatons (see my previous bug report on the drum machine), and sooner or later, in my opinion sooner, you have to start using plugins you have downloaded.

Maybe it is time to throw out those five (?) MESS plugins?

**Comment by spamatica** [comment]
> I see in the code that none of the slider values are saved, it's simply
not implemented, not really a bug. I can't tell if there is a reason behind
it, but it should be possible.
Ah, right. That is old code indeed.

Den tis 1 dec. 2020 kl 21:55 skrev Staffan Melin <notifications@github.com>:

> Thank you for investigating!
>
> For making music with sf2, I have two choices, the MESS Fluidsynth or the
> CALF Fluidsynth player.
>
> For my latest batch of songs I used the MESS FL, so every time I get back
> to a project I have to adjust the Gain, because the default is very low.
>
> This has made me want to use the CALF FL player as the state seems to be
> saved.
>
> If I think out of the box, why ship any synths with MusE. They have
> limitatons (see my previous bug report on the drum machine), and sooner or
> later, in my opinion sooner, you have to start using plugins you have
> downloaded.
>
> Maybe it is time to throw out those five (?) MESS plugins?
>

To talk history, Werner, the original author, wanted MusE to have
everything so he made his own synth format, probably because it was fun.
Later my own justification has probably been that it allows us to be
completely self contained, songs created in MusE with only MusE.

But reality is that the internal synths are somewhat neglected so there is
logic in what you are saying.

Throwing them out isn't that good an option though as there might be songs
using them (not the least myself has lots of old songs with fluidsynth).

So maybe we should take a less hard approach, mark that menu as
Deprecated/Do not use for new projects, or something like that?
Alternatively we fix them up...

**Comment by StaffanMelin** [comment]
Would it be possible to move the MESS synths out into a plugin?

Also, there are some FX plugins included, too?

**Comment by terminator356** [comment]
Hm, I could swear those settings were stored. I think as midi sysex commands. I'll have to check...

> Would it be possible to move the MESS synths out into a plugin?
Ha! I thought about that! Convert them to LV2 or something....

> Throwing them out isn't that good an option
Especially **not** the MESS fluidsynth loader !
Having our own built-in MESS plugin architecture means we can do things that no other plugin system can do.
Like accessing the reverb and chorus directly. And, most importantly, accessing the soundfont drum note names,
 which is something that no other plugin system lets us do.
Yes, there are LV2 soundfont loaders that I believe give us the note names via midinam,
 but that is rather tedious and our midinam support is brand new, although it should work.
I think I examined a few of those LV2 soundfont loaders and the support didn't seem to be as complete as ours.

**Comment by kybos** [comment]
> Hm, I could swear those settings were stored. I think as midi sysex commands. I'll have to check...

As I wrote above, the saving of the slider values (also Chorus type/number) is not implemented. All the other settings are stored indeed (as sysex).
 
> > Throwing them out isn't that good an option
> 
> Especially **not** the MESS fluidsynth loader !

I fully agree. I always had issues with the Calf SF player, and always came back to our MESS one. I even made some improvements recently, so it's now possible to distribute the current SF to all/empty channels.

**Comment by kybos** [comment]
Fix is in master (all fluidsynth parameters should be properly stored now).

**Comment by StaffanMelin** [comment]
Awesome, great work @kybos! Thank you!
