### ISSUE TITLE
. feature request..midi input plugin midi remote control...

### ISSUE THREAD

**Issue by revolverve** [muse-sequencer/muse#915]
Could a feature to assign any controller over the limited choice of notes be doable within the gui?
or,some may have another solution to achieve simple ¨midi binding¨ ,e.g.;
axiom air mini 32 use by default (and kind off hardcode ;™hypercontrol)gen.purp.num:16-17-18 for stop-play-record.

else,(please tell me if i should i open those in another  issue)
-where can i find info/doc about functions of midi input transformator? 

else,with endless round of applause...
An appimage worth all its mb weight rather than multiple attempts and failure at tries compiling !!!
Good grace its a relieve ..

**Comment by revolverve** [comment]
The bot is  brain on a checking spree...good thing!! it found that replica:
 
https://github.com/muse-sequencer/muse/issues/566#issuecomment-751288269
so closed this one for that nice 2017 one.

**Comment by revolverve** [comment]
Greetings ....

**Comment by revolverve** [comment]
Thanks kybos !!!!
Simply works!!!
Very handy feature.

**Comment by kybos** [comment]
Thanks for the feedback, glad it's working.

As for your other question:

> else,(please tell me if i should i open those in another issue)
> -where can i find info/doc about functions of midi input transformator?

I'm afraid there is none, like for many other functions of this pretty complex application. This is simply not doable with the very limited dev resources we have... Help from the community is welcome and necessary here.

I must confess I don't know this function either, but feel free to open a new ticket on it with concrete questions, there is a good chance one of the more experienced devs (or users) will help.
