### ISSUE TITLE
Solo shortcut in arranger (Meta+S) not working

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#923]
Meta+M for mute still works so probably a typo somewhere.

**Comment by kybos** [comment]
Meta+S did not work for me either, because it was taken by the system (for "Show desklets"). After unassigning it there it's working again in MusE.
A typical problem with Alt and Meta shortcuts...

**Comment by spamatica** [comment]
Yeah, just realized this myself... quite annoying.. it's not that long ago I added those and apparently it was working then. I guess I will change the default shortcut to something else... 

The really annoying part is that we can't know that the window manager will eat them so we can't warn about it.
