### ISSUE TITLE
glue audio parts extends event length incorrectly

### ISSUE THREAD

**Issue by spamatica** [muse-sequencer/muse#924]
To illustrate try the following:

Have one audio part, cut it in two pieces, move the later part a bit so they are no longer aligned.
Now use the glue tool and glue them together. 
The result is that the audio event from the first part will be extended to the end of the new part. Which in this case will be audible as an echo as the event from the later part will start to sound also.

**Comment by spamatica** [comment]
Well f*ck me. Now I can't repeat it... did someone recently fix this?

**Comment by terminator356** [comment]
Merry Christmas Robert! No I didn't fix anything...yet.
But I am actually fixing it for the last few days.
One of the things you did in there during 'right wave part border resizing' work was that
 you automatically extended wave events to match the length of the part.
But (and by your own admission in comments) the code is actually wrong and ends up 
 extending the wave event length far **beyond** the right part border.
That causes some problems, and may actually be the cause of your observations here.
So I'm fixing that up, along with adding some embellishments to the horizontal red blue and black line drawing
 to make much clearer the boundaries of part, event, and actual wave. I'm adding this to both the wave editor
 **and** the arranger drawing too, to make boundaries much clearer.

Cheers.
Tim.

**Comment by spamatica** [comment]
Ah, cool!
Yeah, I sort of new I left some parts dangling but couldn't wrap my head around it representing a problem... well of course it can.. 

Maybe there needs to be some other edit operation before this bug is triggered, or something, because I saw it as late as yesterday. Today when I made the ticket and went ahead to try and isolate the issue my test case worked fine :P
I'll wait for your fixes then :)
