### ISSUE TITLE
Mixer: Changing volume of multiple selected tracks resets position to identical value

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#928]
OS Archlinux, MusE 4.0.0-pre1-127-g381f20da

When selecting multiple tracks in the mixer you can adjust their level at the same time. That's very useful, however it will reset all tracks to the same level:

https://user-images.githubusercontent.com/70516194/103299272-6f21bb80-49fc-11eb-987e-07a06ddbc491.mp4

I would expect that all selected tracks would change their position relative to the initial position (like activated groups in ardour):

https://user-images.githubusercontent.com/70516194/103299313-852f7c00-49fc-11eb-826e-61fe56b7d7ed.mp4

**Comment by kybos** [comment]
I looked at the code - it doesn't seem to be a bug but intention.

@terminator356 @spamatica 
Do you know why it's so? Does it really make sense?

**Comment by spamatica** [comment]
No idea.
I agree, if the volume change was relative it would be more usable.

Den ons 6 jan. 2021 kl 10:40 skrev kybos <notifications@github.com>:

**Comment by terminator356** [comment]
Yeah I could swear I added Ctrl or Shift key for that but they don't seem to work.
I'm trying to remember if there was some confounding reason why I didn't do it.
I am certain I must have considered it during that long period of coding that stuff.
It's possible that the rather complex code involved would not let me accomplish it... (easily).
I'll try to examine...

**Comment by kybos** [comment]
I've just found out that if you change the volume for selected tracks by means of the keyboard shortcut (default is Alt+Up/Down), then it works as expected.
If you have a mix of midi/audio - linear and log scale, then the conversions are apparently not as exact as with the new code (when using the mouse), but that will be only a minor issue in most cases.

**Comment by MyLoFy** [comment]
Great! The behaviour is different to the example above, but I don't think that's always the best user scenario anyway. Thanks!
