### ISSUE TITLE
Plugin: Vital synth looses matrix data after deactivation

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#929]
OS Archlinux, MusE 4.0.0-pre1-127-g381f20da
I only tested this with LinuxVST Vital https://vital.audio/ not yet with other synths:
To relieve the CPU I like to print MIDI tracks to audio and then deactivate the MIDI tracks with the CPU hungry synths like Vital. That way I can go back to MIDI in case I wanna tweak stuff.
When I do so with MusE/Vital the matrix data gets lost:
Before deactivating:
![vital_pre](https://user-images.githubusercontent.com/70516194/103300644-9ded6100-49ff-11eb-9587-e40dca9217d4.png)
After deactivating:
![vital_post](https://user-images.githubusercontent.com/70516194/103300661-af366d80-49ff-11eb-88ca-937ad9522aca.png)
Steps to reproduce:
Create Synth track with vital
Add matrix automation
Save and close
Reopen session, deactivate Synth track
Save and close
Reopen session: Matrix data is gone

I have attached the session before (Vital_Pre.med) and after deactivation (Vital_Post.med).
[vitaltest.zip](https://github.com/muse-sequencer/muse/files/5751504/vitaltest.zip)

**Comment by kybos** [comment]
I get only crashes from Vital, no matter if lv2, vst2/3 or standalone, in Carla, MusE, QTractor...
It could be my HiDPI screen, there are several tickets on similar issues on the Vital forum.

**Comment by kybos** [comment]
You mean you lose all the parameters or only the Matrix?

**Comment by MyLoFy** [comment]
Only Matrix data was affected. Can't reproduce it anymore with latest MusE build and updated Vital VST 1.0.5 (LV2 crashes on any host), seems like it was resolved somewhere. Thanks!

**Comment by kybos** [comment]
Good to hear. V1.0.5 solved several problems for Linux, except the LV2 instantiation...
Closing this.
