### ISSUE TITLE
Plugin windows don't resize with window size

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#930]
OS Archlinux, Plasma 5.20.4, MusE 4.0.0-pre1-127-g381f20da
All tested LV2 and LinuxVST plugins do not resize when the window size is changed:

https://user-images.githubusercontent.com/70516194/103304999-53251680-4a0a-11eb-8ea1-73ef6db7ae98.mp4

**Comment by kybos** [comment]
We can't resize plugins that don't support resizing.
The container window itself is resizeable because the plugin definition (of your example LSP plugin) provides no hint that it should be fixed size either.
So unless your plugins behave differently in other hosts/DAWs, such issues should be addressed to the plugin owners.

**Comment by MyLoFy** [comment]
Thanks kybos! Yes, LSP plugins do resize in Ardour, Carla and qtractor, which is especially helpful using EQ plugins for small tweaks during mastering. I can't seem to resize several plugin GUIs in MusE, but I can do so in other hosts (tested: LSP, B.Music plugins, x42 plugins, guitarix LV2s, infamous)
However, the rncb plugins like padthv1, synthv1 resize fine in MusE. 
My current workaround is to use Carla as a wrapper.

**Comment by kybos** [comment]
OK, if they resize in other hosts, I will have a look.

**Comment by kybos** [comment]
I tried to fix it for lv2 x11 plugins. Please check if it's working for you now.

**Comment by MyLoFy** [comment]
Yes, LV2 plugins do resize now, great, thanks!

**Comment by kybos** [comment]
Do you have an example of a VST plugin that should resize but doesn't?

**Comment by MyLoFy** [comment]
No, I initially thought that LSP VSTs would resize in other hosts, but they don't. After testing around 20 VSTs the resizing behaviour in MusE seems to be identical as in other hosts.

**Comment by kybos** [comment]
OK, then let's close this one.
