### ISSUE TITLE
Feature request: Options on automation nodes

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#931]
Multiple feature request for audio automation nodes:
-nodes should be bigger so they can be grabbed more easily
-Option for bezier curves on automation nodes (linear automation mostly sounds unnatural)
-Multiple Select and Copy/Paste support 

Please let me know if single issues should be opened for each item.

**Comment by uzr123x** [comment]
I second this, I wanted to start a bezier curves request myself.

**Comment by kybos** [comment]
I made the nodes a little bigger, they were really hardly visible.

Bezier curves, well... Full-featured editing and evaluation of them? Like e.g. Inkscape? I don't think this is realistic, but I may be mistaken.
Perhaps some kind of approximation, automatic smoothing for 3 selected nodes adding nodes in between as needed, still keeping it linear?

**Comment by MyLoFy** [comment]
oh yeah, nodes are easier to grab now, thanks!

This is purely from a user standpoint, since I'm absolutely clueless about the programming side. 
As per now it is difficult to edit the existing audio automation because you can only move one node at a time. So, moving around parts would mean I have to clear and redraw all automation. 
Regarding the bezier curve I think full featured inkscape-like curves perhaps might be overkill for a DAW, but any additional curve algorithm (or approximation) other than linear could sound easier on the ears.

Just an idea in that context: Another fancy option for automation could be the possibility to somehow assign the MIDI automation of a MIDI track/part to any parameter via the "MIDI control => Assign" dialogue. That way MIDI tracks/parts could be (mis)used as independent automation parts, fully movable and editable. That's only an idea out of the blue :) but perhaps easier to implement.
Cheers!

**Comment by terminator356** [comment]
> Another fancy option for automation could be the possibility to somehow assign the MIDI automation of a MIDI track/part to any parameter via the "MIDI control => Assign" dialogue.

Yep. That is what I was trying to do several years ago when I tried to write a replacement for the overcrowded
 audio automation controllers popup menu. Recently I grabbed that old code and put it into our source tree
 in the hopes of finishing it.
It was going to be an uber controller dialog. Assign any midi or audio controller to any midi or audio parameter.
Very, very complicated. So many things to do in there...

**Comment by uzr123x** [comment]
> Regarding the bezier curve I think full featured inkscape-like curves perhaps might be overkill for a DAW, but any additional curve algorithm (or approximation) other than linear could sound easier on the ears.

exactly

**Comment by spamatica** [comment]
Den fre 15 jan. 2021 kl 06:29 skrev uzr123x <notifications@github.com>:

> Regarding the bezier curve I think full featured inkscape-like curves
> perhaps might be overkill for a DAW, but any additional curve algorithm (or
> approximation) other than linear could sound easier on the ears.
>
> exactly
>
Are there any use cases where this can be illustrated?
I am very much a sceptic that this is a problem often enough to warrant the
effort. You can always draw intermediate points to smooth out a change.

As for adding multi point edit and copy paste, that is a big Yes, we should
have that.

**Comment by MyLoFy** [comment]
> Are there any use cases where this can be illustrated?  

I think this is more how our perception works on a physiological level. Take a fade in/out or a filter sweep for example: both would sound more pleasant when automated with a sigmoidal or logarithmic algorithm (hence the variety of fade in/out types in some DAWs)
> I am very much a sceptic that this is a problem often enough to warrant the effort. You can always draw intermediate points to smooth out a change. 

Absolutely true, this was more of a loose suggestion since I cannot estimate the programming effort involved in such things.
> As for adding multi point edit and copy paste, that is a big Yes, we should have that.

I agree, that would improve the workflow immensely.

**Comment by uzr123x** [comment]
well, Qtractor is a one-man project and it has bezier automation curves as an option..

**Comment by terminator356** [comment]
Most everything requested has been done.
See ChangeLog 19.06.2022 and earlier.

Although there are no Bezier curves, the graphs are logarithmic for log controllers,
 so there shouldn't be a need for Bezier curves, since the graphs are not linear in that case.
The 'node' size is now adjustable in Settings.
