### ISSUE TITLE
Option for showing existing automation

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#932]
Arranger: When using a synth with hundreds of parameters and you have blindly written an automation it is very difficult to find the active audio automation curve in the arranger. An option on the track (e.g. "show all existing automation") would be helpful.

**Comment by kybos** [comment]
Yes, I missed that too...

Fix is in master, see changelog:

03.01.2021
    - Fix #932: Add Show All with Events/Hide All to track automation menu.
        Modify control icons so it's clear which controls contain events.
