### ISSUE TITLE
Arranger: Move multiple tracks

### ISSUE THREAD

**Issue by MyLoFy** [muse-sequencer/muse#934]
OS Archlinux, MusE 4.0.0-pre1-127-g381f20da
Only single tracks can be moved up and down in the arranger. It would be great if selected tracks could be moved together.

**Comment by kybos** [comment]
I'm not quite sure about that one. As you can select any combination of tracks, the results can be quite unpredictable from user perspective.
For me it would only make sense to move a range, a contiguous area. Or what use case exactly did you have in mind?

**Comment by MyLoFy** [comment]
> Or what use case exactly did you have in mind?

I think this is a very common workflow: 
When creating a new song I usually create new tracks as new ideas pop up. So after a while the project becomes cluttered and I need to organize tracks for better clarity. Also, when mixing, it's much faster if the projects have all the same track order (I usually go from top to bottom: drums, bass, keys, guitars, vocals, effects).
So when I add e.g. 5 new percussion tracks (in MusE that could be 10 tracks, 5x synth and 5x MIDI) I would drag and drop all those tracks from bottom to the top one by one.
A MusE specific particularity is that tracks often come in pairs (Synth+MIDI, Input+Wave) that (at least for me) would need to stay together when moved.
> For me it would only make sense to move a range, a contiguous area.

I agree, moving dispersed tracks wouldn't be too useful.

**Comment by kybos** [comment]
It's now possible to move selected tracks up and down (and to the top/bottom). There are menu entries and keyboard shortcuts available (default is Ctrl+Shift+Up/Down/Home/End).

**Comment by MyLoFy** [comment]
Fantastic, thanks!
