### ISSUE TITLE
Shortcuts not cleared when changed allowing multiple hotkeys until restarted

### ISSUE THREAD

**Issue by terminator356** [muse-sequencer/muse#940]
Quick report: Not sure what else this affects yet, but so far I see it with the Tool buttons' hot keys.
Steps to reproduce:
1) In the Shortcuts dialog, change for example the Select Tool hotkey from 'A' to something else like 'K'.
2) Notice that both 'A' and 'K' work. "A' is still active somehow. The button's tooltip still says 'A'.
3) In the Shortcuts dialog, Clear that shortcut.
4) Notice that 'A' works but 'K' does not. 'A' is still active somehow. The button's tooltip still says 'A'.
5) Restart MusE. Notice that no key works now (since it was cleared). The button's tooltip says ().
(Or in case a key is defined when restarting, that key works and the tooltip says that key.)

Not sure how 'dynamic' our toolltip text is - hopefully we update it whenever our configChanged() slots are called,
 and not just when the program is (re-)started.

**Comment by kybos** [comment]
There is duplicate handling of the tool shortcuts - once for the context menu, once for the edit toolbar.
Shortcut change works only for the context menu, the toolbar is static and ignores it (which explain why both old/new work at the same time).
I will fix it.

**Comment by terminator356** [comment]
Thanks!
