### ISSUE TITLE
appimage 8b13c47 crash

### ISSUE THREAD

**Issue by revolverve** [muse-sequencer/muse#979]
Muse appimage 8b13c47 segfault opening mess fluidsynth;
failed: /usr/lib/muse-4.0/synthi/fluid_synth.so: cannot open shared object file: No such file or directory.
if detail needed,just ask.
  Thanks.

**Comment by kybos** [comment]
Thanks for the report.
Should be fixed now.

**Comment by revolverve** [comment]
Well done,fix.
