### ISSUE TITLE
crash when align devices to ports

### ISSUE THREAD

**Issue by bernd100000** [muse-sequencer/muse#983]
I can not align a device to a port. The configuration won't be saved and if I try to connect a 2nd time, Muse 3.1.1 crash by producing xruns.

**Comment by kybos** [comment]
It's not clear what you mean. Could you please give a step-by-step description of the problem?

**Comment by bernd100000** [comment]
- create a jack-device
- name the jack-device 'Test'
- align to device-number '200'
- MusE 3.1 crash

How do I deactivate the autoconnection to midi-devices?
my ports defined in each song. the autoconnection connect the first
device-numbers to own-defined devices and push mine to the end. no
instrument will be connected to the correct device. If I set the correct
device to the correct device-number, muse crash.


Am Di., 27. Apr. 2021 um 20:48 Uhr schrieb kybos ***@***.***>:

**Comment by bernd100000** [comment]
corrction: How do I deactivate the autocreating of and autoconnection to
existing midi-devices?

Am Di., 18. Mai 2021 um 00:25 Uhr schrieb Bernd Mullet <
***@***.***>:

**Comment by terminator356** [comment]
Sorry this was never answered.
There is a command-line option to prevent auto-connection to midi devices:

> -F                             Do not auto-populate midi ports with midi
>                                  devices found, at startup
>

**Comment by terminator356** [comment]
I will close this because a crash has been fixed in the midi config dialog when clicking the ports panel,
 which I assume must have been the complaint here.
