### ISSUE TITLE
How do i build for x11?

### ISSUE THREAD

**Issue by The-Sapphire-Starship** [muse-sequencer/muse#985]
I would like to try and build this program for the x11 platform, could someone tell me how to do that please?

**Comment by kybos** [comment]
Not sure what you mean with x11 platform (MusE is Linux software), but build instructions are in the README file in the repo as usual.
https://github.com/muse-sequencer/muse/blob/master/src/README

**Comment by The-Sapphire-Starship** [comment]
I want to build MusE on my rpi, which is arm processor(x11), most computers are x86 processors

**Comment by The-Sapphire-Starship** [comment]
I'll try what it says there and see if it will work no matter the platform, but I think there will need to be some tweaking of the commands being used to get it to compile

**Comment by kybos** [comment]
It seems to work on rpi4, see here:

https://linuxmusicians.com/viewtopic.php?f=61&t=22773&p=130531&hilit=raspberry#p130531

**Comment by spamatica** [comment]
> I want to build MusE on my rpi4, which is arm processor(x11), most computers are x86 processors

Just nit picking, I think you have mixed up the acronyms. To my knowledge there are no processors called x11 in any of the raspberry PIs. The graphics subsystem in Unix-like operating systems used to be called X11 (nowadays it is called Xorg).

In any case, as kybos mentioned it should work. Possibly depending on which operating system you run on your PI. The default operating system I believe is built on Debian and should be relatively easy to get MusE built.

**Comment by The-Sapphire-Starship** [comment]
> It seems to work on rpi4, see here:
> 
> https://linuxmusicians.com/viewtopic.php?f=61&t=22773&p=130531&hilit=raspberry#p130531

Okay cool, ill try it and eel you all how well it works here, I just wanted to know if it was possible before I tried

**Comment by The-Sapphire-Starship** [comment]
9th

> > I want to build MusE on my rpi4, which is arm processor(x11), most computers are x86 processors
> 
> Just nit picking, I think you have mixed up the acronyms. To my knowledge there are no processors called x11 in any of the raspberry PIs. The graphics subsystem in Unix-like operating systems used to be called X11 (nowadays it is called Xorg).
> 
> In any case, as kybos mentioned it should work. Possibly depending on which operating system you run on your PI. The default operating system I believe is built on Debian and should be relatively easy to get MusE built.

I probly did, I'm new to this stuff

**Comment by The-Sapphire-Starship** [comment]
it compiled sucessfully first try without any edits to anything! It looks like it works and starts running, however, it seems to get stuck on "initializing midi devices"(or does this part just take a little longer to load?
![2021-04-28-160120_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/116483051-33c4bb80-a83b-11eb-9156-bce03b4c8db0.png)
)

**Comment by spamatica** [comment]
Good with the compilation!

I see in the terminal there is a message "Could not open ALSA sequencer". This is a rather fatal error for MusE. ALSA sequencer is pretty much always there on a Linux system so it is likely we handle it badly if it is missing.

Not at my computer right now but I think this can be manually fixed by manually loading alsa sequencer.
Googling i found this old page with some examples
https://help.ubuntu.com/community/Midi/HardwareSynthesisSetup

Try: sudo modprobe snd-seq
but it could be one of the others listed on that page, please give it a try

**Comment by spamatica** [comment]
By the way, also in the trace that it cannot connect to Jack and instead uses PulseAudio, which is good for having something to try but if you want to do serious audio recording you need to get Jack propertly started. Many people use qjackctl which gives a GUI for starting and changing settings for jack.
Or, if you only want to use the MIDI capabilities MusE can be started in MIDI-only mode: muse4 -a

**Comment by The-Sapphire-Starship** [comment]
Running the command you have up there got it past that point but now its getting stuck at "Populating Track Context Menu":

normal mode (this command: muse4):
![2021-04-29-133009_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/116614768-3680e880-a8ef-11eb-89ad-235fa35bd6d8.png)

midi-only mode (this command: muse4 -a):
![2021-04-29-133221_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/116614867-57e1d480-a8ef-11eb-825d-b5d280392647.png)

Im checking muse out so see what music sequencing feature it has, I just want to be able to make music for my games inside of the computer, im not sure what features i would need, if you know of any other better program for this that i could compile and run on my rpi4 please let me know

**Comment by terminator356** [comment]
Hm, from the "cannot allocate memory" warnings, the only thing I can think of to try is this from our README:
>>>
       - create an "audio" group if it does not already exists
        and put yourself into this group

      - For realtime priority, you may want to ensure either the file:
           /etc/security/limits.conf
         or
           /etc/security/limits.d/audio.conf
         contains:
           @audio   -  rtprio     95
           @audio   -  memlock    unlimited

        Some distros have a graphical menu or tool which does this for you.
>>>

Also, regarding the lack of ALSA sequencer, @spamatica mentions trying to load the module manually.
There is this in our README, although I thought it had long since been a relic:
>
      - Some rare distros might not load the alsa sequencer module by default.
        If necessary, load the alsa sequencer module with:
            /sbin/modprobe snd-seq

**Comment by terminator356** [comment]
Also, regarding the "Could not get wanted frequency 1024, got 100" warning:
There is another module that you should try loading.
(@spamatica  @kybos This advice really belongs right up front in the README along side that ALSA snd-seq advice.)
From a forum post by me:

> Please ensure that the ALSA module snd-hrtimer is loaded before starting MusE if you have not started Jack yet.
Try "sudo modprobe snd-hrtimer".
It seems that because Jack uses the ALSA pcm api or some other, that causes the module to be loaded automatically -
 but only if you use Jack.
Loading the snd-hrtimer module will allow MusE to pick the ALSA hi-resolution 1000Hz timer.
This is important for midi timing.

**Comment by The-Sapphire-Starship** [comment]
i did this command: sudo modprobe snd-hrtimer
after doing that it loaded completely and is now ready for me to test
![2021-04-29-164000_1920x1080_scrot](https://user-images.githubusercontent.com/75915540/116631339-b9af3800-a909-11eb-9011-0f447a58ec75.png)
thanks for the help guys :)

**Comment by terminator356** [comment]
Hey, awesome! Glad to help.
Have fun, ask if any more trouble.
MusE, like any complex app, can take some learning.
There are some usage examples and training videos and so on.

**Comment by The-Sapphire-Starship** [comment]
yea, it looks like its going to take some learning, it worked well witht he initial "soft synth" test in the manual and the gui is nice and responsive on my rpi4(unlike some other programs), im already enjoying this and i have a feeling i will continue to enjoy it :) @terminator356 (i only @ed you so that you can see this essage, im not sure if you would be albe to otherwise since the issue is closed)

**Comment by The-Sapphire-Starship** [comment]
I know im new here but i agree with what you are saying, it would make more sense to have the general troubleshooting information and keeping the README for the compilation instructions also makes sense to me, at least it makes sese from the viewpoint of a newcomer :)
