### ISSUE TITLE
Crash when removing plugin from track with open GUI

### ISSUE THREAD

**Issue by hippie403** [muse-sequencer/muse#986]
Running MusE 4.0 on Raspberry Pi 4B
If I remove a plugin from a Wave track while it has it's Native GUI open it causes a crash:

greg@FLIRC:~ $ uname -a
Linux FLIRC 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
greg@FLIRC:~ $ muse4
qt5ct: using qt5ct plugin
-> 16:46:26.548 Read configuration...
Config File </home/greg/.config/MusE/MusE/MusE-seq.cfg>
LOCALE en_AU
-> 16:46:26.587 Load theme...
Config File </usr/local/share/muse-4.0/themes/Dark Flat.cfc>
qt5ct: custom style sheet is disabled
-> 16:46:26.797 Scan plugins...
-> 16:46:34.507 Init audio...
qt5ct: D-Bus global menu: no
Denormal protection enabled.
Select audio device from configuration : 0
User JackAudio backend - backend selected through configuration
MusE:initJackAudio: jack_get_version() returned zeros. Setting version major to 1.
Using Jack
-> 16:46:35.406 Init MIDI...
-> 16:46:36.045 Init plugins...
-> 16:46:36.056 Init VST plugins...
-> 16:46:36.056 Init native VST plugins...
Initializing Native VST support. Using VESTIGE compatibility implementation.
-> 16:46:36.058 Init DSSI plugins...
-> 16:46:36.059 Init LV2 plugins...
-> 16:46:44.250 Init OSC / metronome...
-> 16:46:44.666 Init LASH...
Connected to session bus, unique name is ":1.30"
-> 16:46:45.250 Populating Track context menu...
-> 16:46:46.869 Show GUI...
JACK: buffersize changed 1024
-> 16:46:48.018 Load default project
starting with template /usr/local/share/muse-4.0/templates/default.med
jack connect <MusE:jack-midi-0_out> - <alsa_pcm:UM-1G/midi_capture_1> failed with err:17
jack connect <alsa_pcm:UM-1G/midi_playback_1> - <MusE:jack-midi-0_in> failed with err:17
jack connect <MusE:jack-midi-1_out> - <alsa_pcm:Midi-Through/midi_capture_1> failed with err:17
jack connect <alsa_pcm:Midi-Through/midi_playback_1> - <MusE:jack-midi-1_in> failed with err:17
-> 16:46:48.921 Start application loop...
Total start-up time: 23210 ms
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13067, resource id: 46137347, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13068, resource id: 46137347, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13069, resource id: 46137347, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13070, resource id: 46137347, major code: 12 (ConfigureWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13072, resource id: 46137347, major code: 7 (ReparentWindow), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13073, resource id: 46137347, major code: 18 (ChangeProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 13074, resource id: 46137347, major code: 8 (MapWindow), minor code: 0
Segmentation fault

This was a LV2 Autotune plugin. It seems to affect all the LV2 plugins I have tried. The generic GUI is OK just the native GUI.

**Comment by kybos** [comment]
Fixed in master.
Thanks for the report.
