### ISSUE TITLE
Extended Italian translation

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#992]
Hello,

just wanted to say that I started an extended Italian translation over at [my repo](https://github.com/fpesari/muse). I will probably open a PR to close this issue once it's done but I thought I would announce it in case somebody else is working on it (in that case, we can collaborate for sure!).

If you have any guidelines or suggestions about the order I should follow, I'm all ears :smile_cat:

**Comment by kybos** [comment]
Nice.
What do you mean by extended? I guess you're going to update the existing one?
As for suggestions: As there are so many texts, I would start with the shorter texts, as these are usually the ones displayed on the UI directly. Longer texts like error messages, tooltips, whatsthis-texts etc. take lot of time to translate, but are typically less visible.

**Comment by fpesari** [comment]
Yes, I noticed there are some translated strings already so I started from there. At the end (hoping to get there!) I will do a review for consistency.

I will focus on the shorter texts, then :+1: as soon as they are done I will submit a PR and then move to the longer texts.
