### ISSUE TITLE
JACK starts even when the RtAudio backend is used

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#993]
**Describe the bug**
As I said in the title, JACK starts even when the RtAudio backend is used.

**To Reproduce**
1. Set the MusE backend to RtAudio (I used RtAudio Pulse Audio)
2. Make sure no jackd instance is running via `ps aux | grep jackd`
3. Run MusE
4. Run `ps aux | grep jackd` again. In my case, a jackd instance is indeed running!

**Expected behavior**
If JACK is not selected as the backend, it should not start. Also because when MusE is closed, jackd keeps running and if users don't notice it, it might cause trouble.

I don't know if this is intended but RtAudio seems to not use JACK even for MIDI, judging from the output of `aconnect -l`. So I expected JACK would not be launched.

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Desktop: KDE Plasma
 - MusE version 4.0

**Comment by terminator356** [comment]
I could not make it happen here (on tumbleweed as well), either using the -t command line switch or by
 setting Rt in our Settings dialog. I have never noticed it happening before.

Do you have the 'pulse-module-jack' package installed?
I can't install it at the moment.
But I'm wondering if by starting Pulse, the module (if installed) automatically starts Jack? I can't recall...

**Comment by fpesari** [comment]
> Do you have the 'pulse-module-jack' package installed?
> I can't install it at the moment.
> But I'm wondering if by starting Pulse, the module (if installed) automatically starts Jack? I can't recall...

I do have `pulseaudio-module-jack` installed but I doubt it's that, since the RtAudio ALSA backend does the same...with the difference that after starting JACK itself, MusE then gives me the popup "Was not able to start audio, check if jack is running or try another driver"!

I tried to disable "Try to use Jack Freewheel" but that does not seem to change anything. The same when I changed the backend to "Midi only" and when I launched MusE with the -a option. Not even the `-J` option prevents JACK from starting! I even tried `muse4 -Jta` but nothing changed.

When `jackd` is killed, MusE crashes when using any RtAudio backend. So basically MusE forces me to keep JACK running as long as it's running. I am not a JACK aficionado, as a matter of fact I only launch it when testing programs and I don't use any special setup.

I am using the MusE 4.0 openSUSE TumbleWeed on GeekosDAW made by @KottV ([spec](https://github.com/muse-sequencer)) - I don't know if he can replicate the bug though.

**Comment by spamatica** [comment]
I have noticed here (ubuntu with kxstudio) that some plugins seem to link with jack libs, causing it to start (atleast briefly), but this jack instance have not interfered with Pulse so I haven't investigated deeper.

You can test this theory by starting MusE without plugins
`muse4 -pNI2`

**Comment by terminator356** [comment]
I seem to recall now, that when the pulse-module-jack is installed, Pulse starts Jack automatically.
In fact you cannot even kill Jack. You try, and Pulse just starts Jack again.
I think especially when Jack dbus is enabled, this is the case.
Try to remove pulse-module-jack package to test if it solves the problem.

Either way, this is definitely not a MusE problem. We do not start Jack when in midi-only mode.

**Comment by fpesari** [comment]
Ok, I started with a fresh config and

> `muse4 -pNI2`

Even with all plugins disabled, MusE launches JACK.

> Try to remove pulse-module-jack package to test if it solves the problem.

I did uninstall it but nothing changed, both with the RtAudio ALSA and Pulse backends. As a matter of fact, I always could kill JACK without it respawning and Ardour used in ALSA mode does not launch JACK, this only happens with MusE.

**Comment by KottV** [comment]
It looks that LASH ignite the Jack.
Try to load without it `muse4 -L`

**Comment by fpesari** [comment]
> It looks that LASH ignite the Jack.
> Try to load without it `muse4 -L`

Yes! That did it.

If JACK is not selected as the backend, LASH should not start it.

**Comment by KottV** [comment]
Correct me if i wrong, LASH won't work without Jack, so this option should be switchable then.

**Comment by fpesari** [comment]
> Correct me if i wrong, LASH won't work without Jack, so this option should be switchable then.

They claim to be ALSA-compatible as well but I've personally always seen it used with JACK.

**Comment by spamatica** [comment]
Good information.
Though, I guess this is outside MusE's jurisdiction then so we close this?

**Comment by fpesari** [comment]
> Good information.
> Though, I guess this is outside MusE's jurisdiction then so we close this?

I personally would prefer if MusE automatically disabled LASH when the RtAudio ALSA/Pulse backend is selected (because starting JACK might create problems, especially for newbie users who can't figure out why they don't hear any sound) but I want to hear what others have to say :smiley:

**Comment by spamatica** [comment]
Seems fair. I'll see if I can disable it for other cases.

A releated question is whether LASH is relevant anymore? The last release was 13 years ago.

**Comment by fpesari** [comment]
> A releated question is whether LASH is relevant anymore? The last release was 13 years ago.

Getting philosophical :joy: I personally would not mind if support for it were dropped! MusE can do everything it does without it, right? NSM is a standard which is actively developed.

**Comment by kybos** [comment]
The LASH support is optional, it can be switched off in cmake (and it's switched off automatically if cmake doesn't find the lash dependencies). But by default it's ON.
So (as LASH clearly seems to be a dead project) I suggest to disable it by default. If someone really cares, they can compile themselves.

For NSM there is already a feature request:
https://github.com/muse-sequencer/muse/issues/657

**Comment by spamatica** [comment]
I got LASH 0.6 built and tested this scenario. It seems there is more to it. On my system jack is not started, so if someone out there wants to use LASH, maybe we should not impose limitations that stem from something else.

> So (as LASH clearly seems to be a dead project) I suggest to disable it by default. If someone really cares, they can compile themselves.

There seems to be another session manager, Ladish, that is supposedly backwards compatible with LASH so I guess it is possible someone wants to use that. 
But I am very much in favour of changing the default to OFF, making it more of an optional package.

**Comment by fpesari** [comment]
Ladish has a commit as recent as 2021-02-27 so I agree that it would be a better choice than LASH. If the replacement is easy enough, I think it would be good to replace LASH with Ladish ASAP. If it's hard to replace LASH with Ladish, I think it would be better to keeping using LASH, deprecate it from 4.1 onwards and move to NSM in 5.0.

Speaking for myself both as a user and as a packager, I think it would be better if:
1. MusE is built with LASH support by default (current behavior)
2. The -L flag is be removed and made the default behavior
3. A new option, perhaps `-H` (the last letter of both LASH and Ladish) is added to explicitly **enable LASH** (or in the future, Ladish)

This way everyone is happy: 
1. We packagers are happy to ship MusE with one more feature, LASH support, without creating potential issues for non-LASH users (which could be the majority of users, actually). Existing builds wouldn't need to be modified (aside from updating the tarball)
2. LASH users, whom I suppose are a bit more knowledgeable about GNU/Linux audio, can figure out the change to the command line options and launch MusE with the new -H flag
3. Everyone else can just use MusE without worrying about LASH (and its tendency to stealthily launch JACK without stopping it when MusE is closed...)

**Comment by kybos** [comment]
I agree in principle, but I would keep it simple:
Disable LASH by default, and keep the -L switch for enabling it.
I see no need to implement ladish, as it is meant to be compatible with lash anyway.

**Comment by fpesari** [comment]
> Disable LASH by default, and keep the -L switch for enabling it.

I thought about that too but changing the behavior of a flag to its opposite may break existing scripts, launchers and config files relying on the current behaviour and create chaos. That's why I proposed a new flag. The `-L` could be left as a no-op for backward compatibility purposes and removed in the next major version.

>  I see no need to implement ladish, as it is meant to be compatible with lash anyway.

I agree with you but then I hope NSM will be implemented by 5.0, because having an unmaintained dependency is never a good thing...

**Comment by kybos** [comment]
We are talking about a feature that most probably nobody uses at all, but it's causing side-effects for many people (apart from starting Jack, it issues OS messages about starting LASH session on some Desktops etc.).
BTW: Relying on something that will (or will not) happen in the future is not a good idea in this context IMO (in my experience it's rather deprecations that "create chaos" - just thinking of GTK development and similar... ;-) ).

Anyway: Perhaps it would be best to introduce a global setting in MusE for enabling LASH which would be OFF by default. Thus the command line switch could be left as is.

**Comment by fpesari** [comment]
> Anyway: Perhaps it would be best to introduce a global setting in MusE for enabling LASH which would be OFF by default. Thus the command line switch could be left as is.

100% behind this idea!

**Comment by kybos** [comment]
It's now in master.
