### ISSUE TITLE
[Pencil/Pointer tool] Feature request: Escape key while dragging cancels it

### ISSUE THREAD

**Issue by fpesari** [muse-sequencer/muse#997]
It would be nice to be able to cancel dragging in the Pencil and Pointer tools by pressing the Escape key while the left mouse button is still pressed. True, you can always undo after releasing the mouse button, but the advantage of this little UX tweak is that it leaves the undo/redo stack unchanged.

Some programs assign this behavior to the right mouse click as well but that could happen by mistake, while it's highly unlikely that someone could press the Escape key while the left mouse button is down by mistake...

**Comment by spamatica** [comment]
Are we talking about the arranger here? When inside an editor, by default the Escape key will exit the editor so it could potentially be confusing.
Also I'd be happy with an example. Is some specific operation where you miss it?

**Comment by fpesari** [comment]
Yes, I am talking about the arranger. The operation which inspired this bug report is creating and resizing a MIDI part. Would assigning Escape to cancelling the resize operation break something there?

**Comment by kybos** [comment]
> When inside an editor, by default the Escape key will exit the editor so it could potentially be confusing.

Yes, it would be very confusing. If Escape were used in Arranger in that way, then the user would expect that it does the same in the editors (when resizing the events). 
I don't quite see the need for such a feature, as undo works well here.

**Comment by fpesari** [comment]
It could work like this in the editor too - Escape during any move/resize operation cancels and reverts it. When no such operation is in progress, Escape keeps its normal behavior. It would then be consistent.

But I am not too attached to this feature request - if this is too much work for little benefits, please do close this ticket :smiley:

**Comment by kybos** [comment]
> if this is too much work for little benefits

Yes, it is. The handling of shortcuts in different scopes is not really straight-forward in Qt, and quite error prone.
