### ISSUE TITLE
[FEATURE REQUEST] Moving notes with CTRL+ARROW KEYS shoud audition the notes

### ISSUE THREAD

**Issue by StaffanMelin** [muse-sequencer/muse#999]
When moving notes with the mouse/trackpad I can hear them which is great!

Is it possible to extend this to when I move notes with CTRL+ARROW KEYS?

**Comment by kybos** [comment]
I don't think this is logically possible, as in that case there would be no note ON/OFF trigger (like pressing/releasing the mouse).

**Comment by StaffanMelin** [comment]
Ah, that's correct. But just a short trigger (1/4 of a sec or so) would be great!

**Comment by kybos** [comment]
But then it would probably only work with some sounds (those with short attack phase).

**Comment by StaffanMelin** [comment]
Maybe they could sound until you release CTRL? :)

**Comment by kybos** [comment]
I suppose either until you move to the next note(s), or CTRL is released.
Can't tell ATM if it will really work or how much effort it would be to implement, but yes, it's definitely a valid requirement.

**Comment by StaffanMelin** [comment]
It's no rush, it would just be useful and consistent with how it now works with dragging (which is awesome and sooo useful). Thanks for considering it!

**Comment by kybos** [comment]
I'm afraid it can't be really consistent, especially not with multi selection. There is no "master" item (under the mouse pointer), so how do you decide which note (or chord, depending on the setting) to play? Maybe take the first one (in time) as a workaround?
Sure not play all of them? That could result in bad cacophony...

**Comment by StaffanMelin** [comment]
I think it could/would work like this:

1. One note selected: Play that one as long as CTRL is pressed, retrigger for every move (ARROW keys)
2. Many notes selected: Follow the drag setting (one note or chord). If on all note setting, play all notes. If on single note setting, play the earliest one. If all  at the same time, play the lowest as this in most cases is the base note of the chord.

**Comment by kybos** [comment]
Please test, it should work more or less like described above, except:
On multi-select always the earliest note is played.
If setting = single and there are other notes on the same tick, then the lowest note value is played.
If setting = chord and there are other notes on the same tick as the earliest note, then they are played as a chord.

**Comment by StaffanMelin** [comment]
It works beautifully!!!

Many thanks for this, kybos, this is a huge workflow improvement (for me)!!! :D

**Comment by kybos** [comment]
You're welcome ;-)
